### PR TITLE
Merged overloaded commands

### LINKED ISSUE #9807: `dfr min` stoped working with  `dfr col` in 0.83.0
### Describe the bug

subj

### How to reproduce

```
 ls | dfr into-df | dfr agg [(dfr col modified | dfr min | dfr as 'm_min')]
Error: nu::parser::input_type_mismatch

  × Command does not support expression input.
   ╭─[entry #3:1:1]
 1 │ ls | dfr into-df | dfr agg [(dfr col modified | dfr min | dfr as 'm_min')]
   ·                                                 ───┬───
   ·                                                    ╰── command doesn't support expression input
   ╰────
```

### Expected behavior

I expected nu to work

### Screenshots

_No response_

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.83.0                                               |
| branch             |                                                      |
| commit_hash        |                                                      |
| build_os           | macos-aarch64                                        |
| build_target       | aarch64-apple-darwin                                 |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)                  |
| rust_channel       | 1.69.0-aarch64-apple-darwin                          |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)                  |
| build_time         | 2023-07-26 06:55:18 +00:00                           |
| build_rust_channel | release                                              |
| allocator          | standard                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ayax79**
- fixes #9807

# Description

This pull request merges all overloaded dfr commands into one command:

eager:
dfr first -> eager/first.rs
dfr last -> eager/last.rs
dfr into-nu -> eager/to_nu.rs (merged)

lazy:
dfr min -> expressions/expressions_macro.rs lazy_expressions_macro
dfr max -> expressions/expressions_macro.rs lazy_expressions_macro
dfr sum -> expressions/expressions_macro.rs lazy_expressions_macro
dfr mean -> expressions/expressions_macro.rs lazy_expressions_macro
dfr std -> expressions/expressions_macro.rs lazy_expressions_macro
dfr var   -> expressions/expressions_macro.rs lazy_expressions_macro

series:
dfr n-unique -> series/n_unique.rs
dfr is-not-null -> series/masks/is_not_null.rs
dfr is-null -> series/masks/is_null.rs

# User-Facing Changes
No user facing changes

### CODE REVIEW

**Comment by amtoine** [comment]
hi @ayax79 :wave: :yum: 
thanks again for working on the dataframes :pray:

could you make the title of the PR a bit smaller so that it fits in one line? :yum: 
it looks like it's the first commit's title which is a bit too long :open_mouth: 

i'll mark this as a DRAFT for now as you have a "*WIP*" in the description :relieved:

**Comment by fdncred** [comment]
Most of the conversations related to this PR are here https://discord.com/channels/601130461678272522/1134562453817151528

**Comment by WindSoilder** [comment]
Thanks for the pr!  I like it very much.

A simple thought about organization, after the pr, maybe we can merge `expression` and `lazy` into one module?

**Comment by ayax79** [comment]
@amtoine, updated and the PR is ready to go.

File: crates/nu-cmd-dataframe/src/dataframe/expressions/expressions_macro.rs [hunk 1]
```diff
@@ -456,64 +617,93 @@ expr_command!(
...
     ExprVar,
     "dfr var",
     "Create a var expression for an aggregation",
-    vec![Example {
-        description: "Var aggregation for a group-by",
-        example: r#"[[a b]; [one 2] [one 2] [two 1] [two 1]]
+    vec![
+        Example {
+            description:
+                "Var value from columns in a dataframe or aggregates columns to their var value",
```
Comment (WindSoilder) [inline crates/nu-cmd-dataframe/src/dataframe/expressions/expressions_macro.rs:673]: I love the updated description :-)

**Review by fdncred — APPROVED** [review]
Thanks for working on this. I think dfrs are still a bit of a mess but this at least gets us back to working order. Thanks so much for putting in the time and effort to get us to this point @ayax79!
