### PR TITLE
Recursion def

### LINKED ISSUE #5899: Stack overflow when recursion is not stopped
### Describe the bug

Running a recursive command without stopping causes a stack overflow and nushell crashes

### How to reproduce

```nu
/home/yairf〉def hey [] { hey }                                           06/27/2022 11:09:28 PM
/home/yairf〉hey                                                          06/27/2022 11:09:33 PM

thread 'main' has overflowed its stack
fatal runtime error: stack overflow
[1]    1223672 IOT instruction (core dumped)  nu
```

### Expected behavior

Nu should probably have a recursion limit? (Like other scripting languages e.g python)
when a recursion limit is hit, an exception should be thrown.
recursion limit should be configurable and have a sane default (cpython has 1k iirc) 

### Screenshots

_No response_

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.64.0                                          |
| branch             |                                                 |
| commit_hash        | d1c719a8cc52b1cb3f60810daa8bf28e69eb6617        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.61.0 (Arch Linux rust 1:1.61.0-1)       |
| cargo_version      | cargo 1.61.0                                    |
| pkg_version        | 0.64.0                                          |
| build_time         | 2022-06-15 07:31:53 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

fresh install with empty config file

### PR DESCRIPTION
**Pull request by Mehrbod2002**
Add recursion limit to `def` and `block`.
Summary of this PR , it will detect if `def` call itself or not .
Then execute by using `stack` which I think best choice to use with this design and core as it is available in all crates and mutable and calculate the recursion limit on calling `def`.
Set 50 as recursion limit on `Config`.
Add some tests too .

Fixes #5899

### CODE REVIEW

File: crates/nu-protocol/src/config.rs [hunk 1]
```diff
@@ -127,6 +128,7 @@ impl Default for Config {
             show_clickable_links_in_ls: true,
             render_right_prompt_on_last_line: false,
             explore: HashMap::new(),
+            recursion: 50,
```
Comment (fdncred) [inline crates/nu-protocol/src/config.rs:131]: I see where this is being defaulted to 50 in the config.rs but where is it being read from the config file? Or is this not meant to be configurable and it's just meant to start out with a default?

Comment (Mehrbod2002) [reply crates/nu-protocol/src/config.rs:131]: In `engine_state` which is initial the process of `eval` and available in all functions .
on `engine_state` there is a `config` part on struct which call `Default` on `Config` and it will initialize the value.
As this is necessary to have `engine_state` , it will initialize 100%.

Comment (fdncred) [reply crates/nu-protocol/src/config.rs:131]: Right. What I'm saying is that you're adding a setting to config, recursion, that is hard coded with no way of setting it via config.nu, right?

Also, maybe it should be named `recursion_limit` or something that indicates what it's for.

Comment (Mehrbod2002) [reply crates/nu-protocol/src/config.rs:131]: Can we delete it then ? 
Just use recursion limit which rust allow us , that is 128 ...
Because I think it is unnecessary

Comment (Mehrbod2002) [reply crates/nu-protocol/src/config.rs]: @fdncred 
I added it to `config.nu` and its default its 50.
parameter name changed to recursion_limit too .

Comment (fdncred) [reply crates/nu-protocol/src/config.rs]: Sorry for the late reply. I'm fine with using whatever rust's default recursion limit is and removing/not having a configuration point for this. I'm not sure how much this configuration point would ever be used.

Comment (Mehrbod2002) [reply crates/nu-protocol/src/config.rs]: Deleted from Config . @fdncred

File: crates/nu-engine/src/eval.rs [hunk 2]
```diff
@@ -875,6 +875,15 @@ pub fn eval_block(
     redirect_stdout: bool,
     redirect_stderr: bool,
 ) -> Result<PipelineData, ShellError> {
+    if let Some(recursion) = block.recursion {
+        if recursion {
+            if *stack.recursion_limit == 50 {
```
Comment (fdncred) [inline crates/nu-engine/src/eval.rs:880]: Is 50 what rust defaults to? I thought you said it was a higher number?

Comment (Mehrbod2002) [reply crates/nu-engine/src/eval.rs:880]: It's default depend on architecture, 
On Linux it's 128 .
I want to extend this section to working and throw error but 50 is minimal limit for all architecture

Comment (fdncred) [reply crates/nu-engine/src/eval.rs:880]: ok, thanks for the info.

**Comment by Mehrbod2002** [comment]
@fdncred 
Thanks for your attention .

File: crates/nu-engine/src/eval.rs (hunk 2 above)
Comment (Mehrbod2002) [reply crates/nu-engine/src/eval.rs:880]: > ok, thanks for the info.

If it has possibility to merge ,  would be great , some work on `stack` will conflict on this by working on `ls_color` on my next pull request which is uploading now ...
Thanks again @fdncred

File: crates/nu-engine/src/eval.rs [hunk 3]
```diff
@@ -875,6 +875,15 @@ pub fn eval_block(
...
+                stack.recursion_limit = Box::new(0);
+                return Ok(PipelineData::Empty);
```
Comment (rgwood) [inline crates/nu-engine/src/eval.rs:882]: I think users are going to be confused when the command succeeds but returns nothing.

We should probably return a `ShellError` explaining that the command failed because of the recursion limit.

File: src/tests/test_custom_commands.rs [hunk 4]
```diff
@@ -145,3 +145,14 @@ fn override_table_eval_file() {
     let actual = nu!(cwd: ".", r#"def table [] { "hi" }; table"#);
     assert_eq!(actual.out, "hi");
 }
+
+#[test]
+fn recursion_successful() {
+    let actual = nu!(
+        cwd: ".",
+        r#"
+            def bang [] { bang }
```
Comment (rgwood) [inline src/tests/test_custom_commands.rs:154]:
```suggestion
            def bang [] { bang }
            bang
```

I think you forgot to run `bang` in the test.

File: crates/nu-parser/src/parse_keywords.rs [hunk 5]
```diff
@@ -401,6 +401,41 @@ pub fn parse_def(
             *declaration = signature.clone().into_block_command(block_id);
 
             let mut block = working_set.get_block_mut(block_id);
+            let call_itself = block.pipelines.iter().any(|pipline| {
```
Comment (rgwood) [inline crates/nu-parser/src/parse_keywords.rs:404]:
```suggestion
            let calls_itself = block.pipelines.iter().any(|pipeline| {
```

**Review by rgwood — COMMENTED** [review]
Thanks for the PR! Added some suggestions.

I think the general approach makes sense. I don't know a ton about the parser so I'm not confident in my ability to review the code in `parse_keywords.rs`

File: crates/nu-engine/src/eval.rs (hunk 2 above)
Comment (rgwood) [reply crates/nu-engine/src/eval.rs:880]: Can you please add a comment explaining why you picked 50?

I like to see comments for "magic numbers"; in the future somebody is going to wonder why this was set to 50. Even something like `// picked 50 arbitrarily, should work on all architectures` will help that person out.

**Comment by kubouch** [comment]
Seems OK to me but like Reilly commented, we should return error instead of empty pipeline if we reach max recursion.

**Comment by Mehrbod2002** [comment]
@kubouch @rgwood 
Thanks for your question .
When we return Empty Pipeline , there is a function which call it self , then `eval_block` run and run until we reach recursion limit and then stop .
For example :
`def call [] { call }` ,
`def` are `block` in Nushell , so when reaches to `call` here , it contains another block and then and then .... on last `eval_block` , Empty result which is translate to block like something never executed ... so it's easy and fastest check we can do on `eval_block` .
but it's result from its called functions will save and return too , not and empty , Something like Coil ...

**Comment by rgwood** [comment]
@Mehrbod2002 Microsoft has free Windows VMs for development: https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/

**Comment by Mehrbod2002** [comment]
> @Mehrbod2002 Microsoft has free Windows VMs for development: https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/

Thanks a lot . Going to resolve the Windows problem .

**Comment by rgwood** [comment]
I can't reproduce [the CI stack overflow](https://github.com/nushell/nushell/actions/runs/3835404490/jobs/6528611804) locally on Windows (b83b582) but this looks familiar. We have had stack overflow issues on Windows in CI before: https://github.com/nushell/nushell/pull/7089

Last time we believe this was the problem:

> Our eval functions are recursive, those large numbers of arms with their own variables meant we were putting like 100+ variables on the stack with each step of recursion. That plus debug mode's own use of the stack is likely what blew our limits

We never did figure out why we were having that problem in CI but not locally - maybe the GitHub Windows runners are customized somehow?

The good news is that we're unlikely to hit this stack overflow in release mode or on user machines. But to work around this CI problem, we _might_ need to lower the recursion limit further :(

**Comment by Mehrbod2002** [comment]
> The good news is that we're unlikely to hit this stack overflow in release mode or on user machines. But to work around this CI problem, we _might_ need to lower the recursion limit further :(

Thanks for your tests .
I don't think it will resolve it by going to set limit lower than this . It's minimum . also it's very little than other loops we have on codes .
I have some tests which I want to set it on tests .
` def bang [b] { let t = bang $b; return $b;echo};bang passing_data`
which should pass `passing_data` and :
`def slice [a,b] { let t = slice 1 2;return result_is_not_null };slice 1 2 `
which should pass `result_is_not_null` .
These tests as I see allocate and call a lot functions but with this recursions , it will run safely .
So I believe if it's not going to overflow on Windows OS , I don't think it will be any problem on release mode too .

> > Our eval functions are recursive, those large numbers of arms with their own variables meant we were putting like 
100+ variables on the stack with each step of recursion. That plus debug mode's own use of the stack is likely what blew our limits
> 
I believe this too hard.
Allocating is our problem . When we are not going to `drop` some of our arms like `Box` it will happen again and it's all depend on OS (Ram , ... ) .

I can't test this problem on GitHub OS , but as you said :
Rust is guards all possibility to overflow problem on GitHub Window server .

Do think we can ignore this overflow on GitHub Server ?

**Comment by Mehrbod2002** [comment]
@rgwood Consider to see this please.
https://bugzilla.mozilla.org/show_bug.cgi?id=1677763
https://stackoverflow.com/a/40953927/11689628

I monitored Buffers and Ram on Windows to and it's calling recursion safely without any problem but as I understood on some searches , `stack overflow` happens fairly on Windows OS and Rust Core team trying to avoid it by `Box` widely and permit in future to allocate more space on Windows OS. I think GitHub windows server is facing this problem .  It's not Nushell calling functions problem .

Wired problem I can see in Rust on Windows is while recursion and call function it can't deallocate until it comes to end .
but in Linux after second or third call , past functions deallocate and drop easily 🙅🏻  

I can set `cfg` tag and target OS for tests or delete them to bypass this problem and wait for approval .
Thanks .

File: src/tests/test_custom_commands.rs [hunk 6]
```diff
@@ -145,3 +145,43 @@ fn override_table_eval_file() {
     let actual = nu!(cwd: ".", r#"def table [] { "hi" }; table"#);
     assert_eq!(actual.out, "hi");
 }
+
+#[cfg(not(target_os = "windows"))]
```
Comment (rgwood) [inline src/tests/test_custom_commands.rs:149]:
```suggestion
// These tests are disabled on Windows because they cause a stack overflow in CI (but not locally!).
// For reasons we don't understand, the Windows CI runners are prone to stack overflow.
// TODO: investigate so we can enable these on Windows
#[cfg(not(target_os = "windows"))]
```

**Comment by rgwood** [comment]
> I can set `cfg` tag and target OS for tests or delete them to bypass this problem and wait for approval 

Disabling the tests on Windows for now sounds good to me. But [let's add a comment explaining the current situation](https://github.com/nushell/nushell/pull/7657#discussion_r1061791228).

[This point](https://github.com/nushell/nushell/pull/7657#discussion_r1061068127) also needs to be addressed. After that, I think this is ready to be merged; thanks for your help!

**Comment by Mehrbod2002** [comment]
@rgwood 
Sorry for mistake .
Thanks again . look for forward to solve this problem on CI.

File: crates/nu-engine/src/eval.rs (hunk 3 above)
Comment (rgwood) [reply crates/nu-engine/src/eval.rs:883]: @Mehrbod2002 this point still needs to be addressed.

File: crates/nu-engine/src/eval.rs [hunk 7]
```diff
@@ -875,6 +875,17 @@ pub fn eval_block(
     redirect_stdout: bool,
     redirect_stderr: bool,
 ) -> Result<PipelineData, ShellError> {
+    // if Block contains recursion , calls itself to reaches to recursion limit
+    // picked 50 arbitrarily, should work on all architectures
+    if let Some(recursion) = block.recursion {
+        if recursion {
+            if *stack.recursion_limit == 50 {
```
Comment (Mehrbod2002) [inline crates/nu-engine/src/eval.rs:882]: @rgwood You mean something like this ?

File: crates/nu-engine/src/eval.rs (hunk 3 above)
Comment (rgwood) [reply crates/nu-engine/src/eval.rs:884]: @Mehrbod2002 This line. You are returning `Ok(PipelineData::Empty)` when instead you should return an `Err(ShellError...`

Comment (Mehrbod2002) [reply crates/nu-engine/src/eval.rs:884]: @rgwood But all things we try for recursion is processing by this line .
when we defined recursion , so def should obtain our recursion limit , when it reaches to it , it must stop process

Comment (Mehrbod2002) [reply crates/nu-engine/src/eval.rs:884]: And as you in `eval` empty Data will be ignore
it calls itself and save evaluated response for each function when it reaches to limit , convert it to pipeline and show it .
so we have loop and when we reaches to our limit it should stop not returning error .

Comment (Mehrbod2002) [reply crates/nu-engine/src/eval.rs:884]: @rgwood and also all are tests we provided will be failed too ....

Comment (Mehrbod2002) [reply crates/nu-engine/src/eval.rs:884]: @rgwood 
Consider this :
`(1, (2, (3,  (4,  (5, .... (51,Nil))))))`
`eval_block` works something this . it calls itself when reaches to limit .
it's value is Empty and will be ignore our last loop call and `eval_block` execute `call` for each one and save the result and parse it .

Comment (Mehrbod2002) [reply crates/nu-engine/src/eval.rs:884]: @rgwood 
In most languages contains recursion limit tag , like Rust, it will be defined to avoid errors , no to returning an error.
Hope you got what I am saying .

Comment (rgwood) [reply crates/nu-engine/src/eval.rs:884]: I'm sorry, I don't understand.

Consider `def bang [] { bang }; bang`:

Before this PR, that crashes Nushell with a stack overflow.

After this PR, the call to `bang` should fail but not crash Nushell. We should tell the user why the call to `bang` failed.

Comment (Mehrbod2002) [reply crates/nu-engine/src/eval.rs:884]: @rgwood you are right ... but consider user want to execute it , how can he avoid the recursion problem ? 
there is no any choice for him to execute our tests for example , all of function call itself will occur then ...

Comment (Mehrbod2002) [reply crates/nu-engine/src/eval.rs:884]: @rgwood for example if user wants to execute this  : 
`def slice [a,b] { let t = slice 1 2;return result_is_not_null };slice 1 2 `
before this PR it will crash ... but after this by your intention , it will return Error any way and no way to execute it .
but my intention allow user to execute by our rules like other languages and set recursion limit ....

Comment (Mehrbod2002) [reply crates/nu-engine/src/eval.rs:884]: @rgwood Is there any option in ShellError to return value and error too ?
if user execute these tests just wasting his energy because not will be execute anyway .
but if ShellError we can tell him it reaches to recursion limit and also pass def result too .
Can we do it by ShellError ?

Comment (rgwood) [reply crates/nu-engine/src/eval.rs:884]: > consider user want to execute it , how can he avoid the recursion problem ?

I think the best way to avoid the problem is by not recursing 50+ times :)

We don't currently have any good way to return an error _and_ a value.

Comment (Mehrbod2002) [reply crates/nu-engine/src/eval.rs:884]: @rgwood ShellError with Value is my next PR and going to enhance this .
but right now I prefer user gain called function result rather than gain Error .

So do you think for now is working and merge able ?

Comment (Mehrbod2002) [reply crates/nu-engine/src/eval.rs:884]: @rgwood or I can return Error for now but have to erase test and write new one too .

Comment (rgwood) [reply crates/nu-engine/src/eval.rs:884]: > ShellError with Value is my next PR

I don't think that's a good idea, sorry. I think that would add a lot of complexity to Nushell's error handling for very little value. If you do want to do this, please submit a design document or a draft PR before spending a lot of time on implementation.

> So do you think for now is working and merge able ?

No, sorry. This is how the PR works right now:

```bash
〉def bang [] { bang };
〉bang
〉bang | describe
nothing
〉bang
〉$env.LAST_EXIT_CODE
0
〉try { bang } catch { print "bang failed" }
〉
```

That's not right. The `bang` call succeeds when it should fail. It should also tell the user _why_ it failed - the user has no way of knowing that `bang` failed because it recursed too many times.

Please replace `Ok(PipelineData::Empty)` with an `Err(ShellError...`

Comment (Mehrbod2002) [reply crates/nu-engine/src/eval.rs:884]: @rgwood what error do you think match our error to use this with ShellError ?

Comment (sholderbach) [reply crates/nu-engine/src/eval.rs:884]: A stack overflow is an unrecoverable error. There is no point in trying to pass the user some garbled mess instead of an error.

Comment (rgwood) [reply crates/nu-engine/src/eval.rs:884]: I think I would add a new variant to the `ShellError` enum (in `crates/nu-protocol/src/shell_error.rs`). Something like `ShellError::RecursionError`

Comment (Mehrbod2002) [reply crates/nu-engine/src/eval.rs:884]: @rgwood  Do you think this should work `ShellError::OutOfMemoryError` ?

Comment (rgwood) [reply crates/nu-engine/src/eval.rs:884]: No. We are intentionally returning early _before_ we run out of memory.

Comment (Mehrbod2002) [reply crates/nu-engine/src/eval.rs:884]: @rgwood then `NushellFailed` , it contains only String to show our error !?

File: src/tests/test_custom_commands.rs [hunk 8]
```diff
@@ -145,3 +145,46 @@ fn override_table_eval_file() {
...
+// These tests are disabled on Windows because they cause a stack overflow in CI (but not locally!).
+// For reasons we don't understand, the Windows CI runners are prone to stack overflow.
+// TODO: investigate so we can enable these on Windows
+#[cfg(not(target_os = "windows"))]
+#[test]
+fn recursion_successful() {
+    let actual = nu!(
+        cwd: ".",
+        r#"
+            def bang [] { bang };bang
```
Comment (sholderbach) [inline src/tests/test_custom_commands.rs:158]: I don't think we should allow this. This is a guaranteed stack overflow in imperative code and doesn't express anything useful. Recursion limits are there to gracefully protect you from smashing out of memory or clobbering other regions.
This should be an error instead of a panic like we have now. (We can not implement tail call optimization with our setup so there is no valid way for this code to compile)

File: src/tests/test_custom_commands.rs [hunk 9]
```diff
@@ -145,3 +145,46 @@ fn override_table_eval_file() {
...
+    assert!(actual.err.is_empty());
+}
+
+#[cfg(not(target_os = "windows"))]
+#[test]
+fn call_def_in_def_should_be_successful() {
+    let actual = nu!(
+        cwd: ".",
+        r#"
+            def bang [b] { let t = bang $b; return $b;echo};bang passing_data
```
Comment (sholderbach) [inline src/tests/test_custom_commands.rs:170]: Same as above, infinite recursion. Should be `ShellError::RecursionLimitReached`(explicit)/`::StackOverflow`(alternative)

File: src/tests/test_custom_commands.rs [hunk 10]
```diff
@@ -145,3 +145,46 @@ fn override_table_eval_file() {
...
+fn call_def_in_def_should_be_successful2() {
+    let actual = nu!(
+        cwd: ".",
+        r#"
+            def slice [a,b] { let t = slice 1 2;return result_is_not_null };slice 1 2 
+        "#
+    );
+
+    assert!(actual.out.contains("result_is_not_null"));
+    assert!(actual.err.is_empty());
```
Comment (sholderbach) [inline src/tests/test_custom_commands.rs:189]: Not sure what this test adds to the one above? A worthy test would be to test if a function that is terminating the recursion properly within the recursion limit passes.

**Review by sholderbach — CHANGES_REQUESTED** [review]
I think there was a slight misunderstanding what the graceful handling/no panic means. Thanks for implementing the internals. Let's get the tests up to date and see if we can move this forward to landing.

**Comment by Mehrbod2002** [comment]
@sholderbach yap it was misunderstanding with recursion , from now on it will return error when reaches to out limitation. Can consider to look it .

**Comment by sholderbach** [comment]
Thanks for the quick turnaround!

File: crates/nu-engine/src/eval.rs (hunk 3 above)
Comment (rgwood) [reply crates/nu-engine/src/eval.rs]: No. `NushellFailed` is not appropriate. From the comments for `NushellFailed`:
> /// Catastrophic nushell failure. This reflects a completely unexpected or unrecoverable error.
> /// It is very likely that this is a bug. Please file an issue at https://github.com/nushell/nushell/issues with relevant information.
> // Only use this one if Nushell completely falls over and hits a state that isn't possible or isn't recoverable

I have pushed a commit with a new `ShellError` variant like I suggested.

**Comment by Mehrbod2002** [comment]
Thanks everyone .
and your effort @rgwood  . 🤟🏻

**Comment by rgwood** [comment]
Thank you! This is a nice improvement.

**Comment by Mehrbod2002** [comment]
> I'm not sure if we've broken this again or if it never worked with this PR, but I used to be able to do this an have it work fine. Now it gives a stack overflow error like this 
> ```
> thread 'main' has overflowed its stack
> ```
> 
> ```bash
> def old-ls [path?] {
>   if $path == $nothing {
>     ls . | sort-by type name -i
>   } else {
>     ls $path | sort-by type name -i
>   }
> }
> 
> # ls sort type name -i
> def ls [path?] {
>   if $path == $nothing {
>     old-ls .
>   } else {
>    old-ls $path
>   }
> }
> ```
Can't reproduce it .
Related to Recursion_limit size , we can increase size with tests and step step , but have to make sure about all architecture will work fine

**Comment by fdncred** [comment]
@Mehrbod2002 I wonder if this stack overflow is because the I'm sourcing these defs. For instance, if I copy and paste them in an active nushell session, the new `ls` command works fine. However, if I have those in my `defs.nu` script that gets sourced at nushell launch, then I run `ls`, I get the stack overflow.

**Comment by Mehrbod2002** [comment]
@fdncred So I believe something happening with Stack , act different on Nu script and active session , could be ?

**Comment by Mehrbod2002** [comment]
@fdncred 
Going to debug it by Nu script

**Comment by Mehrbod2002** [comment]
@fdncred something wired .
> > ```shell
> > def old-ls [path?] {
> >   if $path == $nothing {
> >     ls . | sort-by type name -i
> >   } else {
> >     ls $path | sort-by type name -i
> >   }
> > }
> > 
> > # ls sort type name -i
> > def ls [path?] {
> >   if $path == $nothing {
> >     old-ls .
> >   } else {
> >    old-ls $path
> >   }
> > }
> > ```
> 
if you change name second function name from `ls` to something else work alright .
these are not recursion function , stack overflow error is main rust error not Nushell stack overflow , as recursion_limit will not set for these functions as they aren't .
thinking about another situation with response . looking to hear your opining too .

**Comment by fdncred** [comment]
Right, I realize it works with naming `def ls` something like `def lss`. It's always worked that way, but it used to work by naming it `def ls` as well. I wonder what broke that?

The reason why I had to have 2 defs was because it was a recursion thing. I originally tried to write it like this, and it would fail due to a recursion error.
```bash
def ls [path?] {
  if $path == $nothing {
    ls . | sort-by type name -i
  } else {
    ls $path | sort-by type name -i
  }
}
```
That's when I found out that I could have one def call another def and bypass the stack overflow. But that doesn't work any longer. :(

**Comment by Mehrbod2002** [comment]
@fdncred by this I think it would be better thinking about some situation like this situation ;
Have to some rules on alias or def on keyword or external variable . am i right ?

**Comment by fdncred** [comment]
Well, I'd just like it to work the way it did before. I don't expect ls calling ls to work, but that shouldn't throw a stack overflow message either.

**Comment by Mehrbod2002** [comment]
> Well, I'd just like it to work the way it did before. I don't expect ls calling ls to work, but that shouldn't throw a stack overflow message either.

This PR implemented creating Def and set recursion,  thing we have to set recursion for commands too .
