### PR TITLE
use `Stack::get_config()` in more places

### LINKED ISSUE #12746: Inconsistent runtime interpretation of `$env.config` by internal commands (`help`, errors output)
### Describe the bug

For certain internal commands (such as `help` and error output) Newly assigned `$env.config` options within the same script/statement will be updated lazily. 

These options will only take effect for the next command in the interactive session. In the `--commands` mode and scripts `nu test.nu` they will not affect the entire command/script. 

For other internal commands such as`ls` changes in `$env.config` will be visible immediately.

### How to reproduce

1. with `help`
```nu
nu -c "$env.config.use_ansi_coloring = false ; help ls"
# this works
nu -c "$env.config.use_ansi_coloring = false ; ls"
```
Interactive session:
```nu
$env.config.use_ansi_coloring = false ; help ls # Here help still contains ansi

help ls # Here doesn't
```

2. with errors and `use_ansi_coloring`:
```nu
nu -c "$env.config.use_ansi_coloring = false ; error make {msg: 'error still contains ansi'}"
```

3. with errors and `error_style`:
```nu
nu -c "$env.config.error_style = 'plain' ; error make {msg: 'error is still fancy'}"
```

### Expected behavior

Updating the config in the same way as for `ls` for all internal outputs

### Screenshots

_No response_

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.93.1                                          |
| major              | 0                                               |
| minor              | 93                                              |
| patch              | 1                                               |
| branch             | main                                            |
| commit_hash        | bdb6daa4b5046629a88739fb0a2742d5729c04d8        |
| build_os           | macos-aarch64                                   |
| build_target       | aarch64-apple-darwin                            |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)             |
| rust_channel       | 1.77.2-aarch64-apple-darwin                     |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)             |
| build_time         | 2024-05-03 16:22:16 +04:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  |                                                 |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sgvictorino**
Closes #12746

# Release notes summary - What our users need to know

More behavior now reflects changes to `$env.config` during script
execution or within a REPL line:

```diff
$env.config.datetime_format.normal = "%F"; $"(date now)"
-Sun, 23 Nov 2025 06:07:00 -0000 (now)
+2025-11-23
```

### CODE REVIEW

File: crates/nu-protocol/src/errors/report_error.rs [hunk 1]
```diff
@@ -86,62 +89,75 @@ where
...
-    report_warning(working_set, warning, "nu::experimental_option::warning");
+    report_warning(
+        config,
+        working_set,
+        warning,
+        "nu::experimental_option::warning",
+    );
 }
 
 fn report_error(
```
Comment (WindSoilder) [inline crates/nu-protocol/src/errors/report_error.rs:168]: Is there any reason to change this function to accept a `config`?

Comment (sgvictorino) [reply crates/nu-protocol/src/errors/report_error.rs:168]: When applicable I pass the stack's config so errors are formatted correctly:

```
> $env.config.error_style = "plain"; error make { msg: "a plain error" }
Error: a plain error
    Diagnostic severity: error
Begin snippet for entry #1 starting at line 1, column 1
...
```

Comment (WindSoilder) [reply crates/nu-protocol/src/errors/report_error.rs:168]: I think it'd be good to require passing `stack: Option<&Stack>`, it's easy to make user understand the semantic: if you have a stack, pass it, or else pass None.
