### PR TITLE
Fix #3231: Pick up nu-env if cd with shortcuts

### LINKED ISSUE #3231: Autoenv doesn't respect `..` shortcut
**Describe the bug**
If you change directory out of the trusted directory with `..` instead of `cd ..` the exit script doesn't run.

Follow-up from https://github.com/nushell/nushell/pull/3041

**To Reproduce**
1. `autoenv trust` the file below
```
        startup = ["echo ...entering the directory", "echo 1 2 3"]
        on_exit = ["echo ...leaving the directory"]

        [env]
        mykey = "myvalue"
```
2. then `cd` into this directory
3. then use `..` to change directory out of this directory

**Expected behavior**
The `..` should work the same as `cd ..` and run the exit script.

```
> version | pivot
────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────
 #  │      Column0       │                                      Column1                                       
────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────
  0 │ version            │ 0.29.0                                                                             
  1 │ branch             │ refactor/cli-env                                                                   
  2 │ short_commit       │ 267fe6ee                                                                           
  3 │ commit_hash        │ 267fe6ee563ea8a9ade400ebacdb3ad6eb5ab3ea                                           
  4 │ commit_date        │ 2021-03-31 09:10:58                                                                
  5 │ build_os           │ linux-x86_64                                                                       
  6 │ rust_version       │ rustc 1.51.0 (2fd73fabe 2021-03-23)                                                
  7 │ rust_channel       │ stable-x86_64-unknown-linux-gnu (default)                                          
  8 │ cargo_version      │ cargo 1.51.0 (43b129a20 2021-03-16)                                                
  9 │ pkg_version        │ 0.29.0                                                                             
 10 │ build_time         │ 2021-03-31 18:46:32                                                                
 11 │ build_rust_channel │ debug                                                                              
 12 │ features           │ ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, uuid, which, zip 
────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────
```

cc @LhKipp

### PR DESCRIPTION
**Pull request by LhKipp**
This PR fixes #3231.

### CODE REVIEW

File: crates/nu-command/src/commands/run_external.rs [hunk 1]
```diff
@@ -3,21 +3,19 @@ use crate::prelude::*;
...
-use nu_source::Tagged;
 
 #[derive(Deserialize)]
 pub struct RunExternalArgs {}
 
 #[derive(new)]
 pub struct RunExternalCommand {
     /// Whether or not nushell is being used in an interactive context
+    #[allow(dead_code)]
     pub(crate) interactive: bool,
```
Comment (LhKipp) [inline crates/nu-command/src/commands/run_external.rs:19]: interactive is not used anymore. I allowed dead code, so that I don't have to remove it and adjust every user (makes for an easier diff).

File: crates/nu-command/src/commands/run_external.rs [hunk 2]
```diff
@@ -86,12 +84,9 @@ impl WholeStreamCommand for RunExternalCommand {
                 ctrl_c: args.ctrl_c.clone(),
                 configs: args.configs.clone(),
                 current_errors: Arc::new(Mutex::new(vec![])),
-                windows_drives_previous_cwd: Arc::new(Mutex::new(std::collections::HashMap::new())),
```
Comment (LhKipp) [inline crates/nu-command/src/commands/run_external.rs:89]: windows_drives_previous_cwd is moved from ctx into shell_manager.

This variable is only used for cd'ing and is therefore closer to shellmanager

File: crates/nu-command/src/commands/run_external.rs [hunk 3]
```diff
@@ -101,25 +96,6 @@ impl WholeStreamCommand for RunExternalCommand {
             },
         };
 
-        // If we're in interactive mode, we will "auto cd". That is, instead of interpreting
-        // this as an external command, we will see it as a path and `cd` into it.
-        if is_interactive {
-            if let Some(path) = maybe_autocd_dir(&command, &mut external_context) {
-                let cd_args = CdArgs {
```
Comment (LhKipp) [inline crates/nu-command/src/commands/run_external.rs:108]: This code is removed and the case is handled in cd. 

(Actually I strongly believe and tested that maybe_autocd_dir never returns Some(...), as this case was handled in script.rs before anyways.)

File: crates/nu-command/src/commands/run_external.rs [hunk 4]
```diff
@@ -131,55 +107,3 @@ impl WholeStreamCommand for RunExternalCommand {
...
-            && !ctx.host.lock().is_external_cmd(&name))
-    {
-        Some(name)
-    } else {
-        None
-    };
-
-    path_name.map(|name| {
-        #[cfg(windows)]
-        {
```
Comment (LhKipp) [inline crates/nu-command/src/commands/run_external.rs:155]: The following logic is reused.

File: crates/nu-engine/src/filesystem/filesystem_shell.rs [hunk 5]
```diff
@@ -34,6 +38,8 @@ pub struct FilesystemShell {
     pub(crate) path: String,
     pub(crate) last_path: String,
     pub(crate) mode: FilesystemShellMode,
+    #[cfg(windows)]
+    pub(crate) windows_drives_previous_cwd: Arc<Mutex<IndexMap<String, String>>>,
```
Comment (LhKipp) [inline crates/nu-engine/src/filesystem/filesystem_shell.rs:42]: Every fs_shell has one instance of windows_drives_previous_cwd. This instance is shared with all other fs_shells and comes from shell_manager.

File: crates/nu-engine/src/filesystem/filesystem_shell.rs [hunk 6]
```diff
@@ -84,6 +90,45 @@ impl FilesystemShell {
             mode,
         })
     }
+
+    fn get_previous_drive_location_if_shortcut(
```
Comment (LhKipp) [inline crates/nu-engine/src/filesystem/filesystem_shell.rs:94]: This logic is copied from run_external.rs / script.rs

File: crates/nu-engine/src/filesystem/filesystem_shell.rs [hunk 7]
```diff
@@ -241,6 +286,10 @@ impl Shell for FilesystemShell {
                 let Tagged { item: target, tag } = v;
                 if target == Path::new("-") {
                     PathBuf::from(&self.last_path)
+                } else if let Some(previous_drive_cwd) =
+                    self.get_previous_drive_location_if_shortcut(&target)
+                {
+                    previous_drive_cwd
```
Comment (LhKipp) [inline crates/nu-engine/src/filesystem/filesystem_shell.rs:292]: If the target of cd is a shortcut to a previous drive location we cd there

File: crates/nu-engine/src/script.rs [hunk 8]
```diff
@@ -77,32 +76,39 @@ pub fn process_script(
         // ...and it doesn't have any arguments
         // ...and we're in the CLI
         // ...then change to this directory
+        // We do this by renaming the command name to cd
```
Comment (LhKipp) [inline crates/nu-engine/src/script.rs:79]: This is the main part where the logic changed.

On current main, we cd here by doing shell_manager.set_path() directly. However, this does not trigger cd site effects (like autoenv).

With this PR applied, we cd by modifying the parsed block.
The parsed block has in this case a simplified structure of:
```
CmdName: "run_external"
arg1: "directory"
```
Where as the typical `cd directory` has a structure of:
```
CmdName: "cd"
arg1: "directory"
```
So we can trigger cd here by simply changing the name.

File: crates/nu-engine/src/shell/shell_manager.rs [hunk 9]
```diff
@@ -16,13 +18,32 @@ use std::sync::Arc;
...
 }
 
 impl ShellManager {
     pub fn enter_script_mode(&self) -> Result<(), std::io::Error> {
         //New fs_shell starting from current path
-        let fs_shell = FilesystemShell::with_location(self.path(), FilesystemShellMode::Script)?;
-        self.insert_at_current(Box::new(fs_shell));
+        let mut fs_shell =
+            FilesystemShell::with_location(self.path(), FilesystemShellMode::Script)?;
+        self.add_windows_drives_previous_cwd_to_shell(&mut fs_shell);
```
Comment (LhKipp) [inline crates/nu-engine/src/shell/shell_manager.rs:32]: We share the one instance of add_windows_drives_previous_cwd with all fs_shells. This allows to use this feature accross entered fs shells.

File: crates/nu-engine/src/script.rs [hunk 10]
```diff
@@ -117,44 +122,67 @@ pub fn process_script(
...
-                            if split_path.len() > 1 {
-                                ctx.windows_drives_previous_cwd
-                                    .lock()
-                                    .insert(split_path[0].to_string(), current_path);
-                            }
+                    let tag = Tag {
+                        anchor: Some(AnchorLocation::Source(line.into())),
+                        span: name_span,
+                    };
+                    let path = {
```
Comment (LhKipp) [inline crates/nu-engine/src/script.rs:129]: This code gained 1 level of nesting, therefore the diff shows more what actually happend. I commented lines that acutally changed.

File: crates/nu-engine/src/script.rs [hunk 11]
```diff
@@ -117,44 +122,67 @@ pub fn process_script(
...
-                            let name = name.to_uppercase();
-                            let new_drive: Vec<_> = name.split(':').collect();
+                                let name = name.to_uppercase();
+                                let new_drive: Vec<_> = name.split(':').collect();
 
-                            if let Some(val) =
-                                ctx.windows_drives_previous_cwd.lock().get(new_drive[0])
-                            {
-                                ctx.shell_manager.set_path(val.to_string());
-                                return LineResult::Success(line.to_string());
```
Comment (LhKipp) [inline crates/nu-engine/src/script.rs:142]: return val.to_string

File: crates/nu-engine/src/script.rs [hunk 12]
```diff
@@ -117,44 +122,67 @@ pub fn process_script(
...
+                                    ctx.windows_drives_previous_cwd.lock().get(new_drive[0])
+                                {
+                                    val.to_string()
+                                } else {
+                                    name.to_string()
+                                }
                             } else {
-                                ctx.shell_manager
-                                    .set_path(format!("{}\\", name.to_string()));
-                                return LineResult::Success(line.to_string());
```
Comment (LhKipp) [inline crates/nu-engine/src/script.rs:146]: path = format string

File: crates/nu-engine/src/script.rs [hunk 13]
```diff
@@ -117,44 +122,67 @@ pub fn process_script(
...
+                                name.to_string();
                             }
-                        } else {
-                            ctx.shell_manager.set_path(name.to_string());
-                            return LineResult::Success(line.to_string());
```
Comment (LhKipp) [inline crates/nu-engine/src/script.rs:150]: path = name.to_string

File: crates/nu-engine/src/script.rs [hunk 14]
```diff
@@ -117,44 +122,67 @@ pub fn process_script(
...
                         }
-                    }
-                    #[cfg(not(windows))]
-                    {
-                        ctx.shell_manager.set_path(name.to_string());
-                        return LineResult::Success(line.to_string());
```
Comment (LhKipp) [inline crates/nu-engine/src/script.rs:156]: path = name

**Comment by jonathandturner** [comment]
Looks good!
