### PR TITLE
group by to table empty

### LINKED ISSUE #16217: `group-by --to-table` produces empty _records_ on empty inputs
### Describe the bug

`group-by --to-table` does not always return a table (a list)

### How to reproduce

> `[] | group-by --to-table something`

```
╭──────────────╮
│ empty record │
╰──────────────╯
````

### Expected behavior

I expect the result to be an empty _list_ instead.

### Configuration

| key                | value                                                                               |
| ------------------ | ----------------------------------------------------------------------------------- |
| version            | 0.105.1                                                                             |
| major              | 0                                                                                   |
| minor              | 105                                                                                 |
| patch              | 1                                                                                   |
| branch             |                                                                                     |
| commit_hash        |                                                                                     |
| build_os           | linux-x86_64                                                                        |
| build_target       | x86_64-unknown-linux-gnu                                                            |
| rust_version       | rustc 1.87.0 (17067e9ac 2025-05-09) (built from a source tarball)                   |
| cargo_version      | cargo 1.87.0 (99624be96 2025-05-06)                                                 |
| build_time         | 1980-01-01 00:00:00 +00:00                                                          |
| build_rust_channel | release                                                                             |
| allocator          | standard                                                                            |
| features           | default, sqlite, trash                                                              |
| installed_plugins  | file 0.16.0, formats 0.105.1, polars 0.105.1, query 0.105.1, skim 0.15.0, vec 1.1.6 |

### PR DESCRIPTION
**Pull request by Bahex**
- fixes #16217

# Description

> `group-by --to-table` does not always return a table (a list)
> ```nushell
> [] | group-by --to-table something
> #=> ╭──────────────╮
> #=> │ empty record │
> #=> ╰──────────────╯
> ```

Fixed:
```nushell
[] | group-by --to-table something
#=> ╭────────────╮
#=> │ empty list │
#=> ╰────────────╯
```

# Tests + Formatting
+1 test

### CODE REVIEW

File: crates/nu-command/tests/commands/group_by.rs [hunk 1]
```diff
@@ -73,6 +73,13 @@ fn group_by_on_empty_list_returns_empty_record() {
     assert!(actual.out.contains("empty record"));
 }
 
+#[test]
+fn group_by_to_table_on_empty_list_returns_empty_list() {
+    let actual = nu!("[[a b]; [1 2]] | where false | group-by --to-table a");
```
Comment (ysthakur) [inline crates/nu-command/tests/commands/group_by.rs]: Would it be better to do `| to nuon` here, to avoid matching on text?

Not a blocker

Comment (Bahex) [reply crates/nu-command/tests/commands/group_by.rs]: Just imitated the existing test, makes sense to change them both :+1:

**Comment by YPares** [comment]
@Bahex So fast ^^
