### PR TITLE
fix #9653 the cmd `detect columns` with the flag `-c`

### LINKED ISSUE #9653: detect columns crashes nushell
### Describe the bug

nu shell crashes when range is out of bounds in detect columns

fe. 

```
> echo "1 2 3 4 5\n1 2 3 4 5" | detect columns -c 1..5
thread 'main' panicked at 'range end index 6 out of range for slice of length 5', crates/nu-command/src/strings/detect_columns.rs:215:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

but also when I tried "open" range

```
> echo "1 2 3 4 5\n1 2 3 4 5" | detect columns -c 4..
thread 'main' panicked at 'range end index 6 out of range for slice of length 5', crates/nu-command/src/strings/detect_columns.rs:215:33
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::slice::index::slice_end_index_len_fail_rt
   3: core::slice::index::slice_end_index_len_fail
   4: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   5: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
   6: <nu_command::viewers::table::PagingTableCreator as core::iter::traits::iterator::Iterator>::next
   7: <nu_protocol::value::stream::RawStream as core::iter::traits::iterator::Iterator>::next
   8: nu_protocol::pipeline_data::print_if_stream
   9: nu_protocol::pipeline_data::PipelineData::print
  10: nu_cli::util::eval_source
  11: nu_cli::repl::evaluate_repl
  12: nu::run::run_repl
  13: nu::main
```

### How to reproduce

1. run `echo "1 2 3 4 5\n1 2 3 4 5" | detect columns -c 4..`

### Expected behavior

should show some error message but shell should not die

### Screenshots

```
project> echo "1 2 3 4 5\n1 2 3 4 5" | detect columns -c 4..                                                           07/11/2023 09:54:20 AM
thread 'main' panicked at 'range end index 6 out of range for slice of length 5', crates/nu-command/src/strings/detect_columns.rs:215:33
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::slice::index::slice_end_index_len_fail_rt
   3: core::slice::index::slice_end_index_len_fail
   4: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   5: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
   6: <nu_command::viewers::table::PagingTableCreator as core::iter::traits::iterator::Iterator>::next
   7: <nu_protocol::value::stream::RawStream as core::iter::traits::iterator::Iterator>::next
   8: nu_protocol::pipeline_data::print_if_stream
   9: nu_protocol::pipeline_data::PipelineData::print
  10: nu_cli::util::eval_source
  11: nu_cli::repl::evaluate_repl
  12: nu::run::run_repl
  13: nu::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
root@b913c261a5c5:/project# 
```

### Configuration

```
/project> version | transpose key value | to md --pretty
```

| key                | value                                                   |
| ------------------ | ------------------------------------------------------- |
| version            | 0.82.0                                                  |
| branch             |                                                         |
| commit_hash        | ecdb023e2f6cb17445ae799206e464b2daef3d71                |
| build_os           | linux-x86_64                                            |
| build_target       | x86_64-unknown-linux-gnu                                |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27)                     |
| rust_channel       | 1.68.2-x86_64-unknown-linux-gnu                         |
| cargo_version      | cargo 1.68.2 (6feb7c9cf 2023-03-26)                     |
| build_time         | 2023-06-27 17:34:21 +00:00                              |
| build_rust_channel | release                                                 |
| allocator          | standard                                                |
| features           | default, sqlite, static-link-openssl, trash, which, zip |
| installed_plugins  |                                                         |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mengsuenyan**
fix `detect columns` with flag `-c, --combine-columns` run failed when using some range

- fixes #9653 

fix #9653 the cmd detect columns with the flag -c, --combine-columns run failed when using some range.

add unit test for the command `detect columns`

```text
Attempt to automatically split text into multiple columns.

Usage:
  > detect columns {flags} 

Flags:
  -h, --help - Display the help message for this command
  -s, --skip <Int> - number of rows to skip before detecting
  -n, --no-headers - don't detect headers
  -c, --combine-columns <Range> - columns to be combined; listed as a range

Signatures:
  <string> | detect columns -> <table>

Examples:
  Splits string across multiple columns
  > 'a b c' | detect columns -n
  ╭───┬─────────┬─────────┬─────────╮
  │ # │ column0 │ column1 │ column2 │
  ├───┼─────────┼─────────┼─────────┤
  │ 0 │ a       │ b       │ c       │
  ╰───┴─────────┴─────────┴─────────╯

  Splits a multi-line string into columns with headers detected
  > $'c1 c2 c3 c4 c5(char nl)a b c d e' | detect columns
  ╭───┬────┬────┬────┬────┬────╮
  │ # │ c1 │ c2 │ c3 │ c4 │ c5 │
  ├───┼────┼────┼────┼────┼────┤
  │ 0 │ a  │ b  │ c  │ d  │ e  │
  ╰───┴────┴────┴────┴────┴────╯

  
  > $'c1 c2 c3 c4 c5(char nl)a b c d e' | detect columns -c 0..1
  ╭───┬─────┬────┬────┬────╮
  │ # │ c1  │ c3 │ c4 │ c5 │
  ├───┼─────┼────┼────┼────┤
  │ 0 │ a b │ c  │ d  │ e  │
  ╰───┴─────┴────┴────┴────╯

  Splits a multi-line string into columns with headers detected
  > $'c1 c2 c3 c4 c5(char nl)a b c d e' | detect columns -c -2..-1
  ╭───┬────┬────┬────┬─────╮
  │ # │ c1 │ c2 │ c3 │ c4  │
  ├───┼────┼────┼────┼─────┤
  │ 0 │ a  │ b  │ c  │ d e │
  ╰───┴────┴────┴────┴─────╯

  Splits a multi-line string into columns with headers detected
  > $'c1 c2 c3 c4 c5(char nl)a b c d e' | detect columns -c 2..
  ╭───┬────┬────┬───────╮
  │ # │ c1 │ c2 │  c3   │
  ├───┼────┼────┼───────┤
  │ 0 │ a  │ b  │ c d e │
  ╰───┴────┴────┴───────╯

  Parse external ls command and combine columns for datetime
  > ^ls -lh | detect columns --no-headers --skip 1 --combine-columns 5..7

```

### CODE REVIEW

**Comment by fdncred** [comment]
Thanks for working on this!

**Comment by fdncred** [comment]
Looks like the CI is having some issues with the tests.

**Review by fdncred — APPROVED** [review]
Just tested, this works as advertised. Thanks for cleaning up the code!

File: crates/nu-command/src/strings/detect_columns.rs [hunk 1]
```diff
@@ -82,8 +82,87 @@ impl Command for DetectColumns {
             },
             Example {
                 description: "Splits a multi-line string into columns with headers detected",
-                example: "$'c1 c2 c3(char nl)a b c' | detect columns",
-                result: None,
+                example: "\"c1 c2 c3 c4 c5\na b c d e\" | detect columns",
```
Comment (sholderbach) [inline crates/nu-command/src/strings/detect_columns.rs:85]: I am not sure if this get's rendered properly in our `help` or the `F1` help menu. Not sure if we take multiple lines properly into account.

Comment (fdncred) [reply crates/nu-command/src/strings/detect_columns.rs:85]: I think you're right @sholderbach. I believe it's better like this for examples.
```suggestion
                example: "$'c1 c2 c3 c4 c5(char nl)a b c d e' | detect columns",
```

Comment (mengsuenyan) [reply crates/nu-command/src/strings/detect_columns.rs:85]: the string interpolation can not be handled right by the strings::test_example and can not be test passed, so I modified by the escape string and the example display normal

**Comment by mengsuenyan** [comment]
> fix `detect columns` with flag `-c, --combine-columns` run failed when using some range
> 
> 
> 
> - fixes #9653 
> 
> 
> 
> fix #9653 the cmd detect columns with the flag -c, --combine-columns run failed when using some range.
> 
> 
> 
> add unit test for the command `detect columns`
> 
> 
> 
> ```text
> 
> Attempt to automatically split text into multiple columns.
> 
> 
> 
> Usage:
> 
>   > detect columns {flags} 
> 
> 
> 
> Flags:
> 
>   -h, --help - Display the help message for this command
> 
>   -s, --skip <Int> - number of rows to skip before detecting
> 
>   -n, --no-headers - don't detect headers
> 
>   -c, --combine-columns <Range> - columns to be combined; listed as a range
> 
> 
> 
> Signatures:
> 
>   <string> | detect columns -> <table>
> 
> 
> 
> Examples:
> 
>   Splits string across multiple columns
> 
>   > 'a b c' | detect columns -n
> 
>   ╭───┬─────────┬─────────┬─────────╮
> 
>   │ # │ column0 │ column1 │ column2 │
> 
>   ├───┼─────────┼─────────┼─────────┤
> 
>   │ 0 │ a       │ b       │ c       │
> 
>   ╰───┴─────────┴─────────┴─────────╯
> 
> 
> 
>   Splits a multi-line string into columns with headers detected
> 
>   > $'c1 c2 c3 c4 c5(char nl)a b c d e' | detect columns
> 
>   ╭───┬────┬────┬────┬────┬────╮
> 
>   │ # │ c1 │ c2 │ c3 │ c4 │ c5 │
> 
>   ├───┼────┼────┼────┼────┼────┤
> 
>   │ 0 │ a  │ b  │ c  │ d  │ e  │
> 
>   ╰───┴────┴────┴────┴────┴────╯
> 
> 
> 
>   
> 
>   > $'c1 c2 c3 c4 c5(char nl)a b c d e' | detect columns -c 0..1
> 
>   ╭───┬─────┬────┬────┬────╮
> 
>   │ # │ c1  │ c3 │ c4 │ c5 │
> 
>   ├───┼─────┼────┼────┼────┤
> 
>   │ 0 │ a b │ c  │ d  │ e  │
> 
>   ╰───┴─────┴────┴────┴────╯
> 
> 
> 
>   Splits a multi-line string into columns with headers detected
> 
>   > $'c1 c2 c3 c4 c5(char nl)a b c d e' | detect columns -c -2..-1
> 
>   ╭───┬────┬────┬────┬─────╮
> 
>   │ # │ c1 │ c2 │ c3 │ c4  │
> 
>   ├───┼────┼────┼────┼─────┤
> 
>   │ 0 │ a  │ b  │ c  │ d e │
> 
>   ╰───┴────┴────┴────┴─────╯
> 
> 
> 
>   Splits a multi-line string into columns with headers detected
> 
>   > $'c1 c2 c3 c4 c5(char nl)a b c d e' | detect columns -c 2..
> 
>   ╭───┬────┬────┬───────╮
> 
>   │ # │ c1 │ c2 │  c3   │
> 
>   ├───┼────┼────┼───────┤
> 
>   │ 0 │ a  │ b  │ c d e │
> 
>   ╰───┴────┴────┴───────╯
> 
> 
> 
>   Parse external ls command and combine columns for datetime
> 
>   > ^ls -lh | detect columns --no-headers --skip 1 --combine-columns 5..7
> 
> 
> 
> ```

the above is the output of 'detect columns -h'

**Comment by fdncred** [comment]
@mengsuenyan I get this with detect columns --help
image

**Comment by fdncred** [comment]
I think what we might have to do is add the `(char nl)` in the examples, make the example's results `None` and move all the real tests to `tests/commands/detect_columns.rs`. That's probably the simplest way to resolve test errors I think.

**Comment by fdncred** [comment]
@mengsuenyan are you going to be able to make the requested changes?

**Review by fdncred — APPROVED** [review]
Thanks for making the changes I requested. Let's run with this now!
