### PR TITLE
Make HTTP requests cancellable when trying to connect

### LINKED ISSUE #8585: http command should respond to Ctrl-C
### Describe the bug

I forgot to turn on my VPN before attempting to fetch some data from a private server with nu's `http` command this morning, and I was unable to interrupt the command when I realized my mistake.  

Here's the command I executed with the identifying information blacked out.
```
➜ http get -H ['Authorization' '*****'] https://private-server/v1/users/1234567 | get identity.firstName
^C^C

# 30s later...
Error: nu::shell::network_failure

  × Network failure
   ╭─[entry #5:1:1]
 1 │ http get -H ['Authorization' '*****'] https://private-server/v1/users/1234567 | get identity.firstName
   ·                                       ───────────────────┬───────────────────
   ·                                                          ╰── https://private-server/v1/users/1234567: Network Error: timed out reading response
   ╰────

⏱ 30s
```

### How to reproduce

1. Try to fetch data using `http` from an unroutable IP address.  e.g. `http get https://10.255.255.1.1/foo`
2. Attempt to interrupt with `Ctrl-C` before the connection times out.
3. You will not be able to and must wait 30s for the connection to timeout

Example:
```
➜ http get https://10.255.255.1/foo
^C^C^C^CError: nu::shell::network_failure

  × Network failure
   ╭─[entry #6:1:1]
 1 │ http get https://10.255.255.1/foo
   ·          ────────────┬───────────
   ·                      ╰── Cannot make request to https://10.255.255.1/foo, there was an error establishing a connection.

⏱ 30s
```

### Expected behavior

The behavior I expected was for the `http` command to respect the interrupt from `Ctrl-C` and terminate.

### Screenshots

Screenshot 2023-03-23 at 10 09 26

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.77.1                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.68.0 (2c8cc3432 2023-03-06) (built from a source tarball) |
| cargo_version      | cargo 1.68.0 (115f34552 2023-02-26)                               |
| build_time         | 2023-03-17 05:10:56 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | default, zip                                                      |
| installed_plugins  |                                                                   |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rgwood**
Closes #8585.

Prior to this change, the `http` commands could get stuck for 30s while attempting to make a connection to a remote server. After this change, `ctrl+c` works as expected:

image

To make this work, we perform blocking `ureq` calls in a background thread and poll the channel while checking `ctrl+c`.

### CODE REVIEW

File: crates/nu-protocol/src/shell_error.rs [hunk 1]
```diff
@@ -1056,6 +1056,13 @@ pub enum ShellError {
         #[label("Could not access '{column_name}' on this record")]
         span: Span,
     },
+
+    /// Operation interrupted by user
+    #[error("Operation interrupted by user")]
+    InterruptedByUser {
+        #[label("This operation was interrupted")]
+        span: Option<Span>,
+    },
```
Comment (sholderbach) [inline crates/nu-protocol/src/shell_error.rs:1065]: Mhh, my slash `ShellError` brain says could this use `IOInterrupted` so we don't need yet another variant. But I am surprised we don't have a `^C` specific error yet. (future goal would then be to move other stuff to use this variant if possible)

File: crates/nu-command/src/network/http/client.rs [hunk 2]
```diff
@@ -200,19 +212,57 @@ pub fn send_request(
...
+            return Err(ShellErrorOrRequestError::ShellError(
+                ShellError::InterruptedByUser { span: None },
+            ));
+        }
+
+        if let Ok(result) = rx.try_recv() {
+            return result
+                .map_err(|e| ShellErrorOrRequestError::RequestError(request_url.to_string(), e));
+        }
+        std::thread::sleep(Duration::from_millis(100)); // arbitrarily chosen interval
```
Comment (sholderbach) [inline crates/nu-command/src/network/http/client.rs:262]: While this prevents this from turning into a burning spin lock I am not sure if there is the potential for this to stall other stuff.

I think the more appropriate alternative is to use https://doc.rust-lang.org/std/sync/mpsc/struct.Receiver.html#method.recv_timeout

**Review by sholderbach — COMMENTED** [review]
Thanks for tackling this so quickly! The general changes look good to me, the only thing I think needs a change is the blocking logic in the main command thread so we aren't forced to wait for the timeout until we can read from the `Response`.

File: crates/nu-protocol/src/shell_error.rs (hunk 1 above)
Comment (rgwood) [reply crates/nu-protocol/src/shell_error.rs:1065]: Yeah, I think it would be good to finally add a `^C`-specific error. It's something I've wanted to use a few times now.

File: crates/nu-command/src/network/http/client.rs (hunk 2 above)
Comment (rgwood) [reply crates/nu-command/src/network/http/client.rs]: Good call, done!

File: crates/nu-protocol/src/shell_error.rs (hunk 1 above)
Comment (rgwood) [reply crates/nu-protocol/src/shell_error.rs:1065]: (to clarify, I think this new `InterruptedByUser` variant is useful)

Are you OK landing this PR? Thank you for the detailed+helpful review!

File: crates/nu-command/src/network/http/client.rs (hunk 2 above)
Comment (sholderbach) [reply crates/nu-command/src/network/http/client.rs]: We still need to continue the loop when reaching the channel time out.

File: crates/nu-protocol/src/shell_error.rs (hunk 1 above)
Comment (sholderbach) [reply crates/nu-protocol/src/shell_error.rs:1065]: D'accord with the new variant. After addressing the time out "error" we can land

File: crates/nu-command/src/network/http/client.rs (hunk 2 above)
Comment (sholderbach) [reply crates/nu-command/src/network/http/client.rs]: Sorry misread the location of `.map_err` on the mobile diff. I personally would be defensive and panic or "nushell failed" when receiving another error than time out.

**Review by sholderbach — APPROVED** [review]
