### PR TITLE
Sanitize arguments to external commands a bit better

### LINKED ISSUE #4140: ";" is slipping from quotes such as a git commit message
### Describe the bug

When using `;` inside quotes, like in a git commit massage:
Screenshot from 2021-11-20 21-26-00

### How to reproduce

Type, for example:
git commit -m "update 1; update 2"

The git commit message will be only "update 1".

### Expected behavior

Work normally with quotes like in Bash.

### Screenshots

_No response_

### Configuration

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by BraulioVM**
Fixes #4140 

We are passing commands into a shell underneath but we were not
escaping arguments correctly. This new version of the code also takes
into consideration the ";" and "&" characters, which have special
meaning in shells.

We would probably benefit from a more robust way to join arguments to
shell programs. Python's stdlib has shlex.join, and perhaps we can
take that implementation as a reference.

Testing: I have added a few unit tests to the `escape_where_needed` function. Ideally I would add tests that
run an external command and verify that that works, like `^echo aa;bbb`, but I couldn't find any test like that
that I could take as reference. Also I have no idea if this test would also apply to windows because I'm
not familiar with Windows shells. Testing manually on my build of nushell did work.

### CODE REVIEW

**Comment by BraulioVM** [comment]
Oh ok robust sanitization is much easier than I thought. It's just a matter of enclosing each argument in single-quotes (https://github.com/python/cpython/blob/main/Lib/shlex.py#L325). Will fix

**Comment by BraulioVM** [comment]
From my second commit message:

```
Note that this change prevents things like:

^echo "$(ls)"

from executing the ls command (within the subshell). Instead, this will just print

$(ls)
```

**Comment by BraulioVM** [comment]
```
=== stderr

thread 'shell::pipeline::commands::external::it_evaluation::takes_rows_of_nu_value_strings' panicked at 'assertion failed: `(left == right)`
  left: `"\"jonathan_likes_cake.txt\""`,
 right: `"jonathan_likes_cake.txt"`', tests/shell/pipeline/commands/external.rs:114:13

---- shell::pipeline::commands::external::nu_commands::echo_internally_externally stdout ----
```

Ah so that's where the tests for this stuff were haha

**Comment by BraulioVM** [comment]
Ok after looking at the failing tests, I think this is going to be a bit harder than I thought... Maybe the solution in https://github.com/nushell/nushell/pull/4157/commits/09082ac5805e428b248519207b8f4393b20e160c is better.. I will keep looking into it tomorrow

**Comment by danimesq** [comment]
> This new version of the code also takes
> into consideration the ";" and "&" characters, which have special
> meaning in shells.

Characters like "(" are also slipping from quotes.

**Comment by BraulioVM** [comment]
> Characters like "(" are also slipping from quotes.

That's fixed in my build

```
/home/braulio/hacks/nushell(fix/4140)> ^cowsay "a;(&(ls)"
 __________
< a;(&(ls) >
 ----------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```


I have added the tests I meant to add. I think this is ready for review

**Comment by danimesq** [comment]
@fdncred ❤

File: crates/nu-command/src/classified/external.rs [hunk 1]
```diff
@@ -172,9 +164,29 @@ fn spawn_cmd_command(command: &ExternalCommand, args: &[String]) -> Command {
     process
 }
 
+fn has_unsafe_shell_characters(arg: &str) -> bool {
+    lazy_static! {
```
Comment (fdncred) [inline crates/nu-command/src/classified/external.rs:168]: please excuse my ignorance here, but why is lazy_static required here. I thought lazy_static ws for consts or globals or something like that?

Comment (BraulioVM) [reply crates/nu-command/src/classified/external.rs:168]: The reason we want it is:
1. We don't want to compile the regex every time it has to be used. It will be used a bunch of times (once for every external command argument), and it's always the same regex.
2. It cannot be a regular static. I guess this is because it allocates internally? It must, given that regexes can be arbitraily complex but I can't say for sure.

This pattern is actually documented in the regex crate https://github.com/rust-lang/regex#usage-avoid-compiling-the-same-regex-in-a-loop ! And I must say, that's where I got the idea of using `lazy_static` from, as I'm a rust beginner.

**Comment by fdncred** [comment]
Thanks!

**Comment by danimesq** [comment]
When it will be included in the next release?

**Comment by fdncred** [comment]
you can see it in the #general channel in discord, which says Dec 7.
