### PR TITLE
Fixed to/from toml date format

### LINKED ISSUE #11751: `to/from toml` doesn't use native TOML date format
### Describe the bug

When converting dates to toml, dates are converted to a string instead of the TOML dates.  The same applies to the `from` conversion.

### How to reproduce

```Nushell
~> {date: 2024-02-02} | to toml
date = "2024-02-02 00:00:00 +00:00"
~> "dob = 1979-05-27T07:32:00-08:00" | from toml
╭─────┬───────────────────────────╮
│ dob │ 1979-05-27T07:32:00-08:00 │
╰─────┴───────────────────────────╯
```

### Expected behavior

Converting Nushell dates to TOML dates and visa versa.

### Screenshots

_No response_

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.89.0                                                       |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (Alpine Linux 1.72.1-r0) |
| cargo_version      | cargo 1.72.1                                                 |
| build_time         | 2024-01-13 03:02:49 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, trash, which, zip                           |
| installed_plugins  |                                                              |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dannou812**
With this PR i try to resolve #11751 

# Description
I am rather new to Rust so if anything is not the way it should be please let me know.

As described in the title I just fixed the date conversion in the to and from toml commands as i thought it would be a good first issue. The example of the original issue will now work as follows:

```
~> {date: 2024-02-02} | to toml
date = "2024-02-02T00:00:00+00:00"
~> "dob = 1979-05-27T07:32:00-08:00" | from toml
╭─────┬───────────────────────────╮
│ dob │ 44 years ago              |
╰─────┴───────────────────────────╯
```

The `from toml` command now returns a nushell date which is displayed as `44 years ago` in this case.

# User-Facing Changes
none

# Tests + Formatting
all tests pass and formatting has been applied

### CODE REVIEW

File: crates/nu-command/src/formats/from/toml.rs [hunk 1]
```diff
@@ -23,6 +24,19 @@ impl Command for FromToml {
         "Parse text as .toml and create record."
     }
 
+    fn run(
+        &self,
+        __engine_state: &EngineState,
```
Comment (fdncred) [inline crates/nu-command/src/formats/from/toml.rs:29]: Probably just need 1 underscore here.
```suggestion
        _engine_state: &EngineState,
```

File: crates/nu-command/src/formats/to/toml.rs [hunk 2]
```diff
@@ -51,7 +52,9 @@ fn helper(engine_state: &EngineState, v: &Value) -> Result<toml::Value, ShellErr
         Value::Int { val, .. } => toml::Value::Integer(*val),
         Value::Filesize { val, .. } => toml::Value::Integer(*val),
         Value::Duration { val, .. } => toml::Value::String(val.to_string()),
-        Value::Date { val, .. } => toml::Value::String(val.to_string()),
+        Value::Date { val, .. } => {
+            toml::Value::String(val.to_rfc3339_opts(SecondsFormat::AutoSi, false))
```
Comment (fdncred) [inline crates/nu-command/src/formats/to/toml.rs:56]: I'm not familiar with `AutoSi`. Would you mind explaining it please?

**Review by fdncred — CHANGES_REQUESTED** [review]
Thanks for this PR. It seems like a pretty small change. For your first rust PR I'd like to say, good job! There are just a few minor changes that I think we need.

It would also be good to have a test in order to ensure this functionality continues to work as other people make changes.

File: crates/nu-command/src/formats/to/toml.rs (hunk 2 above)
Comment (dannou812) [reply crates/nu-command/src/formats/to/toml.rs:56]: This will, by default include hours minutes and seconds and if there are milliseconds or microseconds and so on it will include those as well.

Comment (fdncred) [reply crates/nu-command/src/formats/to/toml.rs:56]: Ah, ok. Thanks for explaining it.

File: crates/nu-command/src/formats/from/toml.rs [hunk 3]
```diff
@@ -80,7 +81,9 @@ fn convert_toml_to_value(value: &toml::Value, span: Span) -> Value {
             span,
         ),
         toml::Value::String(s) => Value::string(s.clone(), span),
-        toml::Value::Datetime(d) => Value::string(d.to_string(), span),
+        toml::Value::Datetime(d) => {
+            Value::date(chrono::DateTime::from_str(&d.to_string()).unwrap(), span)
```
Comment (fdncred) [inline crates/nu-command/src/formats/from/toml.rs:85]: We do not allow unwrap() except in tests.

**Comment by dannou812** [comment]
I've added tests for both commands now. Also I removed the `unwrap()` call and replaced it with an `expect()` call

File: crates/nu-command/src/formats/from/toml.rs [hunk 4]
```diff
@@ -80,7 +81,10 @@ fn convert_toml_to_value(value: &toml::Value, span: Span) -> Value {
             span,
         ),
         toml::Value::String(s) => Value::string(s.clone(), span),
-        toml::Value::Datetime(d) => Value::string(d.to_string(), span),
+        toml::Value::Datetime(d) => Value::date(
+            chrono::DateTime::from_str(&d.to_string()).expect("from toml date conversion"),
```
Comment (fdncred) [inline crates/nu-command/src/formats/from/toml.rs:85]: Is it possible to have neither unwrap() nor expect() here to keep from panicking? Chrono is super susceptible to panics and we try to avoid them at all costs. Sorry I didn't say that earlier.

Comment (dannou812) [reply crates/nu-command/src/formats/from/toml.rs:85]: What would be the optimal way if the result is not available? Because I don't really see what could be done if the to_string() goes wrong.

Comment (fdncred) [reply crates/nu-command/src/formats/from/toml.rs:85]: Since it needs to be a date, I think we have to supply a sentinel value.

Comment (fdncred) [reply crates/nu-command/src/formats/from/toml.rs:85]: Feel free to think about this a little more. If we can have a date based on what is provided, then that's fine too. So, the question is, in the small case where to_string fails, would it be better to have the date represented as a string in the toml, or would it be better to have a sentinel value? I'm good with whatever direction you want to go.

Comment (dannou812) [reply crates/nu-command/src/formats/from/toml.rs]: I just added the fix for error case, I decided to return the default date instead of a valid string of some kind since this will make piping this command less of an inconvenience in my opinion.
