### PR TITLE
Shell Integration

### LINKED ISSUE #5138: Terminal.app "Automatically Mark Prompt Lines" is broken when starship is enabled in nushell
### Describe the bug

Terminal.app Has a feature to "mark" prompt lines so command+up/down arrow jump to the previous or next prompt. Marks are denoted by a `[` on the left side of the terminal. This feature normally works with nushell, but when starship is installed as the prompt in nushell this functionality is broken and no marks are created for prompt lines.

### How to reproduce

1. Install starship as the prompt for nushell following the instructions in the nushell docs OR starship's docs.
2. Open Terminal.app
3. hit enter a few times (notice marks are not being created, there is no `[` on the prompt line)
4. command+up arrow and input doesn't jump to previous prompt

### Expected behavior

I expect prompt lines to be marked. In the screenshot you can see this is working with `starship` and `fish` (first few prompt lines), but not `starship` and `nushell` (later prompt lines with no `[`)

### Screenshots

Screen Shot 2022-04-08 at 3 12 08 PM

### Configuration

| key                | value                                 |
| ------------------ | ------------------------------------- |
| version            | 0.60.0                                |
| build_os           | macos-aarch64                         |
| rust_version       | rustc 1.59.0                          |
| cargo_version      | cargo 1.59.0                          |
| pkg_version        | 0.60.0                                |
| build_time         | 2022-03-22 19:07:11 +00:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by schrieveslaach**
# Description

This PR renders ANSI chars in order to provide shell integrations such Kitty's opening feature that captures the output of the last command in a pager such as less.

Fixes #5138

I was thinking about the Shell integrations independently from #5138 and I created the code without noticing this issue. So, I did not had issue's discussion as an inspiration. :wink: Surely, I'm willing to finalize it so that Nushell integrates nicely with modern shells.

The suggested changes work with Nushell commands but external commands do not work yet. For example, the output of `cargo run` won't be captured by Kitty's output capturing. Here I would appreciate any guidance.

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [ ] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [ ] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

File: crates/nu-cli/src/repl.rs [hunk 1]
```diff
@@ -263,6 +263,11 @@ pub fn evaluate_repl(
         }
 
         let input = line_editor.read_line(prompt);
+
+        // Just before running a command/program, send the escape code (see
+        // https://sw.kovidgoyal.net/kitty/shell-integration/#notes-for-shell-developers)
+        print!("\x1b]133;C\x1b\\");
```
Comment (schrieveslaach) [inline crates/nu-cli/src/repl.rs:269]: I'll bet that this is the wrong place for printing this here. Here would some guidance helpful.

**Comment by fdncred** [comment]
i think we need to have a way to disable this stuff, so it would either need to be behind a feature or have a config point in config.nu. it could use `config.use_ansi_coloring` for starters maybe. I'm just worried about emitting ansi escapes when all terminal emulators don't support all of them.

**Comment by schrieveslaach** [comment]
@fdncred, I utilized `config.use_ansi_coloring` to enable/disable the shell integration. Please, have a look.

Do you have any idea why external commands do not work?

**Comment by fdncred** [comment]
> Do you have any idea why external commands do not work?

Can you help me understand what external commands aren't working? I just tried your PR and was able to `cat build.rs` without issues.

**Comment by schrieveslaach** [comment]
> Can you help me understand what external commands aren't working?

None of the external command is working with Kitty's `ctrl + shift + g` capturing short. Have a look:

grafik

**Comment by fdncred** [comment]
i have kitty but have no clue what `ctrl-shift-g` is supposed to do. lol - sorry i'm so ignorant with terminal workflows.

**Comment by fdncred** [comment]
as a side not, we also may want to add the ability to set the tab title with code similar to this.

**Comment by schrieveslaach** [comment]
> i have kitty but have no clue what ctrl-shift-g is supposed to do. lol - sorry i'm so ignorant with terminal workflows.

FYI: the feature I captured above is described [here](https://sw.kovidgoyal.net/kitty/shell-integration/).

Do you know if there is some special handling of external command and is that handling the reason why it isn't working work external commands?

> as a side not, we also may want to add the ability to set the tab title with code similar to this.

Yes, that's on my list for this PR. First, I want to figure out why `ctrl+shift+g` is not working. :wink: Additionally, I was wondering what a good interface for determining the content would be (as mentioned [here](https://github.com/nushell/nushell/issues/5138#issuecomment-1095405233)). Something like this:

```
let-env TITLE_COMMAND = {
   echo [ env.$USER '@' (hostname) ] | str collect
}
```

**Comment by fdncred** [comment]
I think you're going to have to merge main before we can test again. Having PRs around releases is a pain sometimes.

I enabled `map ctrl+shift+g show_last_command_output` in kitty and it seems to work with 0.61. I was able to do `ls -al`, watch the output scroll out of view, then hit ctrl+shift+g and it opened up in `less` for paging. You can also do `ls -al | table | less -FRX` to do the same thing but it's less convenient.

I think a good way to set the tab title would be an env var. Seems reasonable to me.

**Comment by fdncred** [comment]
Let's try this and see what happens.
