### PR TITLE
fix(parser): empty span of unbalanced delimiter

### LINKED ISSUE #16284: Panic in `parse_{let|mut|const}` with colon and opposed parens/braces
### Describe the bug

The parsing of binding declarations (`let`/`mut`/`const`) fails under the following circumstances:

1. Binding keyword 
2. No binding name
3. `:` for type specification
4. No type syntax
5. opposed pairing of either parentheses or braces (i.e. having block/subexpression properties) Does not trigger for `][`.

Found via fuzzing of the `parse_with_keywords` target :)

### How to reproduce

Paste:

```nushell
let : )(
```

Observe how your face resembles `: )(`

```
× Main thread panicked.
  ├─▶ at crates/nu-parser/src/parser.rs:3509:65
  ╰─▶ index out of bounds: the len is 0 but the index is 0
         0: 0x584c2d85dd2d - rust_begin_unwind
                      at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/panicking.rs:695
         1: 0x584c2d88d0b0 - core::panicking::panic_fmt::h5764ee7030b7a73d
                      at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/core/src/panicking.rs:75
         2: 0x584c2d88d292 - core::panicking::panic_bounds_check::h0328ca7e7f0749c4
                      at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/core/src/panicking.rs:273
         3: 0x584c2c092797 - <usize as core::slice::index::SliceIndex<[T]>>::index::hd1dd51ab3912034f
                      at /home/stefan/.rustup/toolchains/1.86.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:274
         4: 0x584c2c08dad1 - core::slice::index::<impl core::ops::index::Index<I> for [T]>::index::hee57d0016dde1f6a
                      at /home/stefan/.rustup/toolchains/1.86.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:16
                       - <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index::h3891ab36bc43f826
                      at /home/stefan/.rustup/toolchains/1.86.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:3358
         5: 0x584c2c0c15e6 - nu_parser::parser::parse_var_with_opt_type::hff03f0ecd9f171f0
                      at /home/stefan/nushell/crates/nu-parser/src/parser.rs:3509
         6: 0x584c2c0a4e4f - nu_parser::parser::parse_multispan_value::h5c038c4df499c85e
                      at /home/stefan/nushell/crates/nu-parser/src/parser.rs:850
         7: 0x584c2c0a8ad6 - nu_parser::parser::parse_internal_call::h5a360865c8577ae1
                      at /home/stefan/nushell/crates/nu-parser/src/parser.rs:1234
         8: 0x584c2c07662a - nu_parser::parse_keywords::parse_let::h76b90db079365a21
                      at /home/stefan/nushell/crates/nu-parser/src/parse_keywords.rs:3402
         9: 0x584c2c0df2bf - nu_parser::parser::parse_builtin_commands::hd8391f8e01d382ba
                      at /home/stefan/nushell/crates/nu-parser/src/parser.rs:6058
        10: 0x584c2c0e3634 - nu_parser::parser::parse_pipeline::h0e161b60bfe8cf0e
                      at /home/stefan/nushell/crates/nu-parser/src/parser.rs:6493
        11: 0x584c2c0e3ca9 - nu_parser::parser::parse_block::ha0e7cfb95b101889
                      at /home/stefan/nushell/crates/nu-parser/src/parser.rs:6527
        12: 0x584c2c0e9636 - nu_parser::parser::parse::he6929809bcf933aa
                      at /home/stefan/nushell/crates/nu-parser/src/parser.rs:7083
        13: 0x584c2bc5968e - nu_cli::syntax_highlight::highlight_syntax::hc782dec78cb8cdef
                      at /home/stefan/nushell/crates/nu-cli/src/syntax_highlight.rs:46
        14: 0x584c2bc5933c - <nu_cli::syntax_highlight::NuHighlighter as reedline::highlighter::Highlighter>::highlight::h17a00a5676e86896
                      at /home/stefan/nushell/crates/nu-cli/src/syntax_highlight.rs:21
        15: 0x584c2be489da - reedline::engine::Reedline::buffer_paint::h646fba33d9221b78
                      at /home/stefan/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/reedline-0.41.0/src/engine.rs:1756
        16: 0x584c2be45afb - reedline::engine::Reedline::repaint::h9d096876b213bae7
                      at /home/stefan/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/reedline-0.41.0/src/engine.rs:1521
        17: 0x584c2be3ed8c - reedline::engine::Reedline::read_line_helper::hc16b34bbd176d9a2
                      at /home/stefan/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/reedline-0.41.0/src/engine.rs:814
        18: 0x584c2be3e0dd - reedline::engine::Reedline::read_line::hf1614ad5e2ac10a1
                      at /home/stefan/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/reedline-0.41.0/src/engine.rs:650
        19: 0x584c2bbe2039 - nu_cli::repl::loop_iteration::hc3050af2552c6bf2
                      at /home/stefan/nushell/crates/nu-cli/src/repl.rs:487
        20: 0x584c2bc63e12 - nu_cli::repl::evaluate_repl::{{closure}}::h64418602f50e8d3e
                      at /home/stefan/nushell/crates/nu-cli/src/repl.rs:189
        21: 0x584c2bbd48ff - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h58f31e1038de5307
                      at /home/stefan/.rustup/toolchains/1.86.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272
        22: 0x584c2bcd2d28 - std::panicking::try::do_call::h2a6de2c01561b44f
                      at /home/stefan/.rustup/toolchains/1.86.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:587
        23: 0x584c2bca149b - __rust_try
        24: 0x584c2bca13de - std::panicking::try::h017172b414b0dc7b
                      at /home/stefan/.rustup/toolchains/1.86.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:550
                       - std::panic::catch_unwind::he09f0d04db080a36
                      at /home/stefan/.rustup/toolchains/1.86.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:358
        25: 0x584c2bbdba27 - nu_cli::repl::evaluate_repl::hfd4a7fe1f33915fc
                      at /home/stefan/nushell/crates/nu-cli/src/repl.rs:188
        26: 0x584c29e6de89 - nu::run::run_repl::h2609748962168306
                      at /home/stefan/nushell/src/run.rs:207
        27: 0x584c29e9ec70 - nu::main::h4e6b99472a8e8fb7
                      at /home/stefan/nushell/src/main.rs:535
        28: 0x584c29e8da9b - core::ops::function::FnOnce::call_once::h35f768ee557759f3
                      at /home/stefan/.rustup/toolchains/1.86.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
```

Alternates:
```nushell
let : }{
mut : )(
mut : }{
const : )(
const : }{
```

### Expected behavior

No panic, boring syntax errors

### Configuration

| key                  | value                                              |
| -------------------- | -------------------------------------------------- |
| version              | 0.106.1                                            |
| major                | 0                                                  |
| minor                | 106                                                |
| patch                | 1                                                  |
| branch               | main                                               |
| commit_hash          | c921eadc6aa840e35b4f1e3c80ea8654483f87e1           |
| build_os             | linux-x86_64                                       |
| build_target         | x86_64-unknown-linux-gnu                           |
| rust_version         | rustc 1.86.0 (05f9846f8 2025-03-31)                |
| rust_channel         | 1.86.0-x86_64-unknown-linux-gnu                    |
| cargo_version        | cargo 1.86.0 (adf9b6ad1 2025-02-28)                |
| build_time           | 2025-07-28 22:25:47 +02:00                         |
| build_rust_channel   | debug                                              |
| allocator            | standard                                           |
| features             | default, plugin, rustls-tls, sqlite, trash-support |
| installed_plugins    | plotters 0.1.7+0.105.1                             |
| experimental_options | example=false, reorder-cell-paths=false            |

### PR DESCRIPTION
**Pull request by blindFS**
Fixes #16284 

# Description

#15246 happens to rely on the lexer's bug to work.
Changed to a workaround solution in this PR, not sure that's good enough in terms of perf and accuracy.
@ysthakur Please take your time to review the changes of `parse_record` with care.

# User-Facing Changes

# Tests + Formatting

+1

# After Submitting

### CODE REVIEW

**Comment by blindFS** [comment]
To illustrate what happens for `{a:b}/` before this fix:

The check of
https://github.com/nushell/nushell/blob/2e4900f08504c96365b0c85aa5076dff864ce2e6/crates/nu-parser/src/parser.rs#L6220-L6224

depends on the off-by-1 `span.end` of an unbalanced `}` token to pass. `lex_state.input` is overwritten in

https://github.com/nushell/nushell/blob/2e4900f08504c96365b0c85aa5076dff864ce2e6/crates/nu-parser/src/lex.rs#L499-L506

Which is the consequence of lexing `a:b}/` where the span start is increased by 1 in line 6197, while the span end is untouched, deviating from the meaning of `inner_span`

https://github.com/nushell/nushell/blob/2e4900f08504c96365b0c85aa5076dff864ce2e6/crates/nu-parser/src/parser.rs#L6193-L6211

I suppose the ideal way to solve this issue is to fix the `span` argument passed in from `parse_brace_expr` so that trailing `/` is not included in the first place.

File: crates/nu-parser/src/parser.rs [hunk 1]
```diff
@@ -6174,10 +6174,12 @@ pub fn parse_record(working_set: &mut StateWorkingSet, span: Span) -> Expression
         span_offset: start,
     };
     while !lex_state.input.is_empty() {
-        if lex_state.input[0] == b'}' {
-            extra_tokens = true;
-            unclosed = false;
-            break;
+        if let Some(ParseError::Unbalanced(left, right, _)) = lex_state.error.as_ref() {
+            if left == "{" && right == "}" {
```
Comment (ysthakur) [inline crates/nu-parser/src/parser.rs:6227]: I do see another place in the parser that checks both `left` and `right` before determining if the error is for unbalanced curly braces, but there's currently no situation where `left` would be `"{"` but `right` would be `"]"` or something. Feels kinda weird to use two separate strings rather than an enum or something, but I guess it doesn't matter that much, and it's out of scope for this PR anyway.

**Review by ysthakur — APPROVED** [review]
This looks good to me, thanks for being brave enough to plunge into the parser.

> I suppose the ideal way to solve this issue is to fix the `span` argument passed in from `parse_brace_expr` so that trailing `/` is not included in the first place.

That would be nice, but probably a harder change to make. I like how simple this PR is, much easier to review.

File: crates/nu-command/tests/commands/let_.rs [hunk 2]
```diff
@@ -123,3 +123,12 @@ fn let_raw_string() {
     let actual = nu!(r#"let x = r#'abc'#; $x"#);
     assert_eq!(actual.out, "abc");
 }
+
+#[test]
+fn let_malformed_type() {
+    let actual = nu!("let foo: )a");
+    assert!(actual.err.contains("unbalanced ( and )"));
```
Comment (sholderbach) [inline crates/nu-command/tests/commands/let_.rs:130]: Gotta admit I can't wrap my head around how the change on the `}` side fixes the `)` panic :D

Comment (ysthakur) [reply crates/nu-command/tests/commands/let_.rs:130]: I think it's the off-by-one fix in the lexer for () that fixes it. The fix for {} (and the change to parse_record) seem to be separate?

**Comment by blindFS** [comment]
> Can you merge in `main` with #16231 so we can run the `parse_with_keywords` fuzz target on that for a bit?

Sure, actually I've noticed several unexpected consequences of this fix, running fuzz tests would be a good practice.

File: crates/nu-command/tests/commands/let_.rs (hunk 2 above)
Comment (blindFS) [reply crates/nu-command/tests/commands/let_.rs:130]: Actually I changed the behavior of both `}` and `)`

Comment (blindFS) [reply crates/nu-command/tests/commands/let_.rs:130]: Actually I changed the behavior of both `}` and `)`

Comment (sholderbach) [reply crates/nu-command/tests/commands/let_.rs:130]: Ah I was blind, thanks!

**Comment by sholderbach** [comment]
If you want to give it a go you can find it at

https://github.com/nushell/nushell/tree/main/crates/nu-parser/fuzz

The basic setup would be
```nushell
# cargo install cargo-fuzz
cd crates/nu-parser/fuzz
mkdir out
./gather_seeds.nu
cargo fuzz run parse_with_keywords out seeds
```

I typically run it with some additional flags to the fuzzer:
```
cargo fuzz run parse_with_keywords out seeds -- -max_len=64 -rss_limit_mb=8000
```

- `-only_ascii=1` can be used to find interesting stuff without binary mess but for a lexer change I would also make sure that UTF-8 handling remains sane
- `-max_len=64` not sure what it does for the overall performance of exploring the space, but the reproducers are typically easier to reduce than large seed corpus input with a small cause for the bug
- `-rss_limit_mb=8000` increase of the available memory as there were leaks or excessive memory use that stop before finding interesting stuff (see e.g. #16204)

**Comment by sholderbach** [comment]
#16355 has brought another fix for things found by the fuzzer onto main, so worth rebasing onto that to run it with arbitrary bytes and not just ASCII

**Comment by sholderbach** [comment]
Dang found another one of the `parse_var_with_opt_type` panics (not yet reduced):

```
..(mut  XEz: , e>!(*s  ({$
```

Reduced to:

```
mut : , a
```

```
at crates/nu-parser/src/parser.rs:3515:65
  ╰─▶ index out of bounds: the len is 0 but the index is 0
         0: 0x588f919cd30d - rust_begin_unwind
                      at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/panicking.rs:695
         1: 0x588f919fc360 - core::panicking::panic_fmt::h5764ee7030b7a73d
                      at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/core/src/panicking.rs:75
         2: 0x588f919fc542 - core::panicking::panic_bounds_check::h0328ca7e7f0749c4
                      at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/core/src/panicking.rs:273
         3: 0x588f90287547 - <usize as core::slice::index::SliceIndex<[T]>>::index::hbb5971d2ec5675f5
                      at /home/stefan/.rustup/toolchains/1.86.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:274
         4: 0x588f902848f1 - core::slice::index::<impl core::ops::index::Index<I> for [T]>::index::h3fec42bd6862c540
                      at /home/stefan/.rustup/toolchains/1.86.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:16
                       - <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index::ha3d52af603e6d002
                      at /home/stefan/.rustup/toolchains/1.86.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:3358
         5: 0x588f90249ea6 - nu_parser::parser::parse_var_with_opt_type::h6ab8ee4cc14deda7
                      at /home/stefan/nushell/crates/nu-parser/src/parser.rs:3515
         6: 0x588f9022d64f - nu_parser::parser::parse_multispan_value::hed97fbc8540e3aaa
                      at /home/stefan/nushell/crates/nu-parser/src/parser.rs:850
         7: 0x588f902312d6 - nu_parser::parser::parse_internal_call::h972f5a2c304629a6
                      at /home/stefan/nushell/crates/nu-parser/src/parser.rs:1234
         8: 0x588f9020172a - nu_parser::parse_keywords::parse_mut::hdcccdbab9967ba9d
                      at /home/stefan/nushell/crates/nu-parser/src/parse_keywords.rs:3685
         9: 0x588f90267db0 - nu_parser::parser::parse_builtin_commands::h5ce809c687581bd7
                      at /home/stefan/nushell/crates/nu-parser/src/parser.rs:6081
        10: 0x588f9026c0c4 - nu_parser::parser::parse_pipeline::h5fb0fba33640a7fa
                      at /home/stefan/nushell/crates/nu-parser/src/parser.rs:6511
        11: 0x588f9026c739 - nu_parser::parser::parse_block::h319f8ce0c9dfcc9c
                      at /home/stefan/nushell/crates/nu-parser/src/parser.rs:6545
        12: 0x588f902720c6 - nu_parser::parser::parse::hc26cef30bf13895d
                      at /home/stefan/nushell/crates/nu-parser/src/parser.rs:7101
        13: 0x588f8fd1d6ce - nu_cli::syntax_highlight::highlight_syntax::hef2c0d6fa81f53dc
                      at /home/stefan/nushell/crates/nu-cli/src/syntax_highlight.rs:46
        14: 0x588f8fd1d37c - <nu_cli::syntax_highlight::NuHighlighter as reedline::highlighter::Highlighter>::highlight::h103e95f58b7f6845
                      at /home/stefan/nushell/crates/nu-cli/src/syntax_highlight.rs:21
        15: 0x588f8ffca7ba - reedline::engine::Reedline::buffer_paint::hc872e9f884391fd7
                      at /home/stefan/.cargo/git/checkouts/reedline-68c4267336505bba/faee143/src/engine.rs:1773
        16: 0x588f8ffc78db - reedline::engine::Reedline::repaint::h26b5e97e1f7937c3
                      at /home/stefan/.cargo/git/checkouts/reedline-68c4267336505bba/faee143/src/engine.rs:1538
        17: 0x588f8ffc0609 - reedline::engine::Reedline::read_line_helper::h6cd66d9826daa00b
                      at /home/stefan/.cargo/git/checkouts/reedline-68c4267336505bba/faee143/src/engine.rs:829
        18: 0x588f8ffbf8fd - reedline::engine::Reedline::read_line::hcbecdeaeb783826c
                      at /home/stefan/.cargo/git/checkouts/reedline-68c4267336505bba/faee143/src/engine.rs:660
        19: 0x588f8fd12809 - nu_cli::repl::loop_iteration::h6629932c47c21b01
                      at /home/stefan/nushell/crates/nu-cli/src/repl.rs:487
        20: 0x588f8fd8b502 - nu_cli::repl::evaluate_repl::{{closure}}::h0ccb55285a97b64d
                      at /home/stefan/nushell/crates/nu-cli/src/repl.rs:189
        21: 0x588f8fe20ecf - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h4de3698e4a7a92ea
                      at /home/stefan/.rustup/toolchains/1.86.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272
        22: 0x588f8fe20f38 - std::panicking::try::do_call::h81e68cfb2d9a9582
                      at /home/stefan/.rustup/toolchains/1.86.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:587
        23: 0x588f8fd6386b - __rust_try
        24: 0x588f8fd637ae - std::panicking::try::haa4df45239cc9ebe
                      at /home/stefan/.rustup/toolchains/1.86.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:550
                       - std::panic::catch_unwind::hc3631095f97356ef
                      at /home/stefan/.rustup/toolchains/1.86.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:358
        25: 0x588f8fd0c1f7 - nu_cli::repl::evaluate_repl::h34b726177417d944
                      at /home/stefan/nushell/crates/nu-cli/src/repl.rs:188
        26: 0x588f8dfd33e9 - nu::run::run_repl::he3344d0dba50d4b0
                      at /home/stefan/nushell/src/run.rs:207
        27: 0x588f8e012de4 - nu::main::hd226463d40432cfc
                      at /home/stefan/nushell/src/main.rs:525
        28: 0x588f8e0024bb - core::ops::function::FnOnce::call_once::h34ee1d5d51ac487c
                      at /home/stefan/.rustup/toolchains/1.86.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
```

**Comment by blindFS** [comment]
> Dang found another one of the `parse_var_with_opt_type` panics (not yet reduced):
> 
> ```
> ..(mut  XEz: , e>!(*s  ({$
> ```
> 
> Reduced to:
> 
> ```
> mut : , a
> ```

Should be fixed now.

> https://github.com/nushell/nushell/pull/16355 has brought another fix for things found by the fuzzer onto main, so worth rebasing onto that to run it with arbitrary bytes and not just ASCII

Rebased, but I have trouble running cargo-fuzz:

```
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -Cpasses=sancov-module -Cllvm-args=-sanitizer-coverage-level=4 -Cllvm-args=-sanitizer-coverage-inline-8bit-counters -Cllvm-args=-sanitizer-coverage-pc-table -Cllvm-args=-sanitizer-coverage-trace-compares --cfg fuzzing -Cllvm-args=-simplifycfg-branch-fold-threshold=0 -Zsanitizer=address -Cdebug-assertions -Ccodegen-units=1 --target x86_64-apple-darwin --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg -Wwarnings` (exit status: 1)
  --- stderr
  error: the option `Z` is only accepted on the nightly compiler

  help: consider switching to a nightly toolchain: `rustup default nightly`

  note: selecting a toolchain with `+toolchain` arguments require a rustup proxy; see <https://rust-lang.github.io/rustup/concepts/index.html>

  note: for more information about Rust's stability policy, see <https://doc.rust-lang.org/book/appendix-07-nightly-rust.html#unstable-features>

  error: 1 nightly option were parsed
```

Probably because my rust toolchain is not managed by rustup

**Comment by blindFS** [comment]
@sholderbach Found a new one #16586 near

```
#15547010       REDUCE cov: 17498 ft: 98191 corp: 16516/561Kb lim: 64 exec/s: 653 rss: 6521Mb L: 43/64 MS: 1 EraseBytes-
```

That doesn't necessarily mean this PR won't cause new issues because the random seed of the fuzzer is not fixed?
