### PR TITLE
default to $nothing if cellpath not found

### LINKED ISSUE #6478: column names not recognized
### Describe the bug

When fetching an url and selecting certains columns, nushell doesn't recognized teh column names and makes column suggestions that not recognize either.   

It's a rather frustrating process.

### How to reproduce

While in nushell

1.  fetch a source and show its columns:
```
C:\〉fetch http://openlibrary.org/search.json/?author=tolkien | get docs | columns                                      09/04/2022 10:17:40 
╭────┬─────────────────────────────────────────╮
│  0 │ key                                     │
│  1 │ type                                    │
│  2 │ seed                                    │
│  3 │ title                                   │
│  4 │ title_suggest                           │
│  5 │ edition_count                           │
│  6 │ edition_key                             │
│  7 │ publish_date                            │
│  8 │ publish_year                            │
│  9 │ first_publish_year                      │
│ 10 │ number_of_pages_median                  │
│ 11 │ lccn                                    │
│ 12 │ publish_place                           │
│ 13 │ oclc                                    │
│ 14 │ contributor                             │
│ 15 │ lcc                                     │
│ 16 │ ddc                                     │
│ 17 │ isbn                                    │
│ 18 │ last_modified_i                         │
│ 19 │ ebook_count_i                           │
│ 20 │ ebook_access                            │
│ 21 │ has_fulltext                            │
│ 22 │ public_scan_b                           │
│ 23 │ ia                                      │
│ 24 │ ia_collection                           │
│ 25 │ ia_collection_s                         │
│ 26 │ lending_edition_s                       │
│ 27 │ lending_identifier_s                    │
│ 28 │ printdisabled_s                         │
│ 29 │ cover_edition_key                       │
│ 30 │ cover_i                                 │
│ 31 │ first_sentence                          │
│ 32 │ publisher                               │
│ 33 │ language                                │
│ 34 │ author_key                              │
│ 35 │ author_name                             │
│ 36 │ author_alternative_name                 │
│ 37 │ person                                  │
│ 38 │ place                                   │
│ 39 │ subject                                 │
│ 40 │ id_alibris_id                           │
│ 41 │ id_amazon                               │
│ 42 │ id_bcid                                 │
│ 43 │ id_depósito_legal                       │
│ 44 │ id_dnb                                  │
│ 45 │ id_goodreads                            │
│ 46 │ id_google                               │
│ 47 │ id_librarything                         │
│ 48 │ id_libris                               │
│ 49 │ id_overdrive                            │
│ 50 │ id_wikidata                             │
│ 51 │ ia_loaded_id                            │
│ 52 │ ia_box_id                               │
│ 53 │ publisher_facet                         │
│ 54 │ person_key                              │
│ 55 │ place_key                               │
│ 56 │ person_facet                            │
│ 57 │ subject_facet                           │
│ 58 │ _version_                               │
│ 59 │ place_facet                             │
│ 60 │ lcc_sort                                │
│ 61 │ author_facet                            │
│ 62 │ subject_key                             │
│ 63 │ ddc_sort                                │
│ 64 │ id_amazon_ca_asin                       │
│ 65 │ id_amazon_co_uk_asin                    │
│ 66 │ id_amazon_de_asin                       │
│ 67 │ id_amazon_it_asin                       │
│ 68 │ id_british_national_bibliography        │
│ 69 │ id_nla                                  │
│ 70 │ id_paperback_swap                       │
│ 71 │ id_bibliothèque_nationale_de_france_bnf │
│ 72 │ id_british_library                      │
│ 73 │ id_hathi_trust                          │
│ 74 │ id_scribd                               │
│ 75 │ time                                    │
│ 76 │ time_facet                              │
│ 77 │ time_key                                │
│ 78 │ id_canadian_national_library_archive    │
│ 79 │ subtitle                                │
╰────┴─────────────────────────────────────────╯
```
2.  select one column of data  (title) which is ok:
```
C:\〉fetch http://openlibrary.org/search.json/?author=tolkien | get docs | select title | first 5  
╭───┬────────────────────────────╮
│ # │           title            │
├───┼────────────────────────────┤
│ 0 │ The Hobbit                 │
│ 1 │ The Fellowship of the Ring │
│ 2 │ The Two Towers             │
│ 3 │ The Return of the King     │
│ 4 │ The Lord of the Rings      │
╰───┴────────────────────────────╯
```
4.  select another column of data which fails with weird errors:                     
```
C:\〉fetch http://openlibrary.org/search.json/?author=tolkien | get docs | select oclc | first 5                                                                                                                  Error: nu::shell::name_not_found (link)

  × Name not found
   ╭─[entry #56:1:1]
 1 │ fetch http://openlibrary.org/search.json/?author=tolkien | get docs | select oclc | first 5
    ·                                                                             ──┬─
    ·                                                                               ╰── did you mean 'lcc'?
   ╰────

C:\〉fetch http://openlibrary.org/search.json/?author=tolkien | get docs | select lcc | first 5                                                     
Error: nu::shell::name_not_found (link)

  × Name not found
   ╭─[entry #57:1:1]
 1 │ fetch http://openlibrary.org/search.json/?author=tolkien | get docs | select lcc | first 5
    ·                                                                             ┬──
    ·                                                                             ╰── did you mean 'oclc'?
   ╰──── 
```

### Expected behavior

to select columns by the names appearing in source, specially when are column names shown when using the command "columns"

### Screenshots

_No response_

### Configuration

| column0            | column1                                         |
| ------------------ | ----------------------------------------------- |
| version            | 0.67.0                                          |
| branch             |                                                 |
| commit_hash        | 91976988f032276ca48faff2d1ac13c079eda836        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |
| pkg_version        | 0.67.0                                          |
| build_time         | 2022-08-17 15:20:56 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by merelymyself**
# Description

Maybe fixes #6478.

# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [ ] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [ ] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [ ] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by kubouch** [comment]
Thanks! Maybe we should make it symmetrical to `get` and put this behavior behind the `-i` flag.

Also, please always use spans in your errors. Unspanned errors are strongly discouraged because they are very hard to debug in scripts.

File: crates/nu-command/src/filters/select.rs [hunk 1]
```diff
@@ -140,6 +165,16 @@ fn select(
                 }
             }
 
+            if ignore_empty {
```
Comment (kubouch) [inline crates/nu-command/src/filters/select.rs:168]: Shouldn't this flag be inverted? To me, it seems like an error should be returned if the flag is _not_ activated.

To make sure it's working properly, could you add `[{a: 1} {a: 2} {a: 3}] | select -i b` to the tests?

Comment (merelymyself) [reply crates/nu-command/src/filters/select.rs]: Thanks for pointing it out, kubouch. It should all work now.

File: crates/nu-command/tests/commands/select.rs [hunk 2]
```diff
@@ -159,3 +159,15 @@ fn selects_many_rows() {
         assert_eq!(actual.out, "2");
     });
 }
+
+#[test]
+fn select_ignores_errors_succesfully() {
+    let actual = nu!(
+        cwd: ".", pipeline(
+        r#"
+        [{a: 1, b: 2} {a: 3, b: 5} {a: 3}] | select -i b; [{a: 1} {a: 2} {a: 3}] | select -i b
```
Comment (kubouch) [inline crates/nu-command/tests/commands/select.rs:168]: I think it would be better to have them as separate tests. I just wanted to have a test where you `select` a column that doesn't exist at all (in the first example, the `b` column is still present in some rows).

**Comment by kubouch** [comment]
OK, looks good, thanks!
