### PR TITLE
Fix: missing parse error when extra tokens are given to let bindings

### LINKED ISSUE #12125: Let, mut, const bindings don't parse error when more than one ident is passed in
### Describe the bug

And it only binds to the first ident. Quite weird.

### How to reproduce

```nu
~
❯ let foo bar = 123


~
❯ $foo

123

~
❯ $bar

Error: nu::parser::variable_not_found

  × Variable not found.
   ╭─[entry #3:1:1]
 1 │ $bar
   · ──┬─
   ·   ╰── variable not found.
   ╰────
```

```nu

~
❯ const foo bar = 123


~
❯ $bar

Error: nu::parser::variable_not_found

  × Variable not found.
   ╭─[entry #5:1:1]
 1 │ $bar
   · ──┬─
   ·   ╰── variable not found.
   ╰────


~
❯ $foo

123
```

### Expected behavior

Parse error

### Screenshots

_No response_

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.90.1                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball) |
| cargo_version      | cargo 1.75.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by YizhePKU**
Manual checks are added to `parse_let`, `parse_mut`, and `parse_const`. `parse_var_with_opt_type` is also fixed to update `spans_idx` correctly. Fixes #12125.

It's technically a fix, but I'd rather not merge this directly. I'm making this PR to bring into attention the code quality of the parser code. For example:

* Inconsistent usage of `spans_idx`. What is its purpose, and which parsing functions need it? I suspect it's possible to remove the usage of `spans_idx` entirely.
* Lacking documentation for top-level functions. What does `mutable` mean for `parse_var_with_opt_type()`?
* Inconsistent error reporting. Usage of both `working_set.error()` and `working_set.parse_errors.push()`. Using `ParseError::Expected` for an invalid variable name when there's `ParseError::VariableNotValid` (from `parser.rs:5237`). Checking variable names manually when there's `is_variable()` (from `parser.rs:2905`).
* `span()` is a terrible name for a function that flattens a bunch of spans into one (from `nu-protocal/src/span.rs:92`). The top-level comment (`Used when you have a slice of spans of at least size 1`) doesn't help either.

I've only looked at a small portion of the parser code; I expect there are a lot more. These issues made it much harder to fix a simple bug like #12125. I believe we should invest some effort to cleanup the parser code, which will ease maintainance in the future. I'll willing to help if there is interest.

### CODE REVIEW

**Comment by fdncred** [comment]
Thanks for looking into this! It would be great to have some tests that ensure your fix stays fixed.

**Comment by YizhePKU** [comment]
I've added a simple test case.

File: crates/nu-parser/src/parser.rs [hunk 1]
```diff
@@ -2925,7 +2929,7 @@ pub fn parse_var_with_opt_type(
             }
 
             let ty = parse_type(working_set, &type_bytes, tokens[0].span);
-            *spans_idx += spans.len() - *spans_idx - 1;
+            *spans_idx = spans.len() - 1;
```
Comment (WindSoilder) [inline crates/nu-parser/src/parser.rs:2932]: Good catch!

File: tests/parsing/mod.rs [hunk 2]
```diff
@@ -1,3 +1,4 @@
+use nix::libc::__c_anonymous_ptrace_syscall_info_entry;
```
Comment (WindSoilder) [inline tests/parsing/mod.rs:1]: I don't think it's needed

File: crates/nu-parser/src/parser.rs [hunk 3]
```diff
@@ -2890,6 +2890,10 @@ pub fn parse_import_pattern(working_set: &mut StateWorkingSet, spans: &[Span]) -
     }
 }
 
+// Parse `spans[spans_idx..]` into a variable, with optional type annotation.
+// If the name of the variable ends with a colon (no space in-between allowed), then a type annotation
+// can appear after the variable, in which case the colon is stripped from the name of the variable.
+// `spans_idx` is updated to point to the last span that has been parsed.
```
Comment (WindSoilder) [inline crates/nu-parser/src/parser.rs:2896]: May be we can make them starts with `///`(they can be function docstring)

File: tests/parsing/mod.rs
Comment (WindSoilder) [inline tests/parsing/mod.rs:1]: Can you also add tests for `const a int = 2`, `mut a string = "3"`?

**Review by WindSoilder — CHANGES_REQUESTED** [review]
Thank you for making some changes to improve nushell!  I just leave some comment

File: tests/parsing/mod.rs (hunk 2 above)
Comment (YizhePKU) [reply tests/parsing/mod.rs:1]: Thanks. My IDE must have automatically added this for some reason.

File: crates/nu-parser/src/parser.rs (hunk 3 above)
Comment (YizhePKU) [reply crates/nu-parser/src/parser.rs:2896]: Good catch. There're some code that still uses `//` for top-level comments, but we can deal with that later.

File: tests/parsing/mod.rs
Comment (YizhePKU) [reply tests/parsing/mod.rs:1]: Will do. But I suspect these tests will be obsolete if we refactor the parser code. I think my current fix is hacky.

**Review by WindSoilder — APPROVED** [review]
Thanks!  LGTM

**Comment by fdncred** [comment]
Thanks!
