### PR TITLE
Disallow `encode`'s silent conversion to HTML entities (and add `-i`/`--ignore-errors` flag to re-allow it)

### LINKED ISSUE #7514: Some `encode` issues
### Describe the bug

1. `utf16`, without the hyphen, is not recognised:
```
〉"A" | encode utf8
Length: 1 (0x1) bytes | printable whitespace ascii_other non_ascii
00000000:   41                                                   A
〉"A" | encode utf-8
Length: 1 (0x1) bytes | printable whitespace ascii_other non_ascii
00000000:   41                                                   A
〉"A" | encode utf16
Error:
  × utf16 is not a valid encoding, refer to https://docs.rs/encoding_rs/0.8.23/encoding_rs/#statics for a valid list of encodings
   ╭─[entry #37:1:1]
 1 │ "A" | encode utf16
   ·              ──┬──
   ·                ╰── invalid encoding
   ╰────


〉"A" | encode utf-16
Length: 1 (0x1) bytes | printable whitespace ascii_other non_ascii
00000000:   41                                                   A
```
2. When encoding a character that doesn't exist in that encoding format, the character is converted to a HTML entity (instead of throwing an error)
```
〉"🎈" | encode shift-jis
Length: 9 (0x9) bytes | printable whitespace ascii_other non_ascii
00000000:   26 23 31 32  37 38 38 30  3b                         &#127880;
```

### How to reproduce

See above

### Expected behavior

See above

### Screenshots

_No response_

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.72.2                                   |
| branch             | main                                     |
| commit_hash        | 774769a7ada3e5f8433d1ad1e6c12606ece664a4 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.72.2                                   |
| build_time         | 2022-12-17 23:52:36 +10:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by webbedspace**
# Description

Closes #7514.

 * For both `encode` and `decode`: add a special case allowing `utf16` as a valid alias for `utf-16` (just as `utf-8` has `utf8`).
 * For `encode` , make it an error when encodings_rs replaces characters outside the given encoding with HTML entities
 * For `encode` , add `-i`/`--ignore-errors` flag to bring back this behaviour.

Note: `--ignore-errors` does NOT ignore the error for using a wrong encoding label like `uft8`

# User-Facing Changes

See above.

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

File: crates/nu-command/src/strings/encode_decode/decode.rs [hunk 1]
```diff
@@ -30,11 +30,11 @@ impl Command for Decode {
     }
 
     fn extra_usage(&self) -> &str {
-        r#"Multiple encodings are supported, here is an example of a few:
+        r#"Multiple encodings are supported; here is a few:
```
Comment (fdncred) [inline crates/nu-command/src/strings/encode_decode/decode.rs:33]:
```suggestion
        r#"Multiple encodings are supported; here are a few:
```

File: crates/nu-command/src/strings/encode_decode/encode.rs [hunk 2]
```diff
@@ -26,33 +30,48 @@ impl Command for Encode {
...
+                "ignore-errors",
+                "when a character isn't in the given encoding, replace with a HTML entity (like `&#127880;`)",
+                Some('i'),
+            )
             .category(Category::Strings)
     }
 
     fn extra_usage(&self) -> &str {
-        r#"Multiple encodings are supported, here is an example of a few:
+        r#"Multiple encodings are supported; here is a few:
```
Comment (fdncred) [inline crates/nu-command/src/strings/encode_decode/encode.rs:42]:
```suggestion
        r#"Multiple encodings are supported; here are a few:
```

File: crates/nu-command/src/strings/encode_decode/encode.rs [hunk 3]
```diff
@@ -15,7 +15,11 @@ impl Command for Encode {
     }
 
     fn usage(&self) -> &str {
-        "Encode an UTF-8 string into other kind of representations."
+        // Note: "Encode a UTF-8 string into other forms" is semantically incorrect because
+        // Nushell strings, as abstract values, have no user-facing encoding.
+        // (Remember that "encoding" exclusively means "how the characters are
+        // observably represented by bytes").
```
Comment (fdncred) [inline crates/nu-command/src/strings/encode_decode/encode.rs:21]: Is this comment correct? A nushell `Value::String` holds a rust `String`. This is part of the documentation for rust Strings.

```
/// `String`s are always valid UTF-8. If you need a non-UTF-8 string, consider
/// [`OsString`]. It is similar, but without the UTF-8 constraint. Because UTF-8
/// is a variable width encoding, `String`s are typically smaller than an array of
/// the same `chars`:
```
Maybe I'm just not understanding the point you're trying to make?

Comment (webbedspace) [reply crates/nu-command/src/strings/encode_decode/encode.rs:21]: The point is whether their encoding is *user-facing* or *observable*. In most non-systems programming languages/scripting languages, strings' implementation encodings are not end-user observable because they are *abstract*. The whole point of the word "encoding" is that the user must treat the strings as *not* being any particular sequence of *codes*, but as the "pure characters" in and of themselves.

Comment (rgwood) [reply crates/nu-command/src/strings/encode_decode/encode.rs:21]: I feel like this is a bit of a grey area. Strings tend to be important enough that even in higher-level languages, their encoding is well-known and guaranteed even when it's not directly observable (i.e. how .NET uses UTF-16 internally).

In Nushell's case, `into binary` does a raw conversion from `String` to a `Vec<u8>` so I think you could make the case that the encoding is observable in Nushell.

I don't have a well-formed opinion on this yet, but at first glance I think we'd be OK publicly defining Nushell strings as UTF-8.

**Review by rgwood — APPROVED** [review]
Aside from the "is our UTF-8 encoding user-facing?" question (which I don't think should hold this up), LGTM. Thanks!

File: crates/nu-command/src/strings/encode_decode/encode.rs (hunk 3 above)
Comment (sholderbach) [reply crates/nu-command/src/strings/encode_decode/encode.rs:21]: Our string indexing in `str substring` also follows Rust UTF-8 rules. So implicitly we have leaned on string always being UTF-8 encoded and using byte indices.

Comment (webbedspace) [reply crates/nu-command/src/strings/encode_decode/encode.rs:21]: `str substring` breaking on UTF-8 byte boundaries feels like a bug to me. As an end-user I would expect it to break on codepoints rather than bytes. For instance, `"🥇" | str substring '0,1'` should give `"🥇"` instead of just a useless character. For comparision, Javascript's new (2016+) string iterator correctly breaks strings on codepoints: `[..."🥇"]` produces `["🥇"]`.
