### PR TITLE
Small fixes and refactors to paths & source command

### LINKED ISSUE #3605: Tilde expansion does not work in variables
**To Reproduce**
1. `> let d = ~/Downloads; ls $d`  --> Error: no matches found
2. `> let d = "~/Downloads"; ls $d`  --> Error: no matches found
3. `> let d = ("~/Downloads" | path expand); ls $d`  --> Works fine

**Expected behavior**
It should work fine in all three cases

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
  #         Column0                                                                                         Column1
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   0   version              0.32.1
   1   branch               main
   2   short_commit         b9ca3b20
   3   commit_hash          b9ca3b2039ecdf5e808b4dc4d8d0ebc5575bf90b
   4   commit_date          2021-06-11 09:35:21
   5   build_os             linux-x86_64
   6   rust_version         rustc 1.52.0 (88f19c6da 2021-05-03)
   7   rust_channel         stable (default)
   8   cargo_version        cargo 1.52.0 (69767412a 2021-04-21)
   9   pkg_version          0.32.1
  10   build_time           2021-06-11 10:41:15
  11   build_rust_channel   release
  12   features             clipboard-cli, ctrlc, default, directories, dirs, ptree, rustyline, term, trash, uuid, which, zip
  13   installed_plugins    binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath

```

### PR DESCRIPTION
**Pull request by kubouch**
Notably, fixes #3605 and #1834. Also, improvements to `source` error messages and making sure `source` follows symlinks.

Tracking issue: #3655

### CODE REVIEW

File: crates/nu-command/src/commands/core_commands/source.rs [hunk 1]
```diff
@@ -69,11 +69,15 @@ pub fn source(args: CommandArgs) -> Result<OutputStream, ShellError> {
         for lib_path in dir {
             match lib_path {
                 Ok(name) => {
-                    let path = PathBuf::from(name).join(source_file);
-
-                    if let Ok(contents) =
-                        std::fs::read_to_string(&expand_path(Cow::Borrowed(path.as_path())))
-                    {
```
Comment (andrasio) [inline crates/nu-command/src/commands/core_commands/source.rs:76]: This shouldn't error since this part checks to see if the file is under the `lib_dirs` optional search paths (where you'd have your nu libraries and the like)

File: crates/nu-command/src/commands/core_commands/source.rs [hunk 2]
```diff
@@ -89,9 +93,15 @@ pub fn source(args: CommandArgs) -> Result<OutputStream, ShellError> {
...
     }
 
-    let path = Path::new(source_file);
+    let path = canonicalize(source_file).map_err(|e| {
+        ShellError::labeled_error(
+            format!("Can't load source file. Reason: {}", e.to_string()),
+            "Can't load this file",
+            filename.span(),
+        )
+    })?;
```
Comment (andrasio) [inline crates/nu-command/src/commands/core_commands/source.rs:103]: here is ok to error since by this point it hasn't found any potential nu files.

File: crates/nu-parser/src/parse/source.rs [hunk 3]
```diff
@@ -61,25 +61,33 @@ fn find_source_file(
 
     if let Some(dir) = lib_dirs {
         for lib_path in dir.into_iter().flatten() {
-            let path = PathBuf::from(lib_path).join(&file);
+            let path = canonicalize_with(&file, lib_path).map_err(|e| {
+                ParseError::general_error(
+                    format!("Can't load source file. Reason: {}", e.to_string()),
+                    "Can't load this file".spanned(file_span),
+                )
+            })?;
```
Comment (andrasio) [inline crates/nu-parser/src/parse/source.rs:70]: same here.

File: crates/nu-parser/src/parse/source.rs [hunk 4]
```diff
@@ -61,25 +61,33 @@ fn find_source_file(
...
         }
     }
 
-    let path = Path::new(&file);
+    let path = canonicalize(&file).map_err(|e| {
+        ParseError::general_error(
+            format!("Can't load source file. Reason: {}", e.to_string()),
+            "Can't load this file".spanned(file_span),
+        )
+    })?;
```
Comment (andrasio) [inline crates/nu-parser/src/parse/source.rs:83]: This is ok.
