### PR TITLE
return gid and uid in numbers if name not found

### LINKED ISSUE #6675: ls -l doesn't display numeric id of owner/group when name is not available
### Describe the bug

When ls -l displays files/directories with an owner/group that isn't named, the `uid` and `group` columns are just blank, instead of displaying the numeric owner/group id as traditional `ls -l` does.

### How to reproduce

```
touch file
sudo chown :4927 file # any random group id that isn't taken already
ls -l
```

### Expected behavior

I expected to see the numeric id for the unknown user/group.

### Screenshots

_No response_

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.66.3                                          |
| branch             |                                                 |
| commit_hash        | 5f11be69ed1bd11bf676345149fdb110271b1181        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.62.1 (e092d0b6b 2022-07-16)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.62.1 (a748cf5a3 2022-06-08)             |
| pkg_version        | 0.66.3                                          |
| build_time         | 2022-07-28 23:16:46 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

This situation is fairly common when working with mounted directories in containers, as there will often be a user in the container whose id doesn't match anything on the host system. (Even more confusingly, sometimes the id _does_ match, but it matches a user with a different name, which is fun to debug. Nothing Nu can do about that, however.)

Not a huge issue, but I searched and couldn't find it mentioned anywhere else, so I figured I'd bring it up.

### PR DESCRIPTION
**Pull request by merelymyself**
# Description

Fixes #6675. Not sure how to add tests for this. Follow steps in issue to test.

# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [x] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

File: crates/nu-command/src/filesystem/ls.rs [hunk 1]
```diff
@@ -491,7 +491,10 @@ pub(crate) fn dir_entry_dict(
                         span,
                     });
                 } else {
-                    vals.push(Value::nothing(span))
+                    vals.push(Value::Int {
```
Comment (sholderbach) [inline crates/nu-command/src/filesystem/ls.rs:494]: Open question if `Int` or `String` is better here. String would keep the type of the column consistent but would be indistinguishable from a found username or groupname.

Comment (merelymyself) [reply crates/nu-command/src/filesystem/ls.rs:494]: I thought about it as well, but in the end I thought `Int` was better. It's not inconceivable for a username or groupname to be a number, and in those cases the user should have some way to distinguish the two I feel.

Comment (sholderbach) [reply crates/nu-command/src/filesystem/ls.rs:494]: https://unix.stackexchange.com/questions/287077/why-cant-linux-usernames-begin-with-numbers Welp, some people really want to see the world burn...

I am OK with your decision. Hope that the potential downstream commands are fine with mixed types.

**Review by sholderbach — APPROVED** [review]
