### PR TITLE
Alias to keywords (eg `source`)

### LINKED ISSUE #4822: Alias to source shouldn't source the script
### Describe the bug

When defining `alias foo = (source foo.nu)`, it will parse the script with side effects.

This is currently preventing Python virtualenv from working.

### How to reproduce

Have two scripts:
```
# activate-foo.nu

alias foo = echo foo
alias deactivate-foo = (source deactivate-foo.nu)
```

```
# deactivate-foo.nu

hide foo
```

Then,
```
> source ./activate-foo.nu         

> deactivate-foo 
Error: nu::parser::not_found (https://docs.rs/nu-protocol/0.59.1/nu-protocol/enum.ShellError.html#variant.NotFound)

  × Not found.
   ╭─[deactivate-foo.nu:1:1]
 1 │ hide foo
   ·      ─┬─
   ·       ╰── did not find anything under this name
   ╰────
```

The reason why this happened is that when defining the `alias deactivate-foo = (source deactivate-foo.nu)`, the parser will go into `deactivate-foo.nu` and `hide foo`. Then, when `deactivate-foo` is called, the `foo` is already hidden.

### Expected behavior

Defining an alias with source should not have side effects. Only running the alias should.

Perhaps the alias definition could have a throwaway scope frame? Not sure what would the best fix be...

### Screenshots

_No response_

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.1                                   |
| branch             | main                                     |
| short_commit       | 14dc662e                                 |
| commit_hash        | 14dc662e505f4aa648240329250c125a6b4c859e |
| commit_date        | 2022-03-10 13:37:24 +00:00               |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.1                                   |
| build_time         | 2022-03-10 16:08:48 +02:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | gstat                                    |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jntrnr**
# Description

This allows you to `alias` to a reserve keyword like `source`.

fixes #4822 

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

File: crates/nu-command/tests/commands/alias.rs [hunk 1]
```diff
@@ -0,0 +1,13 @@
+use nu_test_support::{nu, pipeline};
+
+#[test]
+fn echo_range_is_lazy() {
```
Comment (fdncred) [inline crates/nu-command/tests/commands/alias.rs:4]: copy-n-paste error?
