### PR TITLE
Fix negative precision round with ints (issue #9049)

### LINKED ISSUE #9049: `math round --precision -1` : incorrect results if input is an int
### Describe the bug

See example

### How to reproduce

```
〉123.45 | math round --precision -1
120
〉123. | math round --precision -1
120
```
Both correct, but
```
〉123 | math round --precision -1
123
```
Should also be `120`.

Even when a float and int input have the same value, I only get correct results from float.
```
〉let vf = 123.0
〉$vf | describe
float
〉$vf | math round --precision -1
120
```
Right!
```
〉let v = 123
〉$v | describe
int
〉$v | math round --precision -1
123
```
Wrong!

### Expected behavior

Since signature says input is  `<number>`, I'd expect the function to handle ints and floats of the same value consistently.

### Screenshots

_No response_

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.79.1                                   |
| branch             | help_help                                |
| commit_hash        | 0e07c2c70909df961fc4fa30238d2218a4b14238 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)      |
| rust_channel       | 1.67.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)      |
| build_time         | 2023-04-27 17:50:13 -04:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by juanPabloMiceli**
# Description
Before this PR, `math round` ignores the input if it's an `int`. This results in the following behaviour:
```
> 123 | math round --precision -1
123
```
When the correct result is 120.

Now `int values` are converted to `float values` before actually rounding up the number in order to take advantage of the float implementation.

Fixes #9049. 

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

File: crates/nu-command/src/math/round.rs [hunk 1]
```diff
@@ -80,7 +80,17 @@ impl Command for SubCommand {
 }
 
 fn operate(value: Value, head: Span, precision: Option<i64>) -> Value {
-    match value {
+    let mut result_value = value.clone();
```
Comment (amtoine) [inline crates/nu-command/src/math/round.rs:83]: > **Warning**
> i did not run the full suite of tests, so this might not work 100% :wink: 

could we avoid this `clone` by applying the following patch?
```diff
diff --git a/crates/nu-command/src/math/round.rs b/crates/nu-command/src/math/round.rs
index 64b151221..1132c7681 100644
--- a/crates/nu-command/src/math/round.rs
+++ b/crates/nu-command/src/math/round.rs
@@ -80,7 +80,7 @@ impl Command for SubCommand {
 }
 
 fn operate(value: Value, head: Span, precision: Option<i64>) -> Value {
-    let mut result_value = value.clone();
+    let mut result_value = value;
 
     // We treat int values as float values in order to avoid code repetition in the match closure
     if let Value::Int { val, span } = result_value {
@@ -102,7 +102,6 @@ fn operate(value: Value, head: Span, precision: Option<i64>) -> Value {
                 span,
             },
         },
-        Value::Error { .. } => value,
         other => Value::Error {
             error: Box::new(ShellError::OnlySupportsThisInputType {
                 exp_input_type: "numeric".into(),
```

the `value` is only used in the `result_value` declaration and in the `Value::Error` arm and this does not change the behaviour of the `math round` command in the few examples i tried :open_mouth:

Comment (amtoine) [reply crates/nu-command/src/math/round.rs:83]: we might even be able to simplify this further by applying
```diff
diff --git a/crates/nu-command/src/math/round.rs b/crates/nu-command/src/math/round.rs
index 64b151221..691dadd85 100644
--- a/crates/nu-command/src/math/round.rs
+++ b/crates/nu-command/src/math/round.rs
@@ -80,17 +80,17 @@ impl Command for SubCommand {
 }
 
 fn operate(value: Value, head: Span, precision: Option<i64>) -> Value {
-    let mut result_value = value.clone();
-
     // We treat int values as float values in order to avoid code repetition in the match closure
-    if let Value::Int { val, span } = result_value {
-        result_value = Value::Float {
+    let value = if let Value::Int { val, span } = value {
+        Value::Float {
             val: val as f64,
             span,
-        };
-    }
+        }
+    } else {
+        value
+    };
 
-    match result_value {
+    match value {
         Value::Float { val, span } => match precision {
             Some(precision_number) => Value::Float {
                 val: ((val * ((10_f64).powf(precision_number as f64))).round()
@@ -102,7 +102,6 @@ fn operate(value: Value, head: Span, precision: Option<i64>) -> Value {
                 span,
             },
         },
-        Value::Error { .. } => value,
         other => Value::Error {
             error: Box::new(ShellError::OnlySupportsThisInputType {
                 exp_input_type: "numeric".into(),
```

Comment (amtoine) [reply crates/nu-command/src/math/round.rs:83]: > **Note**
> to apply these patches, you can just put the raw text in a `patch.diff` file and run
> `git apply patch.diff` :wink:

**Review by amtoine — CHANGES_REQUESTED** [review]
that solves the issue thanks :partying_face: 

i think we can just make the changes a bit tighter and we'll be good to merge :relieved:

File: crates/nu-command/tests/commands/math/round.rs
[the remark this answers is not in the document]
Comment (juanPabloMiceli) [reply crates/nu-command/tests/commands/math/round.rs:1]: What are the `echos`?

[the remark this answers is not in the document]
Comment (juanPabloMiceli) [reply crates/nu-command/tests/commands/math/round.rs:1]: Ohhh, I see. I actually prefer the number literals

File: crates/nu-command/src/math/round.rs (hunk 1 above)
Comment (juanPabloMiceli) [reply crates/nu-command/src/math/round.rs:83]: Great tip!

**Comment by juanPabloMiceli** [comment]
Is there a way to test error inputs like strings? I don't think comparing to stderr is a good alternative

File: crates/nu-command/tests/commands/math/round.rs
Comment (bobhy) [inline crates/nu-command/tests/commands/math/round.rs:1]: Testing for expected substring in stderr output is about the best you can do with tests using `nu!`, since that invokes Nu like an external command, you get strings back, not actual Nu types.  Current tests mostly look for the gist of the error text, you might do better to test for the exact error path: `Error: nu::shell::unsupported_input`.  I could imagine someone wordsmithing the error text in some future version (or translating it out of English), the error path might be more stable, but even that is subject to change.

**Review by bobhy — APPROVED** [review]
Looks good to me!

File: crates/nu-command/src/math/round.rs (hunk 1 above)
Comment (amtoine) [reply crates/nu-command/src/math/round.rs]: great thanks :star_struck: 
a perfect `git apply`cation, loving it :smirk:

File: crates/nu-command/tests/commands/math/round.rs
[the remark this answers is not in the document]
Comment (amtoine) [reply crates/nu-command/tests/commands/math/round.rs:1]: fixed, that's perfect :ok_hand:

File: crates/nu-command/src/math/round.rs [hunk 2]
```diff
@@ -92,8 +102,6 @@ fn operate(value: Value, head: Span, precision: Option<i64>) -> Value {
                 span,
             },
         },
-        Value::Int { .. } => value,
-        Value::Error { .. } => value,
```
Comment (sholderbach) [inline crates/nu-command/src/math/round.rs:96]: (I currently struggle to create a passable error that doesn't immediately bubble up or gets ignored like in `do -i`)

Removing this `Value::Error` match arm alters the behavior when receiving a collection of values that contain some errors. This would now always replace them with the type error.

Unsure about the practical impact, but there was at least a historical reason why we had the separate match arm for errors coming in.

File: crates/nu-command/tests/commands/math/round.rs [hunk 3]
```diff
@@ -14,8 +14,38 @@ fn can_round_very_large_numbers() {
...
 
     assert_eq!(actual.out, "18.137254478")
 }
+
+#[test]
+fn can_round_integer_with_negative_precision() {
+    let actual = nu!(
+        cwd: ".",
+        "123 | math round -p -1"
+    );
```
Comment (sholderbach) [inline crates/nu-command/tests/commands/math/round.rs:28]: For tests that don't work with files you can omit the `cwd: "."` Leaving it in doesn't cause a direct problem, so just a style suggestion to help with #9021 et al.

```suggestion
    let actual = nu!(
        "123 | math round -p -1"
    );
```

(may need a rustfmt run afterwards)

File: crates/nu-command/tests/commands/math/round.rs [hunk 4]
```diff
@@ -14,8 +14,38 @@ fn can_round_very_large_numbers() {
...
+
+#[test]
+fn can_round_float_with_negative_precision() {
+    let actual = nu!(
+        cwd: ".",
+        "123.3 | math round -p -1"
+    );
+
+    assert_eq!(actual.out, "120")
+}
```
Comment (sholderbach) [inline crates/nu-command/tests/commands/math/round.rs:41]: Maybe worth moving one of the negative precision tests directly to the examples so the user can see it as a possibility. (also the example test are a bit faster to run in CI and locally)

File: crates/nu-command/src/math/round.rs [hunk 5]
```diff
@@ -80,6 +80,16 @@ impl Command for SubCommand {
 }
 
 fn operate(value: Value, head: Span, precision: Option<i64>) -> Value {
+    // We treat int values as float values in order to avoid code repetition in the match closure
+    let value = if let Value::Int { val, span } = value {
+        Value::Float {
+            val: val as f64,
```
Comment (sholderbach) [inline crates/nu-command/src/math/round.rs:86]: This will cause a loss of precision for larger integers that exceed `2^53` but the question is how relevant this is in practice to implement a separate solution via integer division by `10^(-precision)` followed by multiplication as the naive implementation (or whatever exists as the most efficient algorithm in the decimal system)

File: crates/nu-command/src/math/round.rs (hunk 2 above)
Comment (juanPabloMiceli) [reply crates/nu-command/src/math/round.rs:96]: Makes sense, adding it back then

File: crates/nu-command/src/math/round.rs (hunk 5 above)
Comment (juanPabloMiceli) [reply crates/nu-command/src/math/round.rs:98]: I don't really understand why the second implementation wouldn't cause a loss of precision, but the first one would.

Comment (sholderbach) [reply crates/nu-command/src/math/round.rs:98]: In case you have e.g.  `2^60 - 2` this would not accurately fit in the f64 mantissa and would loose more precision than removing the last decimal with  `math round -1`.

**Review by sholderbach — APPROVED** [review]
Thanks for cleaning up the tests!

I won't block landing this fix on the integer precision part as we probably need to clarify our general arithmetic semantics in that regard a bit more.

**Comment by juanPabloMiceli** [comment]
Do you want me to open an issue on the precission loss though?
