### PR TITLE
Fix `ls` for Windows system files

### LINKED ISSUE #4975: "needs compatible type" as result of `ls | where size > 2kb` when running in directory "C:\Windows\System32"
### Describe the bug

Running  `ls | where size > 2kb` in `C:\Windows\System32` created the following error message:

```
C:\Windows\system32〉ls | where size > 2kb                                                        03/26/2022 09:49:11 AM
Error: nu::shell::type_mismatch (link)

  × Type mismatch
   ╭─[entry #18:1:1]
 1 │ ls | where size > 2kb
   ·                 ┬
   ·                 ╰── needs compatible type
   ╰────
```

### How to reproduce

1. Install nu shell over winget `winget install nushell`
2. Install windows terminal over winget `winget install Microsoft.WindowsTerminal`
3. Start windows terminal and add a new profile pointing to nu.exe
4. Start a new session using the nu profile
5. Go to "C:\Windows\System32"
6. Type `ls | where size > 2kb`

### Expected behavior

Expected to see a table with files larger than 2 kb

### Screenshots

_No response_

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.60.0                                   |
| short_commit       | 74af31a4                                 |
| commit_hash        | 74af31a42ff4feb8d5d9897c0d99c7434678a315 |
| commit_date        | 2022-03-22 19:07:11 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.60.0                                   |
| build_time         | 2022-03-22 19:26:49 +00:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rgwood**
# Description

Fixes #4975 on Windows only (does not fix the related issue on MacOS that @hustcer [noted here](https://github.com/nushell/nushell/issues/4975#issuecomment-1079646262)).

In a nushell, some Win32 APIs are unable to return useful information about Windows system files - [including APIs used by the Rust stdlib](https://github.com/rust-lang/rust/issues/96980). The way the .NET runtime solves this is by falling back on [FindFirstFile](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findfirstfilew) if their initial attempt to get file metadata fails ([comment](https://github.com/dotnet/runtime/issues/26216#issuecomment-390269346), [code](https://github.com/dotnet/runtime/blob/6de7147b9266d7730b0d73ba67632b0c198cb11e/src/libraries/Common/src/System/IO/FileSystem.Attributes.Windows.cs#L69-L80)). This PR does the same for Nushell.

### Before
image

### After
image

# Notes

I'm using [Microsoft's `windows` crate](https://github.com/microsoft/windows-rs) for this. It shouldn't add much to build times because our `trash-rs` dependency also uses `windows`.

`windows` is a somewhat underdocumented crate, but once you get some practice it's not too bad; just let me know if you have any questions about how I've used it here.

### CODE REVIEW

**Comment by rgwood** [comment]
Looks like my new test is failing because the GitHub Actions runners (sometimes?) don't have a pagefile. Marking as draft while I figure that out.

**Comment by fdncred** [comment]
very nice work @rgwood! thanks for making this happen.

File: crates/nu-command/src/filesystem/ls.rs [hunk 1]
```diff
@@ -12,12 +12,27 @@ use nu_protocol::{
...
 
+#[cfg(windows)]
+use windows::Win32::Foundation::FILETIME;
+#[cfg(windows)]
+use windows::Win32::Storage::FileSystem::{
+    FindFirstFileW, FILE_ATTRIBUTE_DIRECTORY, FILE_ATTRIBUTE_READONLY,
+    FILE_ATTRIBUTE_REPARSE_POINT, WIN32_FIND_DATAW,
+};
+#[cfg(windows)]
+use windows::Win32::System::SystemServices::{IO_REPARSE_TAG_MOUNT_POINT, IO_REPARSE_TAG_SYMLINK};
```
Comment (WindSoilder) [inline crates/nu-command/src/filesystem/ls.rs:34]: What about using something like this to group up `#[cfg(windows)]`? 
```rust
#[cfg(windows)]
use {
    std::mem::MaybeUninit,
    std::os::windows::prelude::OsStrExt,
    windows::Win32::Foundation::FILETIME,
    windows::Win32::Storage::FileSystem::{
        FindFirstFileW, FILE_ATTRIBUTE_DIRECTORY, FILE_ATTRIBUTE_READONLY,
        FILE_ATTRIBUTE_REPARSE_POINT, WIN32_FIND_DATAW,
    },
    windows::Win32::System::SystemServices::{IO_REPARSE_TAG_MOUNT_POINT, IO_REPARSE_TAG_SYMLINK}
}
```

But to be honest, I don't know if it's a good practise, I'm failed to find out good practise for it, just think maybe we can reduce `#[cfg(windows)]` usage...

File: crates/nu-command/src/filesystem/ls.rs [hunk 2]
```diff
@@ -568,6 +588,180 @@ pub(crate) fn dir_entry_dict(
     Ok(Value::Record { cols, vals, span })
 }
 
+#[cfg(windows)]
```
Comment (WindSoilder) [inline crates/nu-command/src/filesystem/ls.rs:591]: And yeah, what about grouping these windows only functions into a private sub module like 
```rust
#[cfg(windows)]
mod windows_helper {
     pub fn dir_entry_dict_windows_fallback(...) {}
     fn unix_time_from_filetime(...) {}
}
```

**Comment by WindSoilder** [comment]
Really love the implementation which open my mind :-D

File: crates/nu-command/src/filesystem/ls.rs (hunk 1 above)
Comment (rgwood) [reply crates/nu-command/src/filesystem/ls.rs:34]: Good idea! I’ll try that and your other suggestion, I agree that it would be nice to have fewer cfg lines

Comment (rgwood) [reply crates/nu-command/src/filesystem/ls.rs]: I think this is unnecessary now that I've moved Windows code into a module, but I'll keep that idea in mind for the future.

File: crates/nu-command/src/filesystem/ls.rs (hunk 2 above)
Comment (rgwood) [reply crates/nu-command/src/filesystem/ls.rs:602]: Great idea, done.
