### PR TITLE
fix 'let' to properly redirect

### LINKED ISSUE #9767: result of external command is not assigned with `let foo = ...`
### Describe the bug

when not using parentheses in a `let` assignment with external commands, it appears the value is not captured by the variable.

### How to reproduce

1. run `let output = "yes\nno" | fzf; print $"output: ($output)"` and observe
```
yes
output:
```
2. run `let output = git branch --show-current; print $"output: ($output)"` from a Git repo and observe
```
main
output:
```

### Expected behavior

i expected the return values of the external commands to be captured in the variables, i.e.
```nushell
> let output = "yes\nno" | fzf; print $"output: ($output)"
output: yes
```
```nushell
> let output = git branch --show-current; print $"output: ($output)"
output: main
```

### Screenshots

_No response_

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.82.1                                   |
| branch             | main                                     |
| commit_hash        | 656f707a0be48d04c356cc307450213ef1a39619 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)      |
| rust_channel       | 1.69.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)      |
| build_time         | 2023-07-17 19:32:26 +02:00               |
| build_rust_channel | release                                  |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  | hist, plot                               |

### Additional context

the commands above work by either
- wrapping the pipeline in parentheses
- adding `str trim` (any internal command?) after the call to the external command

### PR DESCRIPTION
**Pull request by jntrnr**
# Description

Fixes a bug in `let` where the pipeline wasn't being properly redirected.

fixes #9767

# User-Facing Changes

Shouldn't have any breaking changes, as this should be better for expected use cases.

# Tests + Formatting

# After Submitting

### CODE REVIEW

File: crates/nu-command/tests/commands/let_.rs [hunk 1]
```diff
@@ -46,6 +46,13 @@ fn mut_pipeline_allows_in() {
     assert_eq!(actual.out, "21");
 }
 
+#[test]
+fn let_pipeline_redirects() {
+    let actual = nu!(r#"let x = echo 'bar'; $x | str length"#);
```
Comment (sholderbach) [inline crates/nu-command/tests/commands/let_.rs:51]: Maybe worth having the test with a testbin as an external as well. Just to make sure we don't break if we decide to change the `echo` behavior.

Comment (jntrnr) [reply crates/nu-command/tests/commands/let_.rs:51]: Added.

**Comment by sholderbach** [comment]
Lightning fast! Thanks!
