### PR TITLE
fixes `which` showing aliases as built-in nushell commands

### LINKED ISSUE #8577: `which` shows aliases as built-in commands
### Describe the bug

`which` incorrectly describes aliases as "Nushell built-in commands". I think it probably needs to be updated after @kubouch's recent alias changes.

### How to reproduce

```
> alias foo = print "foo!"
> foo
foo!
> which foo
╭───┬─────┬──────────────────────────┬──────────╮
│ # │ arg │           path           │ built-in │
├───┼─────┼──────────────────────────┼──────────┤
│ 0 │ foo │ Nushell built-in command │ true     │
╰───┴─────┴──────────────────────────┴──────────╯
```

### Expected behavior

I expect `which` to describe `foo` as an alias, and for the `built-in` column to be false.

### Screenshots

_No response_

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.77.2                                   |
| branch             | main                                     |
| commit_hash        | 66ad83c15ce0289a9901b5f618e9ea95ea763974 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-03-22 18:59:19 -07:00               |
| build_rust_channel | debug                                    |
| features           | default, zip                             |
| installed_plugins  | inc                                      |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AyushSingh13**
fixes #8577 

# Description
Currently, using `which` on an alias describes it as a nushell built-in command:
```bash
> alias foo = print "foo!"                                                                                                                                                                                   > which ls foo --all                                                                                                                                                                                        
╭───┬─────┬──────────────────────────┬──────────╮
│ # │ arg │           path           │ built-in │
├───┼─────┼──────────────────────────┼──────────┤
│ 0 │ ls  │ Nushell built-in command │ true     │
│ 1 │ ls  │ /bin/ls                  │ false    │
│ 2 │ foo │ Nushell built-in command │ true     │
╰───┴─────┴──────────────────────────┴──────────╯
```

This PR fixes the behaviour above to the following:
```bash
> alias foo = print "foo!"
> which ls foo --all
╭───┬─────┬──────────────────────────┬──────────╮
│ # │ arg │           path           │ built-in │
├───┼─────┼──────────────────────────┼──────────┤
│ 0 │ ls  │ Nushell built-in command │ true     │
│ 1 │ ls  │ /bin/ls                  │ false    │
│ 2 │ foo │ Nushell alias            │ false    │
╰───┴─────┴──────────────────────────┴──────────╯
```

# User-Facing Changes
Passing in an alias to `which` will no longer return `Nushell built-in command`, `true` for `path` and `built-in` respectively. 

# Tests + Formatting

# After Submitting

### CODE REVIEW

File: crates/nu-command/src/system/which_.rs [hunk 1]
```diff
@@ -97,6 +99,7 @@ fn get_entries_in_nu(
 ) -> Vec<Value> {
     let mut all_entries = vec![];
 
+    // TODO: how can all_entries ever be non-empty here?
```
Comment (AyushSingh13) [inline crates/nu-command/src/system/which_.rs:102]: just a question, will remove this TODO later!

Comment (amtoine) [reply crates/nu-command/src/system/which_.rs:102]: that is a very good question here :laughing: 

because of `let mut all_entries = vec![];`, `all_entries` is empty on the next line and thus `!all_entries.is_empty()` is always `false` regardless of the value of `skip_after_first_found` :eyes:

Comment (amtoine) [reply crates/nu-command/src/system/which_.rs:102]: so we'll want to remove this line to land this PR :wink:

**Review by amtoine — CHANGES_REQUESTED** [review]
looks like a simple change which solves the issue, thanks :ok_hand: 

just a minor change as you probably guessed :wink:

**Comment by amtoine** [comment]
@AyushSingh13 
what do you think about adding a little test to make sure this behaviour is correct in the future?
a simple little scripts as in the PR description :yum:

**Comment by sholderbach** [comment]
@amtoine @AyushSingh13 

We already have some `which` tests involving aliases, that may be worth revisiting and expanding in https://github.com/nushell/nushell/blob/main/crates/nu-command/tests/commands/which.rs

Maybe the following works now and doesn't need to be ignored after @kubouch 's new alias work: 
https://github.com/nushell/nushell/blob/9ef1203ef9da48216fe01e0303fe5838f1de1335/crates/nu-command/tests/commands/which.rs#L13-L22

**Comment by amtoine** [comment]
yup, if we have *ignored* test that we can *un-ignore* then let's go for it :yum:

File: crates/nu-command/src/system/which_.rs (hunk 1 above)
Comment (AyushSingh13) [reply crates/nu-command/src/system/which_.rs:102]: thank you and done! :)

**Comment by AyushSingh13** [comment]
> @AyushSingh13 what do you think about adding a little test to make sure this behaviour is correct in the future? a simple little scripts as in the PR description 😋

Of course! I've added a test `which_custom_alias`. However, the `which_alias_ls()` @sholderbach mentioned still fails because the `path` doesn't include the alias definition just yet. I was trying to figure out how to do this and bounced around `Signature` and `Expression`s a bit but haven't figured it out yet! If it's not urgent, would it be okay for me to open a new issue and PR for this? If not, I'm happy to look into it more to include the definitions in this PR itself :)

**Comment by amtoine** [comment]
@AyushSingh13 
do the tests pass with this PR?

it's hard to tell because the CI stops on Clippy :open_mouth: 

if it passes i'd say let's leave this other issue for another PR, otherwise, it might be related so we should fix the tests in this PR :yum:

File: crates/nu-command/tests/commands/which.rs [hunk 2]
```diff
@@ -21,6 +21,16 @@ fn which_alias_ls() {
     assert_eq!(actual.out, "Nushell alias: ls -a");
 }
 
+#[test]
+fn which_custom_alias() {
+    let actual = nu!(
+        cwd: ".", 
+        r#"alias foo = print "foo!"; which foo | get path.0 | str trim"#
```
Comment (sholderbach) [inline crates/nu-command/tests/commands/which.rs:28]: Here you can omit the `cwd: "."` as it not necessary for the test to access the file system.

I would suggest making the test a bit more broad by changing the output to `| to nuon --raw` instead of just testing one field. Then we can also validate the `built-in` field in the same test.

**Comment by sholderbach** [comment]
> Of course! I've added a test `which_custom_alias`. However, the `which_alias_ls()` @sholderbach mentioned still fails because the `path` doesn't include the alias definition just yet. I was trying to figure out how to do this and bounced around `Signature` and `Expression`s a bit but haven't figured it out yet! If it's not urgent, would it be okay for me to open a new issue and PR for this? If not, I'm happy to look into it more to include the definitions in this PR itself :)

Mhh if the test that is currently ignored still fails for unrelated reasons, let's keep it out of this PR for now. (Maybe there is still a problem with "recursive" aliases)
Let's get your `which` output for the working aliases correct first.

File: crates/nu-command/tests/commands/which.rs (hunk 2 above)
Comment (AyushSingh13) [reply crates/nu-command/tests/commands/which.rs]: done!

**Comment by AyushSingh13** [comment]
> @AyushSingh13 do the tests pass with this PR?
> 
> it's hard to tell because the CI stops on Clippy 😮
> 
> if it passes i'd say let's leave this other issue for another PR, otherwise, it might be related so we should fix the tests in this PR 😋

Apologies for that, I should've run those clippy, fmt and tests locally! The tests and clippy both passed before but fmt gave us this:
```bash
$ cargo fmt --all -- --check
Diff in /Users/ayush/projects/nushell/crates/nu-command/tests/commands/which.rs at line 24:                                                                                                                                                           
 #[test]                                                                                                                                                                                                                                              
 fn which_custom_alias() {                                                                                                                                                                                                                            
     let actual = nu!(                                                                                                                                                                                                                                
-        cwd: ".",                                                                                                                                                                                                                                    
+        cwd: ".",                                                                                                                                                                                                                                    
         r#"alias foo = print "foo!"; which foo | get path.0 | str trim"#                                                                                                                                                                             
     );   
```
I'm unsure what that diff is and not sure how I can go about comparing what it is - both lines look the same to me! 

Either way, I've fixed this now, edited the test to use `to nuon` and made sure all tests are passing too 😊

**Review by sholderbach — APPROVED** [review]
Thanks this looks good!

**Comment by amtoine** [comment]
@AyushSingh13 
> I'm unsure what that diff is and not sure how I can go about comparing what it is - both lines look the same to me!
>
there was a trailing whitespace before the patch :yum: 
i'm not sure `cargo fmt` shows trailing whitespaces properly :thinking: 

the easiest is to run `cargo fmt --all`, without the `--check`, so that `cargo` will patch the code for ya :ok_hand: 
you can also use the `toolkit.nu` of the repo with `toolkit fmt` :wink:

**Comment by AyushSingh13** [comment]
> @AyushSingh13
> 
> > I'm unsure what that diff is and not sure how I can go about comparing what it is - both lines look the same to me!
> 
> there was a trailing whitespace before the patch 😋 i'm not sure `cargo fmt` shows trailing whitespaces properly 🤔
> 
> the easiest is to run `cargo fmt --all`, without the `--check`, so that `cargo` will patch the code for ya 👌 you can also use the `toolkit.nu` of the repo with `toolkit fmt` 😉

Ah, that makes sense - thank you! Will go create the issue for including the alias definition and hopefully get deeper into things! thank you for all your help

**Comment by amtoine** [comment]
> Ah, that makes sense - thank you!
>
anytime :wink: 
i've created the toolkit to not have to remember the `cargo` commands, i typically never run `cargo` with Nushell :smirk: 

> Will go create the issue for including the alias definition and hopefully get deeper into things!
>
:ok_hand:
