### PR TITLE
fix(cd): on android/termux fails to cd into /sdcard

### LINKED ISSUE #8095: Cannot `cd` into `/storage/emulated/0` and any subdirectories of it on Termux
### Describe the bug

Nushell is unable to `cd` into `/storage/emulated/0` and shows a (false) permission error on Termux.

### How to reproduce

1. Open Termux
2. Grant storage permission for Termux
3. `pkg install nushell`
4. `cd /storage/emulated/0`

### Expected behavior

Nushell is expected to change the current working directory to `/storage/emulated/0` as `bash` `zsh` `fish` and other shells do.

### Screenshots

IMG_20230216_160752

### Configuration

| key                | value                                |
| ------------------ | ------------------------------------ |
| version            | 0.75.0                               |
| branch             |                                      |
| commit_hash        |                                      |
| build_os           | linux-x86_64                         |
| build_target       | aarch64-linux-android                |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)  |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu      |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)  |
| pkg_version        | 0.75.0                               |
| build_time         | 2023-02-01 00:37:05 +00:00           |
| build_rust_channel | release                              |
| features           | database, default, trash, which, zip |
| installed_plugins  |                                      |

### Additional context

- Other commands work just fine under that directory.
- The output of `ls -ld /storage/emulated/0` is as follows:
```
drwxrwx--- 149 root everybody 12288 Feb 16 14:50 /storage/emulated/0
```

### PR DESCRIPTION
**Pull request by hardfau1t**
fix on android/termux fails to cd into /sdcard or any directory that user has access via group

fixes #8095

I am not aware how this works on other platform so feel free to modify this pr or even close it if it is not correct

# Description
on android or on linux to check if the user belongs to given directory group, use `libc::getgroups` function

# User-Facing Changes
NA

# Tests + Formatting

# After Submitting

### CODE REVIEW

File: crates/nu-command/src/filesystem/cd.rs [hunk 1]
```diff
@@ -271,7 +271,14 @@ fn have_permission(dir: impl AsRef<Path>) -> PermissionResult<'static> {
...
 
-#[cfg(unix)]
+#[cfg(any(target_os = "linux", target_os = "android"))]
+fn any_group(_current_user_gid: gid_t, owner_group: u32) -> bool {
+    use crate::filesystem::util::users;
+    let Some(user_groups) = users::current_user_groups() else {return false};
+    user_groups.iter().any(|gid| gid.as_raw() == owner_group)
+}
+
+#[cfg(all(unix, not(any(target_os = "linux", target_os = "android"))))]
```
Comment (WindSoilder) [inline crates/nu-command/src/filesystem/cd.rs:281]: So this can be `[cfg(all(unix, not(target_os = "android")))]`

File: crates/nu-command/src/filesystem/util.rs [hunk 2]
```diff
@@ -185,13 +184,38 @@ pub mod users {
         Gid::current().as_raw()
     }
 
+    #[cfg(not(any(target_os = "linux", target_os = "android")))]
```
Comment (WindSoilder) [inline crates/nu-command/src/filesystem/util.rs:187]: The same to above

File: crates/nu-command/src/filesystem/util.rs [hunk 3]
```diff
@@ -185,13 +184,38 @@ pub mod users {
...
     pub fn get_current_username() -> Option<String> {
         User::from_uid(Uid::current())
             .ok()
             .flatten()
             .map(|user| user.name)
     }
 
+    #[cfg(any(target_os = "linux", target_os = "android"))]
```
Comment (WindSoilder) [inline crates/nu-command/src/filesystem/util.rs:195]: The same to above

File: cd-fix.patch
Comment (WindSoilder) [inline cd-fix.patch:1]: What's the purpose of this file?

**Review by WindSoilder — CHANGES_REQUESTED** [review]
Hi, thanks for your pr, I've leaved some comments, would you please have a look?

File: crates/nu-command/src/filesystem/cd.rs [hunk 4]
```diff
@@ -271,7 +271,14 @@ fn have_permission(dir: impl AsRef<Path>) -> PermissionResult<'static> {
     }
 }
 
-#[cfg(unix)]
+#[cfg(any(target_os = "linux", target_os = "android"))]
```
[the remark this answers is not in the document]
Comment (hardfau1t) [reply crates/nu-command/src/filesystem/cd.rs:274]: this works for both linux and android,  this implementation of `any_group` is more efficient than former one, but i wasn't sure whether `osx` comes under linux or not and whether this logic works on `osx` or not, so considered for only `linux` and `android`

File: crates/nu-command/src/filesystem/cd.rs (hunk 1 above)
Comment (hardfau1t) [reply crates/nu-command/src/filesystem/cd.rs:281]: as above, this more efficient way of checking group for linux can done using above implementation so

File: crates/nu-command/src/filesystem/util.rs (hunk 2 above)
Comment (hardfau1t) [reply crates/nu-command/src/filesystem/util.rs:187]: answered above

File: crates/nu-command/src/filesystem/util.rs (hunk 3 above)
Comment (hardfau1t) [reply crates/nu-command/src/filesystem/util.rs:195]: answered  above

File: crates/nu-command/src/filesystem/util.rs [hunk 5]
```diff
@@ -185,13 +184,38 @@ pub mod users {
...
+        let mut buff: Vec<gid_t> = vec![0; ngroups as usize];
+
+        // SAFETY:
+        // buff is the size of ngroups and  getgroups reads max ngroups elements into buff
+        let found = unsafe { libc::getgroups(ngroups, buff.as_mut_ptr()) };
+
+        if found < 0 {
+            None
+        } else {
+            buff.truncate(ngroups as usize);
```
Comment (sholderbach) [inline crates/nu-command/src/filesystem/util.rs:209]: Should we truncate to `found` here? If I read `man getgroups` correctly, this should also contain the length if given not `0` to `size`. Not sure if there could be a small TOCTOU risk here?
```suggestion
            buff.truncate(found as usize);
```

Comment (hardfau1t) [reply crates/nu-command/src/filesystem/util.rs:209]: yes, it make sense to use found instead of ngroups

**Review by sholderbach — COMMENTED** [review]
I don't have a setup to validate that this can resolve the access issues for Android but things sound good to me to simplify getting the groups on Linux (without taking the detour of inquiring the username). Implementation looks safe to me,

Don't have the system knowledge to say whether we could do the same on MacOS or the BSDs.

**Review by WindSoilder — APPROVED** [review]
OK, thank you for your explanation.  Then it looks good to me :-D

**Comment by WindSoilder** [comment]
And BTW, please don't rebase and force-push the branch during a pr, in case we can track changes in pr more easily :)

For more information you can read: https://amtoine.github.io/posts/you-shall-not-rebase/
