### PR TITLE
fix(parse): support char lbrace before trailing capture

### LINKED ISSUE #17814: Escaping '{' in string parse pattern with char lbrace does not work
### Bug report form

- [x] I have done a basic search of the issue tracker to find any existing issues that are similar.
- [x] I have checked that my version is at least the latest stable release available via my installation method.

### Describe the bug

Hi, when parsing strings with `parse`, escaping the '{' character with `(char lbrace)` does not work. Escaping with `(char rbrace)`, `(char pipe)`, etc. does indeed work.

### How to reproduce

```
> "1234|56" | parse $'{a}(char pipe){b}'
╭───┬──────┬────╮
│ # │  a   │ b  │
├───┼──────┼────┤
│ 0 │ 1234 │ 56 │
╰───┴──────┴────╯
> "1234}56" | parse $'{a}(char rbrace){b}'
╭───┬──────┬────╮
│ # │  a   │ b  │
├───┼──────┼────┤
│ 0 │ 1234 │ 56 │
╰───┴──────┴────╯
> "1234{56" | parse $'{a}(char lbrace){b}'
╭────────────╮
│ empty list │
╰────────────╯
>

```

### Expected behavior

Escaping '{' should work like other characters.

### Configuration

| key                  | value                                                                                                                                      |
| -------------------- | ------------------------------------------------------------------------------------------------------------------------------------------ |
| version              | 0.111.0                                                                                                                                    |
| major                | 0                                                                                                                                          |
| minor                | 111                                                                                                                                        |
| patch                | 0                                                                                                                                          |
| branch               |                                                                                                                                            |
| commit_hash          |                                                                                                                                            |
| build_os             | macos-aarch64                                                                                                                              |
| build_target         | aarch64-apple-darwin                                                                                                                       |
| rust_version         | rustc 1.93.1 (01f6ddf75 2026-02-11) (built from a source tarball)                                                                          |
| cargo_version        | cargo 1.93.0                                                                                                                               |
| build_time           | 2026-03-02 07:47:14 +00:00                                                                                                                 |
| build_rust_channel   | release                                                                                                                                    |
| allocator            | standard                                                                                                                                   |
| features             | default, mcp, network, plugin, rustls-tls, sqlite, trash-support                                                                           |
| installed_plugins    | custom_values 0.1.0, example 0.111.0, formats 0.111.0, gstat 0.111.0, inc 0.111.0, polars 0.111.0, query 0.111.0, stress_internals 0.111.0 |
| experimental_options | example=false, reorder-cell-paths=true, pipefail=true, enforce-runtime-annotations=false, native-clip=false                                |

### PR DESCRIPTION
**Pull request by Dexterity104**
## What this does

`parse $'{a}(char lbrace){b}'` on something like `1234{56` gave an empty table. Pipe and rbrace in the same style worked, so this was just lbrace getting eaten by the `{…}` parsing. Adjusted that so the interpolated case lines up with the others.

Closes #17814 

## Release notes summary - What our users need to know

`parse` simple patterns: literal `{` via `(char lbrace)` before a `{name}` capture works now.

## Tasks after submitting

- [ ] Update the [documentation](https://github.com/nushell/nushell.github.io)

### CODE REVIEW

File: crates/nu-command/src/strings/parse.rs [hunk 1]
```diff
@@ -287,7 +287,23 @@ fn build_regex(input: &str, span: Span) -> Result<String, ShellError> {
             if c == '{' {
                 // If '{{', still creating a plaintext parse command, but just for a single '{' char
                 if loop_input.peek() == Some(&'{') {
-                    let _ = loop_input.next();
+                    // Allow `{{name}` at end, like `$'{a}(char lbrace){b}'`, where `{` is literal
+                    let mut lookahead = loop_input.clone();
```
Comment (fdncred) [inline crates/nu-command/src/strings/parse.rs]: I'm wondering if you can do this without a clone here.

**Comment by Dexterity104** [comment]
Thanks for your review. It makes sense for both the clone and the extra `{{foo}` tests.
About `nu!()`, should I switch only the new tests, or migrate the whole parse test file?

**Comment by fdncred** [comment]
Just the new tests are fine.

**Comment by fdncred** [comment]
I hope you don't mind but I took a stab at refactoring your PR a little bit. I really didn't like how brittle it seemed after using manual byte tracking with character iteration. I'm hopeful that working through char_indicies() is a better approach. Also tried to make it a little more readable.

**Comment by Dexterity104** [comment]
@fdncred 
Yeah, this is really better than mine. Thanks for cleaning it up and improving it. I like this approach more.

**Comment by fdncred** [comment]
Thanks
