### PR TITLE
Make `get` hole errors and cell path hole errors identical (improvement on #7002)

### LINKED ISSUE #7498: Cell paths: `foo.1` is not always equal to `1.foo`
### Describe the bug

image

### How to reproduce

1. Run `[ { foo: "bar"}, {  } ] | get foo.1`, it returns `Nothing`
2. Run `[ { foo: "bar"}, {  } ] | get 1.foo`, it fails with a `ShellError`

### Expected behavior

If a cell path has 2 members and one member is a number but the other is a column name, the order of those members should not matter. I'm not sure exactly what the behaviour should be here, but I do think it's desirable for the behaviour to be consistent.

I lean toward making both return a `ShellError`, but I'm not sure if there are some situations where that would be problematic (dealing with JSON files maybe?). Please chime in if you have an opinion or are aware of important scenarios we should be considering.

### Screenshots

_No response_

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.72.2                                   |
| branch             | main                                     |
| commit_hash        | b7572f107fb956259eb979ba9f9a37b89dde2ead |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.72.2                                   |
| build_time         | 2022-12-07 16:34:42 -08:00               |
| build_rust_channel | debug                                    |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by webbedspace**
# Description

This closes #7498, as well as fixes an issue reported in https://github.com/nushell/nushell/pull/7002#issuecomment-1368340773

BEFORE:
```
〉[{foo: 'bar'} {}] | get foo
Error: nu::shell::column_not_found (link)

  × Cannot find column
   ╭─[entry #5:1:1]
 1 │ [{foo: 'bar'} {}] | get foo
   · ────────┬────────   ─┬─
   ·         │            ╰── value originates here
   ·         ╰── cannot find column 'Empty cell'
   ╰────

〉[{foo: 'bar'} {}].foo
╭───┬─────╮
│ 0 │ bar │
│ 1 │     │
╰───┴─────╯
```
AFTER:
```
〉[{foo: 'bar'} {}] | get foo
Error: nu::shell::column_not_found (link)

  × Cannot find column
   ╭─[entry #1:1:1]
 1 │ [{foo: 'bar'} {}] | get foo
   ·               ─┬        ─┬─
   ·                │         ╰── cannot find column 'foo'
   ·                ╰── value originates here
   ╰────

〉[{foo: 'bar'} {}].foo
Error: nu::shell::column_not_found (link)

  × Cannot find column
   ╭─[entry #3:1:1]
 1 │ [{foo: 'bar'} {}].foo
   ·               ─┬  ─┬─
   ·                │   ╰── cannot find column 'foo'
   ·                ╰── value originates here       
   ╰────
```

EDIT: This also changes the semantics of `get`/`select` `-i` somewhat. I've decided to leave it like this because it works more intuitively with `default` and `compact`.
BEFORE:
```
〉[{a:1} {b:2} {a:3}] | select -i foo | to nuon
null
```
AFTER:
```
〉[{a:1} {b:2} {a:3}] | select -i foo | to nuon
[[foo]; [null], [null], [null]]
```

# User-Facing Changes

See above. EDIT: the issue with holes in cases like ` [{foo: 'bar'} {}].foo.0` versus ` [{foo: 'bar'} {}].0.foo` has been resolved.

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by rgwood** [comment]
Nice!

I think this is a step in the right direction. We may also need to adjust the behaviour of `get -i`:

```
〉[{ foo: "bar"} {}] | get -i foo
〉[{ foo: "bar"} {}] | get -i foo | to nuon
null
〉[{ foo: "bar"} {}] | select -i foo
╭───┬─────╮
│ # │ foo │
├───┼─────┤
│ 0 │ bar │
│ 1 │     │
╰───┴─────╯
```

IMO the behaviour of `get -i` where it returns a single `null` value is not very useful; it should behave like `select` and replace missing columns with nulls. At least that's how I envision error handling working.

**Comment by webbedspace** [comment]
I came up with an ingenious way of making `[{foo: 'bar'} {}].foo.0` still work, even though the `.foo` access *should* produce an error at that point in cell path evaluation. See [here](https://github.com/nushell/nushell/pull/7647/files#diff-654f056f1c72a4868170c32aa44d6dd497a83cb1c8b919e24a7dc50e8f81e624R761-R770) for details.

**Comment by rgwood** [comment]
Hmm, I think that change is generally a good idea but `get -i` seems more broken now:

```
〉[{ foo: "bar"} {}] | get -i foo
Error: nu::shell::column_not_found (link)

  × Cannot find column
   ╭─[entry #7:1:1]
 1 │ [{ foo: "bar"} {}] | get -i foo
   ·                ─┬           ─┬─
   ·                 │            ╰── cannot find column 'foo'
   ·                 ╰── value originates here
   ╰────
```

**Comment by webbedspace** [comment]
OK, I fixed it. However, I just noticed I've inadvertently changed the semantics of `-i` somewhat.

BEFORE:
```
〉[{a:1} {b:2} {a:3}] | select -i a | to nuon
[[a]; [1], [null], [3]]
〉[{a:1} {b:2} {a:3}] | select -i foo | to nuon
null
```
AFTER:
```
〉[{a:1} {b:2} {a:3}] | select -i a | to nuon
[[a]; [1], [null], [3]]
〉[{a:1} {b:2} {a:3}] | select -i foo | to nuon
[[foo]; [null], [null], [null]]
```
I've decided that the latter way is better because it can interact with `default` more intuitively:
```
〉[{a:1} {b:2} {a:3}] | select -i a | default 0 a
[[a]; [1], [0], [3]]
〉[{a:1} {b:2} {a:3}] | select -i foo | default 0 foo
[[foo]; [0], [0], [0]]
```

File: crates/nu-command/tests/commands/default.rs [hunk 1]
```diff
@@ -24,7 +24,7 @@ fn adds_row_data_if_column_missing() {
             r#"
                 open los_tres_amigos.json
                 | get amigos
-                | default rusty_luck 1
+                | default 1 rusty_luck
```
Comment (webbedspace) [inline crates/nu-command/tests/commands/default.rs:27]: By the way… am I losing my mind, or was this test always wrong until now? `default rusty_luck 1` is not the correct order of `default` arguments, and never was, right?

File: crates/nu-protocol/src/pipeline_data.rs [hunk 2]
```diff
@@ -671,9 +672,11 @@ impl PipelineData {
         to_stderr: bool,
     ) -> Result<i64, ShellError> {
         for item in self {
+            let mut is_err = false;
             let mut out = if let Value::Error { error } = item {
                 let working_set = StateWorkingSet::new(engine_state);
-
+                // Value::Errors must always go to stderr, not stdout.
+                is_err = true;
```
Comment (webbedspace) [inline crates/nu-protocol/src/pipeline_data.rs:679]: Does anyone have an opinion about these lines? I don't know why Value::Errors seemingly were allowed to go to `stdout`, but that seemed wrong to me (and I needed to make this change to make a test pass, due to the aforementioned business about creating but not returning Value::Errors in `follow_cell_path_helper()`.

**Comment by rgwood** [comment]
> OK, I fixed it. However, I just noticed I've inadvertently changed the semantics of `-i` somewhat.

Sounds good to me - the "`-i` collapses everything into a single `null`" behaviour was bad IMO.

File: crates/nu-protocol/src/pipeline_data.rs (hunk 2 above)
Comment (rgwood) [reply crates/nu-protocol/src/pipeline_data.rs:679]: I think it makes sense to force errors to stderr.

File: crates/nu-command/tests/commands/default.rs (hunk 1 above)
Comment (rgwood) [reply crates/nu-command/tests/commands/default.rs:27]: Suspect the test was always wrong.

FWIW I also assumed that the order was `default <column name> <default value>` instead of when I first encountered `default`, I find the current order somewhat unintuitive.

File: crates/nu-command/src/filters/length.rs [hunk 3]
```diff
@@ -81,7 +81,17 @@ fn length_row(call: &Call, input: PipelineData) -> Result<PipelineData, ShellErr
         PipelineData::Value(Value::Nothing { .. }, ..) => {
             Ok(Value::int(0, call.head).into_pipeline_data())
         }
-        _ => Ok(Value::int(input.into_iter().count() as i64, call.head).into_pipeline_data()),
+        _ => {
+            let mut count: i64 = 0;
+            // Check for and propagate errors
```
Comment (rgwood) [inline crates/nu-command/src/filters/length.rs:86]: I'm a little concerned by this approach of checking for errors in downstream commands.I worry that there will be a long tail of commands where we forget to do it, leading to inconsistency. It also takes us further away from an "errors are just data" approach (which we admittedly do not adhere to very well today).

That said, users who do something like `$foo | get bar | length` will expect it to fail on an unsuccessful `bar` access... so maybe this is an OK approach for now.

In the future it would be nice if this sort of check was handled at a higher level (not sure exactly where).

**Review by rgwood — APPROVED** [review]
Thanks for the PR!

I think this is a good incremental improvement to cell paths. I really like that behaviour is more consistent across `get` and `select` now, and that `-i` no longer collapses multiple errors to a single `null` value.

This one will probably break a handful of scripts, and it will need an explanation in the 0.74 blog post (0.74 is being released on Jan 10): https://github.com/nushell/nushell.github.io/pull/715

**Comment by fdncred** [comment]
+1 for more consistent and expected behavior
