### PR TITLE
Fix 9156 endian consistency

### LINKED ISSUE #9156: Issue with `into binary`
### Describe the bug

The `into binary` fill the high bits first, leaving low bits with zeros. Is this behavior intended?

### How to reproduce

```bash
1 | into binary | into int
```
Output
```
72057594037927936
```

### Expected behavior

1

### Screenshots

_No response_

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.79.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-x86_64                                                      |
| build_target       | x86_64-apple-darwin                                               |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27) (built from a source tarball) |
| cargo_version      | cargo 1.68.1 (6feb7c9cf 2023-03-26)                               |
| build_time         | 2023-04-25 20:06:17 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | default, zip                                                      |
| installed_plugins  |                                                                   |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by herobs**
- fixed #9156

# Description
I'm trying to fix the problems mentioned in the issue. It's my first attempt in Rust. Please let me know if there are any problems.

# User-Facing Changes
- The `--little-endian` option dropped, replaced with `--endian`.
- Add the `--compact` option to the `into binary` command.
- `into int` accepts binary input

### CODE REVIEW

File: crates/nu-command/src/conversions/into/binary.rs [hunk 1]
```diff
@@ -39,6 +40,7 @@ impl Command for SubCommand {
                 (Type::Record(vec![]), Type::Record(vec![])),
             ])
             .allow_variants_without_examples(true) // TODO: supply exhaustive examples
+            .switch("compact", "output without padding zeros", None)
```
Comment (fdncred) [inline crates/nu-command/src/conversions/into/binary.rs:43]: Instead of `None` here, it seems like we should have a shortcut like `Some('c')`

File: crates/nu-command/src/conversions/into/binary.rs [hunk 2]
```diff
@@ -209,6 +206,32 @@ pub fn action(input: &Value, _args: &Arguments, span: Span) -> Value {
...
+    };
+
+    if _args.compact {
+        if let Value::Binary { val, span } = value {
+            let val = if cfg!(target_endian = "little") {
+                let mut idx = val.len() - 1;
+                while val[idx] == 0 {
+                    idx -= 1;
+                }
+                let (val, _) = val.split_at(idx + 1);
```
Comment (fdncred) [inline crates/nu-command/src/conversions/into/binary.rs:218]: This `val.split_at` surprised me. It looks like we're just taking the last 0 off until there are no more zeros. This makes my "spidey sense" go off as not being the right way to handle this, but I could be wrong.

**Comment by herobs** [comment]
I have no idea how to test the big-endian branch. Please give me some hints if you have any.

File: crates/nu-command/src/conversions/into/int.rs [hunk 3]
```diff
@@ -72,7 +73,12 @@ impl Command for SubCommand {
             ])
             .allow_variants_without_examples(true)
             .named("radix", SyntaxShape::Number, "radix of integer", Some('r'))
-            .switch("little-endian", "use little-endian byte decoding", None)
+            .named(
+                "endian",
+                SyntaxShape::String,
+                "byte encode endian, available options: native(default), little, big",
+                None,
```
Comment (fdncred) [inline crates/nu-command/src/conversions/into/int.rs:80]: We prefer to have shortcuts where we can like `Some('e')` here vs `None`.

File: crates/nu-command/src/conversions/into/int.rs [hunk 4]
```diff
@@ -72,7 +73,12 @@ impl Command for SubCommand {
             ])
             .allow_variants_without_examples(true)
             .named("radix", SyntaxShape::Number, "radix of integer", Some('r'))
-            .switch("little-endian", "use little-endian byte decoding", None)
```
Comment (jntrnr) [inline crates/nu-command/src/conversions/into/int.rs:75]: Removing `--little-endian` makes this a bit harder to read (compared to `--endian little`

File: crates/nu-command/tests/commands/mod.rs [hunk 5]
```diff
@@ -8,6 +8,7 @@ mod cal;
 mod cd;
 mod compact;
 mod continue_;
+mod convertions;
```
Comment (amtoine) [inline crates/nu-command/tests/commands/mod.rs:11]: i just think this should be called "*conversions*", not "*convertions*", right? :open_mouth:

**Review by amtoine — CHANGES_REQUESTED** [review]
thanks for the new tests, i think it's great :pray:

**Comment by amtoine** [comment]
running the CI to see if the test pass :wink:

File: crates/nu-command/tests/commands/mod.rs (hunk 5 above)
Comment (amtoine) [reply crates/nu-command/tests/commands/mod.rs]: thanks :blush: 

done in eb6d9f8

**Comment by fdncred** [comment]
let's move forward with this, thanks!
