### PR TITLE
Make `to text` line endings consistent for list (streams)

### LINKED ISSUE #14151: `to text` behave inconsistently with `list<str>` and `list<str>` on stream
### Describe the bug

To text joins list of strings without ending lines, while if we pass that list through `each` it will add a trailing new line.

Initially found [here](https://github.com/nushell/nushell/issues/13155#issuecomment-2430428560)

### How to reproduce

```
> [a] |           to text | into binary                                                                      
Length: 1 (0x1) bytes | printable whitespace ascii_other non_ascii
00000000:   61
                                                  
> [a] | each {} | to text | into binary                                                                      
Length: unknown (stream) | printable whitespace ascii_other non_ascii
00000000:   61 0a
```

### Expected behavior

I expect `to list` behave consistently

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.99.1                                   |
| major              | 0                                        |
| minor              | 99                                       |
| patch              | 1                                        |
| branch             |                                          |
| commit_hash        | 8812072f065be283df3e9a81f3945d0364f2f247 |
| build_os           | macos-aarch64                            |
| build_target       | aarch64-apple-darwin                     |
| rust_version       | rustc 1.79.0 (129f3b996 2024-06-10)      |
| rust_channel       | 1.79.0-aarch64-apple-darwin              |
| cargo_version      | cargo 1.79.0 (ffa9cf99a 2024-06-03)      |
| build_time         | 2024-10-22 18:30:13 -03:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash                   |
| installed_plugins  | polars 0.99.0                            |

### PR DESCRIPTION
**Pull request by IanManske**
# Description
Fixes #14151 where `to text` treats list streams and lists values differently.

# User-Facing Changes
New line is always added after items in a list or record except for the last item if the `--no-newline` flag is provided.

### CODE REVIEW

File: crates/nu-command/src/formats/to/text.rs [hunk 1]
```diff
@@ -40,44 +41,69 @@ impl Command for ToText {
...
+                            let Some(val) = iter.next() else {
+                                return Ok(false);
+                            };
+                            if first {
+                                first = false;
+                            } else {
+                                write!(buf, "{LINE_ENDING}").err_span(head)?;
+                            }
+                            // TODO: write directly into `buf` instead of creating an intermediate
+                            // string.
```
Comment (sholderbach) [inline crates/nu-command/src/formats/to/text.rs:87]: What is the challenge here?

**Comment by sholderbach** [comment]
Is this still relevant on top of whatever closed #14151 ?

Maybe worth expanding the title so folks don't look past the PR.

Generally trust your experience on the stream side and thanks for the extended tests!

**Comment by IanManske** [comment]
> Is this still relevant on top of whatever closed #14151 ?

Yeah, this is still mainly addressing #14151, since I missed a few bugs when reviewing #14158.
