### PR TITLE
Exit early when encountering parsing errors

### LINKED ISSUE #10184: panic when calling custom command with file argument
### Describe the bug

A Nushell script panics when calling a custom command that takes an argument of type `file`.
```console
thread 'main' panicked at 'Internal error: can't run a predeclaration without a body', crates/nu-protocol/src/signature.rs:644:9
stack backtrace:
   0:     0x55e9fbac0a06 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h63269f8f54853ab3
   1:     0x55e9faf6f15f - core::fmt::write::h250dd3fc350bbada
   2:     0x55e9fbad0991 - std::io::Write::write_fmt::h0fd841d7fefd9302
   3:     0x55e9fbac0805 - std::sys_common::backtrace::print::hc99c547a903c74f7
   4:     0x55e9fbadbc75 - std::panicking::default_hook::{{closure}}::h5bbb3f780658c969
   5:     0x55e9fbadb9b3 - std::panicking::default_hook::h1946653929a625f2
   6:     0x55e9fbadc0f9 - std::panicking::rust_panic_with_hook::h8216316e1970270b
   7:     0x55e9fbac0c84 - std::panicking::begin_panic_handler::{{closure}}::h45b7865605f63cc8
   8:     0x55e9fbac0ad6 - std::sys_common::backtrace::__rust_end_short_backtrace::h2efe3248368b98bf
   9:     0x55e9fbadbce2 - rust_begin_unwind
  10:     0x55e9faeef263 - core::panicking::panic_fmt::h90a1387c4eee835e
  11:     0x55e9fb8fbb01 - <nu_protocol::signature::Predeclaration as nu_protocol::engine::command::Command>::run::hcf0650133b43c86e
  12:     0x55e9fb4438fd - nu_engine::eval::eval_call::h4dbe1f2abf9a38a2
  13:     0x55e9fb44974e - nu_engine::eval::eval_expression_with_input::h410485afbabc01b8
  14:     0x55e9fb449d26 - nu_engine::eval::eval_element_with_input::h6376a31af5163b89
  15:     0x55e9fb44afad - nu_engine::eval::eval_block::h42d1849900714f06
  16:     0x55e9fb44ac5e - nu_engine::eval::eval_block_with_early_return::h48aea6f98c4de596
  17:     0x55e9fb444439 - nu_engine::eval::eval_call::h4dbe1f2abf9a38a2
  18:     0x55e9fb44974e - nu_engine::eval::eval_expression_with_input::h410485afbabc01b8
  19:     0x55e9fb449d26 - nu_engine::eval::eval_element_with_input::h6376a31af5163b89
  20:     0x55e9fb44afad - nu_engine::eval::eval_block::h42d1849900714f06
  21:     0x55e9fb44ac5e - nu_engine::eval::eval_block_with_early_return::h48aea6f98c4de596
  22:     0x55e9fb07ddc8 - nu_cli::util::eval_source::he5fefce78c942d30
  23:     0x55e9fb04d03b - nu_cli::eval_file::evaluate_file::h9f3d32681475b12d
  24:     0x55e9fb023985 - nu::run::run_file::h92f4db049085af77
  25:     0x55e9fb0328e2 - nu::main::h335c604ea4943b6b
  26:     0x55e9fb01fa7a - std::sys_common::backtrace::__rust_begin_short_backtrace::hccff6108e01f8ae1
  27:     0x55e9fb01fa85 - std::rt::lang_start::{{closure}}::h36b1955fce03ffb8
  28:     0x55e9fbabcf35 - std::rt::lang_start_internal::h8ab23524475b2279
  29:     0x55e9fb033675 - main
  30:     0x7fc5fc9edace - __libc_start_call_main
  31:     0x7fc5fc9edb89 - __libc_start_main@@GLIBC_2.34
  32:     0x55e9faf17565 - _start
  33:                0x0 - <unknown>
```

### How to reproduce

Write the following to a file called `repro.nu`
```nu
#!/usr/bin/env nu

def main [] {
  somefunc "foo"
}

def somefunc [
  somearg: file
] {
  echo $somearg
}
```

Run `./repro.nu`

### Expected behavior

The script to print the following and exit cleanly.
```console
foo
```

### Screenshots

_No response_

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.84.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03) (built from a source tarball) |
| cargo_version      | cargo 1.71.1                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | standard                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nibon7**
# Description
This PR tries to fix #10184 and #10182.

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Review by amtoine — COMMENTED** [review]
without even looking at the changes, i can confirm that the issues are gone, well done :muscle:

## for https://github.com/nushell/nushell/issues/10184
```nushell
Error: nu::parser::unknown_type

  × Unknown type.
   ╭─[/home/amtoine/documents/repos/github.com/amtoine/nushell/repro.nu:7:1]
 7 │ def somefunc [
 8 │   somearg: unknown_type
   ·            ──────┬─────
   ·                  ╰── unknown type
 9 │ ] {
   ╰────
```
instead of
```
thread 'main' panicked at 'Internal error: can't run a predeclaration without a body', crates/nu-protocol/src/signature.rs:644:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## for https://github.com/nushell/nushell/issues/10182
```nushell
Error: nu::parser::expected_keyword

  × Expected keyword.
   ╭─[/home/amtoine/documents/repos/github.com/amtoine/nushell/junk.nu:1:1]
 1 │ let x = "foo"
   · ─┬─
   ·  ╰── expected def, const, def-env, extern, extern-wrapped, alias, use, module, export or export-env keyword
 2 │
   ╰────
```
instead of
```
thread 'main' panicked at 'Internal error: can't run a predeclaration without a body', crates/nu-protocol/src/signature.rs:644:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

File: tests/eval/mod.rs [hunk 1]
```diff
@@ -6,3 +6,12 @@ fn source_file_relative_to_file() {
 
     assert!(actual.err.contains("redefined"));
 }
+
+#[test]
+fn run_file_parse_error() {
+    let actual = nu!(
+        cwd: "tests/fixtures/eval",
+    "nu script.nu");
```
Comment (amtoine) [inline tests/eval/mod.rs:14]:
```suggestion
    let actual = nu!(
        cwd: "tests/fixtures/eval",
        "nu script.nu"
    );
```

File: crates/nu-cli/src/eval_file.rs [hunk 2]
```diff
@@ -107,6 +107,11 @@ pub fn evaluate_file(
     trace!("parsing file: {}", file_path_str);
     let block = parse(&mut working_set, Some(file_path_str), &file, false);
 
+    if let Some(err) = working_set.parse_errors.first() {
+        report_error(&working_set, err);
```
Comment (sholderbach) [inline crates/nu-cli/src/eval_file.rs:111]: Is it meaningful to report all `working_set.parse_errors` if there are some?

**Review by sholderbach — COMMENTED** [review]
Good catch!

File: crates/nu-cli/src/eval_file.rs (hunk 2 above)
Comment (nibon7) [reply crates/nu-cli/src/eval_file.rs:111]: Looks very verbose :sweat_smile: 

* a.nu
```nu
let a=1
let 0a = 1
let a = '1"
```

./target/debug/nu a.nu

```
Error: nu::parser::unexpected_eof

  × Unexpected end of code.
   ╭─[/data/source/nushell/a.nu:3:1]
 3 │ let a = '1"
   ╰────

Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
   ╭─[/data/source/nushell/a.nu:1:1]
 1 │ let a=1
   ·     ─┬─
   ·      ╰── expected valid variable name
 2 │ let 0a = 1
   ╰────

Error: nu::parser::missing_positional

  × Missing required positional argument.
   ╭─[/data/source/nushell/a.nu:1:1]
 1 │ let a=1
   ·        ▲
   ·        ╰── missing initial_value
 2 │ let 0a = 1
   ╰────
  help: Usage: let <var_name> = <initial_value>

Error: nu::parser::unexpected_eof

  × Unexpected end of code.
   ╭─[/data/source/nushell/a.nu:3:1]
 3 │ let a = '1"
   ╰────
```

Comment (sholderbach) [reply crates/nu-cli/src/eval_file.rs:111]: OK yeah, that would require some extra work to be helpful. 

Let's get this merged as is for now and we can figure out how to improve that later. (The IDE support already uses those multiple errors to produce squigglies)
