### PR TITLE
fix error when exporting constants with type signatures in modules

### LINKED ISSUE #14023: `export const` with a type signature causes `Internal error: failed to find added variable`
### Describe the bug

Declaring an `export const` with a type signature inside a module results in an `Internal error` being thrown with the message `failed to find added variable`.

### How to reproduce

At the REPL, try to define the following module:

```nushell
> module foo { export const FOO: int = 2 }
Error: nu::parser::unknown_state

  × Internal error.
   ╭─[entry #1:1:21]
 1 │ module foo { export const FOO: int = 2 }
   ·                     ─────────┬────────
   ·                              ╰── failed to find added variable
   ╰────
```

Alternatively, define the module in a file named `foo.nu` and try to `use` it from the REPL:

```nushell
# foo.nu
export const FOO: int = 2
```

```nushell
# REPL
> use foo.nu
Error: nu::parser::unknown_state

  × Internal error.
   ╭─[/path/to/foo.nu:1:8]
 1 │ export const FOO: int = 2
   ·        ─────────┬────────
   ·                 ╰── failed to find added variable
   ╰────
```

The error is only produced if the `const` has both `export` _and_ a type signature. The specific type in the signature doesn't seem to matter.

The issue occurs even when running Nu with `--no-config-file --no-std-lib`.

### Expected behavior

I expected module `foo` to be defined without issue.

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.98.0                                                           |
| major              | 0                                                                |
| minor              | 98                                                               |
| patch              | 0                                                                |
| branch             | makepkg                                                          |
| commit_hash        | 6e1e824473e15eba246e1c43704c5d88fa237a17                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.81.0 (eeb90cda1 2024-09-04) (Arch Linux rust 1:1.81.0-1) |
| cargo_version      | cargo 1.81.0 (2dbb1af80 2024-08-20)                              |
| build_time         | 2024-09-18 13:20:08 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | default, sqlite, trash                                           |
| installed_plugins  |                                                                  |

### PR DESCRIPTION
**Pull request by sgvictorino**
Fixes #14023

# Description

- Prevents "failed to find added variable" when modules export constants
  with type signatures:

```nushell
> module foo { export const bar: int = 2 }
Error: nu::parser::unknown_state

  × Internal error.
   ╭─[entry #1:1:21]
 1 │ module foo { export const bar: int = 2 }
   ·                     ─────────┬────────
   ·                              ╰── failed to find added variable
```

- Returns `name_is_builtin_var` errors for names with type signatures:

```nushell
> let env: string = "";
Error: nu::parser::name_is_builtin_var

  × `env` used as variable name.
   ╭─[entry #1:1:5]
 1 │ let env: string = "";
   ·     ─┬─
   ·      ╰── already a builtin variable
```

### CODE REVIEW

File: crates/nu-parser/src/parser.rs [hunk 1]
```diff
@@ -3128,9 +3129,11 @@ pub fn parse_var_with_opt_type(
     }
 
     if bytes.ends_with(b":") {
+        let name_span = Span::new(name_span.start, name_span.end - 1);
+        let var_name = bytes[0..(bytes.len() - 1)].to_vec();
```
Comment (sholderbach) [inline crates/nu-parser/src/parser.rs:3133]: Nice that gets more explicit!

File: crates/nu-parser/src/parse_keywords.rs [hunk 2]
```diff
@@ -3154,7 +3154,7 @@ pub fn parse_let(working_set: &mut StateWorkingSet, spans: &[Span]) -> Pipeline
     garbage_pipeline(working_set, spans)
 }
 
-pub fn parse_const(working_set: &mut StateWorkingSet, spans: &[Span]) -> Pipeline {
+pub fn parse_const(working_set: &mut StateWorkingSet, spans: &[Span]) -> (Pipeline, Option<Span>) {
```
Comment (sholderbach) [inline crates/nu-parser/src/parse_keywords.rs:3157]: Maybe worth adding as part of the doccomment what the content of the `Option<Span>` is, otherwise those tuple return values are hard to deal with.

**Review by sholderbach — COMMENTED** [review]
Thanks for reworking this. Looks good to me and great additional test on the special name detection.
