### PR TITLE
Fix: dst error on cp command

### LINKED ISSUE #7693: Confusing error message for cp
### Describe the bug

```
❯ cp ~/.ssh/config ~/source/ansible-shared/roles/ssh_config/files/config
Error: nu::shell::file_not_found (link)

  × File not found
   ╭─[entry #65:1:1]
 1 │ cp ~/.ssh/config ~/source/ansible-shared/roles/ssh_config/files/config
   · ─┬
   ·  ╰── copy file "/home/user/.ssh/config" failed: No such file or directory (os error 2)
   ╰────
```
It's the target path that was invalid, but the error message makes it look like the issue was with the source path

### How to reproduce

cp source target with target being a non-existent path

### Expected behavior

The error message should indicate that the target path is invalid

### Screenshots

_No response_

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.72.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.67.0-nightly (b28d30e1e 2022-12-06)     |
| rust_channel       | nightly-x86_64-unknown-linux-gnu                |
| cargo_version      | cargo 1.67.0-nightly (f6e737b1e 2022-12-02)     |
| pkg_version        | 0.72.0                                          |
| build_time         | 2022-12-10 17:23:17 +01:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Mehrbod2002**
Fixes #7693 

On `cp` commands there were two error which pass error message with invalid detail about source and destination files . there error were for Not exist file and Permission denied .

Examples:
  Before :
Copy `source_file_valid` to `destination_invalid_dir` throw this error ;
  `copy file "/source_file_valid" failed: No such file or directory (os error 2) `

 After this PR it will throw this if destination will be invalid :
  `copying to destination "/destination_invalid_dir" failed: No such file or directory (os error 2) `

it was for Permission denied too .

### CODE REVIEW

File: crates/nu-command/src/filesystem/cp.rs [hunk 1]
```diff
@@ -355,8 +355,18 @@ fn copy_file(src: PathBuf, dst: PathBuf, span: Span) -> Value {
             let message = format!("copy file {src:?} failed: {e}");
 
             use std::io::ErrorKind;
+            let dst_info = std::fs::metadata(&dst);
```
Comment (sholderbach) [inline crates/nu-command/src/filesystem/cp.rs:358]: I don't think this does the right thing. This will return `Ok` if and only if the file or directory exists and the path leading there is readable for the user. There are several failure modes that are not covered by this: e.g. permissions and that the target doesn't exist is reasonable for `cp` without flags.

File: crates/nu-command/src/filesystem/cp.rs [hunk 2]
```diff
@@ -355,8 +355,18 @@ fn copy_file(src: PathBuf, dst: PathBuf, span: Span) -> Value {
...
             let shell_error = match e.kind() {
-                ErrorKind::NotFound => ShellError::FileNotFoundCustom(message, span),
+                ErrorKind::NotFound => {
+                    if dst_info.is_ok() {
+                        ShellError::FileNotFoundCustom(message, span)
+                    } else {
+                        ShellError::FileNotFoundCustom(
+                            format!("copy file {dst:?} failed: {e}"),
+                            span,
+                        )
```
Comment (sholderbach) [inline crates/nu-command/src/filesystem/cp.rs:367]: `ErrorKind::NotFound` is not the only possible case where the target matters (e.g. `PermissionDenied`)
Maybe worth lifting the `message` generation instead of once using the variable declared before or using the local format string.

**Review by sholderbach — CHANGES_REQUESTED** [review]
Thanks for trying to tackle this. I don't think this covers all the likely problems with the destination path. (Maybe worth adding a test as well if this is not too much of a hassle with the test setup.)

**Comment by sholderbach** [comment]
Thanks for the quick turnaround! Looks much more granular! Thanks for adding tests. Won't be able to check the details today.

**Comment by Mehrbod2002** [comment]
@sholderbach 
Please consider to review it , if you need any questions ask or otherwise close it. 
My old commits conflict with new pushes .
Thanks

**Comment by kubouch** [comment]
Looks OK to me. It would be great if you could include some "before" and "after" examples to the PR description, it is not bery easy to deduce from the code.

File: crates/nu-command/src/filesystem/cp.rs [hunk 3]
```diff
@@ -352,17 +352,32 @@ fn copy_file(src: PathBuf, dst: PathBuf, span: Span) -> Value {
             Value::String { val: msg, span }
         }
         Err(e) => {
-            let message = format!("copy file {src:?} failed: {e}");
-
+            let message_src = format!("copy file {src:?} failed: {e}");
+            let message_dst = format!("copy file {dst:?} failed: {e}");
```
Comment (sholderbach) [inline crates/nu-command/src/filesystem/cp.rs:356]: We should make clear that we refer to the destination

```suggestion
            let message_src = format!("copying file '{src_display}' failed: {e}", src.display());
            let message_dst = format!("copying to destination '{dst_display}' failed: {e}", dst.display());
```

(Little nitpick: we should probably format the output with quotes and escapes that you can directly paste in nushell. `Debug` will output `"` which support C style escapes and might break with windows paths)

File: crates/nu-command/src/filesystem/cp.rs [hunk 4]
```diff
@@ -352,17 +352,32 @@ fn copy_file(src: PathBuf, dst: PathBuf, span: Span) -> Value {
...
+                ErrorKind::PermissionDenied => match std::fs::metadata(&dst) {
+                    Ok(meta) => {
+                        if meta.permissions().readonly() {
+                            ShellError::PermissionDeniedError(message_dst, span)
+                        } else {
+                            ShellError::PermissionDeniedError(message_src, span)
+                        }
+                    }
+                    Err(_) => ShellError::PermissionDeniedError(message_dst, span),
+                },
```
Comment (sholderbach) [inline crates/nu-command/src/filesystem/cp.rs:375]: Thanks! 
(Not the absolute expert on the different platforms if there are edge cases but looks plausible)

File: crates/nu-command/tests/commands/cp.rs [hunk 5]
```diff
@@ -344,3 +347,42 @@ fn copy_ignores_ansi() {
...
+        let actual = nu!(
+            cwd: sandbox.cwd(),
+            "cp valid.txt ~/invalid_dir/invalid_dir1"
+        );
+        assert!(
+            actual.err.contains("invalid_dir1")
+                && (actual.err.contains("No such file or directory")
+                    || actual
+                        .err
+                        .contains("The system cannot find the path specified"))
```
Comment (sholderbach) [inline crates/nu-command/tests/commands/cp.rs:365]: Mhh does this depend on the exact error message from the OS or is this part of the Rust standard library output? While this could be fine in our CI this may break on the machines of developers that use different versions or localized translations.

File: crates/nu-command/tests/commands/cp.rs [hunk 6]
```diff
@@ -344,3 +347,42 @@ fn copy_ignores_ansi() {
...
+        ]);
+
+        let actual = nu!(
+            cwd: sandbox.cwd(),
+            "cp valid.txt invalid_prem.txt",
+        );
+        assert!(
+            actual.err.contains("invalid_prem.txt")
+                && (actual.err.contains("Access is denied")
+                    || actual.err.contains("Permission denied"))
```
Comment (sholderbach) [inline crates/nu-command/tests/commands/cp.rs:385]: Again, make sure that we try to avoid having tests that might fail based on a developers OS.

**Review by sholderbach — COMMENTED** [review]
Thanks for the constant improvements :)

File: crates/nu-command/tests/commands/cp.rs (hunk 5 above)
Comment (Mehrbod2002) [reply crates/nu-command/tests/commands/cp.rs:365]: could we just have `invalid_dir!` , I think it should pass .
out just check stderr is not empty and stdout is empty , can we ?

Comment (sholderbach) [reply crates/nu-command/tests/commands/cp.rs:365]: I think we should refer to the parts of the message that are defined in this PR (Another reason why the message strings should be slightly different (thanks for the quick land))

**Review by sholderbach — APPROVED** [review]
Thanks!

**Comment by kubouch** [comment]
Thanks! Maybe the message could be reworded slightly. Instead of
```
copy file "/destination_invalid_dir" failed: No such file or directory (os error 2) 
```
it could say
```
copy file to "/destination_invalid_dir" failed: No such file or directory (os error 2) 
```
because the first one makes it look as if you copied the destination directory.

**Comment by Mehrbod2002** [comment]
> copy file to "/destination_invalid_dir" failed: No such file or directory (os error 2) 
> ```
The error messages changed by reviewer , sorry forgot to change. Done 
Thanks
