### PR TITLE
Fix for escaping backslashes in interpolated strings (fixes #6737)

### LINKED ISSUE #6737: String interpolation doesn't seem to work with escaped \ characters immediately before it
### Describe the bug

When a \ appears directly before the string interpolation parentheses in a $ string, the parentheses stop working altogether, EVEN if the \ is escaped with another \\.

### How to reproduce

Get a load of this:
```
C:\Users\Leon\TODO〉"foo" | print $"fee fie foe ($in)"
fee fie foe foo
C:\Users\Leon\TODO〉"foo" | print $"fee fie foe \($in)"
fee fie foe ($in)
C:\Users\Leon\TODO〉"foo" | print $"fee fie foe \\($in)"
fee fie foe \($in)
C:\Users\Leon\TODO〉"foo" | print $"fee fie foe \\\($in)"
fee fie foe \($in)
C:\Users\Leon\TODO〉"foo" | print $"fee fie foe \\\\($in)"
fee fie foe \\($in)
C:\Users\Leon\TODO〉"foo" | print $"fee fie foe \\\\\($in)"
fee fie foe \\($in)
C:\Users\Leon\TODO〉"foo" | print $"fee fie foe \\\\\\($in)"
fee fie foe \\\($in)
```
As you can see, there is *NO* amount of \\'s you can use to make the parentheses work again.

### Expected behavior

It should be possible in these examples to make one that outputs "fee fie foe \foo", but it currently isn't possible without writing something demented like `print $"fee fie foe("\\")($in)"`.

### Screenshots

_No response_

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:58:08 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gavinfoley**
# Description

(PR attempt #&#8203;2.)

When using a double-quoted interpolated string (`$"example"`), both escaped characters (e.g., `\n`, `\t`, `\\`) and interpolated expressions (e.g., `(1 + 2)`) are supported.

You can use these features independently or together.

| Expression | Resulting string |
|-|-|
| `$"\""` | `"` |
| `$"\\"` | `\` |
| `$"(1 + 3)"` | `4` |
| `$"\(1 + 3)"` | `(1 + 3)` |

However, there's a bug when you try to use them in sequence:

| Expression | Expected string | Actual string |
|-|-|-|
| `$"\\(1 + 3)"` | `\4` | `\(1 + 3)` |

The first backslash escapes the second, so the expression should not escaped, but the current implementation escapes both the second backslash and the expression (as described in #6737).  This PR addresses that issue.

# Difference from [previous PR](https://github.com/nushell/nushell/pull/7020)

In my previous PR, I changed (approximately)
```rs
if mode == InterpolationMode::String { ... }
if mode == InterpolationMode::Expression { ... }
```
into
```rs
match mode {
    InterpolationMode::String => { ... }
    InterpolationMode::Expression => { ... }
}
```

This introduced a bug, because `mode` can be set to `Expression` within the `String` `if` block, so the `if` blocks are not mutually exclusive.

I've added a new test, `string::interpolation::parse_nested_expressions`, which seems to cover this bug.

This issue was discovered by @fdncred due to errors in parsing [get-weather.nu](https://github.com/nushell/nu_scripts/blob/main/weather/get-weather.nu), so I've run that locally with these changes and it seems to be working.  @fdncred, if you wouldn't mind double-checking that these scripts are working as expected, I'd appreciate it!

# Major Changes

If you're considering making any major change to nushell, before starting work on it, seek feedback from regular contributors and get approval for the idea from the core team either on [Discord](https://discordapp.com/invite/NtAbbGn) or [GitHub issue](https://github.com/nushell/nushell/issues/new/choose).
Making sure we're all on board with the change saves everybody's time.
Thanks!

# Tests + Formatting

Make sure you've done the following, if applicable:

✅ Add tests that cover your changes (either in the command examples, the crate/tests folder, or in the /tests folder)
  - Try to think about corner cases and various ways how your changes could break. Cover those in the tests

Make sure you've run and fixed any issues with these commands:

✅ `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
✅ `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
✅  `cargo test --workspace --features=extra` to check that all tests pass

# After Submitting

* Help us keep the docs up to date: If your PR affects the user experience of Nushell (adding/removing a command, changing an input/output type, etc.), make sure the changes are reflected in the documentation (https://github.com/nushell/nushell.github.io) after the PR is merged.

### CODE REVIEW

**Comment by fdncred** [comment]
@gavinfoley Thanks so much for re-working and resubmitting this PR!!! I had to change my weather script because nushell no longer supports `for` loops the same way it did before. After I made those changes, that are unrelated to this PR, the script works great!

**Review by fdncred — APPROVED** [review]
Thanks for the extra tests. All this looks good to me!

**Comment by gavinfoley** [comment]
I'm glad! Thank you!

File: crates/nu-parser/tests/test_parser.rs [hunk 1]
```diff
@@ -364,6 +324,208 @@ fn test_nothing_comparisson_neq() {
...
+
+            let (_block, err) = parse(
+                &mut working_set,
+                None,
+                br#"
+                $"(($foo))"
+                "#,
+                true,
+                &[],
+            );
```
Comment (sholderbach) [inline crates/nu-parser/tests/test_parser.rs:522]: Is this our only directly named variable expansion unit test? (Sure that in the general nu tests there might be a tested usage.) Do we want to include a full cell path expression like in the scripts that failed for @fdncred (`$"Hello ($foo.bar)")

File: crates/nu-parser/tests/test_parser.rs [hunk 2]
```diff
@@ -364,6 +324,208 @@ fn test_nothing_comparisson_neq() {
...
+
+            assert!(err.is_none());
```
Comment (sholderbach) [inline crates/nu-parser/tests/test_parser.rs:524]: Is there a test where something should error or are they all just incomplete cases like `$"\\\"` that waits for the closing quote `"`

**Review by sholderbach — APPROVED** [review]
Thank you for the quick turnaround, looks good to me as well. 
I was wondering about the test coverage but that shouldn't stop the show.

**Comment by fdncred** [comment]
@gavinfoley I'm excited to land this. Do you have any input on @sholderbach's comments? Also, we have conflicts now. Could you fix those please?

**Comment by fdncred** [comment]
@gavinfoley we'd still like to move forward with this if you're able.

**Comment by gavinfoley** [comment]
@fdncred Absolutely - I'll try to get this PR updated tomorrow.

**Comment by fdncred** [comment]
Thanks @gavinfoley. We appreciate your help.

File: crates/nu-parser/tests/test_parser.rs (hunk 1 above)
Comment (gavinfoley) [reply crates/nu-parser/tests/test_parser.rs]: I've added an additional test `parse_path_expression` (duplicating `parse_nested_expressions`) for the expression you suggested.

File: crates/nu-parser/tests/test_parser.rs (hunk 2 above)
Comment (gavinfoley) [reply crates/nu-parser/tests/test_parser.rs:583]: Because this PR corrects the interpretation of syntax which is accepted by the parser both before and after this change, I don't think we expect/need to test any new error conditions.
