### PR TITLE
Fix `$in` in range expressions

### LINKED ISSUE #13441: `$in` errors with range in 0.96.0
### Describe the bug

previously this code had no problems 
cc @devyn 

### How to reproduce

```nu
> 101 | 1..($in // 100)
Error: nu::shell::variable_not_found

  × Variable not found
   ╭─[entry #9:2:7]
 1 │ 101
 2 │ | 1..($in // 100)
   ·       ─┬─
   ·        ╰── variable not found
   ╰────
```

### Expected behavior

I expect no to accept `$in` in ranges with no problems

### Screenshots

_No response_

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.96.0                                   |
| major              | 0                                        |
| minor              | 96                                       |
| patch              | 0                                        |
| branch             |                                          |
| commit_hash        |                                          |
| build_os           | macos-aarch64                            |
| build_target       | aarch64-apple-darwin                     |
| rust_version       | rustc 1.78.0 (9b00956e5 2024-04-29)      |
| rust_channel       | stable-aarch64-apple-darwin              |
| cargo_version      | cargo 1.78.0 (54d8815d0 2024-03-26)      |
| build_time         | 2024-07-24 10:52:17 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, system-clipboard, trash |
| installed_plugins  | polars 0.96.0, regex                     |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by devyn**
# Description

Fixes #13441.

I must have forgotten that `Expr::Range` can contain other expressions, so I wasn't searching for `$in` to replace within it. Easy fix.

# User-Facing Changes
Bug fix, ranges like `6 | 3..$in` work as expected now.

# Tests + Formatting
Added regression test.

### CODE REVIEW

File: tests/repl/test_engine.rs [hunk 1]
```diff
@@ -75,6 +75,12 @@ fn in_used_twice_and_also_in_pipeline() -> TestResult {
     )
 }
 
+// #13441
+#[test]
+fn in_used_in_range() -> TestResult {
+    run_test(r#"6 | 3..$in | math sum"#, "18")
```
Comment (WindSoilder) [inline tests/repl/test_engine.rs:81]: I think we can add one more test for `6 | $in..10 | math sum`

Comment (devyn) [reply tests/repl/test_engine.rs:81]: sure, why not

**Review by WindSoilder — APPROVED** [review]
Thanks!  Looks good to me.
I think the order is: `merging this pr -> merging 0.96.1 -> release it`, is that right?

**Comment by devyn** [comment]
I think you need to merge 0.96.1 first

**Comment by WindSoilder** [comment]
Sure!  Let's go

**Comment by devyn** [comment]
Thanks!
