### PR TITLE
glob with ../ prefix now works;

### LINKED ISSUE #10503: `glob ` doesn't match files if pattern starts with `../` or `./`
### Describe the bug

Skips reporting files that it should find.

### How to reproduce

```
> ls ..
╭───┬───────┬──────┬──────┬───────────────╮
│ # │ name  │ type │ size │   modified    │
├───┼───────┼──────┼──────┼───────────────┤
│ 0 │ ../r1 │ dir  │  7 B │ 3 hours ago   │
│ 1 │ ../r2 │ dir  │  3 B │ a day ago     │
│ 2 │ ../r3 │ dir  │ 13 B │ 4 minutes ago │
╰───┴───────┴──────┴──────┴───────────────╯
> glob ../r*
╭────────────╮
│ empty list │
╰────────────╯
```

### Expected behavior

```
> glob ../r*
╭───┬──────────────────────────────╮
│ 0 │ /home/bobhy/src/rust/work/r2 │
│ 1 │ /home/bobhy/src/rust/work/r1 │
│ 2 │ /home/bobhy/src/rust/work/r3 │
╰───┴──────────────────────────────╯
```

### Screenshots

_No response_

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.85.1                                   |
| branch             | dt_fixes                                 |
| commit_hash        | bdcb68e2be8e952556ab16c9a1aed35a98045ba7 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)      |
| rust_channel       | 1.70.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)      |
| build_time         | 2023-09-23 08:27:40 -07:00               |
| build_rust_channel | debug                                    |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bobhy**
Fixes #10503 
Also improves link to metacharacter help;

# Description
`glob` code was using pattern as provided by user.  If that had leading `..\`, `wax::Glob` is documented to treat them as literal chars to be matched.
Fix is to use `wax::Glob.partition()` to split such invariant prefixes off the pattern and tack them onto the working directory computed separately.

Before
```
> ls ..
╭───┬───────┬──────┬──────┬───────────────╮
│ # │ name  │ type │ size │   modified    │
├───┼───────┼──────┼──────┼───────────────┤
│ 0 │ ../r1 │ dir  │  7 B │ 3 hours ago   │
│ 1 │ ../r2 │ dir  │  3 B │ a day ago     │
│ 2 │ ../r3 │ dir  │ 13 B │ 4 minutes ago │
╰───┴───────┴──────┴──────┴───────────────╯
> glob ../r*
╭────────────╮
│ empty list │
╰────────────╯
```
After 
```
> glob ../r*
╭───┬──────────────────────────────╮
│ 0 │ /home/bobhy/src/rust/work/r2 │
│ 1 │ /home/bobhy/src/rust/work/r1 │
│ 2 │ /home/bobhy/src/rust/work/r3 │
╰───┴──────────────────────────────╯
```

# User-Facing Changes
None

# Tests + Formatting
- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :green_circle: `toolkit test`
- :green_circle: `toolkit test stdlib`

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
While I agree with this sentiment, we'll have to do something different because it doesn't work right in Windows due to verbatim paths that canonicalize returns. I believe this is the reason `dunce` is used in there example. Not sure `dunce` is still supported or if we use it, but I think `omnipath` supports such things too.
```
❯ glob **/*.{rs,toml} --depth 2
╭──┬────────────────────────────────────────────────────────────────────────╮
│ 0│\\?\C:\Users\dschroeder\source\repos\forks\nushell\.cargo\config.toml   │
│ 1│\\?\C:\Users\dschroeder\source\repos\forks\nushell\.github\.typos.toml  │
│ 2│\\?\C:\Users\dschroeder\source\repos\forks\nushell\benches\benchmarks.rs│
│ 3│\\?\C:\Users\dschroeder\source\repos\forks\nushell\Cargo.toml           │
│ 4│\\?\C:\Users\dschroeder\source\repos\forks\nushell\Cross.toml           │
│ 5│\\?\C:\Users\dschroeder\source\repos\forks\nushell\rust-toolchain.toml  │
│ 6│\\?\C:\Users\dschroeder\source\repos\forks\nushell\scripts\build.rs     │
│ 7│\\?\C:\Users\dschroeder\source\repos\forks\nushell\src\command.rs       │
│ 8│\\?\C:\Users\dschroeder\source\repos\forks\nushell\src\config_files.rs  │
│ 9│\\?\C:\Users\dschroeder\source\repos\forks\nushell\src\ide.rs           │
│10│\\?\C:\Users\dschroeder\source\repos\forks\nushell\src\logger.rs        │
│11│\\?\C:\Users\dschroeder\source\repos\forks\nushell\src\main.rs          │
│12│\\?\C:\Users\dschroeder\source\repos\forks\nushell\src\run.rs           │
│13│\\?\C:\Users\dschroeder\source\repos\forks\nushell\src\signals.rs       │
│14│\\?\C:\Users\dschroeder\source\repos\forks\nushell\src\terminal.rs      │
│15│\\?\C:\Users\dschroeder\source\repos\forks\nushell\src\tests.rs         │
│16│\\?\C:\Users\dschroeder\source\repos\forks\nushell\src\test_bins.rs     │
│17│\\?\C:\Users\dschroeder\source\repos\forks\nushell\tests\main.rs        │
╰──┴────────────────────────────────────────────────────────────────────────╯
```

File: crates/nu-command/src/filesystem/glob.rs [hunk 1]
```diff
@@ -123,7 +123,7 @@ impl Command for Glob {
     }
 
     fn extra_usage(&self) -> &str {
-        r#"For more glob pattern help, please refer to https://github.com/olson-sean-k/wax"#
+        r#"For more glob pattern help, please refer to https://github.com/olson-sean-k/wax/blob/master/README.md#patterns"#
```
Comment (kubouch) [inline crates/nu-command/src/filesystem/glob.rs:126]: I'd rather keep the short URL in case the author decides to restructure the README.

File: crates/nu-command/src/filesystem/glob.rs [hunk 2]
```diff
@@ -186,6 +185,10 @@ impl Command for Glob {
             }
         };
 
+        let mut path = current_dir(engine_state, stack)?;
+        path.push(prefix);
+        let path = path.canonicalize()?;
```
Comment (kubouch) [inline crates/nu-command/src/filesystem/glob.rs:190]: `current_dir()` should be guaranteed to return an absolute path (if it doesn't it's a bug). Therefore, canonicalize here is redundant, and also canonicalizing should be done via our `nu-path` crate. Using Rust's builtin canonicalize reads system environment, which is not supported in Nushell, we keep our own environment.

File: crates/nu-command/src/filesystem/glob.rs (hunk 1 above)
Comment (bobhy) [reply crates/nu-command/src/filesystem/glob.rs:126]: The old link points to the top of the repo and you have to open readme and read down quite a way to find doc on the pattern and metachars.   
I see  https://docs.rs/wax/latest/wax/ points to `https://github.com/olson-sean-k/wax/blob/master/README.md`, maybe that's a stable enough target?

Comment (kubouch) [reply crates/nu-command/src/filesystem/glob.rs:126]: That could work as well :+1:

**Comment by bobhy** [comment]
Whew!  Ready for review!

**Comment by fdncred** [comment]
wow, that was a hard-fought battle. ⚔️

**Comment by fdncred** [comment]
Looks much better on Windows
```
╭──┬──────────────────────────────────────────────────────────────────────╮
│ 0│C:\Users\username\source\repos\forks.bak\nushell\.cargo\config.toml   │
│ 1│C:\Users\username\source\repos\forks.bak\nushell\.github\.typos.toml  │
│ 2│C:\Users\username\source\repos\forks.bak\nushell\benches\benchmarks.rs│
│ 3│C:\Users\username\source\repos\forks.bak\nushell\Cargo.toml           │
│ 4│C:\Users\username\source\repos\forks.bak\nushell\Cross.toml           │
│ 5│C:\Users\username\source\repos\forks.bak\nushell\rust-toolchain.toml  │
│ 6│C:\Users\username\source\repos\forks.bak\nushell\scripts\build.rs     │
│ 7│C:\Users\username\source\repos\forks.bak\nushell\src\command.rs       │
│ 8│C:\Users\username\source\repos\forks.bak\nushell\src\config_files.rs  │
│ 9│C:\Users\username\source\repos\forks.bak\nushell\src\ide.rs           │
│10│C:\Users\username\source\repos\forks.bak\nushell\src\logger.rs        │
│11│C:\Users\username\source\repos\forks.bak\nushell\src\main.rs          │
│12│C:\Users\username\source\repos\forks.bak\nushell\src\run.rs           │
│13│C:\Users\username\source\repos\forks.bak\nushell\src\signals.rs       │
│14│C:\Users\username\source\repos\forks.bak\nushell\src\terminal.rs      │
│15│C:\Users\username\source\repos\forks.bak\nushell\src\tests.rs         │
│16│C:\Users\username\source\repos\forks.bak\nushell\src\test_bins.rs     │
│17│C:\Users\username\source\repos\forks.bak\nushell\tests\main.rs        │
╰──┴──────────────────────────────────────────────────────────────────────╯
```

**Review by fdncred — APPROVED** [review]
Glad to see you finally got this working. I just removed some comments but I think it's ready too.

File: crates/nu-command/src/filesystem/glob.rs [hunk 3]
```diff
@@ -186,6 +185,21 @@ impl Command for Glob {
             }
         };
 
+        let path = current_dir(engine_state, stack)?;
+        let path = match nu_path::canonicalize_with(prefix, path) {
+            Ok(path) => path,
+            Err(e) if e.to_string().contains("os error 2") => std::path::PathBuf::new(),
```
Comment (fdncred) [inline crates/nu-command/src/filesystem/glob.rs:191]: Remind me, what exactly is `os error 2` and why are we eating it?

File: crates/nu-command/src/filesystem/glob.rs (hunk 1 above)
Comment (kubouch) [reply crates/nu-command/src/filesystem/glob.rs]: @bobhy Could you still use the shorter docs.rs link?

File: crates/nu-command/src/filesystem/glob.rs (hunk 3 above)
Comment (bobhy) [reply crates/nu-command/src/filesystem/glob.rs:191]: Means "file or directory not found".  And it's a fair question! Happens if user specifies a directory prefix before the wildcard where the directory doesn't exist. We set empty path to `Glob::walk()` and it returns an empty list.
I added a comment because I couldn't immediately figure it out even though I wrote this code only a day ago!

**Comment by kubouch** [comment]
Ah yeah, wrong link. You could point at https://crates.io/crates/wax, for example (or maybe https://docs.rs/crate/wax) to show the README immediately. Not a big deal, though, I just thought the link was too long for a help message and the # reference might be prone to change.

**Comment by fdncred** [comment]
My changes were reverted by force pushes. So, I made the changes again to change the link and remove some excess comments. We can land this when it's green again.
