### PR TITLE
do not emit None mid-stream during parse

### LINKED ISSUE #9906: `parse` can truncate streams
### Describe the bug

When running `parse` on a `stream` input, the output will be truncated after the first non-matching record.
In the demo below I use `--regex`, but the issue can be reproduced without it as well.

### How to reproduce

1. `[a b c] | str join "\n" | save -f demo`
2. `open demo | lines | parse -r '([ac])'`

### Expected behavior

I expected nu to not truncate streams on the first non-match :smiley_cat: 

### Screenshots

image

### Configuration

| key                | value                                                                           |
| ------------------ | ------------------------------------------------------------------------------- |
| version            | 0.83.1                                                                          |
| branch             |                                                                                 |
| commit_hash        |                                                                                 |
| build_os           | linux-x86_64                                                                    |
| build_target       | x86_64-unknown-linux-gnu                                                        |
| rust_version       | rustc 1.71.0 (8ede3aae2 2023-07-12)                                             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                                                 |
| cargo_version      | cargo 1.71.0 (cfd3bbd8f 2023-06-08)                                             |
| build_time         | 2023-08-02 12:40:14 +02:00                                                      |
| build_rust_channel | release                                                                         |
| allocator          | mimalloc                                                                        |
| features           | dataframe, default, extra, sqlite, static-link-openssl, trash, wasi, which, zip |
| installed_plugins  |                                                                                 |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by panicbit**
# Description

Currently `parse` acts like a `.filter` over an iterator, except that it emits `None` for elements that can't be parsed. This causes consumers of the adapted iterator to stop iterating too early. The correct behaviour is to keep pulling the inner iterator until either the end of it is reached or an element can be parsed.

- this PR should close #9906 

# User-Facing Changes

List streams won't be truncated anymore after the first parse failure.

# Tests + Formatting

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect -A clippy::result_large_err` to check that you're using the standard code style
- [x] `cargo test --workspace` to check that all tests pass
  - 11 tests fail, but the same 11 tests fail on main as well
 - [x] `cargo run -- -c "use std testing; testing run-tests --path crates/nu-std"` to run the tests for the standard library

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
nice work @panicbit! I'll have to test this out tomorrow.

**Review by amtoine — CHANGES_REQUESTED** [review]
it looks like it's solving some issues with `parse`, nice job @panicbit :pray: 

i see
```nushell
let matches = [a b c] | str join "\n" | lines | parse -r '([ac])'; print $matches
```
gives a wrong
```nushell
╭───┬──────────╮
│ # │ capture0 │
├───┼──────────┤
│ 0 │ a        │
╰───┴──────────╯
```
on latest `main` but looks fixed on the tip of this branch :partying_face: 
```nushell
╭───┬──────────╮
│ # │ capture0 │
├───┼──────────┤
│ 0 │ a        │
│ 1 │ c        │
╰───┴──────────╯
```

could you add a test for this to make sure it does not happen again? :yum:

**Comment by amtoine** [comment]
i also have this more complex command with a bunch of lines, regex-like characters, the whole set of complicated stuff you know :smirk:
```nushell
tmux show -g | lines | parse "status-format[1] {format}"
```

on latest `main`, it's not able to parse it and returns an empty list...
this is the same issue i think!


on the tip of this branch, it gives the expected result :partying_face:
```nushell
╭───┬─────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ # │                                             format                                                      │
├───┼─────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 0 │ "#[align=centre]#{P:#{?pane_active,#[reverse],}#{pane_index}[#{pane_width}x#{pane_height}]#[default] }" │
╰───┴─────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by amtoine** [comment]
and wow, i can not reproduce #8352 either on the tip of this branch, amazing :star_struck:

**Comment by panicbit** [comment]
I have added a test, however, I noticed odd behaviour with the tests that I do not quite understand.
`cargo test --workspace` does not run the test I added, only `cargo test --workspace parse_does_not_truncate_list_streams` does.

File: crates/nu-command/tests/commands/parse.rs [hunk 1]
```diff
@@ -197,4 +197,21 @@ mod regex {
...
+
+    #[test]
+    fn parse_does_not_truncate_list_streams() {
+        Playground::setup("parse_test_streaming_1", |dirs, _sandbox| {
+            let actual = nu!(
+                cwd: dirs.test(), pipeline(
+                r#"
+                    [a b c]
+                    | each {|x| $x}
+                    | parse --regex "[ac]"
```
Comment (fdncred) [inline crates/nu-command/tests/commands/parse.rs:209]: Shouldn't this be `| parse --regex "([ac])"`? I think it works either way but `[ac]` produces no usable output since there isn't a capture group.

Comment (panicbit) [reply crates/nu-command/tests/commands/parse.rs:209]: Yeah, it doesn't really matter for the test, but I'll add the parens since it makes the test slighty more understandable when looking at the output of that parse manually.

**Comment by fdncred** [comment]
This looks to me like it works as expected. Nice work!

File: crates/nu-command/tests/commands/parse.rs [hunk 2]
```diff
@@ -197,4 +197,21 @@ mod regex {
...
+                    | length
+                "#
+            ));
+
+            assert_eq!(actual.out, "2");
+        })
+    }
```
Comment (amtoine) [inline crates/nu-command/tests/commands/parse.rs]: maybe it would need to be formatted with `cargo fmt --all` but i suggest simplifying the test in the following way :yum: 
```suggestion
    #[test]
    fn parse_does_not_truncate_list_streams() {
        let actual = nu!(pipeline(
            r#"
                [a b c]
                | each {|x| $x}
                | parse --regex "[ac]"
                | length
            "#
        ));

        assert_eq!(actual.out, "2");
    }
```

**Review by amtoine — CHANGES_REQUESTED** [review]

File: crates/nu-command/tests/commands/parse.rs (hunk 2 above)
Comment (amtoine) [reply crates/nu-command/tests/commands/parse.rs]: the other tests in that file might be incorrect as well...
this is part of https://github.com/nushell/nushell/issues/8670 :thinking:

Comment (panicbit) [reply crates/nu-command/tests/commands/parse.rs]: Good catch!

Comment (amtoine) [reply crates/nu-command/tests/commands/parse.rs]: thanks for the change :pray:

**Comment by fdncred** [comment]
Thanks!

**Comment by amtoine** [comment]
thanks so much @panicbit for fixing this :pray: 
`parse` feels usable now, loving this :blush:
