### PR TITLE
Fix quoting regression in argument handling for evaluate_file; add tests

### LINKED ISSUE #18025: Bug: Arguments passed to scripts come in an escaped form
### Bug report form

- [x] I have done a basic search of the issue tracker to find any existing issues that are similar.
- [x] I have checked that my version is at least the latest stable release available via my installation method.

### Describe the bug

Arguments passed to scripts come in an escaped form now.

After updating to *Nushell* v0.112.1, a lot of my scripts got broken by this.

### How to reproduce

Create `test.nu`:

```nu
#!/usr/bin/nu

def --wrapped main [...args: string] {
  print $args
  print ($args.1 | str substring 0..0)
}
```

Run `test.nu`:

```
$ nu --no-config-file test.nu arg1 "arg 2"
╭───┬─────────╮
│ 0 │ arg1    │
│ 1 │ "arg 2" │
╰───┴─────────╯
"
```

### Expected behavior

The argument 2 should be passed in as `arg 2` not `"arg 2"`. The second print shows that indeed, the first character is a quotation mark.

### Configuration

```
$ version | transpose key value | to md --pretty
| key                  | value                                                                                                                              |
| -------------------- | ---------------------------------------------------------------------------------------------------------------------------------- |
| version              | 0.112.1                                                                                                                            |
| major                | 0                                                                                                                                  |
| minor                | 112                                                                                                                                |
| patch                | 1                                                                                                                                  |
| branch               | makepkg                                                                                                                            |
| commit_hash          | c5cf8ec0023828fddd355dafba70764079d5d3b8                                                                                           |
| build_os             | linux-x86_64                                                                                                                       |
| build_target         | x86_64-unknown-linux-gnu                                                                                                           |
| rust_version         | rustc 1.94.1 (e408947bf 2026-03-25) (Arch Linux rust 1:1.94.1-1)                                                                   |
| cargo_version        | cargo 1.94.1 (29ea6fb6a 2026-03-24) (Arch Linux rust 1:1.94.1-1)                                                                   |
| build_time           | 2026-04-12 08:42:11 +00:00                                                                                                         |
| build_rust_channel   | release                                                                                                                            |
| allocator            | standard                                                                                                                           |
| features             | default, mcp, network, plugin, rustls-tls, sqlite, trash-support                                                                   |
| installed_plugins    |                                                                                                                                    |
| experimental_options | example=false, reorder-cell-paths=true, pipefail=true, enforce-runtime-annotations=false, native-clip=false, cell-path-types=false |
```

### PR DESCRIPTION
**Pull request by fdncred**
Fix the quoting regression reported in #18025 and add a couple tests.
closes #18025
## Release notes summary - What our users need to know
After this PR
```nushell
❯ ./test2.nu a b "c\nd"
a
b
c
d
❯ ./test.nu arg1 "arg 2"
╭───┬───────╮
│ 0 │ arg1  │
│ 1 │ arg 2 │
╰───┴───────╯
a
❯ ./target/debug/nu --no-config-file test2.nu a b "c\nd"
a
b
c
d
❯ ./target/debug/nu --no-config-file test.nu arg1 "arg 2"
╭───┬───────╮
│ 0 │ arg1  │
│ 1 │ arg 2 │
╰───┴───────╯
a
```
with these scripts
```nushell
❯ open test.nu
#!/Users/fdncred/src/nushell/target/debug/nu

def --wrapped main [...args: string] {
  print $args
  print ($args.1 | str substring 0..0)
}
❯ open test2.nu
#!/Users/fdncred/src/nushell/target/debug/nu

def main [...args: string] {
  print ...($args)
}
```

## Tasks after submitting

- [ ] Update the [documentation](https://github.com/nushell/nushell.github.io)

### CODE REVIEW

**Comment by fdncred** [comment]
@Juhan280 LOL. I just noticed that this is nearly identical to your fix https://github.com/nushell/nushell/pull/18027. Feel free to push your other tests onto mine here if you want.

**Comment by Juhan280** [comment]
> @Juhan280 LOL. I just noticed that this is nearly identical to your fix #18027. Feel free to push your other tests onto mine here if you want.

I don't know how to push into your branch. But anyways, my pr also escapes additional characters, and adding the test here will make yours fails as you don't have those characters. You can go ahead with your pr and I will convert mine to just add additional characters for quoting.

File: crates/nu-cli/src/eval_file.rs [hunk 1]
```diff
@@ -226,18 +221,49 @@ mod tests {
...
+  }
+}"#,
             )]);
 
-            // If newline escaping regresses, command parsing fails before returning "ok".
             test()
                 .cwd(dirs.test())
                 .add_nu_to_path()
-                .run("nu test.nu a b \"c\\nd\"; 'ok'")
+                .run(r#"nu test.nu arg1 "arg 2"; 'ok'"#)
```
Comment (Juhan280) [inline crates/nu-cli/src/eval_file.rs:266]: I just realized, you hard coded the "ok" return value. So the test will always pass even if we get malformed input (thats what happened last time)
