### PR TITLE
Fix commandline --cursor to return int

### LINKED ISSUE #11825: `commandline --cursor` returns string
### Describe the bug

`commandline --cursor` returns the current cursor position, but its type is a string.

### How to reproduce

```nu
> commandline --cursor | describe
string
```

### Expected behavior

```nu
> commandline --cursor | describe
int
```

### Screenshots

_No response_

### Configuration

| key                | value                                                                     |
| ------------------ | ------------------------------------------------------------------------- |
| version            | 0.90.1                                                                    |
| branch             |                                                                           |
| commit_hash        | c2992d5d8b8541b64e9fc1440ed2917fc9b757f7                                  |
| build_os           | linux-x86_64                                                              |
| build_target       | x86_64-unknown-linux-musl                                                 |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)                                       |
| rust_channel       | 1.73.0-x86_64-unknown-linux-gnu                                           |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)                                       |
| build_time         | 2024-02-07 02:23:24 +00:00                                                |
| build_rust_channel | release                                                                   |
| allocator          | mimalloc                                                                  |
| features           | dataframe, default, extra, sqlite, static-link-openssl, trash, which, zip |
| installed_plugins  | query, query json, query web, query xml                                   |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kit494way**
# Description

Fix #11825 

# User-Facing Changes

`commandline --cursor` returns int.

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Review by fdncred — APPROVED** [review]
Thanks! This looks good to me.

File: crates/nu-cli/src/commands/commandline.rs [hunk 1]
```diff
@@ -19,6 +19,7 @@ impl Command for Commandline {
             .input_output_types(vec![
                 (Type::Nothing, Type::Nothing),
                 (Type::String, Type::String),
+                (Type::String, Type::Int),
```
Comment (sholderbach) [inline crates/nu-cli/src/commands/commandline.rs:22]: Do we now allow divergence in output type? Otherwise this may still confuse the typecheck

Comment (fdncred) [reply crates/nu-cli/src/commands/commandline.rs:22]: It seems to work but I guess we could have a separate subcommand like `commandline cursor`.

Comment (kit494way) [reply crates/nu-cli/src/commands/commandline.rs:22]: I noticed that typecheck does not work well as @sholderbach pointed out.
```nu
❯ def foo []: string -> int { commandline -c }
Error: nu::parser::output_type_mismatch

  × Command output doesn't match int.
   ╭─[entry #2:1:29]
 1 │ def foo []: string -> int { commandline -c }
   ·                             ───────┬──────
   ·                                    ╰── command doesn't output int
   ╰────
```

It might be better to have a separate subcommand as @fdncred mentioned.
Should we revert this?

Comment (fdncred) [reply crates/nu-cli/src/commands/commandline.rs:22]: We could revert it, or just add a new sub command and do the revert in that PR.

Comment (kit494way) [reply crates/nu-cli/src/commands/commandline.rs:22]: I will create a PR to add a subcommand and I revert this in that PR.

Comment (fdncred) [reply crates/nu-cli/src/commands/commandline.rs:22]: ok, sounds good. thanks.
