### PR TITLE
fix: highlighting for aliased external calls

### LINKED ISSUE #16944: Different alias highlighting in latest nightly
### Bug report form

- [x] I have done a basic search of the issue tracker to find any existing issues that are similar.
- [ ] I have checked that my version is at least the latest stable release available via my installation method.

### Describe the bug

After updating to the latest nightly, an alias in the repl will appear white while in previous versions it was cyan with my theme.

After bisecting #16876 seems to be the culprit @blindFS https://discord.com/channels/601130461678272522/614593951969574961/1433101828978905130

### How to reproduce

.

### Expected behavior

I expected the highlighting to be the same unless there has been a change to some theming config

### Configuration

| key                  | value                                                                                     |
| -------------------- | ----------------------------------------------------------------------------------------- |
| version              | 0.108.1-nightly.11                                                                        |
| major                | 0                                                                                         |
| minor                | 108                                                                                       |
| patch                | 1                                                                                         |
| pre                  | nightly.11                                                                                |
| branch               | main                                                                                      |
| commit_hash          | d9cbd0905829b9d8db754d419b056a243e761199                                                  |
| build_os             | windows-x86_64                                                                            |
| build_target         | x86_64-pc-windows-msvc                                                                    |
| rust_version         | rustc 1.90.0 (1159e78c4 2025-09-14)                                                       |
| rust_channel         | stable-x86_64-pc-windows-msvc                                                             |
| cargo_version        | cargo 1.90.0 (840b83a10 2025-07-30)                                                       |
| build_time           | 2025-10-29 14:57:58 +01:00                                                                |
| build_rust_channel   | release                                                                                   |
| allocator            | standard                                                                                  |
| features             | default, network, plugin, rustls-tls, sqlite, system-clipboard, trash-support             |
| installed_plugins    | clipboard 0.108.0, file 0.19.1, file_dialog 0.18.0, gstat 0.108.0, query 0.108.0          |
| experimental_options | example=false, reorder-cell-paths=true, pipefail=false, enforce-runtime-annotations=false |

### PR DESCRIPTION
**Pull request by blindFS**
Fixes #16944 

## Release notes summary - What our users need to know

None

## Tasks after submitting

### CODE REVIEW

File: src/ide.rs [hunk 1]
```diff
@@ -403,13 +403,13 @@ pub fn hover(engine_state: &mut EngineState, file_path: &str, location: &Value)
...
-            FlatShape::External(_) => println!(
+            FlatShape::External(alias_span) => println!(
                 "{}",
                 json!({
                     "hover": "external",
                     "span": {
-                        "start": span.start - offset,
-                        "end": span.end - offset
+                        "start": alias_span.start - offset,
+                        "end": alias_span.end - offset
```
Comment (blindFS) [inline src/ide.rs:412]: No idea of how to test this part.

File: crates/nu-cli/src/syntax_highlight.rs [hunk 2]
```diff
@@ -98,101 +59,98 @@ pub(crate) fn highlight_syntax(
         global_cursor_offset,
     );
 
-    for shape in &shapes {
-        if shape.0.end <= last_seen_span
-            || last_seen_span < global_span_offset
-            || shape.0.start < global_span_offset
+    for (raw_span, flat_shape) in &shapes {
```
Comment (WindSoilder) [inline crates/nu-cli/src/syntax_highlight.rs:62]: Oh, I like this change!

**Review by WindSoilder — APPROVED** [review]
Thanks!  LGTM
