### PR TITLE
Change type of parameter default values to `Option<Value>`

### LINKED ISSUE #8939: Default parameters should be `Values`, not `Expressions`
### Describe the bug

The type of `default_value` in `PositionalArg` is an [optional expression](https://github.com/nushell/nushell/blob/91c01bf6b3bc58fc1510ba0caa3da414b76fac36/crates/nu-protocol/src/signature.rs#L38), but this is overly flexible. It would make more sense for it to be a constant value.

### How to reproduce

N/A

### Expected behavior

N/A

### Screenshots

_No response_

### Configuration

N/A

### Additional context

This was discovered by my primary investigation for #8928, and should be tackled first.

### PR DESCRIPTION
**Pull request by MariaSolOs**
# Description

Fixes #8939.

# User-Facing Changes

- Parameter default values will now be parsed as constants.
- If the default value is not a constant, a parser error is displayed.

# Tests + Formatting

The [only affected test](https://github.com/nushell/nushell/blob/d42c2b2dbc941d63c5a05404a0c22c4a7cd9f965/src/tests/test_engine.rs#L325-L328) has been updated to reflect the new behavior.

### CODE REVIEW

File: crates/nu-protocol/src/parse_error.rs [hunk 1]
```diff
@@ -349,6 +349,10 @@ pub enum ParseError {
         #[label = "parameter {0} needs to be '{1}' instead of '{2}'"] Span,
     ),
 
+    #[error("Default values should be constant expressions.")]
+    #[diagnostic(code(nu::parser::non_constant_default_value))]
+    NonConstantDefaultValue(#[label = "expected a constant value"] Span),
```
Comment (WindSoilder) [inline crates/nu-protocol/src/parse_error.rs:354]: I'd prefer not intorducing a new variant to `ParseError` because it's really large..

File: crates/nu-parser/src/parser.rs [hunk 2]
```diff
@@ -3646,8 +3646,19 @@ pub fn parse_signature_helper(working_set: &mut StateWorkingSet, span: Span) ->
                                                 }
                                             }
                                         }
+
+                                        *default_value = if let Ok(constant) =
+                                            eval_constant(working_set, &expression)
+                                        {
+                                            Some(constant)
+                                        } else {
+                                            working_set.error(ParseError::NonConstantDefaultValue(
```
Comment (WindSoilder) [inline crates/nu-parser/src/parser.rs:3655]: What about using error directly from `eval_constant`?  So let it be:
```rust
*default_value = match eval_constant(working_set, &expression) {
    Ok(constant) => Some(constant),
    Err(e) => { working_set.error(e); None }
}
```

**Review by WindSoilder — COMMENTED** [review]
Hi, thanks for your pr, generally it looks fine to me, and leave some comments about error handling after `eval_constant`.

File: crates/nu-protocol/src/parse_error.rs (hunk 1 above)
Comment (jntrnr) [reply crates/nu-protocol/src/parse_error.rs:354]: @WindSoilder - I think for this particular case it's okay.

We can refactor how constants are handled in the future, and then we can try to simplify how constants error in a future PR.

File: crates/nu-parser/src/parser.rs (hunk 2 above)
Comment (WindSoilder) [reply crates/nu-parser/src/parser.rs:3655]: So no need to change according to discussion:
https://github.com/nushell/nushell/pull/8940#discussion_r1172379102

**Comment by MariaSolOs** [comment]
> Hi, thanks for your pr, generally it looks fine to me, leave some comments about error handling after `eval_constant`.

Thanks for the review! It seems like we've decided to keep the new parser error though.

File: crates/nu-protocol/src/parse_error.rs (hunk 1 above)
Comment (MariaSolOs) [reply crates/nu-protocol/src/parse_error.rs:354]: I agree. I considered using one of the existing errors instead, but I think that none of them is appropriate for this use case and unhelpful error messages are tragic.

**Review by amtoine — COMMENTED** [review]
:question: this is a breaking change, right? :thinking: 

at least it will break the following command in my `nu_scripts` :yum: 
https://github.com/goatfiles/nu_scripts/blob/nightly/scripts/repo.nu#L78-L80

**Comment by MariaSolOs** [comment]
> ❓ this is a breaking change, right? 🤔
> 
> at least it will break the following command in my `nu_scripts` 😋 https://github.com/goatfiles/nu_scripts/blob/nightly/scripts/repo.nu#L78-L80

It is, sadly. I'm not sure of how such changes should be handled...

That being said, I'm wondering if it would be acceptable for a default value to continue being an expression but require that it evaluates to a constant. We can then store the evaluated `Value` in `PositionalArg`. Thoughts @jntrnr?

**Comment by amtoine** [comment]
@MariaSolOs 

oooook, just trying to figure out if that PR should be tagged with `breaking-change` :wink: 


and i think it is cool to be able to default to some expression, e.g. the `git` user of the system in the case of my `repo pull` (yeah i like that script of mine :laughing:)

**Comment by MariaSolOs** [comment]
@amtoine I spoke with @jntrnr offline in the Discord channel and technically `eval_constant` should be able to parse expressions that evaluate to a constant (which is exactly the kind of default values that we want to accept) but it seems like it isn't able to do that just now. So it sounds like this implementation is what we want, it's just that the tooling it uses will need some extra work in the future.

That being said, this should work for now...?

**Review by amtoine — APPROVED** [review]
> **Warning**
> not a parser expert :eyes: 

the feature seems sensible, the test at the bottom of the changes looks great and the changes themselves look good to me :ok_hand: 

thanks @MariaSolOs :relieved: 

> **Note**
> i did not want to hold back this PR :scream: 
> 
> and i have a simple fix for the breaking change, as said in discord
> ```nushell
> def foo [
>     x?: string
> ] {
>     let x = ($x | default (
>         git config --get user.name | str trim
>     ))
> 
>     print $x
> }
> ```
> which gives
> ```nushell
> >_ foo
> amtoine
> >_ foo MariaSolOs
> MariaSolOs
> ```

**Comment by MariaSolOs** [comment]
@amtoine thank you for the review!

> i did not want to hold back this PR 😱

No worries, I know that you didn't 😉. You brought up really good points.

**Comment by rgwood** [comment]
Next release is April 25; let's merge it after the release so this gets enough testing.

Thanks for the contribution @MariaSolOs!

**Comment by MariaSolOs** [comment]
@rgwood Sounds good! And always happy to help :)

**Comment by fdncred** [comment]
Thanks @MariaSolOs. We appreciate your help!

**Comment by bobhy** [comment]
Sorry, I can't find it.  Where in the signature should help look to find the default value?

**Comment by MariaSolOs** [comment]
> Sorry, I can't find it.  Where in the signature should help look to find the default value?

Each positional parameter has a default value.

**Comment by bobhy** [comment]
@MariaSolOs Follow up question!
named flags can have defaults, too.  But the type for these was left `Option<Expression>`.  I was wondering why it should be different...

**Comment by MariaSolOs** [comment]
@bobhy That's a great question. I think they should be values too, and I don't mind preparing a follow-up PR for that. @fdncred @jntrnr what do you think?

**Comment by fdncred** [comment]
I defer to @jntrnr since I don't really understand the details under-the-hood enough to have an opinion. My questions would be how it affects the user experience if we changed it.

**Comment by bobhy** [comment]
@MariaSolOs Do you think you'll get to changing Expression -> Type for named flags soonish?  If not, I could take a crack at it.  #9804 is working for positionals, but cannot handle an Expression.

**Comment by MariaSolOs** [comment]
@bobhy I was waiting to get some input from @jntrnr before doing so. Let me bring it up on the Discord.

**Comment by MariaSolOs** [comment]
> @bobhy I was waiting to get some input from @jntrnr before doing so. Let me bring it up on the Discord.

Okay it seems like I got a thumbs up for this, will prepare the PR.
