### PR TITLE
Avoid panicking if history can't be saved.

### LINKED ISSUE #461: After entering a file, Ctrl+D panics
Steps to reproduce:

1. Enter a file
2. Ctrl+D
3. Panic and nu shell exits

I get the following error on MacOS 

```
CTRL-D
Error: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
```

What I expected:
1. No panic obviously but,
2. Even if the subshell panics, I'd expect to be dumped back to the last shell, not nu exiting entirely.

### PR DESCRIPTION
**Pull request by andrasio**
Fixes #461.

### CODE REVIEW

File: src/cli.rs [hunk 1]
```diff
@@ -297,7 +297,7 @@ pub async fn cli() -> Result<(), Box<dyn Error>> {
         }
         ctrlcbreak = false;
     }
-    rl.save_history("history.txt")?;
+    let _ = rl.save_history("history.txt");
```
Comment (Porges) [inline src/cli.rs]: It'd be good to have a comment indicating why it's being ignored 👍
