### PR TITLE
let `find` take linebreaks into account in `Value::String`

### LINKED ISSUE #7774: Strange behavior for `open` after been assigned to a variable
### Describe the bug

Strange behavior for `open` after been assigned to a variable, line separators seemed to be removed. I'm not sure it's a bug or a feature.

### How to reproduce

1. Create a file named `resolution.txt` with the following content:
```
width:  1920px
height: 1080px

```
2. Run `open resolution.txt | find width` you will get:
```
╭───┬────────────────╮
│ 0 │ width:  1920px │
╰───┴────────────────╯
```
3. However, if you run `let res = open resolution.txt; $res | find width` you will get:
```
width:  1920px
height: 1080px

```
Looks like the line separators have been removed, as `let res = open resolution.txt; $res | lines | find width` will work as expected

### Expected behavior

`open resolution.txt | find width` and `let res = open resolution.txt; $res | find width` should have the same result

### Screenshots

_No response_

### Configuration

| key                | value                                               |
| ------------------ | --------------------------------------------------- |
| version            | 0.74.1                                              |
| branch             | main                                                |
| commit_hash        | 0353eb4a120f6708a6e00c1b2060d978849963db            |
| build_os           | macos-x86_64                                        |
| build_target       | x86_64-apple-darwin                                 |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)                 |
| rust_channel       | stable-x86_64-apple-darwin                          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)                 |
| pkg_version        | 0.74.1                                              |
| build_time         | 2023-01-16 09:52:28 +08:00                          |
| build_rust_channel | release                                             |
| features           | database, dataframe, default, trash, which, zip     |
| installed_plugins  | gstat, inc, query, query json, query web, query xml |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by merelymyself**
# Description

Fixes #7774. The functionality should be the same as feeding all `PipelineDate::Value(Value::String(_,_),_)` into `lines` before putting it into `find`.

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

File: crates/nu-command/src/filters/find.rs [hunk 1]
```diff
@@ -320,6 +320,29 @@ fn find_with_rest_and_highlight(
     };
     let ls_colors = get_ls_colors(ls_colors_env_str);
 
+    let input = if let PipelineData::Value(Value::String { ref val, span }, _) = input {
+        if val.contains('\n') {
+            Value::List {
+                vals: {
+                    let split_char = if val.contains("\r\n") { "\r\n" } else { "\n" };
+                    val.split(split_char)
```
Comment (sholderbach) [inline crates/nu-command/src/filters/find.rs:328]: I think this is better expressed by just using `val.lines()` as this would tolerate mixed line endings as well and is more terse and explicit.

(I know we use this pattern in a few places like the handling of the external stream below but I am not sure if we gain anything major from it)

File: crates/nu-command/src/filters/find.rs [hunk 2]
```diff
@@ -320,6 +320,29 @@ fn find_with_rest_and_highlight(
     };
     let ls_colors = get_ls_colors(ls_colors_env_str);
 
+    let input = if let PipelineData::Value(Value::String { ref val, span }, _) = input {
+        if val.contains('\n') {
```
Comment (sholderbach) [inline crates/nu-command/src/filters/find.rs:324]: To be perfectly honest I am not too fond of having an "effectively mutating" `if let` for the special case before the main match. On the plus side it fights the rightward drift (i.e. more and more nesting levels) but on the downside It splits the logic apart a bit. 
Might be worth moving the handling of lines in a small well named function that is invoked when encountering a `PipelineData::Value` in the main match to perform this mapping.

But not the end of the world if you don't have time for a refactoring.

File: crates/nu-command/tests/commands/find.rs [hunk 3]
```diff
@@ -109,3 +109,15 @@ fn find_with_filepath_search_with_multiple_patterns() {
         assert_eq!(actual.out, r#"["amigos.txt","arepas.clu"]"#);
     })
 }
+
+#[test]
+fn find_takes_into_account_linebreaks_in_string() {
+    let actual = nu!(
+    cwd: ".", pipeline(
+    r#"
+        "atest\nanothertest" | find a | length
```
Comment (sholderbach) [inline crates/nu-command/tests/commands/find.rs:118]: Be mean in your tests ;)

```suggestion
        "atest\nanothertest\nnohit\n" | find a | length
```

**Review by sholderbach — COMMENTED** [review]
Thanks for the fix, this sounds like a bigger miss.
I think the behavior after your fix is what we want.
Just some small comments to maybe avoid similar problems in the future.

File: crates/nu-command/src/filters/find.rs [hunk 4]
```diff
@@ -147,6 +147,8 @@ impl Command for Find {
     ) -> Result<PipelineData, ShellError> {
         let regex = call.get_flag::<String>(engine_state, stack, "regex")?;
 
+        let input = split_string_if_multiline(input);
```
Comment (sholderbach) [inline crates/nu-command/src/filters/find.rs:150]: Thanks for the quick turnaround! This placement here could interfere with the `--multiline --regex ...` mode, I think.

**Comment by sholderbach** [comment]
Thanks for dealing with all that! Your changes look good to me! The whole find command as it is currently stands still looks messy with all its matches and conversions  but that is not your responsibility. Let's land this fix!
