### PR TITLE
Avoid duplicating post headers

### LINKED ISSUE #5194: `post` is duplicating the `Content-Type` header
### Describe the bug

Using the `post` command to debug a web app I'm working on, I noticed that it is duplicating the `content-type` header.

### How to reproduce

Run an http server that prints out the full request (including unprocessed headers) and then from nu execute `post -t application/json 'http://localhost:8000/' { foo: bar }`.

I was able to reproduce using
```
npm install -g http-echo-server
PORT=8000 http-echo-server

[server] event: listening (port: 8000)
[server] event: connection (socket#1)
[socket#1] event: resume
[socket#1] event: data
--> POST / HTTP/1.1
--> content-type: application/json
--> content-type: application/json
--> content-length: 13
--> accept: */*
--> user-agent: nushell
--> host: localhost:8000
--> 
--> {"foo":"bar"}
[socket#1] event: prefinish
[socket#1] event: finish
[socket#1] event: readable
[socket#1] event: end
[socket#1] event: close
```

Note the duplicate `content-type: application/json`.

### Expected behavior

The `content-type` header should not be duplicated.

### Screenshots

_No response_

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.60.0                                   |
| short_commit       | 74af31a4                                 |
| commit_hash        | 74af31a42ff4feb8d5d9897c0d99c7434678a315 |
| commit_date        | 2022-03-22 19:07:11 +00:00               |
| build_os           | macos-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.60.0                                   |
| build_time         | 2022-03-22 19:23:50 +00:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dantswain**
This should fix #5194

# Description

It appears that reqwest handles not duplicating the content-type header when calling `request.json`, so setting the header before calling it should fix the problem.  I've tested it locally to ensure that the header isn't being duplicated.

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --all --all-features -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo build; cargo test --all --all-features` to check that all the tests pass

### CODE REVIEW

File: crates/nu-command/src/network/post.rs [hunk 1]
```diff
@@ -205,6 +205,13 @@ fn helper(
     };
 
     let mut request = http_client(args.insecure.is_some()).post(location);
+
+    // set the content-type header before using e.g., request.json bc
+    //  that will vaoid duplicating the header value
```
Comment (kubouch) [inline crates/nu-command/src/network/post.rs:210]: a small typo

Comment (fdncred) [reply crates/nu-command/src/network/post.rs]: fixed

**Comment by fdncred** [comment]
thanks
