### PR TITLE
Move path handling to nu-path

### LINKED ISSUE #3616: Path containing tilde and backward slash doesn't work on windows (0.32)
**Describe the bug**
As of 0.32, nushell fails to expand paths starting with ~ and containing \

**To Reproduce**
1. `echo "x" | save ~/tmp.txt`
2. `ls ~\tmp.txt`

**Expected behavior**
`ls ~/tmp.txt` outputs:
```
───┬───────────────────────────┬──────┬──────┬────────────
 # │           name            │ type │ size │  modified
───┼───────────────────────────┼──────┼──────┼────────────
 0 │ C:\Users\njonsson\tmp.txt │ File │  1 B │ 7 secs ago
───┴───────────────────────────┴──────┴──────┴────────────
```
but `ls ~\tmp.txt` fails with
```
error: No matches found
    ┌─ shell:137:4
    │
137 │ ls ~\tmp.txt
    │    ^^^^^^^^^ no matches found

```

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
> version | pivot
───┬────────────────────┬────────────────────────────────────────────────────────────────
 # │      Column0       │                            Column1
───┼────────────────────┼────────────────────────────────────────────────────────────────
 0 │ version            │ 0.32.0
 1 │ build_os           │ windows-x86_64
 2 │ rust_version       │ rustc 1.54.0-nightly (5c0292654 2021-05-11)
 3 │ rust_channel       │ nightly-x86_64-pc-windows-msvc (default)
 4 │ cargo_version      │ cargo 1.54.0-nightly (e51522ab3 2021-05-07)
 5 │ pkg_version        │ 0.32.0
 6 │ build_time         │ 2021-06-02 16:17:54
 7 │ build_rust_channel │ release
 8 │ features           │ ctrlc, default, directories, dirs, rustyline, term, which, zip
───┴────────────────────┴────────────────────────────────────────────────────────────────
```
This happens for non-nushell binaries as well:
```
vim ~/tmp.txt # works
vim ~\tmp.txt # fails
```

### PR DESCRIPTION
**Pull request by NiklasJonsson**
fixes #3616

Some places needed to do path expansion on strings others on actual paths. It made sense to me to do the logic on paths, switch to that where possible, and have the rest work on the *_string versions for expansion which in turn call into the path-based ones. I also wanted to keep Cow semantics (maybe premature optimization :)) where possible but this together with str/path conversions made the code a bit convoluted, see e.g. the mapping functions for `Cow<'a, str>` & `Cow<'a, Path>`. Feel free to suggest simplifications.

### CODE REVIEW

File: crates/nu-path/src/lib.rs [hunk 1]
```diff
@@ -0,0 +1,532 @@
...
+        string.push_str(EXPAND_STR);
+    }
+
+    string.pop(); // remove last '/'
+}
+
+// Expands any occurence of more than two dots into a sequence of ../ (or ..\ on windows), e.g.
+// ... into ../..
+// .... into ../../../
+fn expand_ndots_string<'a>(path: Cow<'a, str>) -> Cow<'a, str> {
```
Comment (NiklasJonsson) [inline crates/nu-path/src/lib.rs:73]: I tried rewriting this to be Cow<Path> based but it was fairly tricky, It then found that it used to be that but was rewritten to be string-based to handle more cases so I left it as is (except for std::path::is_separator).

File: crates/nu-path/src/lib.rs [hunk 2]
```diff
@@ -0,0 +1,532 @@
...
+where
+    P: AsRef<Path>,
+    Q: AsRef<Path>,
+{
+    let path = if path.as_ref() == Path::new(".") {
+        // Joining a Path with '.' appends a '.' at the end, making the prompt
+        // more ugly - so we don't do anything, which should result in an equal
+        // path on all supported systems.
+        relative_to.as_ref().to_owned()
+    } else if path.as_ref().starts_with("~") {
```
Comment (NiklasJonsson) [inline crates/nu-path/src/lib.rs:141]: I left the code here roughly as is but I don't understand why this is expands tilde on the `path`, shouldn't it be `relative_to` or am I misunderstanding?

File: crates/nu-path/src/lib.rs [hunk 3]
```diff
@@ -0,0 +1,532 @@
...
+            Component::CurDir if prev_is_normal(&result) => {}
+            _ => result.push(component),
+        });
+
+    Cow::Owned(dunce::simplified(&result).to_path_buf())
+}
+
+// Expands ~ to home and shortens paths by removing unecessary ".." and "."
+// where possible. Also expands "...+" appropriately.
+pub fn expand_path<'a>(path: Cow<'a, Path>) -> Cow<'a, Path> {
```
Comment (NiklasJonsson) [inline crates/nu-path/src/lib.rs:278]: For a while most public functions in this file has the signature
fn(p: impl Into<Cow<'a, Path>>) -> Cow<'a, Path>
which allows it to be called with fn(&Path) or fn(PathBuf).
I removed them because the signatures started becoming fairly complex and on the callside it was a bit magical what you were actually passing as an arg. I can switch back to it if you prefer simplifying the call sites or even &Path if Cow is too unweildy.

**Comment by NiklasJonsson** [comment]
I found I bug in path completion just now so will need to fix that before merging as well.

File: crates/nu-path/src/lib.rs (hunk 2 above)
Comment (kubouch) [reply crates/nu-path/src/lib.rs:141]: If I understand correctly (I didn't write the functions), the main path you want to absolutize is `path`. If the `path` is relative, it gets joined to `relative_to`. If `path` is absolute, it replaces `relative_to`, according to how `Path.join()` or [`PathBuf.push()` work in the standard library](https://doc.rust-lang.org/std/path/struct.PathBuf.html#method.push): "If `path` is absolute, it replaces the current path.".

**Comment by kubouch** [comment]
I don't have comments about the Cow concerns. Perhaps more experienced Rust programmers from the core team would help answering these. As it is now, it seems pretty consistent, I would merge it.

I made an issue (#3655) with improvements that I think need to be done to paths in Nushell in general, but I would implement them as future PR and merge this. For example, I could imagine splitting this into multiple files, perhaps separate `tests` section, etc. but I think that can be done later, since the current functions might still change.

File: crates/nu-path/src/lib.rs (hunk 2 above)
Comment (NiklasJonsson) [reply crates/nu-path/src/lib.rs:141]: Aah ok, yeah that makes sense.

**Comment by jonathandturner** [comment]
This looks fine to me. I agree the Cow parts seem okay to me. To me, consolidating everything is the important part, as it allows us to more easily improve things in the future (like @kubouch mentions)

Thanks for the PR @NiklasJonsson!
