### PR TITLE
Fix internal panic for `query web`

### LINKED ISSUE #13496: query web with empty input causes panic
### Describe the bug

Running `query web` with an empty input causes a panic.

### How to reproduce

`nu -c 'echo|query web'`

### Expected behavior

Error message but without panicking.

### Screenshots

```
$ nu -c 'echo|query web'
thread 'plugin runner (primary)' panicked at crates/nu_plugin_query/src/query_web.rs:414:42:
Error unwrapping scraperselector::parse: UnexpectedSelectorParseError(EmptySelector)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error:   × Failed to receive response to plugin call from `query`
   ╭─[source:1:6]
 1 │ echo|query web
   ·      ────┬────
   ·          ╰── while waiting for this operation to complete
   ╰────
  help: try restarting the plugin with `plugin use 'query'`
```

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.96.1                                                           |
| major              | 0                                                                |
| minor              | 96                                                               |
| patch              | 1                                                                |
| branch             | makepkg                                                          |
| commit_hash        | f7d6c28a001f94f224e459e21df0da2ab5bdc923                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.80.0 (051478957 2024-07-21) (Arch Linux rust 1:1.80.0-1) |
| cargo_version      | cargo 1.80.0 (376290515 2024-07-16)                              |
| build_time         | 2024-07-30 10:25:58 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | default, sqlite, system-clipboard, trash                         |
| installed_plugins  | formats 0.96.1, gstat 0.96.1, inc 0.96.1, query 0.96.1           |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Embers-of-the-Fire**
# Description

Original implementation contains multiple `expect` which can cause internal runtime panic.

This pr forks the `css` selector impl and make it return an error that nushell can recognize.

**Note:** The original impl is still used in pre-defined selector implementations, but they
should never fail, so the `css` fn is preserved.

Closes #13496.

# User-Facing Changes

Now `query web` will not panic when the `query` parameter is not given or has syntax error.

```plain
❯ .\target\debug\nu.exe -c "http get https://www.rust-lang.org | query web"
Error:   × CSS query parse error
   ╭─[source:1:38]
 1 │ http get https://www.rust-lang.org | query web
   ·                                      ────┬────
   ·                                          ╰─┤ Unexpected error occurred. Please report this to the developer
   ·                                            │ EmptySelector
   ╰────
  help: cannot parse query as a valid CSS selector
```

# Tests + Formatting

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used` to check that you're using the standard code style
- [x] `cargo test --workspace` to check that all tests pass (on Windows make sure to [enable developer mode](https://learn.microsoft.com/en-us/windows/apps/get-started/developer-mode-features-and-debugging))
- [x] `cargo run -- -c "use toolkit.nu; toolkit test stdlib"` to run the tests for the standard library

# After Submitting

- [x] Impl change, no doc update.

### CODE REVIEW

**Review by sholderbach — COMMENTED** [review]
Thanks for immediately getting to the bottom of that issue!
At a glance looks good to me to get rid of the `.expect`s.
The only thing I was thinking about is whether we should use the type-erased `LabeledError` or a specific `ShellError` variant. The latter is certainly cluttered and hard to find a good match for.

File: crates/nu_plugin_query/src/query_web.rs [hunk 1]
```diff
@@ -433,27 +451,36 @@ mod tests {
         <a href="https://example.com" target="_self">Example</a>
     "#;
 
+    fn null_spanned<T: ToOwned + ?Sized>(input: &T) -> Spanned<T::Owned> {
+        Spanned {
+            item: input.to_owned(),
+            span: Span { start: 0, end: 0 },
```
Comment (sholderbach) [inline crates/nu_plugin_query/src/query_web.rs:457]: Maybe this could be:
```suggestion
            span: Span::unknown(),
```

As we get to refactoring the span logic, having fewer places with explicit spans around is better. (you could also supersede your function with `IntoSpanned::into_spanned(Span::unknown())` but thats a question of taste)

**Comment by Embers-of-the-Fire** [comment]
> The only thing I was thinking about is whether we should use the type-erased `LabeledError` or a specific `ShellError` variant. The latter is certainly cluttered and hard to find a good match for.

Based on the existing error variant, I think this may only be a 'IncompatibleParametersSngle' or something similar (because this is not a type error but a higher-level syntax error). So there is actually no significant difference between using `LabeledError` and using this :(. But personally, I still prefer to use a typed version.

**Comment by fdncred** [comment]
Seems like a good fit for this ShellError, right?
```rust
    /// An expected command parameter is missing.
    ///
    /// ## Resolution
    ///
    /// Add the expected parameter and try again.
    #[error("Missing parameter: {param_name}.")]
    #[diagnostic(code(nu::shell::missing_parameter))]
    MissingParameter {
        param_name: String,
        #[label = "missing parameter: {param_name}"]
        span: Span,
    },
```

**Comment by Embers-of-the-Fire** [comment]
@fdncred actually not. This error can be triggered by not only empty param but also param with wrong syntax.

https://github.com/nushell/nushell/blob/main/crates/nu_plugin_query/src/query_web.rs#L414

Our current code will panic due to any parser errors, including syntax error, and that contains empty selectors.

**Comment by fdncred** [comment]
Theoretically it could be handled both ways. If a parameter is missing, like in your example, show the missing parameter error and if it's bad syntax, show your labeled error.

**Review by sholderbach — APPROVED** [review]
Before we bikeshed the error variants, I would say let's merge this, and we can revisit the ShellError variants as we refactor those into a better state.
