### PR TITLE
fix(completion): dotnu completion refactor, fixes path with space for both dotnu module path and external executable

### LINKED ISSUE #16705: Different behavior when completing paths with spaces for `use` vs other commands
### Bug report form

- [x] I have done a basic search of the issue tracker to find any existing issues that are similar.
- [x] I have checked that my version is at least the latest stable release available via my installation method.

### Describe the bug

Nushell seems to handle completion differently when it comes to `use` vs other commands, say `cat`, when dealing with paths that contain spaces.

### How to reproduce

Given:

```
$ mkdir `Temp/spaces dir`
$ touch `Temp/spaces dir/file.nu`
```

Completing a regular command, say `cat` on `file.nu` results in:

```
$ cat Temp/sp<TAB>
# becomes
$ cat `Temp/spaces dir/`
# continue typing `f<TAB>`
$ cat `Temp/spaces dir/`f<TAB>
# becomes
$ cat `Temp/spaces dir/file.nu`
```

Everything (sort of) cool here.

But if the command is `use`:

```
$ use Temp/sp<TAB>
# becomes
$ use Temp/`spaces dir/`
# continue typing `f<TAB>`
$ use Temp/`spaces dir/`f<TAB>
# becomes
$ use Temp/`spaces dirfile.nu
```

which is invalid.

### Expected behavior

The completion should produce a valid command line argument.

### Configuration

| key                  | value                                              |
| -------------------- | -------------------------------------------------- |
| version              | 0.107.0                                            |
| major                | 0                                                  |
| minor                | 107                                                |
| patch                | 0                                                  |
| branch               |                                                    |
| commit_hash          |                                                    |
| build_os             | macos-aarch64                                      |
| build_target         | aarch64-apple-darwin                               |
| rust_version         | rustc 1.89.0 (29483883e 2025-08-04) (Homebrew)     |
| cargo_version        | cargo 1.89.0 (Homebrew)                            |
| build_time           | 2025-09-03 01:21:06 +00:00                         |
| build_rust_channel   | release                                            |
| allocator            | standard                                           |
| features             | default, plugin, rustls-tls, sqlite, trash-support |
| installed_plugins    |                                                    |
| experimental_options | example=false, reorder-cell-paths=false            |

### PR DESCRIPTION
**Pull request by blindFS**
Some rework of dotnu completion. Fixes #16705 #16712
CC @ysthakur 

## Release notes summary - What our users need to know

Bug fix

## Tasks after submitting

None

### CODE REVIEW

File: crates/nu-cli/src/completions/file_completions.rs [hunk 1]
```diff
@@ -84,14 +84,3 @@ impl Completer for FileCompletion {
         non_hidden
     }
 }
-
-pub fn file_path_completion(
```
Comment (ysthakur) [inline crates/nu-cli/src/completions/file_completions.rs:88]: Happy to get rid of this

**Review by ysthakur — COMMENTED** [review]
Should we be putting files before directories? That's what the old behavior was but now directories are being listed first, which might be annoying (especially since most directories aren't going to contain Nushell modules)

**Comment by blindFS** [comment]
> Should we be putting files before directories? That's what the old behavior was but now directories are being listed first, which might be annoying (especially since most directories aren't going to contain Nushell modules)

Makes sense, I guess we have to sort them afterwards?

File: crates/nu-cli/src/completions/dotnu_completions.rs [hunk 2]
```diff
@@ -140,70 +93,50 @@ impl Completer for DotNuCompletion {
...
-                        append_whitespace,
-                        ..Suggestion::default()
-                    },
-                    kind: Some(SuggestionKind::Module),
-                }
+                path.ends_with(".nu")
             })
+            // or directories
+            .chain(completions.iter().filter(|it| it.is_dir))
+            .map(into_suggestion)
```
Comment (ysthakur) [inline crates/nu-cli/src/completions/dotnu_completions.rs:139]: I'm not sure pulling `into_suggestion` out to a closure is necessary, but it's fine either way

**Review by ysthakur — APPROVED** [review]
LGTM, thanks. I'd prefer a separate PR for the external completions issue, but it's a small, somewhat related, change, so let's go ahead and merge

**Comment by ysthakur** [comment]
Actually, could you improve the release notes summary a bit? It helps when writing the release notes. Could just be a single sentence.

**Comment by blindFS** [comment]
> Actually, could you improve the release notes summary a bit? It helps when writing the release notes. Could just be a single sentence.

Updated.

**Comment by ysthakur** [comment]
Could you also mention that completions for external executables with spaces in their path also work properly now?

**Comment by blindFS** [comment]
> Could you also mention that completions for external executables with spaces in their path also work properly now?

Sure, probably not ideally formatted as the guideline suggests though.
