### PR TITLE
Fix for inconsistency when quoted strings are used with with_env shorthand

### LINKED ISSUE #1764: Shorthand notation for with-env inconsistent with quoted strings
**Describe the bug**
`with-env [key value]` and `key=value` will not produce the same results with quoted strings.

**To Reproduce**
1. `MYENV="my env value" echo $nu.env.MYENV`
2. `with-env [MYENV "my env value"] { echo $nu.env.MYENV }`

**Expected behavior**
I expect the same output `echo`-ed in both of the above

**Screenshots**
```
nushell on  add-some-examples is  v0.13.1 via  v1.43.0
❯ with-env [MYENV "my env value"] { echo $nu.env.MYENV }
my env value

nushell on  add-some-examples is  v0.13.1 via  v1.43.0
❯ MYENV="my env value" echo $nu.env.MYENV
"my env value"
```

**Configuration (please complete the following information):**
 - OS: macOS
 - Version: 10.15.4
 - stable,test-bins

### PR DESCRIPTION
**Pull request by k-brk**
Now with_env and shorthand version returns same result when quotes are in use.

Fixes #1764

### CODE REVIEW

File: crates/nu-cli/tests/commands/with_env.rs [hunk 1]
```diff
@@ -29,3 +29,38 @@ fn shorthand_doesnt_reorder_arguments() {
 
     assert_eq!(actual.out, "firstsecond");
 }
+
+#[test]
+fn with_env_shorthand_trimes_quotes() {
```
Comment (thegedge) [inline crates/nu-cli/tests/commands/with_env.rs:34]: nit: `trims` instead of `trimes`
