### PR TITLE
make `into string --decimals` add decimals to integer numbers

### LINKED ISSUE #6078: `into string --decimals` does not add decimals to integer numbers
### Describe the bug

Hi,

I'd like to format a number so that it always has two decimal digits. This should work by using `into string` with the `--decimals` argument. But with integer numbers, the decimals are missing.

### How to reproduce

```nu
10 | into string --decimals 2  #=> 10
```

### Expected behavior

The output should also have the number of decimal digits specified by `--decimals`, even when the input is an integer type.

### Screenshots

_No response_

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.65.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.61.0 (a028ae4 2022-04-29)               |
| pkg_version        | 0.65.0                                          |
| build_time         | 2022-07-08 22:54:42 +02:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by merelymyself**
# Description

Title, fixes #6078.

# Tests

Make sure you've done the following:

- [x] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [x] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [x] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

File: crates/nu-command/src/conversions/into/string.rs [hunk 1]
```diff
@@ -210,6 +218,13 @@ pub fn action(
         Value::Int { val, .. } => {
             let res = if group_digits {
                 format_int(*val) // int.to_formatted_string(*locale)
+            } else if let Some(dig) = digits {
+                let mut val_with_trailing_zeroes = val.to_string();
+                val_with_trailing_zeroes.push('.');
```
Comment (WindSoilder) [inline crates/nu-command/src/conversions/into/string.rs:223]: If user input `5 | into string -d 0`, the result will be `5.`, I don't think it's good

Comment (merelymyself) [reply crates/nu-command/src/conversions/into/string.rs]: Good catch, @WindSoilder !
