### PR TITLE
Don't expand ndots if prefixed with `./`

### LINKED ISSUE #13303: Golang ./... wildcard path syntax regression
### Describe the bug

There was a bug before described [here](https://github.com/nushell/nushell/issues/7015) that has started happening again. The regression started in 0.95.0, was working in 0.94.2

### How to reproduce

Run `go test ./...` or any go command that uses that syntax

### Expected behavior

The commands run correctly

### Screenshots

1720200661-wayshot

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.95.0                                                           |
| major              | 0                                                                |
| minor              | 95                                                               |
| patch              | 0                                                                |
| branch             | makepkg                                                          |
| commit_hash        | f93c6680bd5ae158190556eb1afc924b0290b52f                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.79.0 (129f3b996 2024-06-10) (Arch Linux rust 1:1.79.0-1) |
| cargo_version      | cargo 1.79.0                                                     |
| build_time         | 2024-06-25 20:17:10 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | default, sqlite, system-clipboard, trash                         |
| installed_plugins  |                                                                  |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by 132ikl**
# Description
Prevents ndots from being expanded if they are prefixed with `./`, as the agreed resolution to #13303. Only applies to externals, mirroring the fix from #13218.

I did [attempt](https://github.com/132ikl/nushell/tree/internal-ndots-attempt) to apply the fix for internal commands as well, but it seems like the path is expanded too aggressively and I haven't investigated it further yet. `./...` gets normalized into `<pwd>/./...`, which gets normalized into `<pwd>/...` before being handed to `expand_ndots`, and at that point it just looks like a normal n-dots so we can't tell we shouldn't expand.

(Fixes #13303)

# User-Facing Changes

* N-dots are no longer expanded to external command calls when prefixed with `./`.

# Tests + Formatting

Added tests to prevent regression.

- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :green_circle: `toolkit test`
- :green_circle: `toolkit test stdlib`

# After Submitting

N/A

### CODE REVIEW

File: crates/nu-path/src/tilde.rs [hunk 1]
```diff
@@ -152,7 +152,6 @@ fn expand_tilde_with_another_user_home(path: &Path) -> PathBuf {
 
 /// Expand tilde ("~") into a home directory if it is the first path component
 pub fn expand_tilde(path: impl AsRef<Path>) -> PathBuf {
-    // TODO: Extend this to work with "~user" style of home paths
```
Comment (ysthakur) [inline crates/nu-path/src/tilde.rs:155]: Is this working now? (I have no idea what `~user` style is)

Comment (fdncred) [reply crates/nu-path/src/tilde.rs:155]: Not sure. Strangely enough, `ls ~` and `ls ~fdncred` return the same thing on my mac.

Comment (132ikl) [reply crates/nu-path/src/tilde.rs:155]: oh my bad, I meant to comment on this in the PR description. yes, this is an old comment. this was implemented in #5251

**Review by ysthakur — APPROVED** [review]
LGTM

File: crates/nu-path/src/tilde.rs (hunk 1 above)
Comment (weirdan) [reply crates/nu-path/src/tilde.rs:155]: > I have no idea what `~user` style is

`~user` is expanded to the home directory of `user`.

> Strangely enough, `ls ~` and `ls ~fdncred` return the same thing on my mac.

That's how it works. Effectively, `~` is a shortcut to `~($env.USER)` where `$env.USER` is the current user.
