### PR TITLE
Fix unexpected flattening of data by par-each (Issue #8497)

### LINKED ISSUE #8497: `par-each` unexpectedly flattens data
### Describe the bug

First I thought this was a bug with `flatten` flattening multiple levels at once, but then I tested further and realised that my data was just already (unexpectedly) flattened

### How to reproduce

1. Run `par-each` with a closure producing a list of data:

***Edit:** Fixed this example to have the right input/output combination*

```
['a', 'b', 'c'] | par-each { [$in] } | table -e

# Output
╭───┬───╮
│ 0 │ a │
│ 1 │ b │
│ 2 │ c │
╰───┴───╯

# Expected output
╭───┬───────────╮
│ 0 │ ╭───┬───╮ │
│   │ │ 0 │ a │ │
│   │ ╰───┴───╯ │
│ 1 │ ╭───┬───╮ │
│   │ │ 0 │ b │ │
│   │ ╰───┴───╯ │
│ 2 │ ╭───┬───╮ │
│   │ │ 0 │ c │ │
│   │ ╰───┴───╯ │
╰───┴───────────╯
```

Or, a different example

```
[['a', 'b'], ['c']] | par-each { |list| $list | each { str capitalize } } | table -e

# Output
╭───┬───╮
│ 0 │ A │
│ 1 │ B │
│ 2 │ C │
╰───┴───╯

# Expected Output
╭───┬───────────╮
│ 0 │ ╭───┬───╮ │
│   │ │ 0 │ A │ │
│   │ │ 1 │ B │ │
│   │ ╰───┴───╯ │
│ 1 │ ╭───┬───╮ │
│   │ │ 0 │ C │ │
│   │ ╰───┴───╯ │
╰───┴───────────╯
```

### Expected behavior

I expected `par-each` to essentially behave like `each` and not flatten the output.

The current behaviour feels unpredictable in regards to what level of flattening my output will have without running the code (like in the case I had, where I assumed I have to call `| flatten` on the output, but then accidentally flattened the records inside my assumed list of lists).

With `each`:

```
['a', 'b', 'c'] | each { [$in] } | table -e

# Output
╭───┬───────────╮
│ 0 │ ╭───┬───╮ │
│   │ │ 0 │ a │ │
│   │ ╰───┴───╯ │
│ 1 │ ╭───┬───╮ │
│   │ │ 0 │ b │ │
│   │ ╰───┴───╯ │
│ 2 │ ╭───┬───╮ │
│   │ │ 0 │ c │ │
│   │ ╰───┴───╯ │
╰───┴───────────╯
```

```
[['a', 'b'], ['c']] | each { |list| $list | each { str capitalize } } | table -e

# Output
╭───┬───────────╮
│ 0 │ ╭───┬───╮ │
│   │ │ 0 │ A │ │
│   │ │ 1 │ B │ │
│   │ ╰───┴───╯ │
│ 1 │ ╭───┬───╮ │
│   │ │ 0 │ C │ │
│   │ ╰───┴───╯ │
╰───┴───────────╯
```

### Screenshots

_No response_

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.77.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.68.0 (2c8cc3432 2023-03-06) (built from a source tarball) |
| cargo_version      | cargo 1.68.0 (115f34552 2023-02-26)                               |
| build_time         | 2023-03-14 18:46:42 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | default, zip                                                      |
| installed_plugins  |                                                                   |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by TrMen**
# Description
Previously, `par-each` acted like a `flatmap`: first mapping the data, then applying a `flatten`. This is unlike `each`, which just maps the data. Now `par-each` works like `each` in this regard, leaving nested data unflattened.

Fixes #8497

# User-Facing Changes
Previously:
`[1 2 3] | par-each {|e| [$e, $e] }` --> `[1,1,2,2,3,3]` 
Now:
`[1 2 3] | par-each {|e| [$e, $e] }` --> `[[1,1],[2,2],[3,3]]`

# Tests
This adds one test that verifies the lack of flattening for `par-each`.

### CODE REVIEW

**Review by sholderbach — COMMENTED** [review]
Thanks for picking this up and covering it with a test!
(One thing where I am unsure historically: Do we have an ordering guarantee for `par-each` now, which affects tests and general behavior)

Will mark it as a breaking change to mention it in the release notes but would consider this the expected behavior.

**Comment by TrMen** [comment]
I don't believe this PR changes anything in regards to ordering. I'm just changing what's done with the data after it has already been collected into a Vec.

[rayon::iter::ParallelBridge](https://docs.rs/rayon/latest/rayon/iter/trait.ParallelBridge.html#) doesn't make any guarantees for ordering, so at least the current `par-each` implementation doesn't seem to guarantee any ordering either. That's why my test sorts the list before applying an expectation.

File: crates/nu-command/src/filters/par_each.rs [hunk 1]
```diff
@@ -146,16 +148,15 @@ impl Command for ParEach {
                                 redirect_stdout,
                                 redirect_stderr,
                             ) {
-                                Ok(v) => v,
+                                Ok(v) => v.into_value(span),
```
Comment (sholderbach) [inline crates/nu-command/src/filters/par_each.rs:151]: This will materialize a `PipelineData::ListStream` to a `Value::List` but I think there is no way we can keep this a lazy iterator anyways when we run the evaluation in the parallel threads and collect afterwards.

File: crates/nu-command/src/filters/par_each.rs [hunk 2]
```diff
@@ -298,6 +292,7 @@ impl Command for ParEach {
                 )
             }
         }
+        .and_then(|x| x.filter(|v| !v.is_nothing(), outer_ctrlc))
```
Comment (sholderbach) [inline crates/nu-command/src/filters/par_each.rs:295]: Is this checking for `$nothing` to match the behavior of `each` or to effectively fuse the iterator?

**Review by sholderbach — APPROVED** [review]
Ah I totally missed your `sort` in the test. Great! 

The examples are all still passing, so we are good to go! Thanks for a great first PR!

File: crates/nu-command/src/filters/par_each.rs (hunk 2 above)
Comment (TrMen) [reply crates/nu-command/src/filters/par_each.rs:295]: It's to match `each`. It's not a behavior change though. Previously, `par-each` would already discard `Nothing` like `each` does (and one of the existing examples checks for that). 

It was just implicit due to the `PipelineDataIterator` being flattened I think. So this just keeps existing behavior.

File: crates/nu-command/src/filters/par_each.rs (hunk 1 above)
Comment (TrMen) [reply crates/nu-command/src/filters/par_each.rs:151]: Seems to me like evaluating the streams in parallel makes sense, but I don't know enough about the codebase to make a meaningful comment here about whether it is possible or desirable to keep them lazy.

File: crates/nu-command/src/filters/par_each.rs (hunk 2 above)
Comment (sholderbach) [reply crates/nu-command/src/filters/par_each.rs:295]: Ah, all good!

File: crates/nu-command/src/filters/par_each.rs (hunk 1 above)
Comment (sholderbach) [reply crates/nu-command/src/filters/par_each.rs:151]: @rgwood is probably our resident streaming expert at the moment but there should be no harm to this change.
