### PR TITLE
fix(parser): pitfall of redefining `def`

### LINKED ISSUE #16586: Another panic of the parser
### Bug report form

- [x] I have done a basic search of the issue tracker to find any existing issues that are similar.
- [x] I have checked that my version is at least the latest stable release available via my installation method.

### Describe the bug

Found with `cargo fuzz` from #16292 

### How to reproduce

```nushell
def def (=,|s)>
```

### Expected behavior

Don't panic!

### Configuration

| key                  | value                                                             |
| -------------------- | ----------------------------------------------------------------- |
| version              | 0.106.1                                                           |
| major                | 0                                                                 |
| minor                | 106                                                               |
| patch                | 1                                                                 |
| branch               |                                                                   |
| commit_hash          |                                                                   |
| build_os             | macos-aarch64                                                     |
| build_target         | aarch64-apple-darwin                                              |
| rust_version         | rustc 1.89.0 (29483883e 2025-08-04) (built from a source tarball) |
| cargo_version        | cargo 1.89.0 (c24e10642 2025-06-23)                               |
| build_time           | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel   | release                                                           |
| allocator            | standard                                                          |
| features             | default, plugin, rustls-tls, sqlite, trash-support                |
| installed_plugins    |                                                                   |
| experimental_options | example=false, reorder-cell-paths=false                           |

### PR DESCRIPTION
**Pull request by blindFS**
Fixes #16586 

## Release notes summary - What our users need to know

None

## Tasks after submitting

None

### CODE REVIEW

File: crates/nu-parser/src/parse_keywords.rs [hunk 1]
```diff
@@ -4216,35 +4212,24 @@ pub fn find_in_dirs(
...
+                help: format!(
+                    "consider adding a space between the `{}` command's name and its parameters",
+                    working_set.get_decl(decl_id).name()
+                ),
+                span: Span::new(offset + name_span.start - 1, offset + name_span.start - 1),
+            });
+        }
     }
+
+    None
```
Comment (blindFS) [inline crates/nu-parser/src/parse_keywords.rs:4236]: This change is irrelevant to the fix.

Comment (sholderbach) [reply crates/nu-parser/src/parse_keywords.rs:4236]: Can you nevertheless explain to me what you are doing here. Else may be worth splitting off into its own commit.

File: crates/nu-cmd-lang/tests/commands/attr/deprecated.rs [hunk 2]
```diff
@@ -1,19 +1,12 @@
...
 use nu_parser::parse;
-use nu_protocol::engine::{EngineState, StateWorkingSet};
-
-use nu_cmd_lang::AttrDeprecated;
+use nu_protocol::engine::StateWorkingSet;
 
 #[test]
 pub fn test_deprecated_attribute() {
-    let engine_state = EngineState::new();
+    let engine_state = nu_cmd_lang::create_default_context();
```
Comment (sholderbach) [inline crates/nu-cmd-lang/tests/commands/attr/deprecated.rs:7]: Certainly more compact code. What was the reason to have that change?

**Review by sholderbach — COMMENTED** [review]
Makes sense to me to lock that down, we probably want to lock more of our keywords but we can look into generalizing in a second step.

File: crates/nu-cmd-lang/tests/commands/attr/deprecated.rs (hunk 2 above)
Comment (blindFS) [reply crates/nu-cmd-lang/tests/commands/attr/deprecated.rs:7]: Originally, command `def` was temporarily added to working set, so parse_def will complain about not finding the decl_id of it. Merging it to the engine state is another way of fixing it, but this one is simpler.

File: crates/nu-parser/src/parse_keywords.rs (hunk 1 above)
Comment (blindFS) [reply crates/nu-parser/src/parse_keywords.rs:4236]: > Can you nevertheless explain to me what you are doing here. Else may be worth splitting off into its own commit.

Nothing important, just a simple refactoring into a more readable version.

Comment (sholderbach) [reply crates/nu-parser/src/parse_keywords.rs:4236]: There is something regarding this (and its predecessor) code we might need to fix but that is beside the scope of this PR. 

<details><summary>Details</summary>
<p>
When trying out cursed command names I stumbled across this issue:
```
> def "test[]" [] {}
Error:   × no space between name and parameters
   ╭─[entry #1:1:9]
 1 │ def "test[]" [] {}
   ·         ▲
   ·         ╰── expected space
   ╰────
  help: consider adding a space between the `def` command's name and its parameters
```

</p>
</details>
