### PR TITLE
Respecting $env.NO_PROXY

### LINKED ISSUE #15244: http get not using $env.no_proxy
### Describe the bug

At work I'm behind a proxy and a corporate VPN.

When I call `http get` on my own local server on localhost, I get 403, because the request tries going via the proxy. Same request with curl works fine.

Works for external sites (uses `$env.http_proxy`):

```sh
➜ http get https://httpbin.org/get
╭─────────┬────────────────────────────────────────────────────────────────╮
│ args    │ {record 0 fields}                                              │
│         │ ╭─────────────────┬──────────────────────────────────────────╮ │
│ headers │ │ Accept          │ */*                                      │ │
│         │ │ Accept-Encoding │ gzip                                     │ │
│         │ │ Host            │ httpbin.org                              │ │
│         │ │ User-Agent      │ nushell                                  │ │
│         │ │ X-Amzn-Trace-Id │ Root=1-67c78288-32b0df6f3e730f1f1c474d09 │ │
│         │ ╰─────────────────┴──────────────────────────────────────────╯ │
│ origin  │ 131.228.2.16                                                   │
│ url     │ https://httpbin.org/get                                        │
╰─────────┴────────────────────────────────────────────────────────────────╯
```

Doesn't work on my local server:

```sh
➜ http get http://127.0.0.1:8000/foo
Error: nu::shell::network_failure

  × Network failure
   ╭─[entry #144:1:10]
 1 │ http get http://127.0.0.1:8000/foo
   ·          ────────────┬────────────
   ·                      ╰── Access forbidden (403) to "http://127.0.0.1:8000/foo"
   ╰────
```

Works with curl:

```sh
➜ curl http://127.0.0.1:8000/foo
{"message":"Hello World"}
```

If I remove the `no_proxy` env variable, `curl` also stops working:

```sh
➜ hide-env no_proxy
➜ curl -I http://127.0.0.1:8000/foo
HTTP/1.1 403 Forbidden
Connection: close
Content-Type: text/html
Cache-Control: no-cache
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Length: 2778
```

So I guess it has to be the fact that `http get` doesn't respect the `$env.no_proxy`, contrary to `curl`.

### How to reproduce

1. Call `http get` on a localhost server behind a proxy (both `$env.http_proxy` and `$env.no_proxy` set)
2. `http get` won't respect the `$env.no_proxy` env variable and will try to go via the proxy

### Expected behavior

I would expect `http get` to respect the `$env.no_proxy` env variable (usually set to multiple things, including `localhost` etc.)

### Configuration

➜ version | transpose key value | to md --pretty
| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.102.0                                                          |
| major              | 0                                                                |
| minor              | 102                                                              |
| patch              | 0                                                                |
| branch             | makepkg                                                          |
| commit_hash        | 1aa2ed1947a0b891398558fcf4e4289849cc5a1d                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.84.1 (e71f9a9a9 2025-01-27) (Arch Linux rust 1:1.84.1-1) |
| cargo_version      | cargo 1.84.1 (66221abde 2024-11-19)                              |
| build_time         | 2025-02-05 21:56:07 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | default, sqlite, trash                                           |
| installed_plugins  |                                                                  |

### PR DESCRIPTION
**Pull request by m4siri**
https://github.com/algesten/ureq/commit/1ce334d329d5bdcc8f36126f34c7f61ba851c409 now reads the `NO_PROXY` variable automatically and handles proxy filter. As of writing this, the commit just got merged into main, `ureq` needs to be bumped to `3.1.x` for this work, the hard-coded git revision will be removed as soon as we have a release in ureq.

This implementation makes use of `ProxyBuilder` as the environment variables are scoped and ureq won't be able to read the value. The proxy builder is abstracted into `proxy_builder_from_env(2)` so that in the future we can also add a `--proxy-user` and `--proxy-pass` or `--no-proxy-list` to the `http` command.

### `http` commands now respect the `$env.NO_PROXY` variable
`http` command now reads the environment variable `NO_PROXY` and supports the following patterns.
| Pattern         | Behavior |
------------------|-----------
| `example.com`   | Literally match `example.com`, but not `sub.example.com` |
| `.example.com`  | Match `sub.example.com` and `foo.sub.example.com`, but not `example.com`. |
| `*.example.com` | Exactly like `.example.com` |
| `*`             | Match everything |

> [!NOTE]
> Multiple patterns can be used by seperating them via comma and expressions that are not on the above form are ignored silently.

## Tasks after submitting

- [ ] Update the [documentation](https://github.com/nushell/nushell.github.io)

### CODE REVIEW

**Comment by m4siri** [comment]
Running the network test ` cargo test -p nu-command -F network` seems to be stuck in the following tests, possibly due to change in ureq, haven't confirmed as of now.
- commands::network::http::patch::http_patch_follows_redirect
- commands::network::http::post::http_post_follows_redirect
- commands::network::http::put::http_put_follows_redirect

However skipping those test via `-- --skip follows_redirect` does seem to work.

File: crates/nu-command/src/network/http/client.rs [hunk 1]
```diff
@@ -1014,6 +1016,50 @@ fn retrieve_http_proxy_from_env(engine_state: &EngineState, stack: &mut Stack) -
...
 
+fn retrieve_no_proxy_from_env(engine_state: &EngineState, stack: &mut Stack) -> Option<String> {
+    stack
+        .get_env_var(engine_state, "no_proxy")
+        .or(stack.get_env_var(engine_state, "NO_PROXY"))
+        .cloned()
+        .and_then(|no_proxy| no_proxy.coerce_into_string().ok())
+}
+
+fn proxy_builder_from_env(engine_state: &EngineState, stack: &mut Stack) -> Option<ProxyBuilder> {
```
Comment (cptpiepmatz) [inline crates/nu-command/src/network/http/client.rs]: Did you forget to call this function?

File: crates/nu-command/src/network/http/client.rs [hunk 2]
```diff
@@ -1014,6 +1016,50 @@ fn retrieve_http_proxy_from_env(engine_state: &EngineState, stack: &mut Stack) -
         .and_then(|proxy| proxy.coerce_into_string().ok())
 }
 
+fn retrieve_no_proxy_from_env(engine_state: &EngineState, stack: &mut Stack) -> Option<String> {
+    stack
+        .get_env_var(engine_state, "no_proxy")
+        .or(stack.get_env_var(engine_state, "NO_PROXY"))
```
Comment (cptpiepmatz) [inline crates/nu-command/src/network/http/client.rs]: I think you can use [`get_env_var_insensitive`](https://docs.rs/nu-engine/latest/nu_engine/command_prelude/struct.EngineState.html#method.get_env_var_insensitive) here.

File: crates/nu-command/src/network/http/client.rs [hunk 3]
```diff
@@ -1014,6 +1016,50 @@ fn retrieve_http_proxy_from_env(engine_state: &EngineState, stack: &mut Stack) -
...
+        .cloned()
+        .and_then(|no_proxy| no_proxy.coerce_into_string().ok())
```
Comment (cptpiepmatz) [inline crates/nu-command/src/network/http/client.rs]: I'm not sure if double cloning could happen here 
```suggestion
        .and_then(|no_proxy| no_proxy.coerce_str().to_owned().ok())
```

**Review by cptpiepmatz — CHANGES_REQUESTED** [review]

File: crates/nu-command/src/network/http/client.rs (hunk 1 above)
Comment (m4siri) [reply crates/nu-command/src/network/http/client.rs]: It was correct originally, I think it got messed up during my force push, its a quick fix.

**Comment by fdncred** [comment]
@cptpiepmatz did you fix this recently?

**Comment by cptpiepmatz** [comment]
Not sure if my changes affect this behavior. I have to look into this. I kept this PR up to not forget to check this.

**Comment by fdncred** [comment]
@m4siri Are you going to continue working on this?

**Comment by m4siri** [comment]
Hi @fdncred , I'll check onto it today.

**Comment by m4siri** [comment]
@fdncred @cptpiepmatz LGTM :)

**Comment by cptpiepmatz** [comment]
Please take a look why CI is failing. Formatting is usually done via `cargo fmt` in the root of the repo.

**Comment by m4siri** [comment]
> Please take a look why CI is failing. Formatting is usually done via `cargo fmt` in the root of the repo.

Done, should be good.

**Review by cptpiepmatz — APPROVED** [review]
I think this looks good. Thanks for this. Sorry I did not look into this earlier.
