### PR TITLE
fix the mcp ctrl-c bug

### LINKED ISSUE #17196: Ctrl+C during a long command exits shell entirely (regression in main)
### Bug report form

- [x] I have done a basic search of the issue tracker to find any existing issues that are similar.
- [x] I have checked that my version is at least the latest stable release available via my installation method.

### Describe the bug

In latest main, Ctrl+C during a long command now terminates the shell itself rather than the command. Bisected to #17151.

### How to reproduce

```nushell
cd /
ls **/*
```

Quickly Ctrl+C

Result: The shell is terminated:

```nushell
Error: nu::shell::terminated_by_signal

  × External command was terminated by a signal
   ╭─[entry #13:1:1]
 1 │ ./target/release/nu -n
   · ─────────┬─────────
   ·          ╰── terminated by SIGINT (2)
   ╰────
```

Also can be seen if running `nu -n`, checking `$env.SHLVL`, trying the above, then checking `$env.SHLVL` again.

### Expected behavior

Stop the command, not the shell ;-)

### Configuration

| key                  | value                                                                                     |
| -------------------- | ----------------------------------------------------------------------------------------- |
| version              | 0.109.2                                                                                   |
| major                | 0                                                                                         |
| minor                | 109                                                                                       |
| patch                | 2                                                                                         |
| branch               | main                                                                                      |
| commit_hash          | fb17296d47ecca34350953fa9a2c06cc60e5b4de                                                  |
| build_os             | linux-x86_64                                                                              |
| build_target         | x86_64-unknown-linux-gnu                                                                  |
| rust_version         | rustc 1.90.0 (1159e78c4 2025-09-14)                                                       |
| rust_channel         | 1.90.0-x86_64-unknown-linux-gnu                                                           |
| cargo_version        | cargo 1.90.0 (840b83a10 2025-07-30)                                                       |
| build_time           | 2025-12-13 15:59:22 -05:00                                                                |
| build_rust_channel   | release                                                                                   |
| allocator            | standard                                                                                  |
| features             | default, mcp, network, plugin, rustls-tls, sqlite, trash-support                          |
| installed_plugins    | formats 0.106.2, gstat 0.106.2, polars 0.106.2, query 0.106.2                             |
| experimental_options | example=false, reorder-cell-paths=true, pipefail=false, enforce-runtime-annotations=false |

### PR DESCRIPTION
**Pull request by fdncred**
This PR fixes the ctrl-c bug @NotTheDr01ds discovered.

closes #17196

## Release notes summary - What our users need to know
N/A

## Tasks after submitting
N/A

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -102,8 +100,6 @@ fn main() -> Result<()> {
         report_shell_error(None, &engine_state, &err);
     }
 
-    // TODO: make this conditional in the future
-    #[cfg(not(feature = "mcp"))]
```
Comment (ysthakur) [inline src/main.rs:106]: Do you know why this was added in the first place?

Comment (fdncred) [reply src/main.rs:106]: I have no idea. Maybe @ayax79 knows?

Comment (sgvictorino) [reply src/main.rs:106]: It made the MCP server interruptible with ctrl+c / SIGINT. We might want to branch on `--mcp` at runtime:

```rust
    let handle_ctrlc = true;
    #[cfg(feature = "mcp")]
    let handle_ctrlc = !parsed_nu_cli_args.mcp;
    if handle_ctrlc {
        ctrlc_protection(&mut engine_state);
    }
```
