### PR TITLE
Prevent `each` from swallowing errors when `eval_block` returns a `ListStream`

### LINKED ISSUE #10176: Nested `each` swallows errors
### Describe the bug

Errors like `executable was not found` or any other content do not get propagated when you nest two `each` blocks.

### How to reproduce

1. run `[[1,2]] | each {|x| $x | each {|y| error make {msg: "oh noes"} } }`

### Expected behavior

This should raise the error.

### Screenshots

20230831_21h46m24s_grim

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.84.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03) (built from a source tarball) |
| cargo_version      | cargo 1.71.1                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | standard                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

### Additional context

_No response_

### LINKED ISSUE #11224: Error is not propagated from a nested `each`
Potentially related (from @blm768):
- #10176
- #8615 

### Describe the bug

I tried this code:
```nu
[0] | each { |_|
    [0] | each { |_|
        non-existent-command
    }
}
```
If you put it into a file and run with `nu` you'll see the output:
```
╭───┬───────────────╮
│ 0 │ [list 1 item] │
╰───┴───────────────╯
```
If you put `| debug` after the outermost `each` you'll see:

```
╭───┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 0 │ [EvalBlockWithInput(Span { start: 126475, end: 126476 }, [ExternalCommand { label: "executable was not found", help: "No such file or directory (os error    │
│   │ 2)", span: Span { start: 126499, end: 126519 } }])]                                                                                                          │
╰───┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

And if you put smth like `| to json` after the outermost `each` you'll see the error:

<details>
<summary>Details</summary>

```
Error: nu::shell::eval_block_with_input

  × Eval block failed with pipeline input
   ╭─[/home/veetaha/work/elastio/dbg.nu:5:1]
 5 │ [0] | each { |_|
 6 │     [0] | each { |_|
   ·      ┬
   ·      ╰── source value
 7 │         non-existent-command
   ╰────

Error: nu::shell::external_command

  × External command failed
   ╭─[/home/veetaha/work/elastio/dbg.nu:6:1]
 6 │     [0] | each { |_|
 7 │         non-existent-command
   ·         ──────────┬─────────
   ·                   ╰── executable was not found
 8 │     }
   ╰────
  help: No such file or directory (os error 2)
```

</details>

### Expected behavior

I expected to see the "executable not found" error no matter what happens with the resulting value. The error should be propagated even if there is no `| to json` or similar at the end.

### Configuration

| key                | value                                                   |
| ------------------ | ------------------------------------------------------- |
| version            | 0.87.1                                                  |
| branch             |                                                         |
| commit_hash        | 3d631490bc17cfef2944072f9b7869cd9cac1e7b                |
| build_os           | linux-x86_64                                            |
| build_target       | x86_64-unknown-linux-gnu                                |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03)                     |
| rust_channel       | 1.71.1-x86_64-unknown-linux-gnu                         |
| cargo_version      | cargo 1.71.1 (7f1d04c00 2023-07-29)                     |
| build_time         | 2023-11-18 18:51:59 +00:00                              |
| build_rust_channel | release                                                 |
| allocator          | mimalloc                                                |
| features           | default, sqlite, static-link-openssl, trash, which, zip |
| installed_plugins  | from eml, from ics, from ini, from vcf                  |

### PR DESCRIPTION
**Pull request by merelymyself**
# Description

Prior, it seemed that nested errors would not get detected and shown. This PR fixes that.

Resolves #10176:
```
~/CodingProjects/nushell> [[1,2]] | each {|x| $x | each {|y| error make {msg: "oh noes"} } }                        05/04/2024 21:34:08
Error: nu::shell::eval_block_with_input

  × Eval block failed with pipeline input
   ╭─[entry #1:1:3]
 1 │ [[1,2]] | each {|x| $x | each {|y| error make {msg: "oh noes"} } }
   ·   ┬
   ·   ╰── source value
   ╰────

Error:   × oh noes
   ╭─[entry #1:1:36]
 1 │ [[1,2]] | each {|x| $x | each {|y| error make {msg: "oh noes"} } }
   ·                                    ─────┬────
   ·                                         ╰── originates from here
   ╰────
```

Resolves #11224:
```
~/CodingProjects/nushell> [0] | each { |_|                                                                          05/04/2024 21:35:40
:::     [0] | each { |_|
:::         non-existent-command
:::     }
::: }
Error: nu::shell::eval_block_with_input

  × Eval block failed with pipeline input
   ╭─[entry #1:2:6]
 1 │ [0] | each { |_|
 2 │     [0] | each { |_|
   ·      ┬
   ·      ╰── source value
 3 │         non-existent-command
   ╰────

Error: nu::shell::external_command

  × External command failed
   ╭─[entry #1:3:9]
 2 │     [0] | each { |_|
 3 │         non-existent-command
   ·         ──────────┬─────────
   ·                   ╰── executable was not found
 4 │     }
   ╰────
  help: No such file or directory (os error 2)
```

# User-Facing Changes

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Comment by fdncred** [comment]
Have you done any performance testing to see if this decreases the performance of table/each?

**Comment by merelymyself** [comment]
Yes, there is a noticeable decrease in the performance of `table`. Drafting until resolved.

**Comment by merelymyself** [comment]
With this change, the performance decrease is minimised - only in the specific case where a `ListStream` is fed into `each` is there a slight dip, but it shouldn't be very significant.

File: crates/nu-command/src/filters/each.rs [hunk 1]
```diff
@@ -149,6 +149,15 @@ with 'transpose' first."#
...
                         x.into_pipeline_data(),
                     ) {
+                        Ok(PipelineData::ListStream(s, ..)) => {
+                            let vals: Vec<Value> = s.collect();
+                            for v in &vals {
+                                if let Value::Error { .. } = v {
+                                    return Some(v.clone());
+                                }
+                            }
+                            Some(Value::list(vals, span))
```
Comment (WindSoilder) [inline crates/nu-command/src/filters/each.rs:159]: Hmm...Maybe collect s first is not really good.  What about this?
```rust
let mut vals = vec![];
for v in s {
    if let Value::Error { .. } = v { return Some(v) }
    else { vals.push(v) }
}
Some(Value::list(vals, span))
```

**Comment by merelymyself** [comment]
Rebased and accepted the suggestion. @fdncred @WindSoilder, take a look?

**Comment by WindSoilder** [comment]
Thanks!  It looks good to me.  Since nushell will have a release in 5 days, I'd like to defer it after released

**Review by WindSoilder — APPROVED** [review]

**Comment by fdncred** [comment]
Thanks
