### PR TITLE
Use native toml datetime type in `to toml`

### LINKED ISSUE #11751: `to/from toml` doesn't use native TOML date format
### Describe the bug

When converting dates to toml, dates are converted to a string instead of the TOML dates.  The same applies to the `from` conversion.

### How to reproduce

```Nushell
~> {date: 2024-02-02} | to toml
date = "2024-02-02 00:00:00 +00:00"
~> "dob = 1979-05-27T07:32:00-08:00" | from toml
╭─────┬───────────────────────────╮
│ dob │ 1979-05-27T07:32:00-08:00 │
╰─────┴───────────────────────────╯
```

### Expected behavior

Converting Nushell dates to TOML dates and visa versa.

### Screenshots

_No response_

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.89.0                                                       |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (Alpine Linux 1.72.1-r0) |
| cargo_version      | cargo 1.72.1                                                 |
| build_time         | 2024-01-13 03:02:49 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, trash, which, zip                           |
| installed_plugins  |                                                              |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by KAAtheWiseGit**
# Description

Makes `to toml` use the `toml::value::Datetime` type, so that `to toml` serializes dates properly.

# User-Facing Changes

`to toml` will now encode dates differently, in a native format instead of a string.  This could, in theory, break some workflows:

```Nushell
# Before:
~> {datetime: 2024-05-31} | to toml | from toml | get datetime | into datetime
Fri, 31 May 2024 00:00:00 +0000 (10 hours ago)
# After:
~> {datetime: 2024-05-31} | to toml | from toml | get datetime | into datetime
Error: nu::shell::only_supports_this_input_type

  × Input type not supported.
   ╭─[entry #13:1:36]
 1 │ {datetime: 2024-05-31} | to toml | from toml | get datetime | into datetime
   ·                                    ────┬────                  ──────┬──────
   ·                                        │                            ╰── only string and int input data is supported
   ·                                        ╰── input type: date
   ╰────
```

Fix #11751

### CODE REVIEW

**Comment by fdncred** [comment]
It looks like after the change in datetime format `from toml` is already converting the datetime text into a nushell datetime value since the datetime text is RFC3339/ISO8601 formatted.

File: crates/nu-command/src/formats/to/toml.rs [hunk 1]
```diff
@@ -49,9 +49,7 @@ fn helper(engine_state: &EngineState, v: &Value) -> Result<toml::Value, ShellErr
         Value::Int { val, .. } => toml::Value::Integer(*val),
         Value::Filesize { val, .. } => toml::Value::Integer(*val),
         Value::Duration { val, .. } => toml::Value::String(val.to_string()),
-        Value::Date { val, .. } => {
-            toml::Value::String(val.to_rfc3339_opts(SecondsFormat::AutoSi, false))
```
Comment (fdncred) [inline crates/nu-command/src/formats/to/toml.rs:53]: Seems like you could've just used this to_rfc3339_opts function and removed the surrounding quotes to achieve the same result. I don't see any difference in the format other than the quotes.

Comment (KAAtheWiseGit) [reply crates/nu-command/src/formats/to/toml.rs:53]: @fdncred I don't see a way to remove the quotes, because everything is encoded using `toml`'s machinery.  `to_toml` takes a `toml::Value`, which has it's own encoding rules and requires the `toml::Value::Datetime` variant for bare dates.

Comment (KAAtheWiseGit) [reply crates/nu-command/src/formats/to/toml.rs:53]: And `toml` doesn't provide any useful conversion traits, be it for chrono or strings, so I was stuck converting everything to their ad-hoc format by hand

Comment (fdncred) [reply crates/nu-command/src/formats/to/toml.rs:53]: Ah, ok.

**Comment by NotTheDr01ds** [comment]
Adding some "breaking change" doc here since the original PR description wasn't clear to me.  I needed to merge the PR to see what it was really doing.

### User-Facing Changes

Nushell 0.91 previously [changed `from toml`](https://github.com/nushell/nushell/pull/11846) handle native TOML datetime values (which should not be quoted).  However, `to toml` was not updated, meaning that round-tripping TOML (`from toml | to toml`) required an extra `into datetime`.  This completes the `to toml` support.

For code that is using `into datetime`, this will result in a breaking change that is easily resolved by simply removing the now-unnecessary `into datetime`:

```Nushell
# In 0.94.2
~> {datetime: 2024-05-31} | to toml
datetime = "2024-05-31T00:00:00+00:00"
# After this PR
~> {datetime: 2024-05-31} | to toml
datetime = 2024-05-31T00:00:00+00:00

# In 0.94.2
~> {datetime: 2024-05-31} | to toml | from toml | get datetime | into datetime
Fri, 31 May 2024 00:00:00 +0000 (a week ago)
# After this PR
~> {datetime: 2024-05-31} | to toml | from toml | get datetime | into datetime
Error: nu::shell::only_supports_this_input_type

  × Input type not supported.
   ╭─[entry #16:1:36]
 1 │ {datetime: 2024-05-31} | to toml | from toml | get datetime | into datetime
   ·                                    ────┬────                  ──────┬──────
   ·                                        │                            ╰── only string and int input data is supported
   ·                                        ╰── input type: date
   ╰────

# Fix - remove `into datetime`
~> {datetime: 2024-05-31} | to toml | from toml | get datetime
Fri, 31 May 2024 00:00:00 +0000 (a week ago)
```

**Comment by fdncred** [comment]
let's see how much this breaks things. thanks
