### PR TITLE
Fix #15440 default --empty fails at empty streams

### LINKED ISSUE #1544: autocd doesn't expand tilde
**To Reproduce**
1. type ~, hit enter

output:
```
error: Command not found
- shell:1:1
1 | ~
  | ^ command not found
```

**Expected behavior**
I should cd to my home folder

**Configuration (please complete the following information):**
Void Linux
nu 0.12 from `cargo install nu`

### LINKED ISSUE #15440: `default --empty` fails at empty streams
### Describe the bug

The new flag (#15223) is quite useful but does not trigger if streams are empty.

### How to reproduce

```
glob ? | default -e void
# => empty list
```

### Expected behavior

```
glob ? | collect | default -e void
# => void
```

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.103.0                                     |
| major              | 0                                           |
| minor              | 103                                         |
| patch              | 0                                           |
| branch             |                                             |
| commit_hash        | c98642647878b4f66fb7e38388a3973071b0e27b    |
| build_os           | linux-x86_64                                |
| build_target       | x86_64-unknown-linux-musl                   |
| rust_version       | rustc 1.83.0 (90b35a623 2024-11-26)         |
| rust_channel       | 1.83.0-x86_64-unknown-linux-gnu             |
| cargo_version      | cargo 1.83.0 (5ffbef321 2024-10-29)         |
| build_time         | 2025-03-19 00:29:54 +00:00                  |
| build_rust_channel | release                                     |
| allocator          | standard                                    |
| features           | default, sqlite, static-link-openssl, trash |
| installed_plugins  | query 0.103.0                               |

### PR DESCRIPTION
**Pull request by jjflash95**
Fixes #15440 

# Description
Replaces ListStream stream type from `impl Iterator` to `Peekable<impl Iterator>`, this allows checking for empty streams and treating them as empty values
 
Example:
```
# previously
$ glob ? | default -e void
> # empty list

$ echo '' | default -e void
> void

####################

# now
$ glob ? | default -e void
> void

$ echo '' | default -e void
> void
```

# User-Facing Changes

empty list streams will behave as `nothing` values when testing for emptiness

# Tests + Formatting

- Add 2 tests
- clippy OK
- fmt OK

# After Submitting

### CODE REVIEW

File: crates/nu-protocol/src/pipeline/list_stream.rs [hunk 1]
```diff
@@ -3,17 +3,18 @@
...
+pub type PeekableValueIterator = Peekable<ValueIterator>;
 
 /// A potentially infinite, interruptible stream of [`Value`]s.
 ///
 /// In practice, a "stream" here means anything which can be iterated and produces Values.
 /// Like other iterators in Rust, observing values from this stream will drain the items
 /// as you view them and the stream cannot be replayed.
 pub struct ListStream {
-    stream: ValueIterator,
+    stream: RefCell<PeekableValueIterator>,
```
Comment (jjflash95) [inline crates/nu-protocol/src/pipeline/list_stream.rs:17]: This was added for convenience, checking for emptiness won't require a &mut reference, can be remove though

**Comment by NotTheDr01ds** [comment]
@zhiburt Can you take a look at this when you get a chance since it's in `table`?

File: crates/nu-command/tests/commands/glob.rs [hunk 2]
```diff
@@ -40,6 +40,42 @@ fn nonempty_glob_lists_matching_paths() {
     })
 }
 
+#[test]
+fn empty_glob_list_matches_default() {
```
Comment (sholderbach) [inline crates/nu-command/tests/commands/glob.rs:44]: Clever use of `glob` as a command to generate a `ListStream` (I don't think we have any command that truly guarantees that so could change if we bork something with the implementation). I think for self-documentation purposes of what you want to assert here I would be inclined to place this test under `default` and explicitly mention that is related to the behavior on list *streams*.

**Review by sholderbach — COMMENTED** [review]
My gut feeling as this just addresses a semantic gap in `default` at the moment, changing the internals of `ListStream` feels overkill. Not just the `RefCell` but also every `ListStream` consumer could potentially pay some minimal overhead from remaining `Peekable` code that doesn't get eliminated.

I get that the symmetry to `Value` would be pretty, having a general `is_empty` helper. (If we find that a ton of commands should do this check then I would be inclined to consider this solution)

If it is not too much to implement, I would prefer the `Peekable` living in just `default`'s implementation.

File: crates/nu-command/src/filters/default.rs [hunk 3]
```diff
@@ -146,6 +147,17 @@ fn default(
             && matches!(input, PipelineData::Value(ref value, _) if value.is_empty()))
     {
         Ok(value.into_pipeline_data())
+    } else if let PipelineData::ListStream(ls, metadata) = input {
+        let span = ls.span();
+        let mut stream = ls.into_inner().peekable();
+        if stream.peek().is_none() {
+            return Ok(value.into_pipeline_data());
+        }
+
```
Comment (jjflash95) [inline crates/nu-command/src/filters/default.rs:156]: don't know if this comment is necessary, I know it would help ME understand why we are using `Signals::empty`

Comment (sholderbach) [reply crates/nu-command/src/filters/default.rs:156]: Sounds good to me, I don't really have a good mental model about which iterators are checked either.

File: crates/nu-command/src/filters/default.rs [hunk 4]
```diff
@@ -146,6 +147,17 @@ fn default(
             && matches!(input, PipelineData::Value(ref value, _) if value.is_empty()))
     {
         Ok(value.into_pipeline_data())
+    } else if let PipelineData::ListStream(ls, metadata) = input {
+        let span = ls.span();
+        let mut stream = ls.into_inner().peekable();
+        if stream.peek().is_none() {
+            return Ok(value.into_pipeline_data());
```
Comment (sholderbach) [inline crates/nu-command/src/filters/default.rs:154]: We only need to do the empty ListStream replacement when `--empty` is passed (as represented by `default_when_empty`)

**Review by sholderbach — CHANGES_REQUESTED** [review]
Thanks for iterating on this, the changes look good with the exception of a small snag. We only need to do the check for emptiness when `default --empty` is used. In the basic mode `default` should not replace empty collections.

Thanks for the tests!

File: crates/nu-command/src/filters/default.rs [hunk 5]
```diff
@@ -146,6 +147,20 @@ fn default(
...
+            unreachable!()
+        };
+        let span = ls.span();
+        let mut stream = ls.into_inner().peekable();
+        if stream.peek().is_none() {
+            return Ok(value.into_pipeline_data());
+        }
+
+        // stream's internal state already preserves the original signals config, so if this
+        // Signals::empty list stream gets interrupted it will be catched by the underlying iterator
```
Comment (sholderbach) [inline crates/nu-command/src/filters/default.rs:161]: This typo fix and a `cargo fmt --all` and we should be good to go :)

```suggestion
        // Signals::empty list stream gets interrupted it will be caught by the underlying iterator
```

File: crates/nu-command/src/filters/default.rs [hunk 6]
```diff
@@ -146,6 +147,20 @@ fn default(
             && matches!(input, PipelineData::Value(ref value, _) if value.is_empty()))
     {
         Ok(value.into_pipeline_data())
+    } else if default_when_empty && matches!(input, PipelineData::ListStream(..)) {
+        let PipelineData::ListStream(ls, metadata) = input else {
+            unreachable!()
```
Comment (sholderbach) [inline crates/nu-command/src/filters/default.rs:152]: Yearning for if-let chains...

Apparently reached the end of the FCP today

**Review by sholderbach — APPROVED** [review]

File: crates/nu-command/src/filters/default.rs (hunk 6 above)
Comment (jjflash95) [reply crates/nu-command/src/filters/default.rs:152]: true

**Comment by jjflash95** [comment]
Good catch on the empty flag, I kinda forgot about it while moving stuff around
