### PR TITLE
upserting data of a cellpath that doesn't exist into a record creates the cellpath

### LINKED ISSUE #9254: Delayed recognition of update to record (?!)
### Describe the bug

I'm not going to try to characterize what's going on here.  But it sure looks like non-euclidean geometry!

### How to reproduce

```
〉mut a = {}
〉$a
╭──────────────╮
│ empty record │
╰──────────────╯
```
```
〉$a.b.c.d = 99
〉$a
╭──────────────╮
│ empty record │
╰──────────────╯

# Observation1: A bit suprising, I was expecting an error about missing field `b`,
# was kinda hoping I'd get all the intermediate levels created automagically.  But I get neither!
```
```
〉$a.b
Error: nu::shell::column_not_found

  × Cannot find column
   ╭─[entry #23:1:1]
 1 │ $a.b
   · ─┬ ┬
   ·  │ ╰── cannot find column 'b'
   ·  ╰── value originates here
   ╰────

# OK, column `b` is really not there.  Pushing on...
```
```
〉$a.b = "c"
〉$a
╭───┬───────────────────╮
│ b │ {record 0 fields} │
╰───┴───────────────────╯

# Observation2: Hmm, assigned a string.  Why is `.b` any kind of record?
```
```
〉$a.b.c = "d"
〉$a
╭───┬────────────────────╮
│   │ ╭───┬────────────╮ │
│ b │ │   │ ╭───┬────╮ │ │
│   │ │ c │ │ d │ 99 │ │ │
│   │ │   │ ╰───┴────╯ │ │
│   │ ╰───┴────────────╯ │
╰───┴────────────────────╯

# Observation3: hey, presto! my original assignment was executed after all!
```
```
〉$a.b.c = "e"
〉$a
╭───┬───────────╮
│   │ ╭───┬───╮ │
│ b │ │ c │ e │ │
│   │ ╰───┴───╯ │
╰───┴───────────╯

# Observation4: reality has reasserted its dominance

```

### Expected behavior

At Observation1, I expected an error, something along the lines of `column b not found`.
At Observation2, I expected $a.b to be string "c", not an empty record.
At Observation3, (shrug)
At Observation4, I saw what I expected to see.

### Screenshots

_No response_

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.80.1                                   |
| branch             | fix_9229_v2                              |
| commit_hash        | b4216f8a9706fb1d5ae63ef940b33682479bb4a6 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)      |
| rust_channel       | 1.67.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)      |
| build_time         | 2023-05-19 11:19:00 -04:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by merelymyself**
# Description
Fixes #9254.

# User-Facing Changes
upserting data of a cellpath that doesn't exist into a record now creates the cellpath.

# Tests + Formatting

```
~/CodingProjects/nushell> mut a = {}                                                                       
~/CodingProjects/nushell> $a.b.c = 99                                                                            
~/CodingProjects/nushell> $a                                                                                    
╭───┬────────────╮
│   │ ╭───┬────╮ │
│ b │ │ c │ 99 │ │
│   │ ╰───┴────╯ │
╰───┴────────────╯
```

# After Submitting

### CODE REVIEW

**Review by amtoine — APPROVED** [review]
wow :open_mouth: 

this is amazing and will definitely solve a bunch of problems and ugly mutations, especially with `$env`.
and look at the small diff!!

love it :sparkles:

File: crates/nu-command/tests/commands/mut_.rs [hunk 1]
```diff
@@ -171,3 +171,15 @@ fn mut_path_operator_assign() {
...
 }
+
+#[test]
+fn mut_records_update_properly() {
+    let actual = nu!(
+        cwd: ".", pipeline(
+        r#"
+        mut a = {}; $a.b.c = 100; $a.b.c
+        "#
+    ));
```
Comment (amtoine) [inline crates/nu-command/tests/commands/mut_.rs:182]: oh just one thing, sorry...

i think we do not need `cwd` nor `r#` here :wink:

**Review by amtoine — CHANGES_REQUESTED** [review]

**Review by amtoine — APPROVED** [review]
this is really cool, thanks @merelymyself

can't wait to get rid of my ugly
```bash
$env.config = ($env.config? | default {})
$env.config.color_config = (...)
```
:star_struck:
