### PR TITLE
Replace `ExternalStream` with new `ByteStream` type

### LINKED ISSUE #7017: Why `RawStream` contains an `Iterator` of `Vec<u8>` instead of `std::io::Read`?
### Question

`RawStream` is an iterator of heap-allocated chunks of bytes as opposed to `std::io::Read` which may harm performance in some cases. The only reason that comes to my mind is having a different error type but that could've been implemented by having a custom `Read` trait that's a copy of `std::io::Read` except for error bytes.

Is there any other reason I don' see? If not how hard would it be to refactor it?

### Additional context and details

I started working on optimizing json objects parsing to not collect the whole stream into string as mentioned in https://github.com/nushell/nushell/issues/6979#issuecomment-1304582457 and assumed it implements `Read` which is not the case. I even implemented a bunch of optimizations aiming at significantly reducing heap allocations. :man_facepalming: I'm now wondering how to proceed.

### LINKED ISSUE #10763: Piping is extremely slow
### Describe the bug

Piping when in nushell can be an order of magnitude slower than an equivalent piped command in `bash`. High-throughput commands on my machine suffer a slowdown of up to 50x when compared to similar redirects in `bash` or raw IO (for example redirecting to file vs. a binary that writes to the file itself).

### How to reproduce

I used this Rust code to perform the measurements:

```rust
use std::io::{stdout, Write};
use std::time::{Duration, Instant};

const BUF_SIZE: usize = 8 * 1024;
const WRITE_CNT: usize = 8 * 1024;
const BYTES_LEN: usize = BUF_SIZE * WRITE_CNT;
const SAMPLES: usize = 15;

const BUF: [u8; BUF_SIZE] = [0xFF; BUF_SIZE];

fn main() {
    let mut stdout = stdout().lock();

    let mut samples: Vec<_> = (0..SAMPLES).map(|_| run(&mut stdout)).collect();
    samples.sort();

    let min = samples[0];
    let max = samples[SAMPLES - 1];
    let med = samples[SAMPLES / 2];

    eprintln!("Elapsed: [{min:?}, {med:?}, {max:?}]");
    eprintln!(
        "Throughput: [{:.2} MB/s, {:.2} MB/s, {:.2} MB/s]",
        thpt(min),
        thpt(med),
        thpt(max)
    );
}

fn run<W: Write>(out: &mut W) -> Duration {
    let start = Instant::now();
    for _ in 0..WRITE_CNT {
        out.write_all(&BUF).unwrap();
    }

    start.elapsed()
}

fn thpt(duration: Duration) -> f64 {
    (BYTES_LEN as f64 / 1000000.0) / duration.as_secs_f64()
}
```

It writes 64MBs of bytes in buffers of 8KB into its standard output and measures the time it takes. We measure 15 samples to remove spurious results, and print min, median, and max results/

The overhead is most visible if the receiver of the output has high throughput &ndash; `/dev/null` is hard to beat for that.

### nushell

```console
$ ./target/release/out-thpt out> /dev/null
Elapsed: [275.3485ms, 364.661123ms, 416.359778ms]
Throughput: [243.72 MB/s, 184.03 MB/s, 161.18 MB/s]
```

### bash

```console
$ ./target/release/out-thpt > /dev/null
Elapsed: [3.679879ms, 5.63634ms, 11.30741ms]
Throughput: [18236.70 MB/s, 11906.46 MB/s, 5934.95 MB/s]
```

When writing to files the same effect is seen, but with a smaller difference:

### nushell

```console
$ ./target/release/out-thpt | save out.txt -f
Elapsed: [280.598264ms, 298.941421ms, 538.216298ms]
Throughput: [239.16 MB/s, 224.49 MB/s, 124.69 MB/s]
```

### bash

```console
$ ./target/release/out-thpt > out.txt
Elapsed: [81.644023ms, 82.946274ms, 85.552982ms]
Throughput: [821.97 MB/s, 809.06 MB/s, 784.41 MB/s]
```

Another, more useful example: piping the results to a high-throughput tool like ripgrep:

### nushell

```console
$ ./target/release/out-thpt | rg 'x'
Elapsed: [190.961775ms, 278.648481ms, 652.648382ms]
Throughput: [351.43 MB/s, 240.84 MB/s, 102.83 MB/s]
```

### bash

```console
$ ./target/release/out-thpt | rg 'x'
Elapsed: [24.366165ms, 62.707143ms, 381.635499ms]
Throughput: [2754.18 MB/s, 1070.19 MB/s, 175.85 MB/s]
```

### Expected behavior

I would expect `nu` to perhaps have _some_ overhead on piping, but the level of 5x, 10x, 100x slowdown is _very_ harsh when working with large datasets.

It also creates a very unexpected slowdown when writing to file. It's suddenly much worse to use the shell's redirect to a file than a commands builtin file output (if such exists).

### Screenshots

_No response_

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.83.1                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.71.0 (8ede3aae2 2023-07-12) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.71.0 (cfd3bbd8f 2023-06-08) |
| build_time         | 2023-08-03 13:53:50 +01:00          |
| build_rust_channel | release                             |
| allocator          | standard                            |
| features           | default, sqlite, trash, which, zip  |
| installed_plugins  |                                     |

### Additional context

_No response_

### LINKED ISSUE #12369: Error in `complete` exit_code field instead of numerical exit code
### Describe the bug

When running with an external command which exits with, eg., a SIGABRT,  `complete` contains an internal error:

```
$ ./a.out | complete
SIGABRT: child process './a.out' core dumped
╭───────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ stdout    │                                                                                                                    │
│ stderr    │                                                                                                                    │
│ exit_code │ ExternalCommand { label: "core dumped", help: "SIGABRT: child process './a.out' core dumped", span: Span { start:  │
│           │ 141774, end: 141781 } }                                                                                            │
╰───────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

### How to reproduce

1. Run a program which throws a SIGABRT (may happen for other errors as well?)
```c
#include <signal.h>

int main() {
    raise(SIGABRT);
}
```
2. Run the executable and pipeline into complete, eg. `./a.out | complete`

### Expected behavior

To provide a numerical exit code

### Screenshots

_No response_

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.92.0                                   |
| branch             | makepkg                                  |
| commit_hash        | c3428b891a6ca733fd976971d2f440b5f41cd082 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.75.0 (1d8b05cdd 2023-11-20)      |
| build_time         | 2024-04-02 18:50:27 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | dataframe, default, sqlite, trash, which |
| installed_plugins  | clipboard                                |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by IanManske**
# Description
This PR introduces a `ByteStream` type which is a `Read`-able stream of bytes. Internally, it has an enum over three different byte stream sources:
```rust
pub enum ByteStreamSource {
    Read(Box<dyn Read + Send + 'static>),
    File(File),
    Child(ChildProcess),
}
```

This is in comparison to the current `RawStream` type, which is an `Iterator<Item = Vec<u8>>` and has to allocate for each read chunk.

Currently, `PipelineData::ExternalStream` serves a weird dual role where it is either external command output or a wrapper around `RawStream`. `ByteStream` makes this distinction more clear (via `ByteStreamSource`) and replaces `PipelineData::ExternalStream` in this PR:
```rust
pub enum PipelineData {
    Empty,
    Value(Value, Option<PipelineMetadata>),
    ListStream(ListStream, Option<PipelineMetadata>),
    ByteStream(ByteStream, Option<PipelineMetadata>),
}
```

The PR is relatively large, but a decent amount of it is just repetitive changes.

This PR fixes #7017, fixes #10763, and fixes #12369.

This PR also improves performance when piping external commands. Nushell should, in most cases, have competitive pipeline throughput compared to, e.g., bash.
| Command                                            | Before (MB/s) | After (MB/s) | Bash (MB/s) |
| -------------------------------------------------- | -------------:| ------------:| -----------:|
| `throughput \| rg 'x'`                             | 3059          | 3744         | 3739        |
| `throughput \| nu --testbin relay o> /dev/null`    | 3508          | 8087         | 8136        |

# User-Facing Changes
- This is a breaking change for the plugin communication protocol, because the `ExternalStreamInfo` was replaced with `ByteStreamInfo`. Plugins now only have to deal with a single input stream, as opposed to the previous three streams: stdout, stderr, and exit code.
- The output of `describe` has been changed for external/byte streams.
- Temporary breaking change: `bytes starts-with` no longer works with byte streams. This is to keep the PR smaller, and `bytes ends-with` already does not work on byte streams.
- If a process core dumped, then instead of having a `Value::Error` in the `exit_code` column of the output returned from `complete`, it now is a `Value::Int` with the negation of the signal number.

# After Submitting
- Update docs and book as necessary
- Release notes (e.g., plugin protocol changes)
- Adapt/convert commands to work with byte streams (high priority is `str length`, `bytes starts-with`, and maybe `bytes ends-with`).
- Refactor the `tee` code, Devyn has already done some work on this.

### CODE REVIEW

**Comment by sholderbach** [comment]
That is an impressive chunk of work and a nice improvement!
Resolving those incorrect buffering bugs is long overdue.

Before we run ahead just looking at the streaming side we need to talk about the error changes, to ensure we don't break our execution semantics in unintended ways. 

- What is the motivation for turning the exit codes into `ShellError` variants? (The existing separate `ListStream` certainly feels dirty, but the semantics change in major ways if it is an explicit error passing around but we have to look at all the relevant places, and I haven't gotten to that yet)
- Can they be isolated into a separate PR in an easy way or will this become a furball here?
- As externals are built in the world where bash is run without `set -e` exit codes are non-zero in ways that may not be errors in their logic. We treat them as such in complex executions but have to tolerate them in individual repl executions for example. See 
@sophiajt 's blog [post on examples](https://www.sophiajt.com/exit-codes/)
- Destructuring `ShellErrors` in `catch` is still not smoothly possible, how would this affect the UX?


>  After Submitting
> 
>     * Figure out end line trimming

What is up here? Is there a breakage we need to resolve before merging?

**Comment by WindSoilder** [comment]
I have the same concern about turning the exit codes into `ShellError` variants.
I remember @elferherrera and @sophiajt vote against it before: https://github.com/nushell/nushell/pull/6079#issuecomment-1189168717
https://github.com/nushell/nushell/pull/6079#issuecomment-1189518033

File: crates/nu-protocol/src/io/lines.rs [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+                Some(Ok(line)) => Some(Ok(line)),
+                Some(Err(err)) => Some(Err(err.into_spanned(self.span).into())),
+                None => None,
+            }
+        }
+    }
+}
+
+pub struct Values<R: Read> {
+    lines: ByteLines<R>,
```
Comment (devyn) [inline crates/nu-protocol/src/io/lines.rs:78]: This is something I've already changed on my branch, but just so you know, I don't think `Values` should really be lines. I think it's currently just whatever the buffers coming in are, and it's additionally split up by lines to kind of do a pseudo-line-buffering, but that's a source of bugs.

Changing it to always be the full line is okay for text data, but not ideal for binary data because the chunks are all going to be random sizes / potentially the whole file because you never really know when you'll get a `\n` character.

If you want to check out my branch instead, I made it basically use `BufRead::fill_buf` to get whatever data is pending and try to create valid UTF-8 buffers when in string mode. It's quite obviously different from the output of `lines`, so that should help to force anyone who actually wants lines to use that.

File: crates/nu-protocol/src/io/lines.rs [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+        }
+    }
+
+    pub fn span(&self) -> Span {
+        self.span
+    }
+}
+
+impl<R: Read> Iterator for Lines<R> {
+    type Item = Result<Vec<u8>, ShellError>;
```
Comment (devyn) [inline crates/nu-protocol/src/io/lines.rs:62]: If you're dealing with lines, you're basically always dealing with UTF-8 text anyway (other encodings would potentially have different newline sequences), so in my case I rolled the parsing logic into this iterator and just had it spit out strings. I left `ByteLines` though in case someone really does want that.

File: crates/nu-command/src/filters/lines.rs [hunk 3]
```diff
@@ -76,27 +110,15 @@ impl Command for Lines {
...
-                    // Propagate existing errors
-                    Value::Error { error, .. } => Err(*error),
-                    _ => Err(ShellError::OnlySupportsThisInputType {
-                        exp_input_type: "string or raw data".into(),
-                        wrong_type: val.get_type().to_string(),
-                        dst_span: head,
-                        src_span: val.span(),
-                    }),
+            PipelineData::ByteStream(stream, ..) => {
+                if let Some(lines) = stream.values() {
```
Comment (devyn) [inline crates/nu-command/src/filters/lines.rs:114]: Just in case you do decide to change `Values`, keep in mind this needs to change too

File: crates/nu-cmd-lang/src/core_commands/do_.rs [hunk 4]
```diff
@@ -37,11 +36,6 @@ impl Command for Do {
                 "ignore external program errors as the closure runs",
                 Some('p'),
             )
-            .switch(
```
Comment (devyn) [inline crates/nu-cmd-lang/src/core_commands/do_.rs:40]: In case we do decide to keep the exit codes as `ShellError`, I think you need to change this to a deprecated flag rather than removing it. I have `do -c` in my config file and it fails to parse

File: crates/nu-plugin-protocol/src/lib.rs [hunk 5]
```diff
@@ -82,32 +82,20 @@ pub enum PipelineDataHeader {
...
-    /// Initiate [`nu_protocol::PipelineData::ExternalStream`].
+    /// Initiate [`nu_protocol::PipelineData::ByteStream`].
     ///
     /// Items are sent via [`StreamData`]
-    ExternalStream(ExternalStreamInfo),
+    ByteStream(ByteStreamInfo),
 }
 
 impl PipelineDataHeader {
     /// Return a list of stream IDs embedded in the header
```
Comment (devyn) [inline crates/nu-plugin-protocol/src/lib.rs:92]:
```suggestion
    /// Return the stream ID, if any, embedded in the header
```

File: crates/nu-protocol/src/io/read_iterator.rs
Comment (devyn) [inline crates/nu-protocol/src/io/read_iterator.rs:1]: Because these are quite commonly used with `ByteStream`, I'm thinking of adding something like `ByteStream::from_iter()` and `ByteStream::from_try_iter()` (?) so that you don't have to construct these manually. Thoughts?

File: crates/nu-cmd-lang/src/core_commands/describe.rs [hunk 6]
```diff
@@ -162,59 +162,30 @@ fn run(
...
+                        "type" => Value::string("byte stream", head),
+                        "origin" => Value::string(origin, head),
                         "metadata" => metadata_to_value(metadata, head),
-                    ),
+                    },
                     head,
                 )
             } else {
-                Value::string("raw input", head)
+                stream.drain()?;
```
Comment (devyn) [inline crates/nu-cmd-lang/src/core_commands/describe.rs:184]: probably shouldn't drain if `no_collect`

File: crates/nu-protocol/src/io/read_iterator.rs
Comment (IanManske) [reply crates/nu-protocol/src/io/read_iterator.rs:1]: Oh yeah, that's a good idea!

**Comment by IanManske** [comment]
> Can they be isolated into a separate PR in an easy way or will this become a furball here?

Actually, it looks like it might not be too bad to separate it.

>  > *Figure out end line trimming
>
> What is up here? Is there a breakage we need to resolve before merging?

Whoops, that's a TODO, not sure why I put it under after submitting.

File: crates/nu-protocol/src/io/lines.rs (hunk 1 above)
Comment (IanManske) [reply crates/nu-protocol/src/io/lines.rs:78]: Hmm, yeah the `fill_buf` approach does sound better. Ideally, `values` should not be needed / should not exist on `ByteStream`, and commands would just use the reader directly (or maybe `lines`). Unfortunately, we have a bunch of commands that don't do that and/or use one of the `PipelineData` methods (`map`, `filter`, `flat_map`, `into_iter_strict`, the `IntoIterator` trait, etc.).

**Comment by IanManske** [comment]
Ok, I've split off #12782 and #12799 to make this PR slightly smaller. I've also removed the exit code changes. Otherwise, I just have to add doc comments and maybe some tests.

**Comment by devyn** [comment]
I just gave it a test and while the error is gone and `complete` returns exit codes, I don't seem to be seeing `LAST_EXIT_CODE` set even for very simple commands on the prompt.

File: crates/nu-plugin-core/src/interface/mod.rs [hunk 7]
```diff
@@ -185,31 +180,10 @@ pub trait InterfaceManager {
...
-                                .read_stream(list_info.id, self.get_interface())
-                                .map(|reader| ListStream::new(reader, info.span, ctrlc.cloned()))
-                        })
-                        .transpose()?,
-                    span: info.span,
-                    metadata: None,
-                    trim_end_newline: info.trim_end_newline,
-                }
+                let reader = handle.read_stream(info.id, self.get_interface())?;
+                ByteStream::from_result_iter(reader, info.span, None).into()
```
Comment (devyn) [inline crates/nu-plugin-core/src/interface/mod.rs:186]: In this case, `from_result_iter()` does need to take `ctrlc`, because the underlying stream is not checking it.

**Comment by IanManske** [comment]
Ok, I think this should be mostly ready for review.

Also, I stole some of your tests @devyn :P

**Comment by devyn** [comment]
I'll have a look again, then. Thanks for all of your hard work!

**Review by WindSoilder — COMMENTED** [review]
Thanks for the improvement!  Just leaves some thought about stderr consumer thread.

**Comment by sholderbach** [comment]
Is #12369 still part of this after removing the main error breaking changes?

**Comment by IanManske** [comment]
Yes, this PR still fixes #12369. If there is no exit code (i.e., the process was terminated via signal), then `complete` will now report the negation of the signal number in `exit_code`.

File: crates/nu-cmd-extra/tests/commands/bytes/starts_with.rs [hunk 8]
```diff
@@ -19,102 +19,102 @@ fn basic_string_fails() {
...
-    assert_eq!(
-        actual.err, "",
-        "invocation failed. command line limit likely reached"
-    );
-    assert_eq!(actual.out, "false");
-}
+// #[test]
+// fn short_stream_binary() {
+//     let actual = nu!(r#"
+//             nu --testbin repeater (0x[01]) 5 | bytes starts-with 0x[010101]
```
Comment (sholderbach) [inline crates/nu-cmd-extra/tests/commands/bytes/starts_with.rs:25]: Pin: commented out tests

**Comment by stormasm** [comment]
@devyn so we agreed in the core team meeting today that once you give the green light and have reviewed the PR we will go ahead and land it...

Thank you kindly for doing this ! 😄

File: crates/nu-command/src/bytes/starts_with.rs [hunk 9]
```diff
@@ -60,63 +60,13 @@ impl Command for BytesStartsWith {
...
-                stdout: Some(stream),
-                span,
-                ..
-            } => {
-                let mut i = 0;
-
-                for item in stream {
-                    let byte_slice = match &item {
-                        // String and binary data are valid byte patterns
-                        Ok(Value::String { val, .. }) => val.as_bytes(),
```
Comment (devyn) [inline crates/nu-command/src/bytes/starts_with.rs:75]: Removing this will be a breaking change, as this worked before:

```nushell
^echo foo | bytes starts-with ("foo" | into binary)
```

In general, I think untyped byte streams should be able to be treated as binary

File: crates/nu-command/src/filesystem/save.rs [hunk 10]
```diff
@@ -121,40 +119,102 @@ impl Command for Save {
...
-                            h.join().map_err(|err| ShellError::ExternalCommand {
-                                label: "Fail to receive external commands stderr message"
-                                    .to_string(),
-                                help: format!("{err:?}"),
-                                span,
-                            })??;
+                // https://github.com/nushell/nushell/pull/9377 contains the reason
+                // for not using BufWriter<File>
+                //
+                // TODO: flag to specify buffered (BufWriter), line buffered (LineWriter), or no buffering (File).
```
Comment (devyn) [inline crates/nu-command/src/filesystem/save.rs:125]: I'm not sure this will ever be necessary, because the input stream is generally buffered in some way, even if by the command that produced it. If someone knows they want to use bigger buffers, it might be better to provide a command to adapt the stream with `read_exact()` or `read_until()` calls to ensure the desired chunking behaviour. And of course it should already be possible to do `| lines | save` if you definitely want line buffering.

I like this behaviour though, it means that the output of an external command gets written to file with the flushing behaviour it was intended to have, which is particularly good if saving to something like a FIFO where the interactivity actually matters.

**Review by devyn — COMMENTED** [review]
Looks good. I found one potential issue with `bytes starts-with`. A lot of the files changed are just `into_value()` related, with that being a `Result` now, so this isn't quite as big as it looks.

Didn't have any issues running it yet, and exit code is definitely working now. I'm glad you changed the `each` behaviour to `Chunks` and got rid of implicit line buffering.

Great stuff!

File: crates/nu-command/src/bytes/starts_with.rs (hunk 9 above)
Comment (IanManske) [reply crates/nu-command/src/bytes/starts_with.rs:75]: That was me being ~~lazy~~ making the PR smaller :smile:. After this, I intend to open another PR to restore that command and also make `bytes ends-with` support byte streams properly.

File: crates/nu-command/src/filesystem/save.rs (hunk 10 above)
Comment (IanManske) [reply crates/nu-command/src/filesystem/save.rs:125]: Oh yeah, that's a good observation! There might be an argument to add the flags for performance reasons (e.g., to avoid the allocations), but it's probably not worth it / it won't make a noticeable difference.

**Comment by IanManske** [comment]
Thanks for taking the time to review this @devyn!

**Comment by stormasm** [comment]
@IanManske I am planning on landing this PR in the morning --- its 10pm in Oregon now...

Unless someone beats me to it...

I checked out your branch and ran all of the tests and it looks good to me...

I will await you giving me the green light to let me know if its now ready to go based on Devyn's feedback it looks good to me...

Thanks for all of your hard work on this PR...

**Comment by IanManske** [comment]
Sounds good, feel free to land it whenever @stormasm. Thanks!

**Comment by stormasm** [comment]
@IanManske cool !  thanks for giving the green light 👍 
I will monitor and make sure I don't see any issues now that its landed....

**Comment by rgwood** [comment]
Wow, it’s great to see thoughtful architectural changes like this. Big thanks to Ian and everyone who reviewed this.

**Comment by YizhePKU** [comment]
After wrapping a child process into a `ByteStream`, how do I read from its stderr? The public APIs all seem to be reading from stdout.

I'm currently doing this, but it feels awkward:

```rust
if let PipelineData::ByteStream(byte_stream, ..) = pipeline_data {
    if let ByteStreamSource::Child(child) = byte_stream.source() {
        if let Some(stderr) = child.stderr {
            stderr.read(&mut buf);
        }
    }
}
```

**Comment by YizhePKU** [comment]
```rust
impl ByteStream {
    pub fn write_to(self, dest: &mut impl Write) -> Result<Option<ExitStatus>, ShellError> {
       // ...
    }
}
```

Generic reader/writer functions should take `R: Read` and `W: Write` by value ([Rust API Guidelines](https://rust-lang.github.io/api-guidelines/interoperability.html#c-rw-value)).

**Comment by IanManske** [comment]
> After wrapping a child process into a ByteStream, how do I read from its stderr? The public APIs all seem to be reading from stdout.

This is intentionally verbose. In fact, I should have maybe made it an unsafe API. Reading from `stderr` if `stdout` is present and vice versa could create a deadlock (unless, e.g., a separate thread is used to read `stdout` at the same time). In the vast majority of cases, the child process should not have a `stderr`. Commands that set the `stderr` destination to `OutDest::Capture` make sure to read `stdout` and `stderr` on separate threads. To "read" both `stdout` and `stderr` you can use `ChildProcess::wait_with_output`. Hope this helps.

> Generic reader/writer functions should take `R: Read` and `W: Write` by value ([Rust API Guidelines](https://rust-lang.github.io/api-guidelines/interoperability.html#c-rw-value)).

Oh, good to know. I guess `io::copy` was an unfortunate oversight?

**Comment by YizhePKU** [comment]
> This is intentionally verbose. In fact, I should have maybe made it an unsafe API.

Rust's safety guarantees doesn't cover deadlocks, so it's probably fine.

> I guess io::copy was an unfortunate oversight?

Unfortunate indeed. The Rust team [tried to change it](https://github.com/rust-lang/rust/issues/105643), but couldn't due to API breakage.

**Comment by Kixunil** [comment]
> Generic reader/writer functions should take `R: Read` and `W: Write` by value ([Rust API Guidelines](https://rust-lang.github.io/api-guidelines/interoperability.html#c-rw-value)).

FYI this tends to lead to bigger binary sizes because people are using both variants. If you pass by mut ref they will make owned types into references.
