### PR TITLE
fix(parser): missing span of short flag that requires a value

### LINKED ISSUE #16375: Flag completion fails at `table -<tab>`
### Describe the bug

`ls -<tab>` works while `table -<tab>` doesn't.

Problem rooted at the parser:

```nushell
> ast -f "ls -a"

╭─content─┬───────shape────────┬─────span──────╮
│ ls      │ shape_internalcall │ ╭───────┬───╮ │
│         │                    │ │ start │ 0 │ │
│         │                    │ │ end   │ 2 │ │
│         │                    │ ╰───────┴───╯ │
│ -a      │ shape_flag         │ ╭───────┬───╮ │
│         │                    │ │ start │ 3 │ │
│         │                    │ │ end   │ 5 │ │
│         │                    │ ╰───────┴───╯ │
╰─────────┴────────────────────┴───────────────╯

> ast -f "table -a"

╭─content─┬───────shape────────┬─────span──────╮
│ table   │ shape_internalcall │ ╭───────┬───╮ │
│         │                    │ │ start │ 0 │ │
│         │                    │ │ end   │ 5 │ │
│         │                    │ ╰───────┴───╯ │
╰─────────┴────────────────────┴───────────────╯

> ast -f "table --abbreviated"

╭────content────┬───────shape────────┬──────span──────╮
│ table         │ shape_internalcall │ ╭───────┬───╮  │
│               │                    │ │ start │ 0 │  │
│               │                    │ │ end   │ 5 │  │
│               │                    │ ╰───────┴───╯  │
│ --abbreviated │ shape_flag         │ ╭───────┬────╮ │
│               │                    │ │ start │ 6  │ │
│               │                    │ │ end   │ 19 │ │
│               │                    │ ╰───────┴────╯ │
╰───────────────┴────────────────────┴────────────────╯

```

### How to reproduce

Described in the title.

### Expected behavior

Consistent parsing results.

### Configuration

| key                  | value                                                             |
| -------------------- | ----------------------------------------------------------------- |
| version              | 0.106.1                                                           |
| major                | 0                                                                 |
| minor                | 106                                                               |
| patch                | 1                                                                 |
| branch               |                                                                   |
| commit_hash          |                                                                   |
| build_os             | macos-aarch64                                                     |
| build_target         | aarch64-apple-darwin                                              |
| rust_version         | rustc 1.88.0 (6b00bc388 2025-06-23) (built from a source tarball) |
| cargo_version        | cargo 1.88.0 (873a06493 2025-05-10)                               |
| build_time           | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel   | release                                                           |
| allocator            | standard                                                          |
| features             | default, plugin, rustls-tls, sqlite, trash-support                |
| installed_plugins    |                                                                   |
| experimental_options | example=false, reorder-cell-paths=false                           |

### PR DESCRIPTION
**Pull request by blindFS**
Fixes #16375

# Description

# User-Facing Changes

Bug fix

# Tests + Formatting

+0.5

# After Submitting

### CODE REVIEW

File: crates/nu-parser/src/parser.rs [hunk 1]
```diff
@@ -1144,7 +1144,15 @@ pub fn parse_internal_call(
                             working_set.error(ParseError::MissingFlagParam(
                                 arg_shape.to_string(),
                                 arg_span,
-                            ))
+                            ));
+                            call.add_named((
```
Comment (sholderbach) [inline crates/nu-parser/src/parser.rs:1152]: Based on the PR commit message in the blame it would be highly nebulous why one would need to inject the flag onto the call in the incomplete parse case.

Can you add a comment briefly explaingin why we need this here given our current logic.

Comment (blindFS) [reply crates/nu-parser/src/parser.rs:1152]: Sure, added links to the issue for both long/short flags
