### PR TITLE
Transpose now rejects streams with non-record values

### LINKED ISSUE #13765: `transpose` silently discards list streams
### Describe the bug

When `transpose` is passed a non-table list stream, it returns an empty list.

### How to reproduce

```Nushell
~> generate {|i=1| {out: $i, next: ($i * 2)} } | take 7 | transpose
╭────────────╮
│ empty list │
╰────────────╯
```

### Expected behavior

Throw an error, like `transpose` does for regular lists.

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.97.1                                                       |
| major              | 0                                                            |
| minor              | 97                                                           |
| patch              | 1                                                            |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06) (Alpine Linux 1.80.1-r0) |
| cargo_version      | cargo 1.80.1 (376290515 2024-07-16)                          |
| build_time         | 2024-08-29 21:40:07 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, system-clipboard, trash                     |
| installed_plugins  | endecode 0.2.0, template 0.1.0                               |

### LINKED ISSUE #15141: start command doesn't open nvim/vim
### Describe the bug

I've set my default editors to nvim. However, when using the `start` command, nothing happens.

Example:

```sh
~> $env.EDITOR
nvim
~> $env.config.buffer_editor
nvim
~> start foo.txt
# nothing happens, terminal hangs
```

I don't know id this is an issue with `nu`, but I also checked XDG (don't know if that matters)

In ZSH:

```sh
~> xdg-open foo.txt
# file opens in nvim
```

The default:

```sh
~> xdg-mime query default text/plain
nvim.desktop
```

Thing is, `start somefile.pdf` will open a PDF in a browser etc. So it's like the only problem is with nvim/vim?

### How to reproduce

1. Set `$env.config.buffer_editor` to `"nvim"`
2. Set `$env.EDITOR` to `"nvim"`
3. Execute `start <some_text_file.txt>`

### Expected behavior

I expected `foo.txt` to be opened in `neovim`, but nothing happens.

### Configuration

~> version | transpose key value | to md --pretty
| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.102.0                                                          |
| major              | 0                                                                |
| minor              | 102                                                              |
| patch              | 0                                                                |
| branch             | makepkg                                                          |
| commit_hash        | 1aa2ed1947a0b891398558fcf4e4289849cc5a1d                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.84.1 (e71f9a9a9 2025-01-27) (Arch Linux rust 1:1.84.1-1) |
| cargo_version      | cargo 1.84.1 (66221abde 2024-11-19)                              |
| build_time         | 2025-02-05 21:56:07 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | default, sqlite, trash                                           |
| installed_plugins  |                                                                  |

### PR DESCRIPTION
**Pull request by cosineblast**
# Description

Closes #13765

Transpose now checks if the input consists entirely of records before doing its things, which is fine since it already `.collects()` all of its input already.

# User-Facing Changes

# Tests + Formatting

Adds `rejects_non_table_stream_input` test to cover regressions.

# After Submitting

### CODE REVIEW

File: crates/nu-command/src/filters/transpose.rs [hunk 1]
```diff
@@ -182,6 +182,19 @@ pub fn transpose(
...
+
+    if let Some(non_record_value) = first_non_record_value {
+        return Err(ShellError::OnlySupportsThisInputType {
+            exp_input_type: "table or record".into(),
+            wrong_type: "list<any>".into(),
+            dst_span: call.head,
+            src_span: non_record_value.span(),
+        });
+    }
+
```
Comment (132ikl) [inline crates/nu-command/src/filters/transpose.rs:197]: could you combine this check with the iteration that appears right above so we can avoid an extra iteration?

**Review by 132ikl — CHANGES_REQUESTED** [review]
could you combine this check with the iteration that appears right above so we can avoid an extra iteration?

File: crates/nu-command/src/filters/transpose.rs (hunk 1 above)
Comment (cosineblast) [reply crates/nu-command/src/filters/transpose.rs]: sure

**Comment by 132ikl** [comment]
thank you!
