### PR TITLE
make cd command complete only folders

### LINKED ISSUE #2370: cd should only autocomplete folders
**Describe the bug**
Currently the `cd` command autocompletes all files and directories in the working directory. However, it should only autocomplete folders, as those are the only useful arguments for `cd`.

**To Reproduce**
1. `mkdir folder`
2. `touch file`
3. `cd f<tab>`

**Expected behavior**
`cd` should autocomplete with `cd folder`. Instead on double-tab, it shows `Display all 2 possibilities? (y or n)`.

### PR DESCRIPTION
**Pull request by gorogoroumaru**
fix #2370 

Currently the cd command autocompletes all files and directories in the working directory.
However, it should only autocomplete folders.
I removed filenames from completion results when we use cd command.

### CODE REVIEW

**Comment by jonathandturner** [comment]
Looks like some of the clippy lints are giving an error during the CI tests:

```
error: unneeded `return` statement
  --> crates/nu-cli/src/shell/completer.rs:80:5
   |
80 |     return result;
   |     ^^^^^^^^^^^^^^ help: remove `return`: `result`
   |
   = note: `-D clippy::needless-return` implied by `-D warnings`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_return
```

**Comment by gorogoroumaru** [comment]
Thanks!
I applied your suggested change.

File: crates/nu-cli/src/shell/completer.rs [hunk 1]
```diff
@@ -47,7 +48,12 @@ impl NuCompleter {
                         LocationType::Argument(_cmd, _arg_name) => {
                             // TODO use cmd and arg_name to narrow things down further
                             let path_completer = crate::completion::path::Completer::new();
-                            path_completer.complete(context, partial)
+                            let completed_paths = path_completer.complete(context, partial);
+                            if &line[..2] == "cd" {
```
Comment (thegedge) [inline crates/nu-cli/src/shell/completer.rs:52]: This only handles the case where the line is `cd ...`, but you'd miss out on the opportunity to complete `cd` in other parts of the line. For example:

```
some | line | pipeline; cd <TAB>
```

But you're in luck! See that `_cmd` in the match expression above? Remove the underscore, and what you're left with is an `Option<String>` that is the command name:

```rust
match cmd.as_deref().unwrap_or("") {
  "cd" => autocomplete_only_folders(completed_paths),
  _ => completed_paths,
}
```

Comment (gorogoroumaru) [reply crates/nu-cli/src/shell/completer.rs:52]: Thanks @thegedge!
I tried your solution, but this doesn't seem to work.
When I typed "cd <tab>", cd autocompleted not only folders but also files.

Comment (thegedge) [reply crates/nu-cli/src/shell/completer.rs:52]: Ah, that's probably because I need to fix this TODO: https://github.com/nushell/nushell/blob/4828a7cd296f501d3290439a22eda16a41f6a2ca/crates/nu-cli/src/completion/engine.rs#L96-L98 haha

Let's stick with what you have, and I can return and make this change 🙂
