### PR TITLE
Fixes #1427: Prints help message with -h switch

### LINKED ISSUE #1427: `-h` on some commands doesn't work while `--help` does
**Describe the bug**
In some commands, doing `h` prints an error while --help works perfectly.

**To Reproduce**
1. type `where -h`
2. 
3. 

**Expected behavior**
`where -h` to work the same as doing `where --help`

**Configuration (please complete the following information):**
 - OS: Manjaro Linux
 - Version 0.10.0
 - Optional features - `stable`

### PR DESCRIPTION
**Pull request by rabisg0**
For some commands like `which` -h flag would trigger an error asking for
missing required parameters instead of printing the help message as it
does with --help. This commit adds a check in the command parser to
avoid that.

### CODE REVIEW

File: crates/nu-parser/src/parse_command.rs [hunk 1]
```diff
@@ -115,7 +115,10 @@ pub fn parse_command_tail(
             positional = positionals;
         }
         Err(reason) => {
-            if found_error.is_none() && !tail.source().contains("help") {
+            if found_error.is_none()
+                && !tail.source().contains("help")
+                && !tail.source().contains("h")
```
Comment (jonathandturner) [inline crates/nu-parser/src/parse_command.rs]: Would this change for anything that has an 'h' in it?

Comment (rabisg0) [reply crates/nu-parser/src/parse_command.rs]: I haven't gone through the entire parser logic tbh. Can you help me figure out a case where you think this might break?

Comment (thegedge) [reply crates/nu-parser/src/parse_command.rs]: `echo "a,b,c" | from-csv --headerless asjdasd` would be a good place to start. Right now this happens:

```
error: from-csv unexpected asjdasd
- shell:1:44
1 | echo "a,b,c" | from-csv --headerless asjdasd
  |                                      ^^^^^^^ unexpected argument (try from-csv -h)
```

`--headerless` contains a `h`, though, so it could potentially be impacted by your change.

Comment (rabisg0) [reply crates/nu-parser/src/parse_command.rs]: I see what you mean. I've updated the patch to check for named arguments instead of just string match. I think that would be a better check. Let me know what you think.

**Comment by jonathandturner** [comment]
Looks good!
