### PR TITLE
Fixed mv not throwing error when the source path was invalid

### LINKED ISSUE #1347: mv doesn't throw an error when moving a file to a non-existent folder
**Describe the bug**
When you perform an `mv` operation on a non-existent file to an existent folder it does nothing as expected, but throws no errors.

**To Reproduce**
1. Create a folder named `test`
2. `mv non-existing-file test/`

**Expected behavior**
Throw an error that indicates the source path doesn't exist

**Configuration (please complete the following information):**
 - OS: Windows 10
 - Version: 0.9.0

**Note:**
This happens both on Windows and Linux and theoretically the bug should be cross-platform.
Once the check fails on [line 562](https://github.com/nushell/nushell/blob/812a76d588bf2230b7b47fb95b46ee4addb02257/src/shell/filesystem_shell.rs#L562) it will go check if the destination exists (which it does) but do nothing to throw an error indicating that the source doesn't exist.

### PR DESCRIPTION
**Pull request by UltraWelfare**
Fixes #1347

### CODE REVIEW

File: src/shell/filesystem_shell.rs [hunk 1]
```diff
@@ -559,6 +559,14 @@ impl Shell for FilesystemShell {
             }
         };
 
+        if sources.is_empty() {
+            return Err(ShellError::labeled_error(
+                "Move aborted. Not a valid destination",
+                "not a valid destination",
```
Comment (thegedge) [inline src/shell/filesystem_shell.rs]: I think if sources is empty, the glob on line 538 matched nothing. That means the message and label should perhaps be consistent with other methods. For example:

```
❯ ls *asdljasdluasduklasd
error: Invalid File or Pattern
- shell:1:23
1 | ls *asdljasdluasduklasd
  |    ^^^^^^^^^^^^^^^^^^^^ Invalid File or Pattern
```

One other small nitpick: I would put this above line 549. That way we don't have to do unnecessary work (line 550) if there are no sources 🙂

Comment (UltraWelfare) [reply src/shell/filesystem_shell.rs]: Yep I agree with the change of the error message too.
I made the changes I hope everything is okay!

**Comment by andrasio** [comment]
@UltraWelfare Could you add another test for verifying the error gets reported correctly? Use the `Playground` helper for creating the sandboxed environment. Look also (since we don't have enough documentation yet regarding the test helpers) for tests that use the `nu_error!` macro for it.

It does the same thing as `nu!` does but it reads and gives you back what `stderr` throws from the process.
