### PR TITLE
Fix incorrect display for zero-size files

### LINKED ISSUE #1410: ls should display size when a file is empty.
**Describe the bug**
Empty files display `-` as size field instead of `0`

**To Reproduce**
1. `touch some_file.txt`
2. `ls`

**Expected behavior**
The size being 0 bytes or something.

**Configuration:**
 - macOS

### PR DESCRIPTION
**Pull request by equal-l2**
Fix #1410.

---

`Primitive::Bytes(0u64)` was used to express "Not Applicable", but `Primitive::Nothing` should be used instead.

### CODE REVIEW

File: src/data/files.rs [hunk 1]
```diff
@@ -38,7 +38,7 @@ pub(crate) fn dir_entry_dict(
 
     if full || with_symlink_targets {
         if metadata.is_dir() || metadata.is_file() {
-            dict.insert_untagged("target", UntaggedValue::bytes(0u64));
```
Comment (thegedge) [inline src/data/files.rs]: Great find 🚀
