### PR TITLE
normalize special characters in module names to allow variable access

### LINKED ISSUE #14252: Exported constants in modules with a dash in the name aren't accessible
### Describe the bug

If a module has a dash in its name, and it exports a constant, it's not possible to access the constant when importing the entire module.

### How to reproduce

```nushell
> module foo-bar { export const VALUE = 123 }
> use foo-bar
> $foo_bar.VALUE
Error: nu::parser::variable_not_found

  × Variable not found.
   ╭─[entry #9:1:1]
 1 │ $foo_bar.VALUE
   · ────┬───
   ·     ╰── variable not found. Did you mean '$foo-bar'?
   ╰────
> $foo-bar.VALUE
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
   ╭─[entry #10:1:1]
 1 │ $foo-bar.VALUE
   · ────┬───
   ·     ╰── expected valid variable name
   ╰────
```

### Expected behavior

I expected to be able to access the constant with `$foo_bar.VALUE`.

### Configuration

| key                | value                                                                                                                                                            |
| ------------------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.99.2                                                                                                                                                           |
| major              | 0                                                                                                                                                                |
| minor              | 99                                                                                                                                                               |
| patch              | 2                                                                                                                                                                |
| branch             | makepkg                                                                                                                                                          |
| commit_hash        | 8b19399b1336798197088b90dd8b6a97f4261509                                                                                                                         |
| build_os           | linux-x86_64                                                                                                                                                     |
| build_target       | x86_64-unknown-linux-gnu                                                                                                                                         |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06)                                                                                                                              |
| rust_channel       | 1.80.1-x86_64-unknown-linux-gnu                                                                                                                                  |
| cargo_version      | cargo 1.80.1 (376290515 2024-07-16)                                                                                                                              |
| build_time         | 2024-11-04 09:00:06 +00:00                                                                                                                                       |
| build_rust_channel | release                                                                                                                                                          |
| allocator          | mimalloc                                                                                                                                                         |
| features           | default, sqlite, trash                                                                                                                                           |
| installed_plugins  | custom_values 0.1.0, example 0.98.0, explore 0.99.1, formats 0.98.0, gstat 0.98.0, inc 0.98.0, jwalk 0.8.0, polars 0.98.0, query 0.98.0, stress_internals 0.98.0 |

### PR DESCRIPTION
**Pull request by sgvictorino**
Fixes #14252

# User-Facing Changes

- Special characters in module names are replaced with underscores when
  importing constants, preventing "expected valid variable name":

```nushell
> module foo-bar { export const baz = 1 }
> use foo-bar
> $foo_bar.baz
```

- "expected valid variable name" errors now include a suggestion list:

```nushell
> module foo-bar { export const baz = 1 }
> use foo-bar
> $foo-bar
Error: nu::parser::parse_mismatch_with_did_you_mean

  × Parse mismatch during operation.
   ╭─[entry #1:1:1]
 1 │ $foo-bar;
   · ────┬───
   ·     ╰── expected valid variable name. Did you mean '$foo_bar'?
   ╰────
```

### CODE REVIEW

**Comment by fdncred** [comment]
@sgvictorino is on fire 🔥!!! We appreciate all your PRs. Thanks.

**Comment by WindSoilder** [comment]
Thanks!  But there is one thing I'm not sure:
```nushell
module foo-bar { export const baz = 1 }
use foo-bar
$foo-bar.baz
```
Personally I think it's better to export use `baz` variable like `$foo_bar.baz`, to user, after using `foo-bar` and using it with `$` sign, it's using more like a variable rather than a module name.

**Comment by sholderbach** [comment]
How will this play out with `use <filename>.nu` modules?

**Comment by 132ikl** [comment]
I think normalizing would be the best option, since then it can align with typical variable name rules and can possibly catch more cases than just hyphens and the dot issue you bring up.

**Comment by WindSoilder** [comment]
Yeah, @sgvictorino can you update the code to use `$foo_bar.baz`?

File: crates/nu-protocol/src/module.rs [hunk 1]
```diff
@@ -167,7 +171,7 @@ impl Module {
                 vec![]
             } else {
                 vec![(
-                    final_name.clone(),
+                    name_override.unwrap_or(&self.const_name).to_vec(),
```
Comment (WindSoilder) [inline crates/nu-protocol/src/module.rs:174]: I don't think it's necessary to save `const_name` to a module.
We can just `normalize_variable_name` for final_name.

**Review by WindSoilder — CHANGES_REQUESTED** [review]
Sorry for a delay.  Finally I take time to review it.

And I think the solution can be easier.

File: crates/nu-protocol/src/module.rs (hunk 1 above)
Comment (WindSoilder) [reply crates/nu-protocol/src/module.rs:174]: TBH I can't find a good place either, I think it's ok to make a duplicate function in `module.rs`.

File: crates/nu-protocol/src/module.rs [hunk 2]
```diff
@@ -425,3 +425,32 @@ impl Module {
         result
     }
 }
+
+/// normalize module names for exporting as record constant
+pub fn normalize_module_name(bytes: &[u8]) -> Vec<u8> {
```
Comment (WindSoilder) [inline crates/nu-protocol/src/module.rs:430]: I think it can be private

**Review by WindSoilder — CHANGES_REQUESTED** [review]
Thanks!  Just one thing left, otherwise it looks good to me
