### PR TITLE
Check for interrupt before each IR instruction

### LINKED ISSUE #15308: Can't interrupt `generate`
### Describe the bug

Title

### How to reproduce

(Don't) run
```nu
generate { { next: 1 } } 0
```
You will be unable to cancel the command.

### Expected behavior

To be able to interrupt the command.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.102.1                                  |
| major              | 0                                        |
| minor              | 102                                      |
| patch              | 1                                        |
| branch             | main                                     |
| commit_hash        | 7d17c2eb5ef9c4d97e1eca5afaabc89998a17c68 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.83.0 (90b35a623 2024-11-26)      |
| rust_channel       | 1.83.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.83.0 (5ffbef321 2024-10-29)      |
| build_time         | 2025-03-06 17:42:46 -08:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash                   |
| installed_plugins  |                                          |

### PR DESCRIPTION
**Pull request by 132ikl**
# Description

Fixes #15308. Surprisingly, I can't find any more issues that bring this up. 

This PR adds a check for interrupt before evaluating each IR instruction. This makes it possible to ctrl-c out of things that were difficult/impossible previously, like:
```nushell
loop {}
```

@devyn also [mentioned previously](https://discord.com/channels/601130461678272522/615329862395101194/1268674828492083327) that this might be a feasible option, but mentioned some performance concerns. 

I did some benchmarking previously but it turns out tango isn't the greatest for this. I don't have hard numbers anymore but based on some experimenting I shared in the Discord it seems like no experimental option and limiting this to specific instructions should keep the performance impact minimal.
<details>
<summary>Old benchmarking info</summary>

I did some benchmarks against main. It seems like most benchmarks are between 1-6% slower, with some oddball exceptions.

The worst case seems to a giant loop, which makes sense since it's mostly just jumping back to the beginning, meaning we hit the check over and over again. 

With `bench --pretty -n 100 { for i in 0..1000000 { 1 } }`, it seems like the `ir-interrupt` branch is ~10% slower for this stress case:
```
main: 94ms 323µs 29ns +/- 1ms 291µs 759ns 
ir-interrupt: 103ms 54µs 708ns +/- 1ms 606µs 571ns

(103ms + 54µs + 708ns) / (94ms + 323µs + 29ns) = 1.0925720801438639
```

The performance numbers here aren't great, but they're not terrible either, and I think the usability improvement is probably worth it here.

<details>
<summary>Tango benchmarks</summary>

```
load_standard_lib                                  [   2.8 ms ...   2.9 ms ]      +3.53%*
record_create_1                                    [ 101.8 us ... 107.0 us ]      +5.12%*
record_create_10                                   [ 132.3 us ... 135.6 us ]      +2.48%*
record_create_100                                  [ 349.7 us ... 354.6 us ]      +1.39%*
record_create_1000                                 [   3.7 ms ...   3.6 ms ]      -1.30%
record_flat_access_1                               [  94.8 us ...  99.9 us ]      +5.35%*
record_flat_access_10                              [  96.2 us ... 101.3 us ]      +5.33%*
record_flat_access_100                             [ 106.0 us ... 111.4 us ]      +5.07%*
record_flat_access_1000                            [ 203.0 us ... 208.5 us ]      +2.69%
record_nested_access_1                             [  95.3 us ... 100.1 us ]      +5.03%*
record_nested_access_2                             [  98.4 us ... 104.6 us ]      +6.26%*
record_nested_access_4                             [ 100.8 us ... 105.4 us ]      +4.56%*
record_nested_access_8                             [ 104.7 us ... 108.1 us ]      +3.23%
record_nested_access_16                            [ 110.6 us ... 115.8 us ]      +4.71%*
record_nested_access_32                            [ 119.0 us ... 124.0 us ]      +4.20%*
record_nested_access_64                            [ 137.4 us ... 142.2 us ]      +3.47%*
record_nested_access_128                           [ 176.7 us ... 181.8 us ]      +2.87%*
record_insert_1_1                                  [ 106.2 us ... 111.9 us ]      +5.35%*
record_insert_10_1                                 [ 111.2 us ... 116.0 us ]      +4.28%*
record_insert_100_1                                [ 134.3 us ... 139.8 us ]      +4.06%*
record_insert_1000_1                               [ 387.8 us ... 417.1 us ]      +7.55%
record_insert_1_10                                 [ 162.9 us ... 171.5 us ]      +5.23%*
record_insert_10_10                                [ 159.5 us ... 166.2 us ]      +4.23%*
record_insert_100_10                               [ 183.3 us ... 190.7 us ]      +4.04%*
record_insert_1000_10                              [ 411.7 us ... 418.7 us ]      +1.71%*
table_create_1                                     [ 117.2 us ... 120.3 us ]      +2.66%
table_create_10                                    [ 144.9 us ... 152.2 us ]      +5.02%*
table_create_100                                   [ 476.0 us ... 484.8 us ]      +1.86%*
table_create_1000                                  [   3.7 ms ...   3.7 ms ]      +1.55%
table_get_1                                        [ 121.6 us ... 127.0 us ]      +4.40%*
table_get_10                                       [ 112.1 us ... 117.4 us ]      +4.71%*
table_get_100                                      [ 124.0 us ... 129.5 us ]      +4.41%*
table_get_1000                                     [ 229.9 us ... 245.5 us ]      +6.75%*
table_select_1                                     [ 111.1 us ... 115.6 us ]      +4.03%*
table_select_10                                    [ 112.1 us ... 118.4 us ]      +5.65%*
table_select_100                                   [ 142.2 us ... 147.2 us ]      +3.53%*
table_select_1000                                  [ 383.5 us ... 370.3 us ]      -3.43%*
table_insert_row_1_1                               [ 122.5 us ... 127.8 us ]      +4.35%*
table_insert_row_10_1                              [ 123.6 us ... 128.6 us ]      +3.99%*
table_insert_row_100_1                             [ 124.9 us ... 131.2 us ]      +5.05%*
table_insert_row_1000_1                            [ 177.3 us ... 182.7 us ]      +3.07%*
table_insert_row_1_10                              [ 225.7 us ... 234.5 us ]      +3.90%*
table_insert_row_10_10                             [ 229.2 us ... 235.4 us ]      +2.69%*
table_insert_row_100_10                            [ 253.3 us ... 257.6 us ]      +1.69%
table_insert_row_1000_10                           [ 311.1 us ... 318.3 us ]      +2.32%*
table_insert_col_1_1                               [ 107.6 us ... 113.3 us ]      +5.35%*
table_insert_col_10_1                              [ 109.6 us ... 115.3 us ]      +5.27%*
table_insert_col_100_1                             [ 155.5 us ... 159.8 us ]      +2.71%*
table_insert_col_1000_1                            [ 476.6 us ... 480.8 us ]      +0.88%*
table_insert_col_1_10                              [ 167.7 us ... 177.4 us ]      +5.75%
table_insert_col_10_10                             [ 178.5 us ... 194.8 us ]      +9.16%*
table_insert_col_100_10                            [ 314.4 us ... 322.3 us ]      +2.53%*
table_insert_col_1000_10                           [   1.7 ms ...   1.7 ms ]      +1.35%*
eval_interleave_100                                [ 485.8 us ... 506.5 us ]      +4.27%
eval_interleave_1000                               [   3.3 ms ...   3.2 ms ]      -1.51%
eval_interleave_10000                              [  31.5 ms ...  31.0 ms ]      -1.80%
eval_interleave_with_interrupt_100                 [ 473.2 us ... 479.6 us ]      +1.35%
eval_interleave_with_interrupt_1000                [   3.2 ms ...   3.2 ms ]      -1.26%
eval_interleave_with_interrupt_10000               [  32.3 ms ...  31.1 ms ]      -3.81%
eval_for_1                                         [ 124.4 us ... 130.1 us ]      +4.60%*
eval_for_10                                        [ 124.4 us ... 130.3 us ]      +4.80%*
eval_for_100                                       [ 134.5 us ... 141.5 us ]      +5.18%*
eval_for_1000                                      [ 222.7 us ... 244.0 us ]      +9.59%*
eval_for_10000                                     [   1.0 ms ...   1.2 ms ]     +13.86%*
eval_each_1                                        [ 146.9 us ... 153.0 us ]      +4.15%*
eval_each_10                                       [ 152.3 us ... 158.8 us ]      +4.26%*
eval_each_100                                      [ 169.3 us ... 175.6 us ]      +3.76%*
eval_each_1000                                     [ 346.8 us ... 357.4 us ]      +3.06%*
eval_each_10000                                    [   2.1 ms ...   2.2 ms ]      +2.37%*
eval_par_each_1                                    [ 194.3 us ... 203.5 us ]      +4.73%*
eval_par_each_10                                   [ 186.4 us ... 193.1 us ]      +3.59%*
eval_par_each_100                                  [ 213.5 us ... 222.2 us ]      +4.08%*
eval_par_each_1000                                 [ 433.4 us ... 437.4 us ]      +0.93%
eval_par_each_10000                                [   2.4 ms ...   2.4 ms ]      -0.40%
eval_default_config                                [ 406.3 us ... 414.9 us ]      +2.12%*
eval_default_env                                   [ 475.7 us ... 495.1 us ]      +4.08%*
encode_json_100_5                                  [ 132.7 us ... 128.9 us ]      -2.88%*
encode_json_10000_15                               [  35.5 ms ...  34.0 ms ]      -4.15%*
encode_msgpack_100_5                               [  85.0 us ...  83.9 us ]      -1.20%*
encode_msgpack_10000_15                            [  22.2 ms ...  21.7 ms ]      -2.17%*
decode_json_100_5                                  [ 431.3 us ... 421.0 us ]      -2.40%*
decode_json_10000_15                               [ 119.7 ms ... 117.6 ms ]      -1.76%*
decode_msgpack_100_5                               [ 160.6 us ... 151.1 us ]      -5.90%*
decode_msgpack_10000_15                            [  44.0 ms ...  43.1 ms ]      -2.12%*
```

</details>

</details>

# User-Facing Changes

* It should be possible to ctrl-c in situations where it was not previously possible

# Tests + Formatting

N/A

# After Submitting

N/A

### CODE REVIEW

File: crates/nu-engine/src/eval_ir.rs [hunk 1]
```diff
@@ -19,6 +23,9 @@ use crate::{
     ENV_CONVERSIONS, convert_env_vars, eval::is_automatic_env_var, eval_block_with_early_return,
 };
 
+// checking this is non-trivial, so only do it once
+static CHECK_CTRLC: LazyLock<bool> = LazyLock::new(|| nu_experimental::IR_INTERRUPT.get());
```
Comment (Bahex) [inline crates/nu-engine/src/eval_ir.rs]: Something like this should probably be handled in `nu-experimental` for all options.
cc: @cptpiepmatz

**Comment by Bahex** [comment]
Instead of all instructions maybe we can perform the check for a subset that are likely to be "problematic"

- Collect
- Drain
- DrainIfEnd
- Jump
- BranchIf
- Iterate
- ReturnEarly
- Return

**Comment by 132ikl** [comment]
that's probably a good idea considering the performance concerns

**Comment by 132ikl** [comment]
unfortunately, it seems like adding in the check makes it slower, and not faster, with the notable exception of the `eval_for_10000` case

<details>
<summary>With instruction check vs. without instruction check</summary>

```
load_standard_lib                                  [   3.0 ms ...   3.1 ms ]      +3.64%*
record_create_1                                    [ 106.1 us ... 108.4 us ]      +2.10%
record_create_10                                   [ 127.8 us ... 132.5 us ]      +3.68%*
record_create_100                                  [ 363.0 us ... 366.6 us ]      +0.99%*
record_create_1000                                 [   3.8 ms ...   3.6 ms ]      -3.62%
record_flat_access_1                               [  96.4 us ... 101.5 us ]      +5.27%*
record_flat_access_10                              [  97.8 us ... 102.2 us ]      +4.57%*
record_flat_access_100                             [ 108.3 us ... 112.4 us ]      +3.72%*
record_flat_access_1000                            [ 204.0 us ... 206.0 us ]      +1.00%*
record_nested_access_1                             [  98.1 us ... 102.5 us ]      +4.46%*
record_nested_access_2                             [  98.0 us ... 102.1 us ]      +4.17%*
record_nested_access_4                             [  99.4 us ... 103.4 us ]      +3.98%*
record_nested_access_8                             [ 103.0 us ... 107.1 us ]      +4.06%*
record_nested_access_16                            [ 109.5 us ... 113.8 us ]      +3.87%*
record_nested_access_32                            [ 120.9 us ... 124.9 us ]      +3.29%*
record_nested_access_64                            [ 140.9 us ... 143.7 us ]      +2.02%*
record_nested_access_128                           [ 183.7 us ... 186.9 us ]      +1.78%
record_insert_1_1                                  [ 108.3 us ... 113.0 us ]      +4.37%*
record_insert_10_1                                 [ 109.5 us ... 114.5 us ]      +4.57%*
record_insert_100_1                                [ 134.7 us ... 139.4 us ]      +3.47%*
record_insert_1000_1                               [ 350.3 us ... 355.5 us ]      +1.48%*
record_insert_1_10                                 [ 157.2 us ... 163.3 us ]      +3.90%*
record_insert_10_10                                [ 159.0 us ... 165.7 us ]      +4.18%*
record_insert_100_10                               [ 187.7 us ... 192.1 us ]      +2.33%*
record_insert_1000_10                              [ 420.1 us ... 422.7 us ]      +0.60%
table_create_1                                     [ 112.4 us ... 117.0 us ]      +4.06%*
table_create_10                                    [ 148.2 us ... 153.0 us ]      +3.26%*
table_create_100                                   [ 472.1 us ... 472.7 us ]      +0.12%
table_create_1000                                  [   3.6 ms ...   3.7 ms ]      +2.64%
table_get_1                                        [ 115.9 us ... 122.0 us ]      +5.32%*
table_get_10                                       [ 116.5 us ... 121.1 us ]      +3.93%*
table_get_100                                      [ 125.3 us ... 130.4 us ]      +4.03%*
table_get_1000                                     [ 239.6 us ... 253.4 us ]      +5.76%*
table_select_1                                     [ 117.6 us ... 121.4 us ]      +3.27%
table_select_10                                    [ 110.8 us ... 116.0 us ]      +4.77%*
table_select_100                                   [ 135.4 us ... 140.5 us ]      +3.78%*
table_select_1000                                  [ 351.9 us ... 355.6 us ]      +1.03%*
table_insert_row_1_1                               [ 120.9 us ... 125.1 us ]      +3.44%*
table_insert_row_10_1                              [ 118.0 us ... 123.1 us ]      +4.34%*
table_insert_row_100_1                             [ 125.2 us ... 130.2 us ]      +3.98%*
table_insert_row_1000_1                            [ 174.4 us ... 179.2 us ]      +2.79%*
table_insert_row_1_10                              [ 225.5 us ... 231.1 us ]      +2.51%*
table_insert_row_10_10                             [ 227.7 us ... 234.0 us ]      +2.76%*
table_insert_row_100_10                            [ 231.3 us ... 237.1 us ]      +2.48%*
table_insert_row_1000_10                           [ 298.8 us ... 306.3 us ]      +2.54%*
table_insert_col_1_1                               [ 110.7 us ... 113.2 us ]      +2.22%
table_insert_col_10_1                              [ 109.5 us ... 114.5 us ]      +4.57%*
table_insert_col_100_1                             [ 152.3 us ... 157.2 us ]      +3.26%*
table_insert_col_1000_1                            [ 476.8 us ... 481.9 us ]      +1.07%
table_insert_col_1_10                              [ 153.4 us ... 159.0 us ]      +3.66%*
table_insert_col_10_10                             [ 174.5 us ... 179.7 us ]      +2.96%*
table_insert_col_100_10                            [ 316.3 us ... 322.1 us ]      +1.82%*
table_insert_col_1000_10                           [   1.8 ms ...   1.8 ms ]      +4.12%*
eval_interleave_100                                [ 519.7 us ... 532.0 us ]      +2.36%
eval_interleave_1000                               [   3.2 ms ...   3.2 ms ]      +0.16%
eval_interleave_10000                              [  31.2 ms ...  30.3 ms ]      -2.83%
eval_interleave_with_interrupt_100                 [ 475.4 us ... 480.4 us ]      +1.06%
eval_interleave_with_interrupt_1000                [   3.2 ms ...   3.2 ms ]      +1.04%
eval_interleave_with_interrupt_10000               [  31.6 ms ...  31.1 ms ]      -1.82%
eval_for_1                                         [ 126.7 us ... 131.2 us ]      +3.57%*
eval_for_10                                        [ 123.8 us ... 128.2 us ]      +3.54%*
eval_for_100                                       [ 137.2 us ... 139.7 us ]      +1.78%
eval_for_1000                                      [ 237.5 us ... 237.3 us ]      -0.09%
eval_for_10000                                     [   1.2 ms ...   1.2 ms ]      -4.44%*
eval_each_1                                        [ 146.6 us ... 151.9 us ]      +3.61%*
eval_each_10                                       [ 151.7 us ... 156.7 us ]      +3.30%*
eval_each_100                                      [ 167.6 us ... 172.4 us ]      +2.84%*
eval_each_1000                                     [ 357.3 us ... 359.7 us ]      +0.65%*
eval_each_10000                                    [   2.2 ms ...   2.2 ms ]      +0.80%
eval_par_each_1                                    [ 184.8 us ... 189.8 us ]      +2.71%
eval_par_each_10                                   [ 184.7 us ... 196.0 us ]      +6.11%*
eval_par_each_100                                  [ 216.7 us ... 225.3 us ]      +3.99%*
eval_par_each_1000                                 [ 432.6 us ... 444.8 us ]      +2.82%*
eval_par_each_10000                                [   2.4 ms ...   2.5 ms ]      +1.62%
eval_default_config                                [ 407.4 us ... 409.7 us ]      +0.57%
eval_default_env                                   [ 479.4 us ... 495.1 us ]      +3.29%*
encode_json_100_5                                  [ 128.5 us ... 126.6 us ]      -1.47%*
encode_json_10000_15                               [  34.1 ms ...  33.6 ms ]      -1.40%*
encode_msgpack_100_5                               [  83.5 us ...  83.6 us ]      +0.14%
encode_msgpack_10000_15                            [  21.6 ms ...  21.7 ms ]      +0.05%
decode_json_100_5                                  [ 422.9 us ... 427.3 us ]      +1.05%
decode_json_10000_15                               [ 118.3 ms ... 117.7 ms ]      -0.50%*
decode_msgpack_100_5                               [ 152.8 us ... 153.0 us ]      +0.11%
decode_msgpack_10000_15                            [  43.1 ms ...  43.2 ms ]      +0.12%
```

</details>

<details>
<summary>With instruction check vs. main</summary>

```
load_standard_lib                                  [   2.9 ms ...   3.0 ms ]      +5.12%*
record_create_1                                    [  99.4 us ... 106.9 us ]      +7.58%*
record_create_10                                   [ 125.3 us ... 133.0 us ]      +6.12%*
record_create_100                                  [ 354.7 us ... 362.3 us ]      +2.14%*
record_create_1000                                 [   3.7 ms ...   3.6 ms ]      -1.27%
record_flat_access_1                               [  95.0 us ... 102.0 us ]      +7.38%*
record_flat_access_10                              [  96.1 us ... 102.8 us ]      +6.96%*
record_flat_access_100                             [ 109.1 us ... 116.5 us ]      +6.78%*
record_flat_access_1000                            [ 204.3 us ... 209.7 us ]      +2.64%*
record_nested_access_1                             [  96.6 us ... 103.9 us ]      +7.55%*
record_nested_access_2                             [  96.6 us ... 104.0 us ]      +7.66%*
record_nested_access_4                             [  99.6 us ... 106.5 us ]      +6.94%*
record_nested_access_8                             [ 101.2 us ... 108.4 us ]      +7.19%*
record_nested_access_16                            [ 106.2 us ... 113.2 us ]      +6.63%*
record_nested_access_32                            [ 118.2 us ... 124.9 us ]      +5.67%*
record_nested_access_64                            [ 142.4 us ... 147.1 us ]      +3.31%*
record_nested_access_128                           [ 182.7 us ... 187.9 us ]      +2.85%
record_insert_1_1                                  [ 106.1 us ... 114.8 us ]      +8.12%*
record_insert_10_1                                 [ 111.8 us ... 117.4 us ]      +5.01%*
record_insert_100_1                                [ 133.0 us ... 140.7 us ]      +5.81%*
record_insert_1000_1                               [ 356.2 us ... 362.2 us ]      +1.69%*
record_insert_1_10                                 [ 152.8 us ... 163.2 us ]      +6.80%*
record_insert_10_10                                [ 156.3 us ... 166.2 us ]      +6.33%*
record_insert_100_10                               [ 194.4 us ... 202.3 us ]      +4.07%*
record_insert_1000_10                              [ 412.4 us ... 421.0 us ]      +2.09%*
table_create_1                                     [ 109.6 us ... 116.4 us ]      +6.19%*
table_create_10                                    [ 144.1 us ... 151.9 us ]      +5.46%*
table_create_100                                   [ 472.3 us ... 480.0 us ]      +1.62%*
table_create_1000                                  [   3.6 ms ...   3.6 ms ]      +0.56%
table_get_1                                        [ 109.1 us ... 116.3 us ]      +6.63%*
table_get_10                                       [ 111.0 us ... 118.7 us ]      +6.98%*
table_get_100                                      [ 123.7 us ... 131.4 us ]      +6.21%*
table_get_1000                                     [ 239.5 us ... 266.4 us ]     +11.25%*
table_select_1                                     [ 108.7 us ... 115.5 us ]      +6.20%*
table_select_10                                    [ 109.9 us ... 116.9 us ]      +6.36%*
table_select_100                                   [ 135.6 us ... 141.0 us ]      +3.98%*
table_select_1000                                  [ 384.7 us ... 376.6 us ]      -2.10%
table_insert_row_1_1                               [ 115.7 us ... 123.6 us ]      +6.85%*
table_insert_row_10_1                              [ 118.5 us ... 126.7 us ]      +6.91%*
table_insert_row_100_1                             [ 125.5 us ... 135.4 us ]      +7.90%*
table_insert_row_1000_1                            [ 182.3 us ... 188.3 us ]      +3.33%*
table_insert_row_1_10                              [ 223.4 us ... 234.4 us ]      +4.89%*
table_insert_row_10_10                             [ 224.7 us ... 235.8 us ]      +4.95%*
table_insert_row_100_10                            [ 233.5 us ... 244.7 us ]      +4.81%*
table_insert_row_1000_10                           [ 300.7 us ... 311.9 us ]      +3.74%*
table_insert_col_1_1                               [ 106.1 us ... 113.5 us ]      +7.05%*
table_insert_col_10_1                              [ 110.9 us ... 119.0 us ]      +7.37%*
table_insert_col_100_1                             [ 156.2 us ... 163.1 us ]      +4.41%*
table_insert_col_1000_1                            [ 485.6 us ... 492.9 us ]      +1.52%
table_insert_col_1_10                              [ 151.7 us ... 163.7 us ]      +7.85%*
table_insert_col_10_10                             [ 167.6 us ... 178.3 us ]      +6.37%*
table_insert_col_100_10                            [ 312.3 us ... 325.1 us ]      +4.11%*
table_insert_col_1000_10                           [   1.7 ms ...   1.8 ms ]      +1.59%*
eval_interleave_100                                [ 472.7 us ... 487.5 us ]      +3.13%*
eval_interleave_1000                               [   3.2 ms ...   3.2 ms ]      +1.46%
eval_interleave_10000                              [  31.7 ms ...  32.5 ms ]      +2.69%
eval_interleave_with_interrupt_100                 [ 527.3 us ... 549.4 us ]      +4.19%
eval_interleave_with_interrupt_1000                [   3.5 ms ...   3.5 ms ]      +0.81%
eval_interleave_with_interrupt_10000               [  31.3 ms ...  33.0 ms ]      +5.24%
eval_for_1                                         [ 127.3 us ... 137.1 us ]      +7.75%*
eval_for_10                                        [ 125.3 us ... 137.0 us ]      +9.38%*
eval_for_100                                       [ 144.1 us ... 150.9 us ]      +4.70%*
eval_for_1000                                      [ 249.4 us ... 260.1 us ]      +4.28%*
eval_for_10000                                     [   1.2 ms ...   1.3 ms ]      +5.82%*
eval_each_1                                        [ 156.2 us ... 162.0 us ]      +3.66%*
eval_each_10                                       [ 152.1 us ... 159.5 us ]      +4.89%*
eval_each_100                                      [ 173.0 us ... 183.5 us ]      +6.09%*
eval_each_1000                                     [ 355.9 us ... 369.2 us ]      +3.74%*
eval_each_10000                                    [   2.2 ms ...   2.3 ms ]      +4.96%
eval_par_each_1                                    [ 182.0 us ... 195.4 us ]      +7.34%*
eval_par_each_10                                   [ 192.2 us ... 202.2 us ]      +5.20%*
eval_par_each_100                                  [ 216.3 us ... 229.8 us ]      +6.25%*
eval_par_each_1000                                 [ 470.0 us ... 465.5 us ]      -0.95%
eval_par_each_10000                                [   2.5 ms ...   2.6 ms ]      +1.53%
eval_default_config                                [ 415.1 us ... 421.9 us ]      +1.63%*
eval_default_env                                   [ 478.7 us ... 501.7 us ]      +4.80%*
encode_json_100_5                                  [ 133.2 us ... 127.5 us ]      -4.29%*
encode_json_10000_15                               [  36.4 ms ...  34.7 ms ]      -4.57%*
encode_msgpack_100_5                               [  85.6 us ...  84.5 us ]      -1.32%*
encode_msgpack_10000_15                            [  22.5 ms ...  22.0 ms ]      -2.36%*
decode_json_100_5                                  [ 439.3 us ... 432.1 us ]      -1.62%
decode_json_10000_15                               [ 121.0 ms ... 117.6 ms ]      -2.77%*
decode_msgpack_100_5                               [ 156.9 us ... 154.0 us ]      -1.83%*
decode_msgpack_10000_15                            [  60.7 ms ...  58.5 ms ]      -3.72%
```

</details>

**Comment by 132ikl** [comment]
here's the diff, I won't push since it doesn't seem to help

<details>
<summary>diff</summary>

```diff
commit 8e71d42ef1058828ee239d87df62d45a7133cfaf
Author: 132ikl <132@ikl.sh>
Date:   Tue Jul 8 20:11:14 2025 -0400

    Limit IR interrupt check to specific instructions

diff --git a/crates/nu-engine/src/eval_ir.rs b/crates/nu-engine/src/eval_ir.rs
index da97fb16a..b9701fd82 100644
--- a/crates/nu-engine/src/eval_ir.rs
+++ b/crates/nu-engine/src/eval_ir.rs
@@ -299,7 +299,7 @@ fn eval_instruction<D: DebugContext>(
 ) -> Result<InstructionResult, ShellError> {
     use self::InstructionResult::*;
 
-    if *CHECK_CTRLC {
+    if instruction.allow_interrupt() && *CHECK_CTRLC {
         // Check for ctrl-c
         ctx.engine_state.signals().check(span)?;
     }
diff --git a/crates/nu-protocol/src/ir/mod.rs b/crates/nu-protocol/src/ir/mod.rs
index 6cb284087..9c4439e98 100644
--- a/crates/nu-protocol/src/ir/mod.rs
+++ b/crates/nu-protocol/src/ir/mod.rs
@@ -382,6 +382,21 @@ impl Instruction {
         }
         Ok(())
     }
+
+    /// Whether the evaluator is allowed to check for an interrupt before evaluating an instruction
+    pub fn allow_interrupt(&self) -> bool {
+        match self {
+            Instruction::Collect { .. } => true,
+            Instruction::Drain { .. } => true,
+            Instruction::DrainIfEnd { .. } => true,
+            Instruction::Jump { .. } => true,
+            Instruction::BranchIf { .. } => true,
+            Instruction::Iterate { .. } => true,
+            Instruction::ReturnEarly { .. } => true,
+            Instruction::Return { .. } => true,
+            _ => false,
+        }
+    }
 }
 
 // This is to document/enforce the size of `Instruction` in bytes.
```

</details>

File: crates/nu-engine/src/eval_ir.rs (hunk 1 above)
Comment (cptpiepmatz) [reply crates/nu-engine/src/eval_ir.rs]: Is `get` that pricy?

**Comment by Bahex** [comment]
I have one or two ideas about how to optimize this but one of them could be a maintenance burden and the other relies on the compiler to elide some checks and optimize stuff out. 

I'll try them out later today when I'm free

**Comment by 132ikl** [comment]
after [discussion about the performance in Discord](https://discord.com/channels/601130461678272522/615962413203718156/1392585829821583441), I've change it to just interrupt before jump and return, and removed the experimental option. Force pushed just to make my life easier, the change is minimal now

File: crates/nu-protocol/src/pipeline/signals.rs [hunk 2]
```diff
@@ -44,11 +44,11 @@ impl Signals {
     ///
     /// Otherwise, returns `Ok`.
     #[inline]
-    pub fn check(&self, span: Span) -> Result<(), ShellError> {
+    pub fn check(&self, span: &Span) -> Result<(), ShellError> {
```
Comment (sholderbach) [inline crates/nu-protocol/src/pipeline/signals.rs:47]: What is the motivation to change it here? Causes unrelated diff.

Comment (132ikl) [reply crates/nu-protocol/src/pipeline/signals.rs:47]: `eval_ir` has `Span` passed via a reference, so we would have to dereference in the hot path in order to check interrupt. It's not as big of a deal as it was previously now that it's limited to `Jump` and `Return`. But `check` doesn't really need a whole entire `Span` and it's (presumably) a minor optimization in the hottest of hot paths

Comment (sholderbach) [reply crates/nu-protocol/src/pipeline/signals.rs:47]: OK that makes sense.

**Review by Bahex — APPROVED** [review]
