### PR TITLE
fix: switch parameters are now typed bool

### LINKED ISSUE #17112: if there are more than one flags in a custom command, a table with type annotation will cause nu::parser::type_mismatch
### Bug report form

- [x] I have done a basic search of the issue tracker to find any existing issues that are similar.
- [x] I have checked that my version is at least the latest stable release available via my installation method.

### Describe the bug

When defining a custom command like this, a flag without type annotation will be considered as **bool**.   
But on nu 0.109, if there are more than one flags in a custom command, a table with correct type annotation will cause nu::parser::type_mismatch( a list or record with type annotation works normally, this bug jumps only on a table with type annotation )

Image

if there are more than 3 flags defined, other type annotations will also cause parse failure, like this:

Image

i encountered this bug after updating to 0.109.0, and 0.109.1 doesnt fix it.

### How to reproduce

1. use nu 0.109.0 or 0.109.1 on Windows or GNU/Linux, it's not a platform specialized issue
2. define some flags  without type annotation in a custom command
3. in the scope of the custom command, create a table with type annotation to collect flags' values

### Expected behavior

the custom command should pass type check and would not throw the Error(Error: nu::parser::type_mismatch)

### Configuration

| key                  | value                                                                                     |
| -------------------- | ----------------------------------------------------------------------------------------- |
| version              | 0.109.1                                                                                   |
| major                | 0                                                                                         |
| minor                | 109                                                                                       |
| patch                | 1                                                                                         |
| branch               |                                                                                           |
| commit_hash          | cde5f7be8c813173e95ea65f96e79a133f587de7                                                  |
| build_os             | windows-x86_64                                                                            |
| build_target         | x86_64-pc-windows-msvc                                                                    |
| rust_version         | rustc 1.89.0 (29483883e 2025-08-04)                                                       |
| rust_channel         | 1.89.0-x86_64-pc-windows-msvc                                                             |
| cargo_version        | cargo 1.89.0 (c24e10642 2025-06-23)                                                       |
| build_time           | 2025-12-02 20:37:39 +00:00                                                                |
| build_rust_channel   | release                                                                                   |
| allocator            | standard                                                                                  |
| features             | default, network, plugin, rustls-tls, sqlite, trash-support                               |
| installed_plugins    | formats 0.106.1                                                                           |
| experimental_options | example=false, reorder-cell-paths=true, pipefail=false, enforce-runtime-annotations=false |

### PR DESCRIPTION
**Pull request by Bahex**
- fixes #17112 

### Switch flags in custom commands are properly typed as `bool`

Switch flags (named flags without a type or default value) are typed `bool`, previously this information was not available to the parse-time type checking.

### Table columns with values of differing types are no longer inferred as `nothing` were `any` is the correct type

### CODE REVIEW

File: crates/nu-parser/src/parser.rs [hunk 1]
```diff
@@ -4527,7 +4535,7 @@ pub fn parse_signature_helper(working_set: &mut StateWorkingSet, span: Span) ->
                                         // Flags with no TypeMode are just present/not-present switches
                                         // in the case, `var_type` is any.
```
Comment (WindSoilder) [inline crates/nu-parser/src/parser.rs]: Is the comment still valid?
