### PR TITLE
prevent parser from parsing variables as units

### LINKED ISSUE #11274: (range) parsing is weird
### Describe the bug

```
> let day = 9
> 0..<$day
Error:   × duration value must be a number
   ╭─[entry #37:1:1]
 1 │ 0..<$day
   · ──┬──
   ·   ╰── not a number
   ╰────

> let ab = 8
> 0..$ab
Error:   × filesize value must be a number
   ╭─[entry #40:1:1]
 1 │ 0..$ab
   · ──┬──
   ·   ╰── not a number
   ╰────
```
The workaround for now is parenthesize the variable, i.e. `0..<($day)`

### How to reproduce

see above

### Expected behavior

Both of them parsed as ranges without parentheses

Neither `0..<$` or `0..$` (replace 0 with any other number value) can't contain duration or filesize values, due to `..` or `$` not a possible token within a number.

### Screenshots

_No response_

### Configuration

| key                | value                                     |
| ------------------ | ----------------------------------------- |
| version            | 0.87.2                                    |
| branch             | main                                      |
| commit_hash        | aacf481aaf2c814ff6898fd8a935868f59c075c3  |
| build_os           | linux-x86_64                              |
| build_target       | x86_64-unknown-linux-gnu                  |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13)       |
| rust_channel       | 1.72.1-x86_64-unknown-linux-gnu           |
| cargo_version      | cargo 1.72.1 (103a7ff2e 2023-08-15)       |
| build_time         | 2023-12-08 23:21:17 -08:00                |
| build_rust_channel | release                                   |
| allocator          | mimalloc                                  |
| features           | default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                           |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by merelymyself**
# Description

Resolves #11274.

```
~/CodingProjects/nushell> let day = 2; echo 0..<$day
╭───┬───╮
│ 0 │ 0 │
│ 1 │ 1 │
╰───┴───╯
~/CodingProjects/nushell> let kb = "jan"; echo 0..$kb 
Error: nu::shell::type_mismatch

  × Type mismatch during operation.
   ╭─[entry #1:1:22]
 1 │ let kb = "jan"; echo 0..$kb
   ·                      ┬─┬─┬─
   ·                      │ │ ╰── string
   ·                      │ ╰── type mismatch for operator
   ·                      ╰── int
   ╰────
```

# User-Facing Changes

# Tests + Formatting

Relevant test added :up: 

# After Submitting

### CODE REVIEW

File: crates/nu-parser/src/parser.rs [hunk 1]
```diff
@@ -2323,6 +2323,9 @@ pub fn parse_unit_value<'res>(
         let lhs = strip_underscores(value[..lhs_len].as_bytes());
         let lhs_span = Span::new(span.start, span.start + lhs_len);
         let unit_span = Span::new(span.start + lhs_len, span.end);
+        if lhs.ends_with('$') {
+            return None;
```
Comment (sholderbach) [inline crates/nu-parser/src/parser.rs:2327]: Maybe worth commenting on the reasoning on this otherwise obscure special case.

```suggestion
            // If `parse_unit_value` has higher precedence over `parse_range`,
            // a variable with the name of a unit could otherwise not be used as the end of a range.
            return None;
```

**Review by sholderbach — APPROVED** [review]
Thanks for the fix and test! You are really chipping away at our bug backlog.

**Comment by crides** [comment]
This doesn't _fully_ resolve #11274.

Things like `0..$d` is fine, but things like `0..$ab` (where what-could-be-the-unit starts some chars after the `$`). It's easy to see why from the diff though... the `lhs` of the unit should really just be one of:
1. number literals (ints, floats)
2. variables (`$` followed by identifier/cell path)
3. parenthesized expressions (and let the evaluator deal with the incorrect type)

**Comment by sholderbach** [comment]
Good point that we can rule out more for the `lhs` in `parse_unit_value` but that should be limited to just a numeric literal based on what our unit-literals support.

I am going to reopen #11274, it seems we have more to figure out around how the range expression parsing works or how the different literal/expression parses interact in their precedence.
