### PR TITLE
fix(overlay use): report errors in export-env

### LINKED ISSUE #10242: `overlay use` and `nu` do not report error inside `export-env`
### Describe the bug

Errors in `export-env` are sometimes not reported (when running `nu` or `overlay use`, but there might be other cases). 

### How to reproduce

```nushell
export-env { let-env FOO = 'bar' }
```

Save the above into `spam.nu` and call `overlay use spam.nu` and `nu spam.nu`.  You'll see that in both cases nothing happens.

### Expected behavior

```
Error: nu::shell::removed_command

  × Removed command: let-env
   ╭─[/home/kubouch/git/forks/nupm/spam.nu:1:1]
 1 │ export-env { let-env FOO = 'bar' }
   ·              ───┬───
   ·                 ╰── 'let-env' has been removed from Nushell. Please use '$env.<environment variable> = ...' instead.
   ╰────
```

### Screenshots

_No response_

### Configuration

| key                | value                                                                                                                      |
| ------------------ | -------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.84.1                                                                                                                     |
| branch             | main                                                                                                                       |
| commit_hash        | 54394fe9af746230c6c7cbb399c54672477bfa84                                                                                   |
| build_os           | linux-x86_64                                                                                                               |
| build_target       | x86_64-unknown-linux-gnu                                                                                                   |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)                                                                                        |
| rust_channel       | 1.70.0-x86_64-unknown-linux-gnu                                                                                            |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)                                                                                        |
| build_time         | 2023-09-05 17:43:59 +03:00                                                                                                 |
| build_rust_channel | release                                                                                                                    |
| allocator          | standard                                                                                                                   |
| features           | default, extra, sqlite, trash, which, zip                                                                                  |
| installed_plugins  | from eml, from ics, from ini, from vcf, gstat, highlight, hist, inc, plot, query, query json, query web, query xml, xyplot |

### Additional context

Calling `use spam.nu` reports the error correctly.

### PR DESCRIPTION
**Pull request by Bahex**
- fixes #10242

# Tests + Formatting
Added 2 tests to confirm `use` and `overlay use` report errors in `export-env` blocks.

### CODE REVIEW

File: crates/nu-cmd-lang/src/core_commands/overlay/use_.rs [hunk 1]
```diff
@@ -158,7 +158,7 @@ impl Command for OverlayUse {
                 }
 
                 let eval_block = get_eval_block(engine_state);
-                let _ = eval_block(engine_state, &mut callee_stack, block, input);
+                let _ = eval_block(engine_state, &mut callee_stack, block, input)?;
```
Comment (sholderbach) [inline crates/nu-cmd-lang/src/core_commands/overlay/use_.rs:161]: Nasty 😅 Thanks for catching that
