### PR TITLE
Return error on a divide by zero

### LINKED ISSUE #1363: Shell panics on divide by zero
**Describe the bug**
When dividing by zero using `calc`, nushell panics.

**To Reproduce**
1. do `echo "2/0" | calc` in nu
 

**Expected behavior**
An error should be returned.

**Screenshots**
image

**Configuration (please complete the following information):**
 - OS: Manjaro Linux
 - Version - master with where the latest commit is e606407d7998738f0daef812e11d0569827d45e4
 - Optional features - `stable`

### PR DESCRIPTION
**Pull request by coolshaurya**
Fixes #1363.

### CODE REVIEW

File: src/commands/calc.rs [hunk 1]
```diff
@@ -49,9 +49,15 @@ fn calc(input: Value, args: &RawCommandArgs) -> Result<OutputStream, ShellError>
 }
 
 pub fn parse(math_expression: &str, tag: impl Into<Tag>) -> Result<Value, String> {
+    use std::f64;
     let num = meval::eval_str(math_expression);
     match num {
-        Ok(num) => Ok(UntaggedValue::from(Primitive::from(num)).into_value(tag)),
+        Ok(num) => {
+            if num == f64::INFINITY || num == f64::NEG_INFINITY {
+                return Err(String::from("Cannot divide by zero"));
```
Comment (thegedge) [inline src/commands/calc.rs]: Since infinity could be produced in other ways (e.g., `log(0)`), how about we have a more generic error message like `"cannot represent result"`?

On a side note, we should think about whether or not we want to be able to represent these 🙂
