### PR TITLE
Make ls show only the file name

### LINKED ISSUE #1269: ls shows full file path instead of only the file name
**Describe the bug**
Currently `ls` shows the full file path in the name column. This becomes a bit annoying when `ls`ing deep in the filesystem tree.

examples of current behavior : 

```sh
❯ pwd
/home/shaurya/stuff/expr

❯ ls stuff/
───┬──────────────────────────────────┬──────┬───────┬─────────────
 # │ name                             │ type │ size  │ modified 
───┼──────────────────────────────────┼──────┼───────┼─────────────
 0 │ stuff/abaracadabra.txt           │ File │ 401 B │ 3 weeks ago 
 1 │ stuff/coww.txt                   │ File │  24 B │ 3 weeks ago 
 2 │ stuff/randomweirdstuff.txt       │ File │ 197 B │ 3 weeks ago 
 3 │ stuff/youshouldeatmorecereal.txt │ File │ 768 B │ 3 weeks ago 
 4 │ stuff/zebrasarecrazy.txt         │ File │ 556 B │ 3 weeks ago 
───┴──────────────────────────────────┴──────┴───────┴─────────────

❯ cd /

❯ ls ~/stuff/expr/stuff/
───┬──────────────────────────────────────────────────────────┬──────┬───────┬─────────────
 # │ name                                                     │ type │ size  │ modified 
───┼──────────────────────────────────────────────────────────┼──────┼───────┼─────────────
 0 │ home/shaurya/stuff/expr/stuff/abaracadabra.txt           │ File │ 401 B │ 3 weeks ago 
 1 │ home/shaurya/stuff/expr/stuff/coww.txt                   │ File │  24 B │ 3 weeks ago 
 2 │ home/shaurya/stuff/expr/stuff/randomweirdstuff.txt       │ File │ 197 B │ 3 weeks ago 
 3 │ home/shaurya/stuff/expr/stuff/youshouldeatmorecereal.txt │ File │ 768 B │ 3 weeks ago 
 4 │ home/shaurya/stuff/expr/stuff/zebrasarecrazy.txt         │ File │ 556 B │ 3 weeks ago 
───┴──────────────────────────────────────────────────────────┴──────┴───────┴─────────────
```

**To Reproduce**
1. Do `ls <foldername>`

**Expected behavior**
`ls stuff/` and `ls ~/stuff/expr/stuff/` both should give - 
```sh
───┬──────────────────────────────────┬──────┬───────┬─────────────
 # │ name                             │ type │ size  │ modified 
───┼──────────────────────────────────┼──────┼───────┼─────────────
 0 │ abaracadabra.txt                 │ File │ 401 B │ 3 weeks ago 
 1 │ coww.txt                         │ File │  24 B │ 3 weeks ago 
 2 │ randomweirdstuff.txt             │ File │ 197 B │ 3 weeks ago 
 3 │ youshouldeatmorecereal.txt       │ File │ 768 B │ 3 weeks ago 
 4 │ zebrasarecrazy.txt               │ File │ 556 B │ 3 weeks ago 
───┴──────────────────────────────────┴──────┴───────┴─────────────
```

**Screenshots**
**Configuration (please complete the following information):**
 - OS: Manjaro Linux
 - Version : from master ; latest commit on my machine at time of reporting is commit [bc5a969](https://github.com/nushell/nushell/commit/bc5a9695627f1445386f9a85671b4cdf8c5aa186v)
 - Optional features : `stable`

### PR DESCRIPTION
**Pull request by coolshaurya**
Fixes #1269 .

I've added two `unwrap`s. Looking for guidance on how to remove them.

### CODE REVIEW

File: src/shell/filesystem_shell.rs [hunk 1]
```diff
@@ -144,10 +143,10 @@ impl Shell for FilesystemShell {
                         if let Ok(entry) = entry {
                             let filepath = entry.path();
                             if let Ok(metadata) = std::fs::symlink_metadata(&filepath) {
-                                let filename = if let Ok(fname) = filepath.strip_prefix(&cwd) {
-                                    fname
+                                let filename = if let Some(fname) = filepath.file_name() {
+                                    Path::new(fname)
                                 } else {
-                                    Path::new(&filepath)
+                                    Path::new(Path::new(&filepath).file_name().unwrap())
```
Comment (thegedge) [inline src/shell/filesystem_shell.rs]: To avoid the `unwrap`, you could do something similar to line 146, although I'll make another recommendation:

```
let fname = filepath
  .file_name()
  .or_else(|| Path::new(&filepath).file_name())
  .unwrap_or(filepath);

Path::new(fname)
```

Not 100% that'll work (not sure if the types line up), so you may have to tweak it.

**Comment by jonathandturner** [comment]
@coolshaurya - I think some people would definitely like this feature. Let's add a new flag to `ls` for it.

By default, having the longer names is actually good for processing data, building up a pipeline that works across multiple directories and in the future for scripting also. Like you said, sometimes you don't want to look at them, so it'd be good to be able to output just the filename.

You could make the flag something like `--short-names`

File: src/shell/filesystem_shell.rs (hunk 1 above)
Comment (coolshaurya) [reply src/shell/filesystem_shell.rs]: thanks for the tip

**Comment by jonathandturner** [comment]
Looks good!
