### PR TITLE
use encoding on open for #1939

### LINKED ISSUE #1939: Character encoding in files with  open  and  save
I have had some issues with a file recently.   I spent ages on it until I realised the real issue.

I have a big CSV file which uses ';' separators, so I was hoping that nushell would be useful.
But when I tried to process it in any way I got strange messages:

```
❯ open nilg.csv  --raw | lines
error: Expected a string from pipeline
- shell:1:28
1 | open nilg.csv  --raw | lines
  |                        ^^^^^ requires string input
- shell:1:28
1 | open nilg.csv  --raw | lines
  |      -------- value originates from here
```

When I tried to just open it

`❯ open nilg.csv  --raw `

I got this:

```
172450:   3b 22 22 3b  22 22 3b 22  22 0d 0a 22  4d 72 22 3b   ;"";"";"".."Mr";
172460:   22 57 69 6c  73 6f 6e 20  4d 50 22 3b  22 53 61 6d   "Wilson MP";"Sam
172470:   6d 79 22 3b  22 48 6f 75  73 65 20 6f  66 20 43 6f   my";"House of Co
172480:   6d 6d 6f 6e  73 0b 4c 6f  6e 64 6f 6e  0b 53 57 31   mmons.London.SW1
172490:   41 20 30 41  41 22 3b 22  22 3b 22 30  31 37 31 20   A 0AA";"";"0171 
1724a0:   32 31 39 20  33 30 30 30  22 3b 22 22  3b 22 44 55   219 3000";"";"DU
1724b0:   50 22 3b 22  4d 50 22 3b  22 22 3b 22  22 3b 22 22   P";"MP";"";"";""
1724c0:   3b 22 22 3b  22 22 3b 22  22 3b 22 22  3b 22 22 3b   ;"";"";"";"";"";
```

After a bit of scratching around I tried this:

```
❯ open nilg.csv  --raw | describe
binary
```

This confused me a lot, as every other tool I used had no problem with this file.

After a couple of hours of trying various things, like cutting columns, selecting some rows only using LibreOffice, and looking at other files, I realised that this was the only file that nushell complained about.

Anyway to cut a long story short, the underlying issue is that my file was encoded in ISO-8859-1 and used a few 'special' characters.  When I used LibreOffice to save it as UTF-8, and then try that file in nushell everything is fine.

Now this process of saving new files is not a good general solution going forward, and I think that nushell should not assume that all input files are in some UTF encoding.  There's a lot of historic data out there, from many platforms.

So is it possible to add a '--encoding' flag to `open` and to `save` so these aspects can be dealt with properly in nushell.

That way I can do:  `open nilg.csv --encoding iso-8859-1 --raw | lines `
without having an external tool to do re-encoding.

### PR DESCRIPTION
**Pull request by fdncred**
The intent of this PR is to enable a user to use `--encoding <encoding_name>` or `-e` for short, on `open` and `enter`. This is supposed to resolve #1939. However, there may be some unintended consequences, so I left the original code in `open.rs` for easy re-use if we need to patch something.

The encoding conversion code came straight from https://github.com/hsivonen/recode_rs and tweaked a tiny bit.

I have tested with some of the sample data here https://github.com/thuleqaid/rust-chardet/tree/master/tests/data.

`rust-chardet` may be a future enhancement so that one doesn't have to supply the encoding at all and chardet just guesses at the encoding.

Known problems: UTF-32 doesn't appear to be supported.

### CODE REVIEW

File: crates/nu-cli/src/commands/open.rs [hunk 1]
```diff
@@ -85,11 +130,175 @@ async fn open(args: CommandArgs, registry: &CommandRegistry) -> Result<OutputStr
 
 pub async fn fetch(
     cwd: &PathBuf,
-    location: &PathBuf,
+    _location: &PathBuf,
```
[the remark this answers is not in the document]
Comment (fdncred) [reply crates/nu-cli/src/commands/open.rs:133]: It was changed because rust wanted it to be changed, not me. :)

File: crates/nu-cli/src/deserializer.rs [hunk 2]
```diff
@@ -92,7 +92,7 @@ impl<'de, 'a> de::Deserializer<'de> for &'a mut ConfigDeserializer<'de> {
     {
         unimplemented!("deserialize_any")
     }
-    fn deserialize_bool<V>(self, visitor: V) -> Result<V::Value, Self::Error>
+    fn deserialize_bool<V>(self, _visitor: V) -> Result<V::Value, Self::Error>
```
Comment (jonathandturner) [inline crates/nu-cli/src/deserializer.rs:95]: Same comment with these. Seems like they're used. We're you setting warnings?

Comment (fdncred) [reply crates/nu-cli/src/deserializer.rs]: Oh ya. Good catch. I forgot I took a trip through deserialize land. These should be fixed now.
