### PR TITLE
Fix #6888 and rename `fill-na` to `fill-nan`

### LINKED ISSUE #6888: Does `fill-na` actually work?
### Describe the bug

`fill-na` has no help examples (?!), and moreover doesn't seem to have any referents in the codebase outside of its file, so I'm not sure how it's supposed to work. Nevertheless, based on what I know about `fill-null`, I'm positive that this behaviour below is a bug.

### How to reproduce

```
〉[1 2 3 NaN NaN null 4] | into df | fill-na 0
╭───┬─────╮
│ # │  0  │
├───┼─────┤
│ 0 │   1 │
│ 1 │   2 │
│ 2 │   3 │
│ 3 │ NaN │
│ 4 │ NaN │
│ 5 │     │
│ 6 │   4 │
╰───┴─────╯
〉[1 2 3 NaN NaN 4] | into lazy | fill-na 0 | collect
╭───┬─────╮
│ # │  0  │
├───┼─────┤
│ 0 │   1 │
│ 1 │   2 │
│ 2 │   3 │
│ 3 │ NaN │
│ 4 │ NaN │
│ 5 │   4 │
╰───┴─────╯
```

### Expected behavior

I expect the NaNs to be replaced with 0. On another note, shouldn't this command be named `fill-nan` ??

### Screenshots

_No response_

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:55:02 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Mehrbod2002**
The PR makes a process to change NaN value with `fill-na`
Reference to #6888  , `fll-na` changed to `fill-nan` , which is use by Polars crate and process of filling a NaN values coded on Value Object type value and indepintent from Polars.
Added example and description for Help command .

Fixes #6888 .

### CODE REVIEW

**Review by fdncred — APPROVED** [review]
LGTM. Thanks!

File: crates/nu-command/src/dataframe/lazy/mod.rs [hunk 1]
```diff
@@ -1,7 +1,7 @@
 pub mod aggregate;
 mod collect;
 mod fetch;
-mod fill_na;
+mod fill_nan;
```
Comment (sholderbach) [inline crates/nu-command/src/dataframe/lazy/mod.rs:4]: This just replaces `fill_na.rs` with `fill_nan.rs`. But the file for `fill_na` remains? What is the intent here?

Should this be a breaking change that removes the `fill-na` command. Or should there be both? 
(If thats the case both need to be added to the default context in the `bind_command!()` invocation below)

File: crates/nu-command/src/dataframe/values/nu_dataframe/mod.rs [hunk 2]
```diff
@@ -204,6 +204,24 @@ impl NuDataFrame {
...
+    pub fn columns(&self, span: Span) -> Result<Vec<Column>, ShellError> {
+        let height = self.df.height();
+        self.df
+            .get_columns()
+            .iter()
+            .map(
+                |col| match conversion::create_column(col, 0 as usize, height, span) {
+                    Ok(col) => Ok(col),
+                    Err(e) => Err(e),
+                },
```
Comment (sholderbach) [inline crates/nu-command/src/dataframe/values/nu_dataframe/mod.rs:220]: This `match` seems unnecessary.

File: crates/nu-command/src/dataframe/lazy/fill_nan.rs [hunk 3]
```diff
@@ -0,0 +1,112 @@
...
+            )
+            .input_type(Type::Custom("dataframe".into()))
+            .output_type(Type::Custom("dataframe".into()))
+            .category(Category::Custom("lazyframe".into()))
+    }
+
+    fn examples(&self) -> Vec<Example> {
+        vec![Example {
+            description: "Fills the NaN values by 0",
+            example: "[1 2 2 3 3] | into df | fill-nan 0",
```
Comment (sholderbach) [inline crates/nu-command/src/dataframe/lazy/fill_nan.rs:37]: This example is not really helpful as it doesn't show a value being replaced.

**Review by sholderbach — CHANGES_REQUESTED** [review]
It is a bit unclear to me if there is a place for both `fill-na` and `fill-nan`?

`pandas >=1.0` makes a distinction between missing values expressed through the IEEE 754 `NaN` that is also result of invalid float computations and masked missing values through the arrow representation.
I think polars doesn't fully have this distinction.

**Comment by Mehrbod2002** [comment]
> It is a bit unclear to me if there is a place for both `fill-na` and `fill-nan`?
> 
> `pandas >=1.0` makes a distinction between missing values expressed through the IEEE 754 `NaN` that is also result of invalid float computations and masked missing values through the arrow representation. I think polars doesn't fully have this distinction.

**Comment by Mehrbod2002** [comment]
@sholderbach 

Pandas , Polars which is used in our crate is not support NaN covering . NaN is Float 64 and Polars use vectors in Series .
In NuShell , developers coded an Object , which we can user can fill the array object with different values .
But when user use a NaN values with Float types value , fill_nan in Polars will work , except of this , it's not and as we use our Custome Value , I changed fill-nan command to fill NaN values independently from Polars.

Obviously we are changing `fill-na` command to `fill-nan` , so `fill-na` will delete by just rename its file and have changes on mod file .

File: crates/nu-command/src/dataframe/lazy/fill_nan.rs (hunk 3 above)
Comment (Mehrbod2002) [reply crates/nu-command/src/dataframe/lazy/fill_nan.rs]: Fixed

File: crates/nu-command/src/dataframe/values/nu_dataframe/mod.rs (hunk 2 above)
Comment (Mehrbod2002) [reply crates/nu-command/src/dataframe/values/nu_dataframe/mod.rs]: Fixed

**Comment by sholderbach** [comment]
Thanks for the quick turnaround! Sorry that I'm playing a bit of "bad cop" on the issue of renaming.
Makes it a breaking change in top of a bug fix.

NaN to me is somewhat specific to float numbers. While NA as "not available" also makes sense in other types.
But I can see the argument of sharing the naming with polars.

What is the behavior for columns that are not float or easily coerceable to float? Might be worth a small example as well, as documentation for those edge cases is always appreciated 

When we rename, can you please remove/`git rm` the old file.

Thanks for the solid first PR!

**Comment by Mehrbod2002** [comment]
> Thanks for the quick turnaround! Sorry that I'm playing a bit of "bad cop" on the issue of renaming. Makes it a breaking change in top of a bug fix.
> 
> NaN to me is somewhat specific to float numbers. While NA as "not available" also makes sense in other types. But I can see the argument of sharing the naming with polars.
> 
> What is the behavior for columns that are not float or easily coerceable to float? Might be worth a small example as well, as documentation for those edge cases is always appreciated
> 
> When we rename, can you please remove/`git rm` the old file.
> 
> Thanks for the solid first PR!

Do you think can we still use `fill-na`  but have my solution on it for now  ?
Because `fill-na` not working correctly . look , NuShell use Object which not implemented in `Polars` .
And further issue I pointed to , is about `types` .
So there is no another way to filling NaNs .
Later we can set `fill-nan` and reference to this pull-request.

**Comment by Mehrbod2002** [comment]
Do you think we have to close this pull request then?

**Comment by Mehrbod2002** [comment]
@sholderbach 
Do you think I have to close this pull request then ?

**Comment by Mehrbod2002** [comment]
Hope see some actions and specify the situation of this Pull request from you .
CC @fdncred  @jntrnr @rgwood @webbedspace 

Thanks

**Comment by fdncred** [comment]
Let's wait for @sholderbach to jump in again. If his concerns are addressed then we could probably land it.

File: crates/nu-command/src/dataframe/lazy/fill_nan.rs [hunk 4]
```diff
@@ -0,0 +1,125 @@
...
+            Ok(PipelineData::Value(
+                NuExpression::into_value(expr, call.head),
+                None,
+            ))
+        } else {
+            let cloned = value.clone();
+            let span = cloned.span()?;
+            let _type = NuDataFrame::get_df(cloned)?.get_type();
+
+            if _type[0] == DataType::Float64 {
```
Comment (sholderbach) [inline crates/nu-command/src/dataframe/lazy/fill_nan.rs:79]: This type check only works for single columns correctly and else will only look at the first column, which is a problem for full dataframes if the first column is a float:
grafik

**Example 1:** non numeric data in the second column. (I don't think we have to worry about that too much if we consider that outside the scope for `fill-nan`)

**Example 2:** same problem as reported in #6888 for a single column of mixed ints and nan.

**Example 3:** works because everything was valid float data before `into df`

I think to close #6888 example 2 should also work.

**NB:** `_variable` names by convention are mostly used in special circumstances (unused params and macro interior). To avoid keyword conflicts there is the `r#` prefix but in this case it is probably better to just give a slightly longer more descriptive name.

File: crates/nu-command/src/dataframe/lazy/mod.rs (hunk 1 above)
Comment (sholderbach) [reply crates/nu-command/src/dataframe/lazy/mod.rs:4]: OK with the name change.
Please delete `fill_na.rs`

File: crates/nu-command/src/dataframe/values/nu_dataframe/mod.rs [hunk 5]
```diff
@@ -204,6 +204,19 @@ impl NuDataFrame {
...
+    pub fn get_type(&self) -> Vec<DataType> {
+        self.df.dtypes()
+    }
+
+    pub fn columns(&self, span: Span) -> Result<Vec<Column>, ShellError> {
+        let height = self.df.height();
+        self.df
+            .get_columns()
+            .iter()
+            .map(|col| conversion::create_column(col, 0 as usize, height, span))
```
Comment (sholderbach) [inline crates/nu-command/src/dataframe/values/nu_dataframe/mod.rs:216]:
```suggestion
            .map(|col| conversion::create_column(col, 0, height, span))
```

File: crates/nu-command/src/dataframe/lazy/fill_nan.rs [hunk 6]
```diff
@@ -0,0 +1,125 @@
...
+                "Expression to use to fill the NAN values",
+            )
+            .input_type(Type::Custom("dataframe".into()))
+            .output_type(Type::Custom("dataframe".into()))
+            .category(Category::Custom("lazyframe".into()))
+    }
+
+    fn examples(&self) -> Vec<Example> {
+        vec![Example {
+            description: "Fills the NaN values by 0",
```
Comment (sholderbach) [inline crates/nu-command/src/dataframe/lazy/fill_nan.rs:36]:
```suggestion
            description: "Fills the NaN values with 0",
```

File: crates/nu-command/src/dataframe/lazy/fill_nan.rs [hunk 7]
```diff
@@ -0,0 +1,125 @@
...
+            let expr: NuExpression = expr.into_polars().fill_nan(fill).into();
+
+            Ok(PipelineData::Value(
+                NuExpression::into_value(expr, call.head),
+                None,
+            ))
+        } else {
+            let cloned = value.clone();
+            let span = cloned.span()?;
+            let _type = NuDataFrame::get_df(cloned)?.get_type();
```
Comment (sholderbach) [inline crates/nu-command/src/dataframe/lazy/fill_nan.rs:77]: Not a blocker for me but this looks inefficient to copy the whole value with potentially the dataframe just to get the types.

File: crates/nu-command/src/dataframe/lazy/fill_nan.rs [hunk 8]
```diff
@@ -0,0 +1,125 @@
...
+#[derive(Clone)]
+pub struct LazyFillNA;
+
+impl Command for LazyFillNA {
+    fn name(&self) -> &str {
+        "fill-nan"
+    }
+
+    fn usage(&self) -> &str {
+        "Replaces NA values with the given expression"
```
Comment (sholderbach) [inline crates/nu-command/src/dataframe/lazy/fill_nan.rs:19]:
```suggestion
        "Replaces NaN values with the given expression"
```

**Review by sholderbach — COMMENTED** [review]
Happy you are excited about this change. We don't have to hurry as it is > 2 weeks till the next release. The core team currently doesn't have too much time to dedicate to the dataframe feature (part of why we have removed it from the core distribution)

File: crates/nu-command/src/dataframe/lazy/fill_nan.rs (hunk 4 above)
Comment (Mehrbod2002) [reply crates/nu-command/src/dataframe/lazy/fill_nan.rs:79]: I solved this issue .
Yes `_type` parameter actually I used is force code to act code like this. 
Beside of this issue , do you think we have to implement something which is going to be use with this example too  ? 
`[[a,b]; [[nan nan] [nan nan]] | fill-nan 0 ]`

I can implement something in `nu_dataframe` to call itself and match types to replace NaNs values .

Do you think is it a good id ?

Comment (Mehrbod2002) [reply crates/nu-command/src/dataframe/lazy/fill_nan.rs]: Thanks for your time and helping and apologize to not been patient , I am not familiar very lot yet , and new on this platform ( on contributing ) .
Anyway I deleted our first condition , because our second can do it anyway .
I added for List and can be processed now with Dataframe in Dataframe too now .

Thanks again @sholderbach  . Learning from you .

**Review by sholderbach — APPROVED** [review]
Awesome, that works for all examples now!
Thanks for sticking with us.

**Comment by Mehrbod2002** [comment]
> Awesome, that works for all examples now! Thanks for sticking with us.

Thanks a lot @sholderbach .
