### PR TITLE
Fix merging child stack into parent

### LINKED ISSUE #12423: `mut` variables don't update in v0.92
### Describe the bug

Since updating to 0.92 `mut` variables don't change on update. Works fine in 0.91

### How to reproduce

Two examples after starting an interactive shell:

```nu
> mut x = 1
> $x = 2
> $x
1
>
> mut r = {a: 1, b: "abc"}
> $r.a = 2
> $r.c = "xxx"
> $r
{a: 1, b: "abc"}
```

### Expected behavior

I expect nu 0.92 to update `mut` values on update (upsert). Based on the two examples above I would expect:

- `$x == 2`
- `$r == {a: 2, b: "abc", c: "xxx"}`

### Screenshots

_No response_

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.92.1                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | macos-aarch64                       |
| build_target       | aarch64-apple-darwin                |
| rust_version       | rustc 1.77.1 (7cf61ebde 2024-03-27) |
| rust_channel       | stable-aarch64-apple-darwin         |
| cargo_version      | cargo 1.77.1 (e52e36006 2024-03-26) |
| build_time         | 2024-04-04 21:28:51 +01:00          |
| build_rust_channel | release                             |
| allocator          | mimalloc                            |
| features           | default, sqlite, trash, which       |
| installed_plugins  |                                     |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by IanManske**
# Description
Fixes #12423 where changes to mutable variables are not properly persisted after a REPL entry.

### CODE REVIEW

**Comment by fdncred** [comment]
I tested it and it fixes the problem. Thanks for the quick fix!

File: crates/nu-plugin-test-support/src/plugin_test.rs [hunk 1]
```diff
@@ -337,12 +337,6 @@ impl PluginTest {
                 // All equal, and same length
                 Ok(true)
             }
-            (Value::Range { val: a_rng, .. }, Value::Range { val: b_rng, .. }) => {
```
Comment (fdncred) [inline crates/nu-plugin-test-support/src/plugin_test.rs:340]: seems like an odd thing to remove for this pr?

Comment (IanManske) [reply crates/nu-plugin-test-support/src/plugin_test.rs:340]: Somehow my other range PR was affecting the CI for this PR. I merged with main and fixed a compile error that was somehow missed? I think the CI was drunk, it also failed to "download bash" for one of the runs
