### PR TITLE
Fix ParseOption handling in from ini

### LINKED ISSUE #17569: nu_plugin_formats: allow setting parse options in `from ini`
### Basics

- [x] I have done a basic search through the issue tracker to find similar or related issues.
- [x] I have made myself familiar with the available features of Nushell for the particular area this enhancement request touches.

### Description

`rust-ini` has multiple configurable [`ParseOption`s](https://docs.rs/rust-ini/latest/ini/struct.ParseOption.html).
It would be great if these could be configured using flags when running `from ini`. Instead of `load_from_str`, `load_from_str_opt` would have to be used.
Since ini is not standardized and many variations exist, this is important so parsing can be more closely aligned to other tools interacting with the files.

This should also address #12477 by allowing users to toggle the `enabled_escape` option (which is on by default and causes the undesired behavior).

### PR DESCRIPTION
**Pull request by teddygood**
Closes #17569
Related to #12477

## Description

Switched `from ini` from `Ini::load_from_str` to `Ini::load_from_str_opt` and wired command flags to rust-ini `ParseOption` fields.

Added flags:
- `--no-quote`
- `--no-escape`
- `--indented-multiline-value`
- `--preserve-key-leading-whitespace`

Default behavior is unchanged when flags are not provided.

## Tests + formatting checks

- Ran `target/debug/nu -c "use toolkit.nu; toolkit check pr"` (passes)
- Validated on Windows: `from ini --no-escape` correctly parses paths like `C:\Windows\System32\xcopy.exe`

### More flexible INI parsing options

`from ini` now supports rust-ini ParseOption flags (`--no-quote`, `--no-escape`, `--indented-multiline-value`, `--preserve-key-leading-whitespace`) for better compatibility with INI variations. 

In particular, `from ini --no-escape` allows Windows-style paths with backslashes (including `\x`) to be parsed literally.

## Tasks after submitting

- [ ] Update the [documentation](https://github.com/nushell/nushell.github.io)

### CODE REVIEW

File: crates/nu_plugin_formats/src/from/ini.rs [hunk 1]
```diff
@@ -21,6 +21,22 @@ impl SimplePluginCommand for FromIni {
     fn signature(&self) -> Signature {
         Signature::build(self.name())
             .input_output_types(vec![(Type::String, Type::record())])
+            .switch("no-quote", "Disable quote handling for values", None)
+            .switch(
+                "no-escape",
+                "Disable escape sequence handling for values",
+                None,
```
Comment (fdncred) [inline crates/nu_plugin_formats/src/from/ini.rs]: Can we have short's for all these long flags please?

File: crates/nu_plugin_formats/src/from/ini.rs [hunk 2]
```diff
@@ -21,6 +21,22 @@ impl SimplePluginCommand for FromIni {
     fn signature(&self) -> Signature {
         Signature::build(self.name())
             .input_output_types(vec![(Type::String, Type::record())])
+            .switch("no-quote", "Disable quote handling for values", None)
```
Comment (fdncred) [inline crates/nu_plugin_formats/src/from/ini.rs]: I think it might be better if these 2 no-blah flags are not negatives. So `--quote` and `--escape` vs `--no-quote` and `--no-escape`. Especially since the last two are positive flags vs negative flags like these. Being consistent would help I think.

File: crates/nu_plugin_formats/src/from/ini.rs [hunk 3]
```diff
@@ -83,18 +117,30 @@ impl SimplePluginCommand for FromIni {
...
-    }]
+            description: "Converts ini formatted string to record",
+            result: Some(Value::test_record(record! {
+                "foo" => Value::test_record(record! {
+                    "a" =>  Value::test_string("1"),
+                    "b" =>  Value::test_string("2"),
+                }),
+            })),
+        },
+        Example {
```
Comment (fdncred) [inline crates/nu_plugin_formats/src/from/ini.rs:133]: good example. Can we have an example for each of the new flags?

**Comment by teddygood** [comment]
> Generally, the code looks good. Thanks! I have a few things that I'd like to change that I mentioned above.

Thanks for the careful review. I’ll reply to each comment directly. 

On the typo item, with our current dependency (`rust- ini` 0.21.3), the public field is still `enabled_indented_mutiline_value`, and changing the code to `...multiline...` fails compilation. 

For now, I think we should add `enabled_indented_mutiline_value = "enabled_indented_mutiline_value"` under `[default.extend-identifiers]` in `typos.toml` to keep CI green. Once `rust-ini` releases the spelling fix, I’ll update the code usage and remove this exception. Does that sound good?

File: crates/nu_plugin_formats/src/from/ini.rs (hunk 2 above)
Comment (teddygood) [reply crates/nu_plugin_formats/src/from/ini.rs]: Agreed, I’ll switch to consistent positive naming for these parser options.

File: crates/nu_plugin_formats/src/from/ini.rs (hunk 1 above)
Comment (teddygood) [reply crates/nu_plugin_formats/src/from/ini.rs]: Thanks. I’ll add short flags for all four options in this PR so they’re easier to use from the CLI.

File: crates/nu_plugin_formats/src/from/ini.rs (hunk 3 above)
Comment (teddygood) [reply crates/nu_plugin_formats/src/from/ini.rs:133]: I’ll add an example for each new flag.

**Comment by fdncred** [comment]
> For now, I think we should add enabled_indented_mutiline_value = "enabled_indented_mutiline_value" under [default.extend-identifiers] in typos.toml to keep CI green. Once rust-ini releases the spelling fix, I’ll update the code usage and remove this exception. Does that sound good?

ugh, but ya. if the upstream crate has a typo we need to ignore it for now.

File: crates/nu_plugin_formats/src/from/ini.rs (hunk 2 above)
Comment (lunagl) [reply crates/nu_plugin_formats/src/from/ini.rs]: Does this mean that the default is "off" for all flags? Because then we'd be deviating from the rust-ini default and introducing a breaking change

Comment (fdncred) [reply crates/nu_plugin_formats/src/from/ini.rs]: Good point. We want to avoid breaking changes if we can. I hate having negative flags and positive flags, that's so confusing but if we have to do that to avoid breaking changes I guess it's fine.

Comment (teddygood) [reply crates/nu_plugin_formats/src/from/ini.rs]: Thanks for calling this out. I should have thought this through more carefully.

**Comment by fdncred** [comment]
ping me when you're ready for me to review again.

**Comment by teddygood** [comment]
> ping me when you're ready for me to review again.

@fdncred Thanks. I’m done. Could you review again?

File: crates/nu_plugin_formats/src/from/ini.rs [hunk 4]
```diff
@@ -21,6 +21,22 @@ impl SimplePluginCommand for FromIni {
     fn signature(&self) -> Signature {
         Signature::build(self.name())
             .input_output_types(vec![(Type::String, Type::record())])
+            .switch("no-quote", "Disable quote handling for values", Some('q'))
```
Comment (fdncred) [inline crates/nu_plugin_formats/src/from/ini.rs]: This is a nit but these need to start with a capital letter (which they do) and end with a period (which they don't). We've just had 10 PRs to try and standardize this with the last PR unmerged right now.

```suggestion
            .switch("no-quote", "Disable quote handling for values.", Some('q'))
```

File: crates/nu_plugin_formats/src/from/ini.rs [hunk 5]
```diff
@@ -21,6 +21,22 @@ impl SimplePluginCommand for FromIni {
...
+            .switch(
+                "no-escape",
+                "Disable escape sequence handling for values",
```
Comment (fdncred) [inline crates/nu_plugin_formats/src/from/ini.rs]:
```suggestion
                "Disable escape sequence handling for values.",
```

File: crates/nu_plugin_formats/src/from/ini.rs [hunk 6]
```diff
@@ -21,6 +21,22 @@ impl SimplePluginCommand for FromIni {
...
+                Some('e'),
+            )
+            .switch(
+                "indented-multiline-value",
+                "Allow values to continue on indented lines",
```
Comment (fdncred) [inline crates/nu_plugin_formats/src/from/ini.rs]:
```suggestion
                "Allow values to continue on indented lines.",
```

File: crates/nu_plugin_formats/src/from/ini.rs [hunk 7]
```diff
@@ -21,6 +21,22 @@ impl SimplePluginCommand for FromIni {
...
+                Some('m'),
+            )
+            .switch(
+                "preserve-key-leading-whitespace",
+                "Preserve leading whitespace in keys",
```
Comment (fdncred) [inline crates/nu_plugin_formats/src/from/ini.rs]:
```suggestion
                "Preserve leading whitespace in keys.",
```

File: crates/nu_plugin_formats/src/from/ini.rs [hunk 8]
```diff
@@ -83,18 +117,50 @@ impl SimplePluginCommand for FromIni {
...
+            result: Some(Value::test_record(record! {
+                "foo" => Value::test_record(record! {
+                    "bar" => Value::test_string("\"quoted\""),
+                }),
+            })),
+        },
+        Example {
+            example: "[\"[foo]\" \"bar=line one\" \"  line two\"] | str join (char newline) | from ini --indented-multiline-value",
+            description: "Allow values to continue on indented lines",
+            result: None,
```
Comment (fdncred) [inline crates/nu_plugin_formats/src/from/ini.rs]: why are there no results in these last 2. it would be great to have results because examples are tested as tests during cargo test.

File: crates/nu_plugin_formats/src/from/ini.rs (hunk 4 above)
Comment (teddygood) [reply crates/nu_plugin_formats/src/from/ini.rs]: Thanks for pointing this out. I’ll update the other ones below as well.

File: crates/nu_plugin_formats/src/from/ini.rs (hunk 8 above)
Comment (teddygood) [reply crates/nu_plugin_formats/src/from/ini.rs]: Good catch, thanks. I’ll add results for those two examples.

**Comment by teddygood** [comment]
@fdncred I’m done. Could you review again?

**Comment by fdncred** [comment]
Thanks
