### PR TITLE
change the test to use the origin column

### LINKED ISSUE #1877: Windows - Error piping string values with multi-byte characters into stdin of external process
**Describe the bug**
The test `takes_rows_of_nu_value_strings_and_pipes_it_to_stdin_of_external` is consistently failing on my Windows machine, but not my MacOS machine. This particular test case is piping the string `Andrés` into `chop`, but `Andrés` is being omitted. 

I was able to verify this by writing the `line` variable seen [here](https://github.com/nushell/nushell/blob/master/crates/nu-cli/src/utils/test_bins.rs#L49) into a log file and trying different input.

Checking the [Rust stdin docs](https://doc.rust-lang.org/std/io/fn.stdin.html) indicates `the Windows implementation of this stream does not support non-UTF-8 byte sequences`. This [old rust issue](https://github.com/rust-lang/rust/issues/23344) also indicates there are some issues handling multi-byte character encoding with stdio on Windows.

Changing from `Andrés` to `Andres` fixes this issue, however then we would be spelling Andrés name incorrectly 😞 . An alternative would be to change the test to use the `origin` column.

**To Reproduce**
1.  Run `cargo test --all --features=stable` on Windows To view the error.
2.  Change `Andrés` to `Andres` to see the test now passing

Alternative:
1. Create a Rust program to print out all args passed into it.
```
fn main() {
    use std::env;

    for argument in env::args() {
        println!("{}", argument);
    }
}
```
2. Create a test CSV exactly as it is in the [test case](https://github.com/nushell/nushell/blob/ae8c8649345b85c05fe69c210fedbc1f7417ce76/tests/shell/pipeline/commands/internal.rs#L13)
3. Inside nu, run the pipeline `open nu_times.csv | get name | ^echo $it | target\debug\your_rust_program.exe $it`
4. Toggle `nu_times.csv` between `Andrés` and `Andres` to view difference in output.

**Expected behavior**
I would expect this test to pass, however this looks to be a bug that isn't due to Nushell. It could be a problem for Windows users piping data into external programs.

**Configuration (please complete the following information):**
 - Windows 10
 - Nu version 0.14.1

**Other**
- Do we have a CI running Windows and is this test failing?
- If there is no great solution, this should be documented.

### PR DESCRIPTION
**Pull request by notryanb**
Fixes #1877 

Rather than change Andrés name, I opted to use the `origin` column from the csv. The assertion is a little strange, because the string `\"Estados Unidos\" ` is passed to `chop`. The last escaped quote is chopped off, which looks awkward to me, but is correct.

### CODE REVIEW

File: tests/shell/pipeline/commands/internal.rs [hunk 1]
```diff
@@ -31,7 +31,8 @@ fn takes_rows_of_nu_value_strings_and_pipes_it_to_stdin_of_external() {
             "#
         ));
 
-        assert_eq!(actual.out, "AndKitKat");
+        // chop will remove the last escaped double quote from \"Estados Unidos\"
+        assert_eq!(actual.out, "\"Estados Unidos");
```
Comment (thegedge) [inline tests/shell/pipeline/commands/internal.rs:35]: `Estados Unido` should be the expected output 🙂

Comment (notryanb) [reply tests/shell/pipeline/commands/internal.rs:35]: I thought it would too, but due to the argument having spaces, it is adding surrounding `"` and counting them as characters in the argument.

I'll double check this.

Comment (thegedge) [reply tests/shell/pipeline/commands/internal.rs:35]: Ohhh, interesting. If quotes are being added, we should look into fixing that 😬

Comment (notryanb) [reply tests/shell/pipeline/commands/internal.rs:35]: Here is the difference in output between my Windows machine and macbook when logging the line from stdin inside `chop`

### Windows: 
```
Ok("Canada")
Ok("\"New Zealand\"")
Ok("Ecuador")
Ok("\"Estados Unidos\"")
```

### Mac: 
```
Ok("Canada")
Ok("New Zealand")
Ok("Ecuador")
Ok("Estados Unidos")
```

Comment (thegedge) [reply tests/shell/pipeline/commands/internal.rs:35]: Oh wow, that's really interesting. There's nothing in our code or the csv crate that would separate windows behaviour from other systems, so my guess is that the external `echo` on windows does this when there are spaces in an argument.

What happens if you drop the `^echo $it` line? There's a possibility that there may no longer be lines (I think `^echo` was adding newlines for us), so you may have to tweak the test. The main thing here is that we feed an internal command into the stdin of an external (which we get from `get origin | nu --testbin chop`).

**Comment by notryanb** [comment]
@thegedge I opted to go with `get origin` and asserting on one of the rows with a non-spaced value. I thought about what you said re: this behavior is coming from outside of nu.

I am assuming an experienced Windows user that needs to use native `echo` would be aware of this difference in behavior. I agree the point that this specific test is to check for Nu's ability to feed an internal command into the stdin of an external program - not test for some OS specific behavior.

**Comment by thegedge** [comment]
That works for me. I think this is one of the few tests where we call an external that isn't built into nushell, and has been really flaky. If this something that will make it deterministic, 🎉 🎉 🎉
