### PR TITLE
fixed handling of ranges with respect to parentheses

### LINKED ISSUE #16969: Why does `0..<(random int 1..2) ` give me a "external command" error?
### Discussed in https://github.com/nushell/nushell/discussions/16968

<div type='discussions-op-text'>

<sup>Originally posted by **halloleo** November  3, 2025</sup>
I need a random range, either `0..0` (containing 1 element) or `0..1` (containing 2 elements) . For this I tried:

    0..<(random int 1..2) 

but I get an `nu::shell::external_command` error. Why is that? 

This is particularly strange because

    0..<(["a", "b"] | length)

works as expected. 

Both expressions use the command execution parentheses, both use only nu builtins....</div>

### PR DESCRIPTION
**Pull request by blackhat-hemsworth**
## Release notes summary - What our users need to know

added logic to exclude parenthesized expressions in the search for the optional second piece of a range expression, ex

```0..(1..2 | first)```

will now parse as a simple range `0..1` rather than an invalid complex range `0..(1..2`

fixes #16969 

## Tasks after submitting

- [ ] Update the [documentation](https://github.com/nushell/nushell.github.io)

### CODE REVIEW

File: crates/nu-parser/src/parser.rs [hunk 1]
```diff
@@ -1911,8 +1911,16 @@ pub fn parse_range(working_set: &mut StateWorkingSet, span: Span) -> Option<Expr
...
+    let dotdot_pos: Vec<_> = token
+        .match_indices("..")
+        .filter_map(|(pos, _)| {
+            // paren_depth = count of unclosed parens prior to pos
+            let before = &token[..pos];
+            let paren_depth = before.chars().filter(|&c| c == '(').count()
+                - before.chars().filter(|&c| c == ')').count();
+            if paren_depth == 0 { Some(pos) } else { None }
+        })
+        .collect();
```
Comment (blindFS) [inline crates/nu-parser/src/parser.rs:1923]: The complexity is not ideal, we can easily make it O(n) by a stateful iteration.

**Comment by blindFS** [comment]
Thanks for working on this issue.

I think the method is correct, just needs some optimizations.

BTW there're edge cases where unmatched `(` could be in quoted string which shouldn't increase paren_depth, but that bug is pretty common in other places of the parser. We may ignore them ATM.

File: crates/nu-parser/src/parser.rs (hunk 1 above)
Comment (blindFS) [reply crates/nu-parser/src/parser.rs:1923]: Forget about it, it probably won't hurt much considering `..` is not a common pattern.

**Comment by blackhat-hemsworth** [comment]
ah, I had a feeling there was some weird case lurking, thanks for letting me know!

**Comment by fdncred** [comment]
Thanks

File: crates/nu-parser/src/parser.rs [hunk 2]
```diff
@@ -1911,8 +1911,16 @@ pub fn parse_range(working_set: &mut StateWorkingSet, span: Span) -> Option<Expr
...
 
-    // First, figure out what exact operators are used and determine their positions
-    let dotdot_pos: Vec<_> = token.match_indices("..").map(|(pos, _)| pos).collect();
+    let dotdot_pos: Vec<_> = token
+        .match_indices("..")
+        .filter_map(|(pos, _)| {
+            // paren_depth = count of unclosed parens prior to pos
+            let before = &token[..pos];
+            let paren_depth = before.chars().filter(|&c| c == '(').count()
+                - before.chars().filter(|&c| c == ')').count();
```
Comment (blindFS) [inline crates/nu-parser/src/parser.rs:1920]: Probably needs `checked_sub` here. #17146
