### PR TITLE
Make hook execution stream instead of collecting

### LINKED ISSUE #7431: `ListStream` pages are not displayed before pressing `ctrl+c`
### Describe the bug

Say you have a command that returns a `ListStream` of values slowly. Nu's `PagingTableIterator` _should_ handle this well; its purpose is to stream values into a buffer until it has reached `STREAM_PAGE_SIZE` (currently 1000) items _or_  a full second has elapsed, and then render that "page" of values as a table. See [here](https://github.com/nushell/nushell/blob/2bacc29d30fc6bb4798c9ef99801267492feb80d/crates/nu-command/src/viewers/table.rs#L1571).

However, I'm noticing that pages are not being displayed until the `ListStream` finishes or I press `ctrl+c`. This is a little tricky to reproduce with a regular Nu install, so [here's a branch where I created a new streaming command and set `STREAM_PAGE_SIZE` to 10.](https://github.com/nushell/nushell/compare/main...rgwood:nushell:liststream-experiments)

image

### How to reproduce

1. Check out my `liststream-experiments` branch: https://github.com/rgwood/nushell/tree/liststream-experiments
2. `cargo run`
3. `errmaker 300` (or whatever number you like)
4. Observe that the numbers aren't printed unless you press `ctrl+c`

### Expected behavior

I expected Nu to display pages before pressing `ctrl+c`.

### Screenshots

_No response_

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.72.2                                   |
| branch             | liststream-experiments                   |
| commit_hash        | bd788336a2dd9416141595c700162f73284d1c9b |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.72.2                                   |
| build_time         | 2022-12-10 17:33:30 -08:00               |
| build_rust_channel | debug                                    |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

### Additional context

I wonder if this is somehow related to https://github.com/nushell/nushell/issues/7342

### PR DESCRIPTION
**Pull request by rgwood**
Closes #7431. In a nutshell:
- `run_hook_block()` in repl.rs was collecting all input into a `Value` instead of handling streaming input properly
- this was a problem because now we have a default `display_output` hook that _everything_ gets piped to
- this PR fixes the problem by tweaking `run_hook_block()` to return a `PipelineData` instead of a `Value`

After this change, individual pages are rendered as they finish. This is a little easier to see if I tweak `STREAM_PAGE_SIZE` in table.rs to 10:
image

## Future work

This does _not_ fix https://github.com/nushell/nushell/issues/7342.

### CODE REVIEW

File: crates/nu-cli/src/repl.rs [hunk 1]
```diff
@@ -709,6 +709,13 @@ pub fn eval_hook(
 ) -> Result<PipelineData, ShellError> {
     let value_span = value.span()?;
 
+    // Hooks can optionally be a record in this form:
+    // {
+    //     condition: {|before, after| ... }  # block that evaluates to true/false
+    //     code: # block or a string
+    // }
+    // The condition block will be run to check whether the main hook (in `code`) should be run.
+    // If it returns true (the default if a condition block is not specified), the hook should be run.
```
Comment (rgwood) [inline crates/nu-cli/src/repl.rs:718]: Not really related to this change, I just had trouble understanding this part of the hooks code and decided to add comments. More deets in the original PR: https://github.com/nushell/nushell/pull/5982
