### PR TITLE
Errors when `let in`, `let env` and similar commands are passed.

### LINKED ISSUE #5848: Cannot shadow some builtin variables
### Describe the bug

Generally, it is possible to shadow any variable declaration, with a `let` binding, or by assigning it as a function argument. For some builtin variables (`$env` and `$nu` for example), this silently fails.

### How to reproduce

Attempt to shadow a builtin variable with a let-binding.

```nu
let env = 42
$env
```

### Expected behavior

Either the first line should throw an error, saying that shadowing builtin variable definitions is not valid, or it should complete successfully, and further references to `$env` should reference the shadowed value.

### Screenshots

```nu
> let env = 42
> $env == 42
false
```

### Configuration

> version | transpose key value | to md --pretty

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.63.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | macos-x86_64                                    |
| build_target       | x86_64-apple-darwin                             |
| rust_version       | rustc 1.61.0                                    |
| cargo_version      | cargo 1.61.0                                    |
| pkg_version        | 0.63.0                                          |
| build_time         | 1980-01-01 00:00:00 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by merelymyself**
# Description

Fixes #5848. 

# Tests

Make sure you've done the following:

- [x] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [x] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [x] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by WindSoilder** [comment]
@merelymyself You can apply my commit and try it :)
https://github.com/WindSoilder/nushell/commit/7cd22256e30abdfa7c1ada7c2c2b99849dbee8c0

**Comment by kubouch** [comment]
I think this should be treated in the parser when parsing `let`. When calling `echo $env` for example, the parser detects it's a built-in and short-circuits instead of looking it up like a normal variable. Parsing `let` still allows you to assign a unique ID to the built-in variables, but looking them up short-circuits and that's why it seems impossible to shadow them. So the cleanest solution to me seems to add these special cases into parsing `let`.

File: crates/nu-parser/src/parse_keywords.rs [hunk 1]
```diff
@@ -2286,6 +2286,28 @@ pub fn parse_let(
                             parse_var_with_opt_type(working_set, &spans[1..(span.0)], &mut idx);
                         error = error.or(err);
 
+                        let var_name =
+                            String::from_utf8_lossy(working_set.get_span_contents(spans[1]))
+                                .to_string();
+
+                        if var_name == "in" {
```
Comment (WindSoilder) [inline crates/nu-parser/src/parse_keywords.rs:2293]: What about using the following, I think it can reduce lines
```rust
if ["in", "nu", "env", "nothing"].contains(&var_name.as_str()) {
    error = error.or_else(...)
}
```

File: crates/nu-parser/src/parse_keywords.rs [hunk 2]
```diff
@@ -2286,6 +2286,28 @@ pub fn parse_let(
                             parse_var_with_opt_type(working_set, &spans[1..(span.0)], &mut idx);
                         error = error.or(err);
 
+                        let var_name =
+                            String::from_utf8_lossy(working_set.get_span_contents(spans[1]))
+                                .to_string();
```
Comment (WindSoilder) [inline crates/nu-parser/src/parse_keywords.rs:2291]: Sorry, I have no idea about it, can you please explain why we need to get_span_contents from `spans[1]`, but not from `lvalue`'s span?

File: crates/nu-parser/src/parse_keywords.rs (hunk 1 above)
Comment (merelymyself) [reply crates/nu-parser/src/parse_keywords.rs]: That's a great suggestion, thanks!

File: crates/nu-parser/src/parse_keywords.rs (hunk 2 above)
Comment (merelymyself) [reply crates/nu-parser/src/parse_keywords.rs:2291]: Both are the same afaik, but I guess using `lvalue`'s span will make more sense.

**Comment by kubouch** [comment]
OK, thanks, looks good to me!
