### PR TITLE
Fix cp bug

### LINKED ISSUE #5637: cp will clear the source file if source and destination is the same
### Describe the bug

As title

### How to reproduce

1. echo asdfasdfasdf | save test_file
2. cp test_file test_file

### Expected behavior

Maybe we can make it behave like zsh, which throws out the following message with exit code `1`:
```bash
cp: test_file and test_file are identical (not copied).
```

### Screenshots
Screen Shot 2022-05-25 at 17 24 47

### Configuration

```
| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.63.0                                      |
| branch             |                                             |
| commit_hash        |                                             |
| build_os           | macos-x86_64                                |
| build_target       | x86_64-apple-darwin                         |
| rust_version       | rustc 1.62.0-nightly (34a6c9f26 2022-04-13) |
| rust_channel       | nightly-x86_64-apple-darwin                 |
| cargo_version      | cargo 1.62.0-nightly (e2e2dddeb 2022-04-05) |
| pkg_version        | 0.63.0                                      |
| build_time         | 2022-05-25 17:18:34 +08:00                  |
| build_rust_channel | release                                     |
| features           | default, trash, which, zip                  |
| installed_plugins  |                                             |
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Kangaxx-0**
# Description

Fix #5637

image

image

---
Update - New iteration also address symbolic issue with follow checking points:

On Unix-like OS, `cp.txt` is the symbolic link of `1.txt`
- [x]  cp -i 1.txt 1.txt -> Should fail
- [x]  cp -i cp.txt cp.txt -> Should fail
- [x]  cp -i 1.txt cp.txt -> Should fail
- [x]  cp -i cp.txt 1.txt -> Should fail

# Tests

Make sure you've run and fixed any issues with these commands:

- [x] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [x] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [x] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by WindSoilder** [comment]
Hi, thanks for your PR, I have little thought about this

File: crates/nu-command/src/filesystem/cp.rs [hunk 1]
```diff
@@ -154,6 +154,19 @@ impl Command for Cp {
                     if src.is_file() {
                         let res = if interactive && dst.exists() {
                             interactive_copy_file(interactive, src, dst, span)
+                        } else if src == dst {
```
Comment (WindSoilder) [inline crates/nu-command/src/filesystem/cp.rs:157]: this `else if src == dst` should check first rather than `if interactive && dst.exists()`.  Or else `cp test_file test_file -i` will also clear the origin file

File: crates/nu-command/src/filesystem/cp.rs [hunk 2]
```diff
@@ -223,6 +236,19 @@ impl Command for Cp {
                     if s.is_file() {
                         let res = if interactive && d.exists() {
                             interactive_copy_file(interactive, s, d, span)
+                        } else if src == dst {
```
Comment (WindSoilder) [inline crates/nu-command/src/filesystem/cp.rs:239]: The same to above comment

**Comment by WindSoilder** [comment]
And refer to your commit: https://github.com/nushell/nushell/pull/5642/commits/def702d398c81f9d7c330939158f5cb6bd92d0e7 , I think we still need to have UT for this behavior (but not sure why it's failed)

File: crates/nu-command/src/filesystem/cp.rs (hunk 1 above)
Comment (Kangaxx-0) [reply crates/nu-command/src/filesystem/cp.rs:157]: Interesting, I thought `-i` is not in use, it turned out my nu is out of dated :) Thanks for the catching

Comment (Kangaxx-0) [reply crates/nu-command/src/filesystem/cp.rs]: Done

**Comment by fdncred** [comment]
changing to draft until completed to prevent accidental merge.

**Comment by WindSoilder** [comment]
I've manually test the build on mac, it works fine for me, but it's strange that the test code is failed.  After debugging, the `run` method in `cp` even not executed..

**Comment by fdncred** [comment]
@WindSoilder are you saying this is ready to merge?

**Comment by WindSoilder** [comment]
I'm afraid the answer is no, I just debug and find out one corner case which needs to be handled.

If we copy symbolic file, we still get success message.
```
1. echo aaa | save test1
2. ln -s test1 test2
3. cp test2 test2
```

And then the original `test1` file is going to be empty.

**Comment by fdncred** [comment]
> Sorry, I'm afraid the answer is no, 

ok, thanks for the followup. We'll just leave it draft until this gets corrected.

**Comment by Kangaxx-0** [comment]
New iteration and I've added checking list in description

File: crates/nu-command/tests/commands/cp.rs [hunk 3]
```diff
@@ -318,3 +318,17 @@ fn copy_dir_symlink_file_body_not_changed() {
         assert!(actual.contains("hello_data"));
     });
 }
+
```
Comment (WindSoilder) [inline crates/nu-command/tests/commands/cp.rs:321]: Can you please add a comment says that it doesn't work in windows, needs more work. ?

For the remaining code, looks good to me :-)

**Comment by Kangaxx-0** [comment]
I don't know why the unit test still failing in CI, I've got all test cases passed locally 
image

**Comment by fdncred** [comment]
i have your tested your pr on windows, merged with the latest main, i had to build different and test differently than the ci, but all tests worked for me.  the ci is kind of mystical and probably only @rgwood can unravel why it works or doesn't work. lol.

**Comment by rgwood** [comment]
I can take a look and try to reproduce the failure on Windows.

**Comment by rgwood** [comment]
Unfortunately I'm not able to reproduce the failure, the test runs successfully for me. Rerunning CI with additional logging just in case that helps.

**Comment by rgwood** [comment]
> Rerunning CI with additional logging just in case that helps.

It didn't help. Could try adding some extra logging in the `copy_identical_file` test itself (like, log `actual.err` and `actual.out`).

**Comment by fdncred** [comment]
So, the fix is to not run this test - Windows uses don't get to benefit from this?

```rust
#[test]
#[cfg(not(windows))]
fn copy_identical_file() {
    Playground::setup("cp_test_15", |_dirs, sandbox| {
        sandbox.with_files(vec![EmptyFile("empty_file")]);

        let actual = nu!(
            cwd: sandbox.cwd(),
            "cp empty_file empty_file",
        );
        assert!(actual.err.contains("Copy aborted"));
    });
}
```

**Comment by Kangaxx-0** [comment]
> So, the fix is to not run this test - Windows uses don't get to benefit from this? Well, I guess the functionality is still there, just not the test?
> 
> ```rust
> #[test]
> #[cfg(not(windows))]
> fn copy_identical_file() {
>     Playground::setup("cp_test_15", |_dirs, sandbox| {
>         sandbox.with_files(vec![EmptyFile("empty_file")]);
> 
>         let actual = nu!(
>             cwd: sandbox.cwd(),
>             "cp empty_file empty_file",
>         );
>         assert!(actual.err.contains("Copy aborted"));
>     });
> }
> ```

I would say this might be a good workaround for now, since all of us could not reproduce this unit test failure? I am not sure how the CI is configured, specifically, what is Windows version being used?  If you guys can share the details, then I can send a message to company internal group to see if it is an outstanding issue or bug from Windows?

Or you guys want to keep this a draft for now, I am ok with that too. I am currently looking into another issue

**Comment by rgwood** [comment]
I'm a little hesitant to merge this without doing a little more investigation. As mentioned, we could try logging a little more info when this fails on the runner.

> what is Windows version being used?

We're using `windows-latest` GitHub runners, not sure exactly what Windows version that is off the top of my head.

**Comment by Kangaxx-0** [comment]
I am not a Github guy :-), but I can send a message to ask for help either from Github support or MS internal channel. Let me change mine to a draft in case it gets merged accidentally

**Comment by rgwood** [comment]
> I can send a message to ask for help either from Github support or MS internal channel.

Thanks for the offer. Before you do that I would suggest a little more investigation into the failing test.

The test failure indicates that stderr does not contain "Copy aborted"; it does not tell us what stderr and stdout contain. I think the first step toward figuring this out would be to print `actual.err` and `actual.out` so we can see their contents when the test fails.

```
thread 'commands::cp::copy_identical_file' panicked at 'assertion failed: actual.err.contains(\"Copy aborted\")', crates\nu-command\tests\commands\cp.rs:332:9
```

**Comment by rgwood** [comment]
Thanks for adding the logging. Looks like there's nothing in the stderr or stdout, hmm.

```
actual err is 
actual out is 
thread 'commands::cp::copy_identical_file' panicked at 'assertion failed: actual.err.contains(\"Copy aborted\")', crates\nu-command\tests\commands\cp.rs:333:9
```

**Comment by WindSoilder** [comment]
Trying to help on this and add more debug message in #5681, finally I think I get the reason.

The windows ci is failed is because in github ci, `dst` seems to be `symbolic link`, and `dst` doesn't canonicalize

File: crates/nu-command/src/filesystem/cp.rs [hunk 4]
```diff
@@ -158,7 +157,25 @@ impl Command for Cp {
 
                 for (src, dst) in sources {
                     if src.is_file() {
-                        let res = if interactive && dst.exists() {
+                        #[cfg(not(windows))]
+                        let dst = match std::fs::canonicalize(dst.clone()) {
```
Comment (WindSoilder) [inline crates/nu-command/src/filesystem/cp.rs:161]: using `nu_path::canonicalize_with` instead of `std::fs::canonicalize` should make everything works fine (which because `nu_path::canonicalize_with` use `dunce::canonicalize` internal, and it works specially for windows path.

```rust
let dst = match canonicalize_with(dst.clone(), &current_dir_path) {
    Ok(path) => path,
    Err(_) => dst,
};
```

Comment (Kangaxx-0) [reply crates/nu-command/src/filesystem/cp.rs:161]: Thanks guys, much appreciated! I will try this tomorrow :).

BTW, I took a quick look at crate dunce - [Filesystem paths in Windows are a total mess](https://docs.rs/dunce/1.0.1/dunce/)

**Comment by WindSoilder** [comment]
Thank you so much!  I think it's ready to merge

**Comment by Kangaxx-0** [comment]
> Thank you so much! I think it's ready to merge

Thank you! For the big help

**Comment by fdncred** [comment]
Boom! Let's do it. Thanks y'all!
