### PR TITLE
Unify closure serializing logic for `to nuon`, `to msgpack`, and `to json`

### LINKED ISSUE #11738: Closure to data format conversion is inconsistent
### Describe the bug

A closure gets handled differently by various `to` subcommands.  `csv`, `tsv`, and `nuon` error out, `json` and `yaml` convert it to `null`, and `toml` stringifies it.

### How to reproduce

```Nushell
~> let record = {closure: {|x| 2 * $x}}
~> $record | to md 
|closure|
|-|
|<Closure 1672>|
~> $record | to csv 
Error: nu::shell::cant_convert

  × Can't convert to CSV.
   ╭─[entry #21:1:1]
 1 │ $record | to csv 
   ·           ───┬──
   ·              ╰── can't convert record<closure: closure> to CSV
   ╰────

~> $record | to yaml 
closure: null

~> $record | to text 
closure: <Closure 1672>
~> $record | to json 
{
  "closure": null
}
~> $record | to toml 
closure = "{|x| 2 * $x}"

~> $record | to nuon 
Error: nu::shell::cant_convert

  × Can't convert to NUON.
   ╭─[entry #26:1:1]
 1 │ $record | to nuon 
   ·           ───┬───
   ·              ╰── can't convert record<closure: closure> to NUON
   ╰────
```

### Expected behavior

Uniform handling across all of those types.  I don't know how exactly it should be handled, though:

- As `null`
- With error.
- Converting to string (functionally, as `toml`, or cosmetically, as plain text and Markdown)

### Screenshots

_No response_

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.89.0                                                       |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (Alpine Linux 1.72.1-r0) |
| cargo_version      | cargo 1.72.1                                                 |
| build_time         | 2024-01-13 03:02:49 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, trash, which, zip                           |
| installed_plugins  | method from                                                  |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by 132ikl**
# Description

Before this PR, `to msgpack`/`to msgpackz` and `to json` serialize closures as `nil`/`null` respectively, when the `--serialize` option isn't passed. This PR makes it an error to serialize closures to msgpack or JSON without the `--serialize` flag, which is the behavior of `to nuon`.

This PR also adds the `--serialize` flag to `to msgpack`.

This PR also changes `to nuon` and `to json` to return an error if they cannot find the block contents of a closure, rather than serializing an empty string or an error string, respectively. This behavior is replicated for `to msgpack`.

 It also changes `to nuon`'s error message for serializing closures without `--serialize` to be the same as the new errors for `to json` and `to msgpack`.

# User-Facing Changes

* Add `--serialize` flag to `to msgpack`, similar to the `--serialize` flag for `to nuon` and `to json`.
* Serializing closures to JSON or msgpack without `--serialize`

Partially fixes #11738

# Tests + Formatting

N/A

# After Submitting

N/A

### CODE REVIEW

**Comment by fdncred** [comment]
`to nuon` already has the `--serialize` flag. Oh, I bet you mean `to msgpack`. I definitely didn't add it there.

**Review by fdncred — APPROVED** [review]
LGTM

File: crates/nu-command/src/formats/to/msgpack.rs [hunk 1]
```diff
@@ -208,25 +228,53 @@ pub(crate) fn write_value(
...
+                    return Err(WriteError::Shell(Box::new(ShellError::CantConvert {
+                        to_type: "string".into(),
+                        from_type: "closure".into(),
+                        span,
+                        help: Some(format!(
+                            "unable to retrieve block contents for closure with id {}",
+                            val.block_id.get()
+                        )),
+                    })));
+                };
```
Comment (sholderbach) [inline crates/nu-command/src/formats/to/msgpack.rs:268]: Could this part you repeated across a few places live on the closure type?

e.g. `Closure::coerce_to_string`

**Review by sholderbach — COMMENTED** [review]
That description has a lot of "also"s for stuff not subsumed by the title.

File: crates/nu-command/src/formats/to/json.rs [hunk 2]
```diff
@@ -78,16 +78,12 @@ impl Command for ToJson {
...
                 Ok(PipelineData::Value(res, Some(metadata)))
             }
-            _ => Ok(Value::error(
-                ShellError::CantConvert {
-                    to_type: "JSON".into(),
-                    from_type: value.get_type().to_string(),
-                    span,
-                    help: None,
-                },
+            _ => Err(ShellError::CantConvert {
```
[the remark this answers is not in the document]
Comment (132ikl) [reply crates/nu-command/src/formats/to/json.rs:81]: > The problem is preexiting

could you elaborate on this, I'm not quite following

> but this use of CantConvert irks me

honestly same, I'm willing to change them to something else. do you have any suggestions?

File: crates/nu-command/src/formats/to/msgpack.rs (hunk 1 above)
Comment (132ikl) [reply crates/nu-command/src/formats/to/msgpack.rs:268]: that sounds good to me, I thought of doing something like that but wasn't sure where to put it. not sure if `Closure` is really the _best_ place to put it, but it keeps it out of the other stringifying logic so it's good enough for me. we can probably revisit this as part of #15286 and #14090

**Comment by 132ikl** [comment]
draft mode to address stefan's comments

File: crates/nu-command/src/formats/to/json.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (sholderbach) [reply crates/nu-command/src/formats/to/json.rs:81]: That is probably more a young man yells at cloud moment, I don't remember us having a specific variant for file format / spec intricacies.

It was like this before, so I don't want to force you to make a change in this PR, we can look at this when chipping away at the whole TypeError complex.

File: crates/nu-command/src/formats/to/msgpack.rs (hunk 1 above)
Comment (sholderbach) [reply crates/nu-command/src/formats/to/msgpack.rs:268]: I like on the type more than in a large `match` like on `Value`. Could also be useful if you want to debug print stuff in places like the engine.

With engine_state should be fine in `nu-protocol`

**Comment by sholderbach** [comment]
Do we want to ship this with `0.103.0`? 
Addressing my request for a helper should be relatively straightforward. Or are there any other concerns after our last meeting?

**Comment by 132ikl** [comment]
> Do we want to ship this with 0.103.0

all good with me. just moved the string coercion code into `impl Closure`.

also, I renamed `capture_block.rs` to `closure.rs` since the only thing in there now is `Closure` itself, and `CaptureBlock` was renamed to `Closure` a long time ago

**Review by sholderbach — APPROVED** [review]
Nice

**Comment by fdncred** [comment]
I'm wondering now if `to text` should have the same treatment.

**Comment by 132ikl** [comment]
> I'm wondering now if to text, to toml, to yaml should have the same treatment.

yes, definitely. also kind of along the same lines as #15286
