### PR TITLE
fix: panic on large duration number

### LINKED ISSUE #16592: Panic on large float number of duration with debug target
### Bug report form

- [x] I have done a basic search of the issue tracker to find any existing issues that are similar.
- [x] I have checked that my version is at least the latest stable release available via my installation method.

### Describe the bug

Not reproducible with release target

### How to reproduce

1. cargo run
2. paste `222222222222222222222222222222222222222222222222222221ms` in the repl

### Expected behavior

Don't panic!

### Configuration

main branch on macOS with rust 1.87.0

### PR DESCRIPTION
**Pull request by blindFS**
Fixes #16592

Maybe a more organized version of type Duration (like those of #14369) is better, but that's beyond this naive fix.

## Release notes summary - What our users need to know

Fixed a panic when `duration`s were created with a value outside of the supported value range with certain unit suffixes.

## Tasks after submitting

None

### CODE REVIEW

File: crates/nu-protocol/src/ast/unit.rs [hunk 1]
```diff
@@ -35,6 +35,20 @@ pub enum Unit {
     Week,
 }
 
+/// TODO: something like `Filesize::from_unit` in the future?
```
Comment (sholderbach) [inline crates/nu-protocol/src/ast/unit.rs]:
```suggestion
// TODO: something like `Filesize::from_unit` in the future?
```

File: crates/nu-protocol/src/ast/unit.rs [hunk 2]
```diff
@@ -35,6 +35,20 @@ pub enum Unit {
...
+fn duration_mul_and_check(size: i64, factor: i64, span: Span) -> Result<Value, ShellError> {
+    match size.checked_mul(factor) {
+        Some(val) => Ok(Value::duration(val, span)),
+        None => Err(ShellError::GenericError {
+            error: "duration too large".into(),
```
Comment (sholderbach) [inline crates/nu-protocol/src/ast/unit.rs:43]: For @cptpiepmatz 's war on `GenericError` maybe `InvalidValue` or one of the overflow variants could fit this application.

**Review by sholderbach — APPROVED** [review]
Thanks for spotting this edge case. That was indeed a curious construction to have overflow checking for some of the variants.

We could have a test for this but may be somewhat optional given the explicitness of the code.
