### PR TITLE
Map `DirectoryNotFound` to `FileNotFound` for `open` command (issue #10085)

### LINKED ISSUE #10085: "open" reports nu::shell::directory_not_found, should report nu::shell::file_not_found
### Describe the bug

Per the title, very common command returns confusing feedback:

```
at 11:33:05 ❯ open "qweqwqe"
Error: nu::shell::directory_not_found

  × Directory not found
   ╭─[entry #76:1:1]
 1 │ open "qweqwqe"
   ·      ────┬────
   ·          ╰── directory not found
   ╰────
```

Since `open` only applies to files, not directories, this is confusing.

### How to reproduce

Full repro above.

### Expected behavior

I expect the following feedback:
```
at 11:33:05 ❯ open "qweqwqe"
Error: nu::shell::file_not_found

  × File not found
   ╭─[entry #76:1:1]
 1 │ open "qweqwqe"
   ·      ────┬────
   ·          ╰── file not found
   ╰────
```

### Screenshots

_No response_

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.83.1                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.71.0 (8ede3aae2 2023-07-12) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.71.0 (cfd3bbd8f 2023-06-08) |
| build_time         | 2023-08-04 19:49:10 -04:00          |
| build_rust_channel | release                             |
| allocator          | standard                            |
| features           | default, sqlite, trash, which, zip  |
| installed_plugins  |                                     |

### Additional context

`open` [calls](https://github.com/nushell/nushell/blob/0786ddddbd92fdcb848efc52c7a186c4891244c8/crates/nu-command/src/filesystem/open.rs#L102) `glob_from`, which [defaults](https://github.com/nushell/nushell/blob/0786ddddbd92fdcb848efc52c7a186c4891244c8/crates/nu-engine/src/glob_from.rs#L85) to `ShellError::DirectoryNotFound`.

I am not sure whether `DirectoryNotFound` is a better default than FileNotFound for `glob_from`, but I'm pretty sure it isn't for `open`. 

I'm happy to contribute a patch fixing `open` (seems very local) if that's the correct way to go, less sure about `glob_from`. Maybe the correct solution is to expand the glob API with a  `glob_files_from` and use that instead where warranted?

### PR DESCRIPTION
**Pull request by GPadley**
# Description

This PR should close #10085
Maps `DirectoryNotFound` errors to `FileNotFound`. All other errors are left unchanged.

# User-Facing Changes

This means a user will see `FileNotFound` instead of `DirectoryNotFound` which is more meaning full to the user.

# Tests + Formatting

# After Submitting

### CODE REVIEW

**Review by amtoine — CHANGES_REQUESTED** [review]
i've been able to see that this PR fixes the unhelpful error :ok_hand: 

could we have a little test to make sure that `open euwiqoeu` gives a `file not found` error? :yum:

**Comment by GPadley** [comment]
>could we have a little test to make sure that open euwiqoeu gives a file not found error? 😋

Looked into the tests and found one that was already testing this functionality, updated to check `file not found` is within the error message rather than general `not found` which was used before. 

I'm new to Rust, is there a way to capture the actual error instead and assert it is of type `nu_protocol::ShellError::FileNotFound`? Probably is a little overkill, but is how I often do testing in Python.

Let me know if that fulfills the requirements you expect.

**Comment by amtoine** [comment]
because
```nushell
~ INSERT > open i_dont_exist.txt
Error: nu::shell::directory_not_found

  × Directory not found
   ╭─[entry #1:1:1]
 1 │ open i_dont_exist.txt
   ·      ────────┬───────
   ·              ╰── directory not found
   ╰────
```
should have `file not found` now, i think the change you made to the existing test is very nice :ok_hand:

**Comment by amtoine** [comment]
> I'm new to Rust, is there a way to capture the actual error instead and assert it is of type `nu_protocol::ShellError::FileNotFound`? Probably is a little overkill, but is how I often do testing in Python.
>
not sure at all in that case :thinking: 

`nu!` is testing *as if the test was in the REPL*, so it does not see the `ShellError::FileNotFound`, but only the output as you'd do in the REPL, this is why `actual.err` is a string and not a `ShellError` and we need to use `.contains` on it.

**Comment by GPadley** [comment]
@amtoine OOI what's the process for getting this reviewed and merged in? Is it done on a schedule or quite ad-hoc?

**Comment by amtoine** [comment]
> @amtoine OOI what's the process for getting this reviewed and merged in? Is it done on a schedule or quite ad-hoc?
>
there's no schedule to land PRs, only to release Nushell every 4 weeks :yum: 

this PR touches parts of the source base i'm not familiar with, so it might need another quick look from another member of the core team, but other than that, it looks it's in a good shape to land soon :relieved:

**Review by sholderbach — APPROVED** [review]
Thank you for your patience! This looks like a great first PR to nushell!

If you can resolve the merge conflict this should be good to go

**Comment by fdncred** [comment]
@GPadley I think we're ready to land this if you can resolve the conflicts. Thanks!

**Comment by GPadley** [comment]
Apologies for the delay  - have fixed merge conflicts with main so should be ready to go once all check are passed.

**Comment by fdncred** [comment]
After reviewing this again, it looks like we have 13 places where `file_only` is set to false and 1 place where it's set to true. I'm wondering if it would be better just to remove all the `file_only` bools and just change the error message to "file or directory not found"?

**Comment by amtoine** [comment]
> After reviewing this again, it looks like we have 13 places where `file_only` is set to false and 1 place where it's set to true. I'm wondering if it would be better just to remove all the `file_only` bools and just change the error message to "file or directory not found"?
> 
> I'm not sure it's worth all these changes just to have it used in 1 place. What do others think?
>
sounds sensible to me to say "file or directory", this is what Bash is doing and it does the job, in the end, files and directories are mostly the same thing in the file system :yum: 
```bash
$ ls euqwio
ls: cannot access 'euqwio': No such file or directory
```
```bash
$ cd ewuqi
bash: cd: ewuqi: No such file or directory
```

**Comment by GPadley** [comment]
So there are a couple ways I could do this:
* Remove the `DirectoryNotFound` and `FileNotFound` error messages and only have a `FileOrDirectoryNotFound` error
* Add a `FileOrDirectoryNotFound`  error and update this single instance. 
What are people's opinions?

File: crates/nu-command/src/filesystem/open.rs [hunk 1]
```diff
@@ -103,7 +111,7 @@ impl Command for Open {
             let arg_span = path.span;
             // let path_no_whitespace = &path.item.trim_end_matches(|x| matches!(x, '\x09'..='\x0d'));
 
-            for path in nu_engine::glob_from(&path, &cwd, call_span, None)?.1 {
```
Comment (sholderbach) [inline crates/nu-command/src/filesystem/open.rs:106]: Alternative number 3: using a `.map_err` here to convert a `DirectoryNotFound` to `FileNotFound`. It may be a bit hacky but minimally invasive.

**Review by sholderbach — COMMENTED** [review]
I am neither a fan of degrading the error message quality nor bloating the `ShellError` with rarely used variants, people will almost certainly pick the wrong one in the future.

File: crates/nu-command/src/filesystem/open.rs (hunk 1 above)
Comment (fdncred) [reply crates/nu-command/src/filesystem/open.rs:106]: Seems like a good compromise to remove all the file_only bools and just use map_err here. Thanks for the idea!

Comment (GPadley) [reply crates/nu-command/src/filesystem/open.rs:106]: This should be done now

**Review by sholderbach — APPROVED** [review]
Thanks for making this error nicer for the users and iterating on this with us! Let's go!

**Comment by daniel-vainsencher** [comment]
@GPadley thank you! I had reported the linked issue, and its cool you fixed it :)
