### PR TITLE
ensure that when nu evaluates files, it allows early returns

### LINKED ISSUE #7301: Can't `return` from a script without a `main` definition
### Describe the bug

The following script works:

```
def main [] {
  if true {
    print "returning early"
    return
  }

  print "done"
}
```

```bash
〉nu foo.nu
returning early
```

However, if I leave out the `main` definition it does not work:
```
if true {
  print "returning early"
  return
}

print "done"
```
```bash
〉nu bar.nu
returning early
Error: 
  × Return used outside of function
   ╭─[bar.nu:2:1]
 2 │   print "returning early"
 3 │   return
   ·   ───┬──
   ·      ╰── used outside of function
 4 │ }
   ╰────
```

### How to reproduce

1. Write a Nu script (`foo.nu`) without explicitly defining a `main` function
2. Run it with `nu foo.nu`
3. Observe the "Return used outside of function" error

### Expected behavior

I expect `return` to work even without explicitly defining `main` in a script.

### Screenshots

_No response_

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.72.0                                   |
| branch             | main                                     |
| commit_hash        | fa97e819ebfa6c568101da4cefec1505964b48b7 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.72.0                                   |
| build_time         | 2022-11-29 22:27:52 -08:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by merelymyself**
# Description

Fixes #7301.

# User-Facing Changes

`return` can now be used in scripts without explicit `def main`.

# Tests + Formatting

Don't forget to add tests that cover your changes. (I'm not sure how to test this.)

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by kubouch** [comment]
Could you add tests for this PR?

Also, in which cases is it supposed to work? Currently, it seems to work for `nu file.nu`. Should it work for `source file.nu` and `source-env script.nu` as well? I'm thinking maybe it should, otherwise you'd be able to run the script with `nu file.nu` but not with `source file.nu`.

**Comment by merelymyself** [comment]
I know the test for return is a bit wonky, but I can't think of an alternative that fits all situations.

File: crates/nu-command/tests/commands/return_.rs [hunk 1]
```diff
@@ -23,3 +23,16 @@ fn early_return_if_false() {
...
     assert_eq!(actual.out, r#"100"#);
 }
+
+#[cfg(not(windows))]
+#[test]
+fn return_works_in_script_without_def_main() {
+    let actual = nu!(
+        cwd: "tests/fixtures/formats", pipeline(
+        r#"
+            exec (ls ../../../target/*/nu | get name.0) early_return.nu
```
Comment (kubouch) [inline crates/nu-command/tests/commands/return_.rs:33]: This seems too hacky. Does `nu early_return.nu` work?

Comment (merelymyself) [reply crates/nu-command/tests/commands/return_.rs:33]: No, because that requires nu to be installed to the path. Without it, the test will return an error like "did you mean 'du'"?

Comment (kubouch) [reply crates/nu-command/tests/commands/return_.rs:33]: That's weird because it works on my end and I've used `nu` in tests before. Try `pipeline("nu early return.nu")`, it should work.

Looking up the `target` directory manually is not sound because `CARGO_TARGET_DIR` can move it to another location.

Comment (merelymyself) [reply crates/nu-command/tests/commands/return_.rs]: whoops, you were right @kubouch . Thanks for the help!

**Comment by fdncred** [comment]
are we ready to merge this?
