### PR TITLE
Fix reject regression

### LINKED ISSUE #14929: Can no longer `reject` rows in a flattened table/list (regression in main)
### Describe the bug

`reject` now errors when passed a list that has been `flatten`ed.

Note that this causes `std-rfc/tables` to fail.  Noticed this when moving it over from the "old" `std-rfc` to the latest.

### How to reproduce

```nushell
[[N, u, s, h, e, l, l]] | flatten | reject 1
# => Error: nu::shell::not_a_list
# => 
# =>   × Not a list value
# =>    ╭─[entry #33:1:3]
# =>  1 │ [[N, u, s, h, e, l, l]] | flatten | reject 1
# =>    ·   ┬                                        ┬
# =>    ·   │                                        ╰── value not a list
# =>    ·   ╰── value originates here
# =>    ╰────
```

This works in 0.101.

It also fails even if the before-and-after flattened table are "equal":

```nushell
let list = [N, u, s, h, e, l, l]
let nested_list = [[N, u, s, h, e, l, l]]
$list == ($nested_list | flatten)
# => true

$list | reject 1
# => ╭───┬───╮
# => │ 0 │ N │
# => │ 1 │ s │
# => │ 2 │ h │
# => │ 3 │ e │
# => │ 4 │ l │
# => │ 5 │ l │
# => ╰───┴───╯

$nested_list | flatten | reject 1
# => Error: nu::shell::not_a_list
# => 
# =>   × Not a list value
# =>    ╭─[entry #38:1:21]
# =>  1 │ let nested_list = [[N, u, s, h, e, l, l]]
# =>    ·                     ┬
# =>    ·                     ╰── value originates here
# =>    ╰────
# =>    ╭─[entry #41:1:33]
# =>  1 │ $nested_list | flatten | reject 1
# =>    ·                                 ┬
# =>    ·                                 ╰── value not a list
# =>    ╰────
```

### Expected behavior

Works as in 0.101 and rejects the item without error.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.101.1                                  |
| major              | 0                                        |
| minor              | 101                                      |
| patch              | 1                                        |
| branch             | main                                     |
| commit_hash        | f88ed6ecd52c167485f50f1c1bd9dea2d2d8fc04 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.82.0 (f6e511eec 2024-10-15)      |
| rust_channel       | 1.82.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.82.0 (8f40fc59f 2024-08-21)      |
| build_time         | 2025-01-26 08:27:20 -05:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash                   |
| installed_plugins  | formats 0.101.0, gstat 0.101.1           |

### PR DESCRIPTION
**Pull request by cosineblast**
This PR solves the regression introduced by #14622 (sorry about that). It also adds a test to cover the regression.
Closes #14929.

The main issue was that the update to reject failed to consider the case in which the cell paths are integers, in which case it should stick with the default behavior (similar to what was done to `get` in the same PR).

Off: Has nushell tried using property-based testing in the past? I think it sounds suitable for a project like this.

### CODE REVIEW

**Comment by NotTheDr01ds** [comment]
Thanks for the quick turnaround!  Testing now.

File: crates/nu-command/src/filters/reject.rs [hunk 1]
```diff
@@ -220,11 +220,19 @@ fn reject(
...
+            .any(|member| matches!(member, PathMember::Int { .. }))
+    });
+
     match input {
-        PipelineData::ListStream(stream, ..) => {
+        PipelineData::ListStream(stream, ..) if !has_integer_path_member => {
             let result = stream
                 .into_iter()
                 .map(move |mut value| {
+                    eprintln!("uhh");
```
Comment (NotTheDr01ds) [inline crates/nu-command/src/filters/reject.rs:234]:
```suggestion
```

**Review by NotTheDr01ds — CHANGES_REQUESTED** [review]
Thanks again!  I just took out the debug print, and it looks like it's good to go.

**Review by NotTheDr01ds — APPROVED** [review]

File: crates/nu-command/src/filters/reject.rs [hunk 2]
```diff
@@ -220,11 +220,18 @@ fn reject(
...
+            .any(|member| matches!(member, PathMember::Int { .. }))
+    });
+
     match input {
-        PipelineData::ListStream(stream, ..) => {
+        PipelineData::ListStream(stream, ..) if !has_integer_path_member => {
             let result = stream
                 .into_iter()
                 .map(move |mut value| {
+
```
Comment (NotTheDr01ds) [inline crates/nu-command/src/filters/reject.rs:234]:
```suggestion
```

File: crates/nu-command/src/filters/reject.rs (hunk 1 above)
Comment (cosineblast) [reply crates/nu-command/src/filters/reject.rs]: lmao, sorry about that

**Comment by sholderbach** [comment]
> Has nushell tried using property-based testing in the past? I think it sounds suitable for a project like this.

I remember us using `proptest` in the past. The results were mixed so we removed the particular tests (for the `to nuon` generation, #8688 )
As the test used had all the overhead of spawning a new `nu` process (and we possibly had some lock contention ensuring we have a correct `nu` build at the time) it was really slow (https://github.com/nushell/nushell/pull/6391#issuecomment-1305066138). (Our sense for what is a waste of time in the CI tests may have changed in the mean time due to the shear number of tests and the long time out tests for plugins and `http` commands).
So if you want to work on adding some new property based testing, it may be worth looking into a strategy to launch those tests as performant as possible while still having access to proper shrinking/expanding (so not just codegening a big batch once and looking for failures in all)
The second part that we had to wait months for a failure to be caught may be a skill issue that we can overcome by being a bit smarter about generation strategies.

We still have one call to `quickcheck` that serves as a poor persons fuzzer to try to throw garbage at the parser until a panic happens. Not sure if that really serves a good purpose in the CI. We have a few issues that seem to catch some stray failures (https://github.com/nushell/nushell/issues/1760, https://github.com/nushell/nushell/issues/3082) but we apparently not really got to investigating them systematically. Especially since we now have fuzz targets that can run dedicatedly and use coverage information via the llvm fuzzing library.

**Comment by cosineblast** [comment]
I see now, thanks for the detailed response.
