### PR TITLE
Expand alias when sending command to external completion

### LINKED ISSUE #8483: Alias completions with external completers does not work anymore (after #8123)
### Describe the bug

I use fish as a completer with the exact same setup as [in the docs](https://www.nushell.sh/book/custom_completions.html#external-completions).

Before, in 0.76 I could `alias k = kubectl` and get automcompletion for the resource names from the fish completion file (`kubectl completion fish`)

In 0.77, this completion does not work anymore and I have to use the full command to get completion.

### How to reproduce

1. `alias k = kubectl`
2. `> k get pods <TAB>`

(0. Have kubectl installed and external completion setup)

### Expected behavior

Autocomplete as if I typed `kubectl get pods`.

### Screenshots

image

(Not screenshotting expected behavior because I'm at work)

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.77.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | fd09609b44b53d41ac7929e90708cdeba7bfb571                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.68.0 (2c8cc3432 2023-03-06) (Arch Linux rust 1:1.68.0-1) |
| cargo_version      | cargo 1.68.0                                                     |
| build_time         | 2023-03-15 09:27:56 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | default, zip                                                     |
| installed_plugins  |                                                                  |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by simonborje**
An attempt to fix #8483.

When an alias is used, `flatten_expression` returns a `FlatShape::External(span)` which contains the expanded alias. Use that to get the expanded alias and send it to external completion instead of the alias itself.

```
alias glo = git log --oneline

// Without patch
glo test<TAB>   =>   external completer called with ["glo" "log" "--oneline" "test"}

// With patch
glo test<TAB>   =>   external completer called with ["git" "log" "--oneline" "test"}
```

### Aliases are now expanded before being sent to external completers

Before this change, when an external completer was invoked for an alias, the first argument sent to the completer would be the alias itself instead of the aliased command.

For example, with an alias defined as `alias gl = git log`, typing `gl branch_name` and pressing `TAB` would send the arguments `gl`, `log`, `branch_name` to the external completer.

After this change, the alias is expanded and the arguments sent to the external completer will be `git`, `log`, `branch_name`.

## Tasks after submitting

- [ ] Update the [documentation](https://github.com/nushell/nushell.github.io)

### CODE REVIEW

**Comment by 132ikl** [comment]
awesome! would you be able to add a test for this? (not totally sure where, i havent worked on tests for completions myself)

**Comment by simonborje** [comment]
I'm not very familiar with the test framework but I'll see if I can figure something out.

**Comment by simonborje** [comment]
I managed to add a test that seems to be working, but it ended up a bit more complicated than I had hoped. I suspect that there are easier/better ways to test it.

**Comment by blindFS** [comment]
Thanks for the simple fix, you can add your test to [this file](https://github.com/nushell/nushell/blob/main/crates/nu-cli/tests/completions/mod.rs) which should be much easier. Please add one for nested aliases as well.

BTW, I think the text span is not fully separated for aliased commands, not sure if it matters.

**Comment by simonborje** [comment]
Thanks for the pointers! I removed the first version of the test and added two simpler ones - one of them tests what I assume is "nested aliases".

**Comment by 132ikl** [comment]
looks great -- just one last thing, @simonborje could you fill out the release notes summary section? there's info on how to do so in CONTRIBUTING.md. if you need any help let me know!

File: crates/nu-cli/tests/completions/mod.rs [hunk 1]
```diff
@@ -2723,6 +2723,46 @@ fn cellpath_assignment_operator_completions() {
...
+
+    let mut completer = NuCompleter::new(Arc::new(engine), Arc::new(stack));
+    let completion_str = "example_alias extra_arg";
+    let suggestions = completer.complete(completion_str, completion_str.len());
+    let expected: Vec<_> = vec!["example_cmd", "arg1", "arg2", "extra_arg"];
+    match_suggestions(&expected, &suggestions);
+}
+
+#[test]
+fn nested_alias_expansion_for_external_completions() {
```
Comment (blindFS) [inline crates/nu-cli/tests/completions/mod.rs:2744]: Would be better to combine the 2 cases into a single one, with the same expected result.

Comment (blindFS) [reply crates/nu-cli/tests/completions/mod.rs:2744]: Not a big deal, probably need to cleanup all those duplicated code in that file using rstest in the future anyways

**Comment by simonborje** [comment]
I've added a release notes section. I was unsure about which terms to use and how detailed the notes should be so please make any changes you like :)

**Comment by 132ikl** [comment]
perfect! thanks so much!

**Comment by Malix-Labs** [comment]
See https://github.com/nushell/nushell/issues/8483#issuecomment-4105002205, which highlight a similar bug still unfixed
