### PR TITLE
Fix memory leaks in REPL

### LINKED ISSUE #16340: REPL leaks memory
### Describe the bug

When a variable unused elsewhere is shadowed, it doesn't get freed.

### How to reproduce

```Nushell
~> ps | last | select name mem
──────┬─────────
 name │ nu      
 mem  │ 39.5 MB 
──────┴─────────
~> let x = random binary 100mb
~> ps | last | select name mem
──────┬──────────
 name │ nu       
 mem  │ 141.1 MB 
──────┴──────────
~> let x = random binary 100mb
~> ps | last | select name mem
──────┬──────────
 name │ nu       
 mem  │ 241.9 MB 
──────┴──────────
~> let x = random binary 100mb
~> ps | last | select name mem
──────┬──────────
 name │ nu       
 mem  │ 343.0 MB 
──────┴──────────
```

### Expected behavior

I expected buffers used by previous versions of `x` to be freed.

### Configuration

| key                  | value                                              |
| -------------------- | -------------------------------------------------- |
| version              | 0.106.1                                            |
| major                | 0                                                  |
| minor                | 106                                                |
| patch                | 1                                                  |
| branch               |                                                    |
| commit_hash          | 682d593d3f53e5337dceedf98c9603a698af6a64           |
| build_os             | linux-x86_64                                       |
| build_target         | x86_64-unknown-linux-musl                          |
| rust_version         | rustc 1.86.0 (05f9846f8 2025-03-31)                |
| rust_channel         | 1.86.0-x86_64-unknown-linux-musl                   |
| cargo_version        | cargo 1.86.0 (adf9b6ad1 2025-02-28)                |
| build_time           | 2025-08-03 12:10:49 +03:00                         |
| build_rust_channel   | release                                            |
| allocator            | standard                                           |
| features             | default, plugin, rustls-tls, sqlite, trash-support |
| installed_plugins    | template 0.105.1                                   |
| experimental_options | example=false, reorder-cell-paths=false            |

### PR DESCRIPTION
**Pull request by hustcer**
This PR should close #16340 

# Description

After this change on Windows:
```nu
~ $> ps | where name == 'nu.exe' | select name mem
 #    name      mem
──────────────────────
 0   nu.exe   47.7 MB
 1   nu.exe   67.6 MB

~ $> let x = random binary 100mb
~ $> ps | where name == 'nu.exe' | select name mem
 #    name      mem
───────────────────────
 0   nu.exe    47.7 MB
 1   nu.exe   166.6 MB

~ $> let x = random binary 100mb
~ $> ps | where name == 'nu.exe' | select name mem
 #    name      mem
───────────────────────
 0   nu.exe    47.7 MB
 1   nu.exe   165.8 MB

~ $> let x = random binary 100mb
~ $> ps | where name == 'nu.exe' | select name mem
 #    name      mem
───────────────────────
 0   nu.exe    47.7 MB
 1   nu.exe   167.3 MB

~ $> let x = random binary 100mb
~ $> ps | where name == 'nu.exe' | select name mem
 #    name      mem
───────────────────────
 0   nu.exe    47.7 MB
 1   nu.exe   166.5 MB

~ $> let x = random binary 10mb
~ $> ps | where name == 'nu.exe' | select name mem
 #    name      mem
──────────────────────
 0   nu.exe   47.7 MB
 1   nu.exe   76.3 MB

~ $> let x = random binary 1mb
~ $> ps | where name == 'nu.exe' | select name mem
 #    name      mem
──────────────────────
 0   nu.exe   47.7 MB
 1   nu.exe   68.4 MB

~ $> ps | where name == 'nu.exe' | select name mem
 #    name      mem
──────────────────────
 0   nu.exe   47.7 MB
 1   nu.exe   67.7 MB

# After a while
~ $> ps | where name == 'nu.exe' | select name mem
 #    name      mem
──────────────────────
 0   nu.exe   38.6 MB
 1   nu.exe   55.7 MB
```

# User-Facing Changes

Hopefully none, and this https://github.com/nushell/nushell/issues/16340#issuecomment-3149930258 just work as before.

### CODE REVIEW

**Comment by hustcer** [comment]
On macOS, memory might not drop as quickly after variables are shadowed compared to what I've observed on Windows—but it should still show a noticeable decrease after a few minutes:

```nu
~ $> ps | where name == 'nu' | select name mem
 #   name     mem
────────────────────
 0   nu     20.8 MB
 1   nu     51.1 MB

~ $> let x = random binary 100mb
~ $> ps | where name == 'nu' | select name mem
 #   name     mem
─────────────────────
 0   nu      20.8 MB
 1   nu     159.1 MB

~ $> let x = random binary 100mb
~ $> ps | where name == 'nu' | select name mem
 #   name     mem
─────────────────────
 0   nu      20.8 MB
 1   nu     255.1 MB

~ $> let x = random binary 100mb
~ $> ps | where name == 'nu' | select name mem
 #   name     mem
─────────────────────
 0   nu      20.8 MB
 1   nu     162.0 MB

~ $> ps | where name == 'nu' | select name mem
 #   name     mem
─────────────────────
 0   nu      20.8 MB
 1   nu     124.8 MB

~ $> let x = random binary 1mb
~ $> ps | where name == 'nu' | select name mem
 #   name     mem
────────────────────
 0   nu     20.8 MB
 1   nu     66.7 MB

~ $> ps | where name == 'nu' | select name mem
 #   name     mem
────────────────────
 0   nu     21.5 MB
 1   nu     63.1 MB

~ $> let x = random binary 100mb
~ $> ps | where name == 'nu' | select name mem
 #   name     mem
─────────────────────
 0   nu      21.5 MB
 1   nu     162.2 MB
 
~ $> let x = random binary 1mb
~ $> ps | where name == 'nu' | select name mem
 #   name     mem
────────────────────
 0   nu     21.5 MB
 1   nu     63.6 MB
```

**Comment by fdncred** [comment]
Seems to work with scoped variables too so far. Not sure about `hide` variables. I'm not sure `hide` even works these days.

File: crates/nu-cli/src/repl.rs [hunk 1]
```diff
@@ -207,11 +207,13 @@ pub fn evaluate_repl(
         }));
         match iteration_panic_state {
             Ok((continue_loop, es, s, le)) => {
+                // We apply the changes from the updated stack back onto our previous stack
+                let mut merged_stack = Stack::with_changes_from_child(previous_stack_arc, s);
+                // Clean up unused variables from stack to prevent memory leaks from variable shadowing
+                es.cleanup_stack_variables(&mut merged_stack);
```
Comment (blindFS) [inline crates/nu-cli/src/repl.rs]: Does it get executed for each loop in the REPL, even if it has nothing to do with variable shadowing at all?

I guess the extra overhead is marginal comparing to other heavy stuff like prompt painting, yet I still prefer a lighter solution, if possible.

**Comment by hustcer** [comment]
I've just published a nightly build here: https://github.com/nushell/nightly/releases/tag/v0.106.2 with the changes of this PR included, don't hesitate to give it a try

File: crates/nu-cli/src/repl.rs (hunk 1 above)
Comment (hustcer) [reply crates/nu-cli/src/repl.rs]: Yep, you're right, I'll try to refine this approach a bit later.

**Comment by hustcer** [comment]
> Seems to work with scoped variables too so far. Not sure about `hide` variables. I'm not sure `hide` even works these days.

I did a quick test, and it seems like `hide` and `hide-env` should work fine.

File: crates/nu-protocol/src/engine/engine_state.rs [hunk 2]
```diff
@@ -371,6 +371,28 @@ impl EngineState {
...
+        // Collect all VarIds that are still referenced by overlays
+        let referenced_vars: HashSet<_> = self
+            .scope
+            .overlays
+            .iter()
+            .flat_map(|(_, overlay)| overlay.vars.values())
+            .copied()
+            // Always preserve critical system variables
+            .chain([NU_VARIABLE_ID, IN_VARIABLE_ID, ENV_VARIABLE_ID])
+            .collect();
```
Comment (blindFS) [inline crates/nu-protocol/src/engine/engine_state.rs]: Maybe we can do better with a whitelist of shadowed variables, which could be marked from:

https://github.com/nushell/nushell/blob/f015409253bf56ad6854cdaa7b69b6fa6a2b98f6/crates/nu-protocol/src/engine/overlay.rs#L211-L213

Just an unverified thought, will test it later

Comment (blindFS) [reply crates/nu-protocol/src/engine/engine_state.rs:388]: Never mind, it doesn't work like that. A new ScopeFrame is created for each REPL iteration.

Comment (blindFS) [reply crates/nu-protocol/src/engine/engine_state.rs]: Here's what I meant: [commit](https://github.com/blindFS/nushell/commit/0239563cda8a9dfeb759a996fec53f6ca7981c07).

However I don't see freed RAM on macOS, with or without the refactoring.

Comment (hustcer) [reply crates/nu-protocol/src/engine/engine_state.rs]: I tested the latest commit on Windows last night, and it worked as expected. But I haven't tried the latest commit on my MacBook yet. Based on past experience, the memory usage on macOS might not drop immediately—sometimes it takes a few minutes, and other times it might need to hit a certain threshold before decreasing. Maybe try a few more times and observe. On Windows, though, the effect is almost instant.

Comment (blindFS) [reply crates/nu-protocol/src/engine/engine_state.rs]: After running `let x = random binary 100mb` a couple of times, the memory usage is kept at a threshold.
I guess it's working then. It would be better to figure out how to test it properly.

Comment (hustcer) [reply crates/nu-protocol/src/engine/engine_state.rs]: Which approach is better—should we merge this PR first and then you refine upon it, or would you prefer to make changes directly within this PR?

Comment (blindFS) [reply crates/nu-protocol/src/engine/engine_state.rs]: > Which approach is better—should we merge this PR first and then you refine upon it, or would you prefer to make changes directly within this PR?
> 

Would you please cherry pick my commit to this PR and test it on windows to make sure it doesn't regress?

Comment (hustcer) [reply crates/nu-protocol/src/engine/engine_state.rs]: Okay, I will try it tonight

Comment (blindFS) [reply crates/nu-protocol/src/engine/engine_state.rs]: Oops, I'm pretty sure `hide` doesn't free anything in my way. Might need to tweak it a bit more.

Comment (hustcer) [reply crates/nu-protocol/src/engine/engine_state.rs]: > > Which approach is better—should we merge this PR first and then you refine upon it, or would you prefer to make changes directly within this PR?
> 
> Would you please cherry pick my commit to this PR and test it on windows to make sure it doesn't regress?

I just picked your commit and tested it on Windows, it works pretty good so far — just as expected! 👍

Comment (sholderbach) [reply crates/nu-protocol/src/engine/engine_state.rs]: With that logic, is there a way for things to not be shadowed anymore, that would then be unreachable?

Comment (blindFS) [reply crates/nu-protocol/src/engine/engine_state.rs]: > With that logic, is there a way for things to not be shadowed anymore, that would then be unreachable?

Is it possible to undo the shadowing of a variable in nushell? Overlays are handled differently which shouldn't be affected.

Comment (hustcer) [reply crates/nu-protocol/src/engine/engine_state.rs]: Do you mean revert the last commit ?

> Can we undo the shadowing of a variable? Overlays are handled differently which shouldn't be affected.

Comment (hustcer) [reply crates/nu-protocol/src/engine/engine_state.rs]: > With that logic, is there a way for things to not be shadowed anymore, that would then be unreachable?

Could you provide an example that currently works on main branch but would break after this PR? That would help me further verify  and fix the issue.

**Review by WindSoilder — APPROVED** [review]
Thanks!  I think it's good to land it.
