### PR TITLE
Raise error if http method is defined dynamically

### LINKED ISSUE #16851: http errors with Uncategorized error when dynamically generating the method or using upper case.
### Bug report form

- [x] I have done a basic search of the issue tracker to find any existing issues that are similar.
- [x] I have checked that my version is at least the latest stable release available via my installation method.

### Describe the bug

I tried to call the `http` command with a dynamically-set HTTP method (e.g. `"GET"`, `"POST"`) stored in a variable, but Nushell refuses to use the variable as the method token. I expect the string variable to be used as the HTTP method, but instead the call fails (no request is sent / an error is returned).

The command fails to interpret the variable $method as the HTTP method token.

```bash
❯ test
Error: nu::shell::io::uncategorized_error

  × I/O error
     ╭─[/home/sado/.config/nushell/config.nu:209:3]
 208 │   mut $method = $method | default "get"
 209 │   http $method https://www.nushell.sh/
     ·   ──┬─
     ·     ╰── Uncategorized error
 210 │ }
     ╰────
```

and this also break with same `uncategorized error` without even dynamically generating methods, it should be command insensitive:

```bash
> http GET https://www.nushell.sh
```

@cptpiepmatz | Pinging cuz they asked me to create an issue, as the Uncategorized error is always bad and should at best never occur. 

### How to reproduce

```nu
def test [method?: string] {
  mut $method = $method | default "get"
  http $method https://www.nushell.sh/
}
```

### Expected behavior

When $method is "get", the call should be equivalent to:

```bash
http get https://www.nushell.sh/
```

### Configuration

| key                  | value                                                                   |
| -------------------- | ----------------------------------------------------------------------- |
| version              | 0.107.0                                                                 |
| major                | 0                                                                       |
| minor                | 107                                                                     |
| patch                | 0                                                                       |
| branch               |                                                                         |
| commit_hash          | c3a699294685c6c6a6581dff2bc4089ca275eb58                                |
| build_os             | linux-x86_64                                                            |
| build_target         | x86_64-unknown-linux-musl                                               |
| rust_version         | rustc 1.87.0 (17067e9ac 2025-05-09)                                     |
| rust_channel         | 1.87.0-x86_64-unknown-linux-gnu                                         |
| cargo_version        | cargo 1.87.0 (99624be96 2025-05-06)                                     |
| build_time           | 2025-09-03 01:36:57 +00:00                                              |
| build_rust_channel   | release                                                                 |
| allocator            | standard                                                                |
| features             | default, plugin, rustls-tls, sqlite, static-link-openssl, trash-support |
| installed_plugins    |                                                                         |
| experimental_options | example=false, reorder-cell-paths=false                                 |

### PR DESCRIPTION
**Pull request by cptpiepmatz**
- closes #16851

Running a command like `let method = "get"; http $method example.com` used to fail with an unhelpful uncategorized error. This PR now catches such cases and returns a proper error message. ~~I also improved the handling of `http get something`, which previously produced a confusing I/O error.~~

### Better errors for dynamic `http` commands

Defining an HTTP command dynamically using a string for the method used to cause an unclear, uncategorized error. It now produces a clear and specific error message instead.

```nu
let method = "get"; http $method example.com
# => Error: nu::shell::error
# => 
# =>   × Invalid command construction
# =>    ╭─[entry #5:1:26]
# =>  1 │ let method = "get"; http $method example.com
# =>    ·                          ───┬───
# =>    ·                             ╰── Using "get" dynamically is bad command construction
# =>    ╰────
# =>   help: Prefer to use `http get` directly
  ```

<details>

<summary>ANSI for changelog</summary>

```ansi
[38;5;14m> [1m[36mlet[22m[39m [35mmethod[39m = [32m"get"[39m; [1m[36mhttp[22m[39m [35m$method[39m [32mexample.com[39m
Error: [31mnu::shell::error
[39m
  [31m×[39m Invalid command construction
   ╭─[[1m[4m[36mentry #5:1:26[22m[24m[39m]
 [2m1[22m │ let method = "get"; http $method example.com
   · [1m[35m                         ───┬───[22m[39m
   ·                             [1m[35m╰── Using "get" dynamically is bad command construction[22m[39m
   ╰────[36m
  help: [39mPrefer to use `http get` directly[0m
```

</details>

## Tasks after submitting

- [ ] Update the [documentation](https://github.com/nushell/nushell.github.io)

### CODE REVIEW

**Comment by cptpiepmatz** [comment]
The error handling is not playing nice, I'm going to pull this out of the PR. So that it is only the PR about the dynamic http methods.

File: crates/nu-command/src/network/http/http_.rs [hunk 1]
```diff
@@ -119,19 +119,33 @@ impl Command for Http {
...
+        let data: Option<Value> = call.opt::<Value>(engine_state, stack, 1)?;
+
+        // prefer stricter calls over aliasing with variables
+        if let Some(Spanned { item: method, span }) = &url
+            && let method @ ("delete" | "get" | "head" | "options" | "patch" | "post" | "put") =
+                method.to_lowercase().as_str()
+        {
+            return Err(ShellError::GenericError {
+                error: "Invalid command construction".into(),
+                msg: format!("Using {method:?} dynamically is bad command construction"),
```
Comment (sholderbach) [inline crates/nu-command/src/network/http/http_.rs]:
```suggestion
                msg: format!("Using {method:?} dynamically is bad command construction. You are providing it to the `url` positional argument of `http`"),
```

**Review by WindSoilder — APPROVED** [review]
