### PR TITLE
Fix insert/upsert creation for nested lists (#15131)

### LINKED ISSUE #15131: Insert/Upsert does not work as expected on nested lists
### Describe the bug

When inserting or upserting, records are created, at arbitrary depth, to fill in gaps:
```nu 
$ {} | insert a value
╭───┬───────╮
│ a │ value │
╰───┴───────╯
$ {} | upsert a value
╭───┬───────╮
│ a │ value │
╰───┴───────╯
$ {} | insert a.b.c.d.e.f.g.h.i value
╭───┬───────────────────────────────────────────────────────────────────────╮
│   │ ╭───┬───────────────────────────────────────────────────────────────╮ │
│ a │ │   │ ╭───┬───────────────────────────────────────────────────────╮ │ │
│   │ │ b │ │   │ ╭───┬───────────────────────────────────────────────╮ │ │ │
│   │ │   │ │ c │ │   │ ╭───┬───────────────────────────────────────╮ │ │ │ │
│   │ │   │ │   │ │ d │ │   │ ╭───┬───────────────────────────────╮ │ │ │ │ │
│   │ │   │ │   │ │   │ │ e │ │   │ ╭───┬───────────────────────╮ │ │ │ │ │ │
│   │ │   │ │   │ │   │ │   │ │ f │ │   │ ╭───┬───────────────╮ │ │ │ │ │ │ │
│   │ │   │ │   │ │   │ │   │ │   │ │ g │ │   │ ╭───┬───────╮ │ │ │ │ │ │ │ │
│   │ │   │ │   │ │   │ │   │ │   │ │   │ │ h │ │ i │ value │ │ │ │ │ │ │ │ │
│   │ │   │ │   │ │   │ │   │ │   │ │   │ │   │ ╰───┴───────╯ │ │ │ │ │ │ │ │
│   │ │   │ │   │ │   │ │   │ │   │ │   │ ╰───┴───────────────╯ │ │ │ │ │ │ │
│   │ │   │ │   │ │   │ │   │ │   │ ╰───┴───────────────────────╯ │ │ │ │ │ │
│   │ │   │ │   │ │   │ │   │ ╰───┴───────────────────────────────╯ │ │ │ │ │
│   │ │   │ │   │ │   │ ╰───┴───────────────────────────────────────╯ │ │ │ │
│   │ │   │ │   │ ╰───┴───────────────────────────────────────────────╯ │ │ │
│   │ │   │ ╰───┴───────────────────────────────────────────────────────╯ │ │
│   │ ╰───┴───────────────────────────────────────────────────────────────╯ │
╰───┴───────────────────────────────────────────────────────────────────────╯
$ {} | upsert a.b.c.d.e.f.g.h.i value
╭───┬───────────────────────────────────────────────────────────────────────╮
│   │ ╭───┬───────────────────────────────────────────────────────────────╮ │
│ a │ │   │ ╭───┬───────────────────────────────────────────────────────╮ │ │
│   │ │ b │ │   │ ╭───┬───────────────────────────────────────────────╮ │ │ │
│   │ │   │ │ c │ │   │ ╭───┬───────────────────────────────────────╮ │ │ │ │
│   │ │   │ │   │ │ d │ │   │ ╭───┬───────────────────────────────╮ │ │ │ │ │
│   │ │   │ │   │ │   │ │ e │ │   │ ╭───┬───────────────────────╮ │ │ │ │ │ │
│   │ │   │ │   │ │   │ │   │ │ f │ │   │ ╭───┬───────────────╮ │ │ │ │ │ │ │
│   │ │   │ │   │ │   │ │   │ │   │ │ g │ │   │ ╭───┬───────╮ │ │ │ │ │ │ │ │
│   │ │   │ │   │ │   │ │   │ │   │ │   │ │ h │ │ i │ value │ │ │ │ │ │ │ │ │
│   │ │   │ │   │ │   │ │   │ │   │ │   │ │   │ ╰───┴───────╯ │ │ │ │ │ │ │ │
│   │ │   │ │   │ │   │ │   │ │   │ │   │ ╰───┴───────────────╯ │ │ │ │ │ │ │
│   │ │   │ │   │ │   │ │   │ │   │ ╰───┴───────────────────────╯ │ │ │ │ │ │
│   │ │   │ │   │ │   │ │   │ ╰───┴───────────────────────────────╯ │ │ │ │ │
│   │ │   │ │   │ │   │ ╰───┴───────────────────────────────────────╯ │ │ │ │
│   │ │   │ │   │ ╰───┴───────────────────────────────────────────────╯ │ │ │
│   │ │   │ ╰───┴───────────────────────────────────────────────────────╯ │ │
│   │ ╰───┴───────────────────────────────────────────────────────────────╯ │
╰───┴───────────────────────────────────────────────────────────────────────╯
```

This behavior should be expected of lists as well, and works if the lists encountered along the path already exist:
```nu
{a: {b: {c: {d: {e: {f: {g: {h: {i: []}}}}}}}}}  | insert a.b.c.d.e.f.g.h.i.0 value
╭───┬───────────────────────────────────────────────────────────────────────────────╮
│   │ ╭───┬───────────────────────────────────────────────────────────────────────╮ │
│ a │ │   │ ╭───┬───────────────────────────────────────────────────────────────╮ │ │
│   │ │ b │ │   │ ╭───┬───────────────────────────────────────────────────────╮ │ │ │
│   │ │   │ │ c │ │   │ ╭───┬───────────────────────────────────────────────╮ │ │ │ │
│   │ │   │ │   │ │ d │ │   │ ╭───┬───────────────────────────────────────╮ │ │ │ │ │
│   │ │   │ │   │ │   │ │ e │ │   │ ╭───┬───────────────────────────────╮ │ │ │ │ │ │
│   │ │   │ │   │ │   │ │   │ │ f │ │   │ ╭───┬───────────────────────╮ │ │ │ │ │ │ │
│   │ │   │ │   │ │   │ │   │ │   │ │ g │ │   │ ╭───┬───────────────╮ │ │ │ │ │ │ │ │
│   │ │   │ │   │ │   │ │   │ │   │ │   │ │ h │ │   │ ╭───┬───────╮ │ │ │ │ │ │ │ │ │
│   │ │   │ │   │ │   │ │   │ │   │ │   │ │   │ │ i │ │ 0 │ value │ │ │ │ │ │ │ │ │ │
│   │ │   │ │   │ │   │ │   │ │   │ │   │ │   │ │   │ ╰───┴───────╯ │ │ │ │ │ │ │ │ │
│   │ │   │ │   │ │   │ │   │ │   │ │   │ │   │ ╰───┴───────────────╯ │ │ │ │ │ │ │ │
│   │ │   │ │   │ │   │ │   │ │   │ │   │ ╰───┴───────────────────────╯ │ │ │ │ │ │ │
│   │ │   │ │   │ │   │ │   │ │   │ ╰───┴───────────────────────────────╯ │ │ │ │ │ │
│   │ │   │ │   │ │   │ │   │ ╰───┴───────────────────────────────────────╯ │ │ │ │ │
│   │ │   │ │   │ │   │ ╰───┴───────────────────────────────────────────────╯ │ │ │ │
│   │ │   │ │   │ ╰───┴───────────────────────────────────────────────────────╯ │ │ │
│   │ │   │ ╰───┴───────────────────────────────────────────────────────────────╯ │ │
│   │ ╰───┴───────────────────────────────────────────────────────────────────────╯ │
╰───┴───────────────────────────────────────────────────────────────────────────────╯
```
But returns an error when it does not (e.g when the list at `i` is removed above):
```nu
{a: {b: {c: {d: {e: {f: {g: {h: {}}}}}}}}}  | insert a.b.c.d.e.f.g.h.i.0 value
Error: nu::shell::not_a_list

  × Not a list value
   ╭─[entry #24:1:72]
 1 │ {a: {b: {c: {d: {e: {f: {g: {h: {}}}}}}}}}  | insert a.b.c.d.e.f.g.h.i.0 value
   ·                                                                        ┬ ──┬──
   ·                                                                        │   ╰── value originates here
   ·                                                                        ╰── value not a list
   ╰────
```
Similarly if any of its ancestors are missing:
```nu
$ {} | insert a.0 value
Error: nu::shell::not_a_list

  × Not a list value
   ╭─[entry #25:1:15]
 1 │ {} | insert a.0 value
   ·               ┬   ┬
   ·               │   ╰── value originates here
   ·               ╰── value not a list
   ╰────
```
A similar, though distinct, error is found when inserting descendants:
```nu
$ {a:[]} | upsert a.0.b value
Error: nu::shell::access_beyond_end

  × Row number too large (max: 18446744073709551615).
   ╭─[entry #29:1:19]
 1 │ {a:[]} | upsert a.0.b value
   ·                   ┬
   ·                   ╰── index too large (max: 18446744073709551615)
   ╰────
```

### How to reproduce

1. Insert value into non-existent list:
    ```nu
    {}  | insert a.0 value
    Error: nu::shell::not_a_list
    
      × Not a list value
       ╭─[entry #35:1:16]
     1 │ {}  | insert a.0 value
       ·                ┬ ──┬──
       ·                │   ╰── value originates here
       ·                ╰── value not a list
       ╰────
    ```
1. Insert value into descendents in non-existent list:
    ```nu
    {}  | insert a.0.b value # {a:[{ b:"value"}]}
    Error: nu::shell::not_a_list
    
      × Not a list value
       ╭─[entry #38:1:16]
     1 │ {}  | insert a.0.b value
       ·                ┬   ──┬──
       ·                │     ╰── value originates here
       ·                ╰── value not a list
       ╰────
    ```

### Expected behavior

I expected `nu` to: 
1. Insert value into non-existent list:    
    ```nu
    {}  | insert a.0 value # {a:["value"]}
    ```
    Should output
    ```
    ╭───┬───────────────╮
    │   │ ╭───┬───────╮ │
    │ a │ │ 0 │ value │ │
    │   │ ╰───┴───────╯ │
    ╰───┴───────────────╯
    ```
1. Insert value into descendents in non-existent list:
    ```nu
    {}  | insert a.0.b value # {a:[{ b:"value"}]}
    ```
    Should output
    ```
    ╭───┬───────────────╮
    │   │ ╭───┬───────╮ │
    │ a │ │ # │   b   │ │
    │   │ ├───┼───────┤ │
    │   │ │ 0 │ value │ │
    │   │ ╰───┴───────╯ │
    ╰───┴───────────────╯
    ```

### Configuration

| key                | value                                          |
| ------------------ | ---------------------------------------------- |
| version            | 0.102.0                                        |
| major              | 0                                              |
| minor              | 102                                            |
| patch              | 0                                              |
| branch             |                                                |
| commit_hash        |                                                |
| build_os           | macos-aarch64                                  |
| build_target       | aarch64-apple-darwin                           |
| rust_version       | rustc 1.84.1 (e71f9a9a9 2025-01-27) (Homebrew) |
| cargo_version      | cargo 1.84.1                                   |
| build_time         | 2025-02-04 15:49:35 +00:00                     |
| build_rust_channel | release                                        |
| allocator          | mimalloc                                       |
| features           | default, sqlite, trash                         |
| installed_plugins  | diff 0.1.0                                     |

### PR DESCRIPTION
**Pull request by MMukundi**
# Description
This PR fixes #15131 by allowing the `insert` and `upsert` commands to create lists where they may be expected based on the cell path provided. For example, the below would have previously thrown an error, but now creates lists and list elements where necessary
Screenshot 2025-02-17 at 2 46 12 AM
Screenshot 2025-02-17 at 2 46 16 AM
Screenshot 2025-02-17 at 2 45 43 AM

# User-Facing Changes

This change removes errors that were previously raised by `insert_data_at_cell_path` and `upsert_data_at_cell_path`. If one of these commands encountered an unknown cell path in cases such as these, it would either raise a "Not a list value" as the list index is used on a record:

Screenshot 2025-02-17 at 2 46 43 AM

Or a "Row number too large" when required to create a new list element along the way:
Screenshot 2025-02-17 at 2 46 51 AM

But both now succeed, which seems to be the intention as it is in parity with record behavior. Any consumers depending on this specific behavior will see these errors subside.

This change also includes the public static method `Value::with_data_at_cell_path` that creates a value with a given nested value at a given cell path, creating records or lists based on the path member type. Plugin developers may begin using this method as its part of the public API now, quite similar to related siblings `Value::insert_data_at_cell_path` and`Value::upsert_data_at_cell_path`.

# Tests + Formatting
In addition to unit tests for the altered behavior, both affected user-facing commands (`insert` and `upsert`) gained a new command example to both explain and test this change at the user level.
Screenshot 2025-02-17 at 2 29 26 AM

Note: A single test did fail locally, due to my config directory differing from expected, but works where this variable is unset (`with-env { XDG_CONFIG_HOME: null } {cargo test}`):
```
---- repl::test_config_path::test_default_config_path stdout ----
thread 'repl::test_config_path::test_default_config_path' panicked at tests/repl/test_config_path.rs:101:5:
assertion failed: `(left == right)`

Diff < left / right > :
<[home_dir]/Library/Application Support/nushell
>[home_dir]/.config/nushell
```
# After Submitting

### CODE REVIEW

File: crates/nu-protocol/src/value/mod.rs [hunk 1]
```diff
@@ -1813,6 +1786,42 @@ impl Value {
         Ok(())
     }
 
+    /// Creates a new [Value] with the specified member at the specified path.
+    /// This is used by [Value::insert_data_at_cell_path] and [Value::upsert_data_at_cell_path] whenever they have the need to insert a non-existent element
+    pub fn with_data_at_cell_path(
```
Comment (IanManske) [inline crates/nu-protocol/src/value/mod.rs:1791]:
```suggestion
    fn with_data_at_cell_path(
```

This can be private I think.

File: crates/nu-protocol/src/value/mod.rs [hunk 2]
```diff
@@ -1813,6 +1786,42 @@ impl Value {
...
+        cell_path: &[PathMember],
+        value: Value,
+        span: Span,
```
Comment (IanManske) [inline crates/nu-protocol/src/value/mod.rs:1794]:
```suggestion
```

This doesn't need to be passed a `Span`, since it looks like `span` is always `value.span()`.

**Review by IanManske — COMMENTED** [review]
Thanks for the PR! Creating new lists with an insert seems like an odd use case, but I don' t see a reason why it should be disallowed. I think the PR looks good, just a few minor things:

**Comment by MMukundi** [comment]
Thanks for taking a look, I'll get those fixes in!

**Comment by IanManske** [comment]
Thanks again for the PR!
