### PR TITLE
make `first` behave same way as `last`: always return list when with number argument

### LINKED ISSUE #6611: Inconsistent `first` vs `last` behavior
### Describe the bug

`first` and `last` have different behavior when given a positional argument of `1`. `first 1` behaves analogously to `first` (yields an element), whereas `last 1` always maintains a table/list. The behavior of `last 1` seems more useful (as `first` changes type/behavior based on the value of the param given).

### How to reproduce

```
/tmp〉echo [a, b] | first
a
/tmp〉echo [a, b] | last
b
/tmp〉echo [a, b] | first 1
a
/tmp〉echo [a, b] | last 1
╭───┬───╮
│ 0 │ b │
╰───┴───╯
/tmp〉echo [a, b] | first 2
╭───┬───╮
│ 0 │ a │
│ 1 │ b │
╰───┴───╯
/tmp〉echo [a, b] | last 2
╭───┬───╮
│ 0 │ a │
│ 1 │ b │
╰───┴───╯
```

### Expected behavior

All behavior is as expected except for `first 1`, for which I expect the output to be:

```
/tmp〉echo [a, b] | first 1
╭───┬───╮
│ 0 │ a │
╰───┴───╯
```

### Screenshots

_No response_

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.68.1                                          |
| branch             |                                                 |
| commit_hash        | e76b3d61deef832adce76b0f73f19131de8cbc9e        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.63.0 (Arch Linux rust 1:1.63.0-1)       |
| cargo_version      | cargo 1.63.0                                    |
| pkg_version        | 0.68.1                                          |
| build_time         | 2022-09-10 09:52:14 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by merelymyself**
# Description

Fixes #6611. This is a breaking change, but a necessary one; this brings `first` in line with `last`, where `first 1` returns a list as well.

# Tests

Make sure you've done the following:

- [x] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [x] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [x] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [ ] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [ ] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [ ] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

File: crates/nu-command/src/filters/first.rs [hunk 1]
```diff
@@ -145,20 +148,11 @@ fn first_helper(
...
-                        .take(rows_desired)
-                        .into_pipeline_data(ctrlc)
-                        .set_metadata(metadata))
-                }
-            }
+            _ => Ok(input_peek
+                .into_iter()
+                .take(rows_desired)
+                .into_pipeline_data(ctrlc)
+                .set_metadata(metadata)),
```
Comment (extemporalgenome) [inline crates/nu-command/src/filters/first.rs:155]: Based on what the change appears to be doing, this will once again break consistency with `last`: `first 1` will now return a list, just as `last 1` already did, but `first` (without a positional param) will now also return a list whereas `last` (without a positional param) will return an element.

Compare to https://github.com/nushell/nushell/blob/483f007b092fee3cfcdc77461daba9f838fd6594/crates/nu-command/src/filters/last.rs#L34-L46

The only real difference is that `last` (prior to this PR) had the more self-consistent implementation.

**Comment by extemporalgenome** [comment]
> as far as possible, commands should always return the same data type.

Arguably `first` and `last` (at least as likely intended) had a fine, useful design:

1. When given a positional argument, always produce a collection (`list<T> -> list<T>`).
2. When not given a positional argument, produce an element (`list<T> -> `T`).

A typical caller will presumably have consistent use (or non-use) of a positional parameter, and thus the types would be consistent for either calling style (i.e. regardless of the _value_ of the parameter when passed).

`last` without a positional parameter, as a means to return the last element, is particularly useful since the alternative would, afaict, be `get (($it | length) - 1)`, which is considerably less concise.

Similarly, `first` without a positional parameter conveys more semantic meaning to the reader than `get 0` (which involves a magic number).

**Comment by merelymyself** [comment]
Hmm, I see. Your suggestion makes sense.

**Comment by extemporalgenome** [comment]
It might be prudent to add `Example` tests for `[1 2 3] | first 1` and `[1 2 3] | last 1`, as those are the regression behaviors covered/enforced by this fix.

**Comment by extemporalgenome** [comment]
Looks awesome, thanks!

**Comment by fdncred** [comment]
thanks
