### PR TITLE
Deprecate `register` and add `plugin use`

### LINKED ISSUE #11923: Parsing a `register` command at the prompt can execute arbitrary files
### Describe the bug

This happens during completion, or even just if the whole register command is typed without executing it. The parser runs the plugin to get the signatures immediately even while still typing at the prompt. The file must begin with `nu_plugin_` in order to be executed, but that's the only caveat - any kind of file that could be a valid plugin will be run.

### How to reproduce

On Unix-like operating systems, a really easy way is to just create an executable nushell script:

1. Save the following into "nu_plugin_drop_file.nu"
    
    ```nushell
    #!/usr/bin/env nu
    "I dropped a file!" | save dropped_file.txt
    ```
2. Make the file executable: `chmod +x nu_plugin_drop_file.nu`
3. Type `register nu_plugin_drop_file.nu`, or autocomplete to get to that point - it just needs to be on the prompt
4. Without executing the command, notice that "dropped_file.txt" now exists in the current directory.

### Expected behavior

Typing a register command at the prompt shouldn't cause anything to be executed until the user actually runs the command.

### Screenshots

_No response_

### Configuration

| key                | value                                                                         |
| ------------------ | ----------------------------------------------------------------------------- |
| version            | 0.90.1                                                                        |
| branch             |                                                                               |
| commit_hash        |                                                                               |
| build_os           | linux-x86_64                                                                  |
| build_target       | x86_64-unknown-linux-gnu                                                      |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)                                           |
| rust_channel       | stable-x86_64-unknown-linux-gnu                                               |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)                                           |
| build_time         | 2024-02-07 01:27:39 -08:00                                                    |
| build_rust_channel | release                                                                       |
| allocator          | mimalloc                                                                      |
| features           | dataframe, default, extra, sqlite, trash, which, zip                          |
| installed_plugins  | dbus, dbus call, dbus get, dbus get-all, dbus introspect, dbus list, dbus set |

### Additional context

It's pretty unlikely that this could be exploited for malicious intent, but it still seems unexpected that arbitrary code could execute just by existing on the prompt, without explicitly running it.

### PR DESCRIPTION
**Pull request by devyn**
# Description

Adds a new keyword, `plugin use`. Unlike `register`, this merely loads the signatures from the plugin cache file. The file is configurable with the `--plugin-config` option either to `nu` or to `plugin use` itself, just like the other `plugin` family of commands. At the REPL, one might do this to replace `register`:

```nushell
> plugin add ~/.cargo/bin/nu_plugin_foo
> plugin use foo
```

This will not work in a script, because `plugin use` is a keyword and `plugin add` does not evaluate at parse time (intentionally). This means we no longer run random binaries during parse.

The `--plugins` option has been added to allow running `nu` with certain plugins in one step. This is used especially for the `nu_with_plugins!` test macro, but I'd imagine is generally useful. The only weird quirk is that it has to be a list, and we don't really do this for any of our other CLI args at the moment.

`register` now prints a deprecation parse warning.

This should fix #11923, as we now have a complete alternative to `register`.

# User-Facing Changes

- Add `plugin use` command
- Deprecate `register`
- Add `--plugins` option to `nu` to replace a common use of `register`

# Tests + Formatting

I think I've tested it thoroughly enough and every existing test passes. Testing nu CLI options and alternate config files is a little hairy and I wish there were some more generic helpers for this, so this will go on my TODO list for refactoring.

- :green_circle: `toolkit fmt`
- :green_circle: `toolkit clippy`
- :green_circle: `toolkit test`
- :green_circle: `toolkit test stdlib`

# After Submitting

- [ ] Update plugins sections of book
- [ ] Release notes

### CODE REVIEW

**Comment by sholderbach** [comment]
Not sold that the creation of a separate `nu-cmd-plugin` crate is warranted in this PR. This bloats up the diff on top of having to figure out if things are coming from your additional plugin related branches (or is this just https://github.com/nushell/nushell/pull/12607/commits/5795b930442ccff3be1632d79bcf5274a0a8af56)
Also each command crate needs some additional eyeballs if the testing harness is wired up correctly.

**Comment by devyn** [comment]
> Not sold that the creation of a separate `nu-cmd-plugin` crate is warranted in this PR. This bloats up the diff on top of having to figure out if things are coming from your additional plugin related branches (or is this just [5795b93](https://github.com/nushell/nushell/commit/5795b930442ccff3be1632d79bcf5274a0a8af56)) Also each command crate needs some additional eyeballs if the testing harness is wired up correctly.

Apologies, this was created in [5795b93](https://github.com/nushell/nushell/commit/5795b930442ccff3be1632d79bcf5274a0a8af56). I created this PR early, before that got merged. I've rebased to clean up the history.

Let me know on tests - I'm currently in the battle to fix all of that now and I think I've finally got it. The only complicated part is testing `nu` with a specific plugin cache file, because there isn't a helper for that at the moment. I noticed that there's a whole bunch of stuff in `Playground` with `Director` that doesn't really seem to be used anymore, in favor of the macros, but I'm sort of thinking that could be brought back for when it's necessary to run `nu` with custom options.

`nu_plugin_nu_example` was also tricky because it doesn't work with `nu_with_plugins!` because the path is different from what that expects, so I had to do that as a one-off too.

File: crates/nu-cmd-plugin/src/commands/plugin/use_.rs [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+`--plugin` option to `nu` instead.
+
+If the plugin was already loaded, this will reload the latest definition from
+the cache file into scope.
+"#
+        .trim()
+    }
+
+    fn search_terms(&self) -> Vec<&str> {
+        vec!["add", "plugin", "register", "scope", "use"]
```
Comment (fdncred) [inline crates/nu-cmd-plugin/src/commands/plugin/use_.rs:49]: The unwritten rule here is to not have any search terms here that are in the name of the command, because these are exclusively here for `help -f`, searching. I've noticed this on a few of your recent commands and forgot to mention it. So, what I'm saying, to be clear, this should probably remove `plugin` and `use` in the search terms here because they're part of the command name.

File: src/command.rs [hunk 2]
```diff
@@ -337,12 +367,19 @@ impl Command for Nu {
...
+                .named(
+                    "plugin-config",
+                    SyntaxShape::String,
+                    "start with an alternate plugin cache file",
+                    None,
+                )
+                .named(
+                    "plugins",
+                    SyntaxShape::List(Box::new(SyntaxShape::String)),
+                    "list of plugin executables to load, separately from the cache file",
```
Comment (fdncred) [inline src/command.rs:380]: Does this list contain the the name (inc), the filename (nu_plugin_inc), or the command name (inc)? As I mentioned with your PR that I landed earlier today, we should standardize because it's a bit confusing.

File: crates/nu-cmd-plugin/src/commands/plugin/use_.rs (hunk 1 above)
Comment (sholderbach) [reply crates/nu-cmd-plugin/src/commands/plugin/use_.rs:49]: I added the test that is draconian about this back in the day when all commands just lived in `nu-command` local to that crate (https://github.com/nushell/nushell/pull/6380).
It wasn't moved to a better place during cratification, so it doesn't affect new additions of `nu-cmd-*` crates.

File: src/command.rs (hunk 2 above)
Comment (devyn) [reply src/command.rs:380]: This is executable file names. It's meant to be used when adding to a plugin cache isn't convenient.

File: crates/nu-cmd-plugin/src/commands/plugin/use_.rs (hunk 1 above)
Comment (devyn) [reply crates/nu-cmd-plugin/src/commands/plugin/use_.rs]: Thanks - let me know if I step on anything like this in the future too, for sure

File: src/command.rs (hunk 2 above)
Comment (devyn) [reply src/command.rs]: I think I've cleared this up so that it appears as a filepath now, and says 'executable files'

**Comment by devyn** [comment]
I notice that the `--include-path` arg separates by `char record_sep` (`\x1e`) to take multiple arguments. Should I do the same for `--plugins` instead?

Not sure which is worse - having to pass a list of quoted strings as nuon, or having to use a character that not a lot of people are familiar with

**Comment by fdncred** [comment]
> I notice that the --include-path arg separates by char record_sep (\x1e) to take multiple arguments. Should I do the same for --plugins instead?

I wouldn't use record_sep in your situation here. I had to use it in `--include-path` because that is specifically for serialization/deserialization to the vscode extension that implements the lsp-like code that we currently use. We tried a few other separators and each failed, so I got tired of using a common separator and chose an uncommon one.

**Comment by devyn** [comment]
> Having said that, I'm still not real sure what `--plugins` is all about. I guess it's for specifying which plugins to load at startup when you don't want all of them... maybe?

It's actually more for launching nushell with a specific set of plugins, especially if you're also going to use `--no-config-file`. It's possible that if you're using nushell as more of a generic scripting/programming language, you don't want user configuration to mess with your script, and you also might have specific plugins you need to run with. This allows you to pass all of that to `nu`.

This is actually something we need ourselves, because previously we were just adding `register` commands to `--commands` for our tests (`nu_with_plugins!()`), but this becomes rather difficult now with the `plugin add` / `plugin use` split, and the only other way I could think to do it is to run `nu` twice to prepare a plugin cache file the first time, and then use it in the test. That seems like a pain, so I'm just providing an escape hatch from that with the `--plugins` option, where it doesn't touch plugin cache files at all and just gets signatures directly from the plugin immediately on startup.

The implicit assumption also being that you're going to use the plugins anyway if you're specifying them there, so it doesn't really matter that we have to launch the plugin to get the signatures; we're going to do that anyway. Very different from the shell context where we want to have the quickest startup time possible and it's very likely that a user is going to use only a few if any of their installed plugins at any given time.

**Comment by fdncred** [comment]
Thanks for explaining. Let's move forward with this since it's a big piece of the new plugin upgrade.
