### PR TITLE
fix: Add error handling for rounding non finite numbers

### LINKED ISSUE #16927: `math round` converts `inf` to a large integer
### Bug report form

- [x] I have done a basic search of the issue tracker to find any existing issues that are similar.
- [x] I have checked that my version is at least the latest stable release available via my installation method.

### Describe the bug

`inf | math round` returns 9223372036854775807, `i64::MAX`, which is a bit counterintuitive.

### How to reproduce

```nushell
~> inf | math round 
9223372036854775807
~> nan | math round
0
```

### Expected behavior

I'd expect `math round` to either leave `inf` and `nan` as is or throw an error.  This conversion only takes place when the signature is `float -> int` (so, precision >= 0), so perhaps an error would be more appropriate.

### Configuration

| key                  | value                                              |
| -------------------- | -------------------------------------------------- |
| version              | 0.107.0                                            |
| major                | 0                                                  |
| minor                | 107                                                |
| patch                | 0                                                  |
| branch               |                                                    |
| commit_hash          | c3a699294685c6c6a6581dff2bc4089ca275eb58           |
| build_os             | linux-x86_64                                       |
| build_target         | x86_64-unknown-linux-musl                          |
| rust_version         | rustc 1.89.0 (29483883e 2025-08-04)                |
| rust_channel         | stable-x86_64-unknown-linux-musl                   |
| cargo_version        | cargo 1.89.0 (c24e10642 2025-06-23)                |
| build_time           | 2025-09-03 11:05:42 +03:00                         |
| build_rust_channel   | release                                            |
| allocator            | standard                                           |
| features             | default, plugin, rustls-tls, sqlite, trash-support |
| installed_plugins    | endecode 0.107.0, fs 0.107.0                       |
| experimental_options | example=false, reorder-cell-paths=false            |

### PR DESCRIPTION
**Pull request by AnandajithS**
Fixes #16927 

## Release notes summary - What our users need to know
`math round` now returns an error when trying to round non-finite numbers (inf or nan), instead of converting them to large integer values.

## Tasks after submitting

- [ ] Update the [documentation](https://github.com/nushell/nushell.github.io)

### CODE REVIEW

File: crates/nu-command/src/math/round.rs [hunk 1]
```diff
@@ -134,14 +134,28 @@ fn operate(value: Value, head: Span, precision: Option<i64>) -> Value {
...
-                span,
-            ),
-            None => Value::int(val.round() as i64, span),
-        },
+        Value::Float { val, .. } => {
+            if !val.is_finite() {
+                return Value::error(
+                    ShellError::UnsupportedInput {
+                        msg: "cannot round non-finite number".into(),
+                        input: " ".into(),
```
Comment (WindSoilder) [inline crates/nu-command/src/math/round.rs]:
```suggestion
                        input: "value originates from here".into(),
```

**Review by WindSoilder — CHANGES_REQUESTED** [review]
Hi, thank you for your contribution.  Looks good to me, just left a thought

**Review by WindSoilder — APPROVED** [review]
Thanks!
