### PR TITLE
check signals in `nu-glob` and `ls`

### LINKED ISSUE #10144: ls hangs and cannot be killed with ^C
### Describe the bug

`ls /**/*.html` hangs and cannot be killed with ^C (Ctrl-C).

### How to reproduce

1. launch nushell
2. `ls /**/*.html` (aka look for all html files from the root dir, ran as non-root on Mac OS)
3. Type `^C`

`^C`  will be printed multiple times on the last line of the shell, but does not kill `ls`.

### Expected behavior

I should be able to kill `ls` at any time if it's taking too long to return something.

### Screenshots

_No response_

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.84.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03) (built from a source tarball) |
| cargo_version      | cargo 1.71.2 (1a737af0c 2023-08-07)                               |
| build_time         | 2023-08-22 21:09:23 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | standard                                                          |
| features           | dataframe, default, sqlite, trash, which, zip                     |
| installed_plugins  |                                                                   |

### Additional context

I can reproduce this almost every time, since it always hang by itself anyways.
But sometimes I can kill `ls` if I'm fast enough, as soon as it has printed the first table for example. But it's difficult to be fast enough.

### PR DESCRIPTION
**Pull request by sgvictorino**
Fixes #10144

# User-Facing Changes

Long running glob expansions and `ls` runs (e.g. `ls /**/*`) can now be
interrupted with ctrl-c.

### CODE REVIEW

File: crates/nu-glob/src/lib.rs [hunk 1]
```diff
@@ -983,7 +1011,13 @@ fn fill_todo(
                     //             .starts_with('.')
                     //     });
                     // }
-                    children.sort_by(|p1, p2| p2.file_name().cmp(&p1.file_name()));
+                    children.sort_by(|p1, p2| {
+                        if signals.interrupted() {
+                            std::cmp::Ordering::Equal
```
Comment (sholderbach) [inline crates/nu-glob/src/lib.rs:1016]: Can this `Ordering::Equal` cause any weirdness? 

I think we should check below again for `signals.interrupted` and explicitly return the error.

File: crates/nu-command/src/filesystem/ls.rs [hunk 2]
```diff
@@ -969,8 +976,14 @@ fn read_dir(
                 .map_err(ShellError::from)
         });
     if !use_threads {
-        let mut collected = items.collect::<Vec<_>>();
+        let mut collected = items
+            .map(|i| {
+                signals.check(span)?;
+                Ok(i)
+            })
```
Comment (sholderbach) [inline crates/nu-command/src/filesystem/ls.rs:983]: While I guess this protects from stalling in the `FromIterator` stage, this only seems to introduce a checkpoint for the `!use_threads` case. Are we guarding the `use_threads` case in another way?

Would it make sense to lift this into the upper `map` closer to the I/O operations which may take even longer compared to the alloc?

File: crates/nu-glob/src/lib.rs (hunk 1 above)
Comment (sholderbach) [reply crates/nu-glob/src/lib.rs]: While I understand the potential for speedup, I think [`sort_by` may choose to panic](https://doc.rust-lang.org/std/primitive.slice.html#panics-38) if the interrupt changes the sort order mid-operation.

Changing a relation of three elements `a` `b` `c` from some ordering to `Equals` can violate both the [transitivity and duality properties for `PartialOrd`](https://doc.rust-lang.org/std/cmp/trait.PartialOrd.html) and the [rules for `Ord`](https://doc.rust-lang.org/std/cmp/trait.Ord.html#corollaries)

File: crates/nu-command/src/filesystem/ls.rs (hunk 2 above)
Comment (sholderbach) [reply crates/nu-command/src/filesystem/ls.rs]: OK if the other branch is interrupting its fine to not duplicate that check. But whatever is readable enough so it doesn't break easily on the next refactor/feature addition is fine by me.

**Comment by sholderbach** [comment]
Are we through this?

Just as a heads up from a reviewing point of view, force-pushed amended commits are really hard to follow when a conversation is happening, as we squash at the end its fine to leave an iterative history. (I am fine with a force-push when things are rebased onto larger upstream change and its more readable than a big merge commit blob which GH doesn't render well, or if you tweaked one particular commit due to formatting or whatever in a larger history)

**Comment by sholderbach** [comment]
Thanks, let's give it a try :)
