### PR TITLE
bugfix: add "to yml" command

### LINKED ISSUE #15240: Saving a data structure as yaml works with .yaml extension but not .yml
### Describe the bug

Piping into `save` with yaml extension works but yml fails

### How to reproduce

1. Run `ls|save -f test.yaml`
2. Notice command succeded
3. Run `ls|save -f test.yml`
4. Notice failure

### Expected behavior

I expected behavior to be consistent regardless of the extension

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.102.0                                                           |
| major              | 0                                                                 |
| minor              | 102                                                               |
| patch              | 0                                                                 |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.84.1 (e71f9a9a9 2025-01-27) (built from a source tarball) |
| cargo_version      | cargo 1.84.0 (66221abde 2024-11-19)                               |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash                                            |
| installed_plugins  | formats 0.102.0, highlight 1.4.3+0.102.0, query 0.102.0           |

### PR DESCRIPTION
**Pull request by LoicRiegel**
# Description
This fixes #15240, which can be closed after merge.

# User-Facing Changes
- user get now use `to yml` -> exactly the same as `to yaml`

2025-03-06_00h01_27

# Tests + Formatting
Cargo fmt and clippy 🆗 
I added a test in the only place I could find where `to yaml` was already tested.

I didn't see the `save.rs::convert_to_extension` function tested anywhere, but maybe I missed it.

# After Submitting

Not sure this needs an update on the documentation ❓ What do you suggest?

### CODE REVIEW

File: crates/nu-command/src/formats/to/yaml.rs [hunk 1]
```diff
@@ -47,6 +47,52 @@ impl Command for ToYaml {
...
+            .category(Category::Formats)
+    }
+
+    fn description(&self) -> &str {
+        "Convert table into .yaml/.yml text."
+    }
+
+    fn examples(&self) -> Vec<Example> {
+        vec![Example {
+            description: "Outputs an YML string representing the contents of this table",
```
Comment (sholderbach) [inline crates/nu-command/src/formats/to/yaml.rs:75]: I would say this is still a `YAML` string based on the format, its just the extension for the lazy/3-letter purists
```suggestion
            description: "Outputs a YAML string representing the contents of this table",
```

**Review by sholderbach — APPROVED** [review]
Thanks!

I was thinking if we could get by with a `.nu` version of this as part of the `std` prelude. But supporting all the flags and documentation like this may still be kind of messy. So I am fine with the Rust-duplication alias.

**Comment by LoicRiegel** [comment]
> Thanks!
> 
> I was thinking if we could get by with a `.nu` version of this as part of the `std` prelude. But supporting all the flags and documentation like this may still be kind of messy. So I am fine with the Rust-duplication alias.

I thought the duplication was okay because that's already the case for `FromYaml` and `FromYml`, but if there's a better approach I'm okay to change

**Comment by LoicRiegel** [comment]
> Not sure this needs an update on the documentation ❓ What do you suggest?

Also what's your take on this?

**Comment by sholderbach** [comment]
> I thought the duplication was okay because that's already the case for `FromYaml` and `FromYml`, but if there's a better approach I'm okay to change

Yeah fine based on precedent as well. Let's go with this approach for now


> > Not sure this needs an update on the documentation ❓ What do you suggest?
> 
> Also what's your take on this?

I think it suffices that the command will appear in the autogenerated command help.
 We may want to improve the docs around this `open`/`save` mapping to `to ...` and `from ...` at some point.
But for this change I think you don't need to change anything in the permanent docs. Just free free to add it to the release notes as a new command with a brief example that saving with `.yml` ending works now. 
- https://github.com/nushell/nushell.github.io/pull/1783

**Comment by sholderbach** [comment]
If you edit it in the web interface it will probably ask you to open a PR. If you start your changes locally, you will have to set the target branch of the PR to `release-notes-0.103.0`.

**Comment by LoicRiegel** [comment]
Hi @sholderbach I did [that PR](https://github.com/nushell/nushell.github.io/pull/1828) for the release note but I think nobody saw it
I saw the contribution mentioned in the weekly blog, though

**Comment by sholderbach** [comment]
Thanks! Sorry that I didn't get around to it. Nice user-friendly writeup!
