### PR TITLE
Command-wide completions

### LINKED ISSUE #14504: `def --wrapped` does not invoke shell completions for positional arguments
### Describe the bug

I have a custom command for running git with an env, as follows:

```nu
def --wrapped git [...x] { TZ=UTC ^git ...$x }
```

When working with this new `git`, nushell does not invoke shell completions for positional arguments like file names. It does seem to work correctly for flags.

### How to reproduce

Configure an external completer that logs the spans it gets:

```nu
let external_completer = {|spans|
    $"SPANS: ($spans)\n" | save --append ~/nu-log
    # ...
}

$env.config = {
    # ...

    completions: {
        case_sensitive: false
        quick: true
        partial: true
        algorithm: "prefix"
        external: {
            enable: true
            max_results: 100
            completer: $external_completer
        }
        use_ls_colors: true
    }
    # ...
```

Get a baseline, this behavior is expected:

```
$ git commit --**TAB** # shows completions like --all, --allow-empty
$ cat ~/nu-log
SPANS: [git, commit, --]
$ git commit --fixup **TAB** # space after --fixup, shows completions from the previous commits
$ cat ~/nu-log
SPANS: [git, commit, --]
SPANS: [git, commit, --fixup, ]
```

Add a wrapper definition and reload the shell:

```nu
# Always commit in UTC
def --wrapped git [...x] { TZ=UTC ^git ...$x }
```

Delete no-log and reload the shell, retry the above

```
$ git commit --**TAB** # works correctly
$ cat ~/nu-log
SPANS: [git, commit, --]
$ git commit --fixup **TAB** # space after --fixup, shows no completions
$ cat ~/nu-log
SPANS: [git, commit, --]
```

The flag completions work fine, but trying to complete an argument after `--fixup` doesn't seem to invoke the completion script. Results seem similar for anything positional like `git add **TAB**` which should list file.

### Expected behavior

Completion should work the same with and without the `--wrapped` function.

### Configuration

```
| key                | value                                          |
| ------------------ | ---------------------------------------------- |
| version            | 0.100.0                                        |
| major              | 0                                              |
| minor              | 100                                            |
| patch              | 0                                              |
| branch             |                                                |
| commit_hash        |                                                |
| build_os           | macos-aarch64                                  |
| build_target       | aarch64-apple-darwin                           |
| rust_version       | rustc 1.82.0 (f6e511eec 2024-10-15) (Homebrew) |
| cargo_version      | cargo 1.82.0                                   |
| build_time         | 2024-11-13 03:28:47 +00:00                     |
| build_rust_channel | release                                        |
| allocator          | mimalloc                                       |
| features           | default, sqlite, trash                         |
| installed_plugins  |                                                |
```

### LINKED ISSUE #14806: Enable dynamic completion by providing a list of strings during completion
As mentioned on [discord](https://discord.com/channels/601130461678272522/958067223187062834/1323124762007961703), a single completer function can be used for all scenarios of a single command by defining it like this:

```nushell
def "nu-complete foo" [ctx: string, pos: int] { }
def foo [...rest: any@"nu-complete foo"] { }
```

For an external command, this looks like this:

```nushell
def "nu-complete foo" [ctx: string, pos: int] { }
export extern foo [...rest: any@"nu-complete foo"] { }
```

`ctx` is the entire command line up to the cursor, and `pos` is the length of `ctx`. This behavior would be much more useful if `nu-complete foo` would instead take a list of strings, similar to what external completers get.

The motivation for this is [dynamic completion](https://github.com/clap-rs/clap/issues/5840). In the case of `clap`, this means that the binary gets all arguments and then returns a `json` with the completions. One can already do this with nushell's external completer feature as demonstrated in https://github.com/clap-rs/clap/pull/5841, but one has to be careful to wrap the existing completers and only use the completer that actually handles the requested command.

### PR DESCRIPTION
**Pull request by Bahex**
- closes #14504
- closes #14806
- partially addresses #5035

---

Added `attr complete external`, which enables using the external completer for `extern` and custom command `def`initions:

```nushell
@complete external
def --wrapped jc [...args] {
    ^jc ...$args | from json
}
```

Added `attr complete` which uses another command (similar to the `arg: string@"command"`) to provide completions for _all arguments_ of a command:

```nushell
def fish-completer [spans: list<string>] {
	^fish ...
}

def carapace-completer [spans: list<string>] {
    ^carapace ...
}

@complete fish-completer
extern git []

@complete carapace-completer
def --env get-env [name] { $env | get $name }

@complete carapace-completer
def --env set-env [name, value] { load-env { $name: $value } }

@complete carapace-completer
def --env unset-env [name] { hide-env $name }
```

<details>
    <summary>Full implementation of <code>fish-completer</code> from the cookbook.</summary>

```nushell
def fish-completer [spans: list<string>] {
	^fish --command $"complete '--do-complete=($spans | str replace --all "'" "\\'" | str join ' ')'"
	| from tsv --flexible --noheaders --no-infer
	| rename value description
	| update value {|row|
		let value = $row.value
		let need_quote = ['\' ',' '[' ']' '(' ')' ' ' '\t' "'" '"' "`"] | any { $in in $value }
		if ($need_quote and ($value | path exists)) {
			let expanded_path = if ($value starts-with ~) { $value | path expand --no-symlink } else { $value }
			$'"($expanded_path | str replace --all "\"" "\\\"")"'
		} else { $value }
	}
}
```

</details>

Also includes the following bugfix:

-   `spans: list<string>` argument provided to the external completer (and completer commands used with `attr complete` with this addition) previously had invalid spans (from `Span::unknown`).
    These values now have correct spans pointing to their location in the source code.

<details><summary>This change was moved out to another PR</summary>

Using a nonexistent command name as a parameter completer now throws a parse error:
```
Error: nu::parser::unknown_command

  × Unknown command.
   ╭─[source:1:17]
 1 │ def foo [p: any@bar] { }
   ·                 ─┬─
   ·                  ╰── unknown command
   ╰────
```

</details>

## Release notes summary - What our users need to know

TODO

## Tasks after submitting
- [ ] Update the [custom completion documentation](https://www.nushell.sh/book/custom_completions.html)

### CODE REVIEW

File: crates/nu-protocol/src/signature.rs [hunk 1]
```diff
@@ -319,6 +319,8 @@ pub struct Signature {
     pub is_filter: bool,
     pub creates_scope: bool,
     pub allows_unknown_args: bool,
+    /// TODO: Use a proper type here
+    pub complete: Option<Option<DeclId>>,
```
Comment (blindFS) [inline crates/nu-protocol/src/signature.rs]: Another enum type named differently from the one used in Argument?

File: crates/nu-cmd-lang/src/core_commands/attr/complete.rs [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+impl Command for AttrComplete {
+    fn name(&self) -> &str {
+        "attr complete"
+    }
+
+    fn signature(&self) -> Signature {
+        Signature::build("attr complete")
+            .input_output_types(vec![
+                (Type::Nothing, Type::Nothing),
+                (Type::Nothing, Type::String),
```
Comment (blindFS) [inline crates/nu-cmd-lang/src/core_commands/attr/complete.rs]: Maybe unrelated, but why is `attr category`'s output type `list<string>`?

File: crates/nu-cli/src/completions/completer.rs [hunk 3]
```diff
@@ -349,143 +347,175 @@ impl NuCompleter {
...
-                            self.process_completion(&mut flag_completions, &ctx)
+                        if let Some(mut completion) = completion {
+                            let ctx = Context::new(working_set, span, b"", offset);
+                            let results = self.process_completion(&mut completion, &ctx);
+
+                            if !completion.need_fallback {
+                                // Prioritize external results over (sub)commands
+                                suggestions.splice(0..0, results);
+                                return suggestions;
+                            }
```
Comment (blindFS) [inline crates/nu-cli/src/completions/completer.rs:501]: I know that `need_fallback` goes hand in hand with empty results. But I would prefer moving the `splice` call out of the if block for better readability.

File: crates/nu-cli/src/completions/custom_completions.rs [hunk 4]
```diff
@@ -166,3 +167,176 @@ impl<T: Completer> Completer for CustomCompletion<T> {
...
+        if let Some(pos_arg) = block.signature.required_positional.first()
+            && let Some(var_id) = pos_arg.var_id
+        {
+            callee_stack.add_var(
+                var_id,
+                Value::list(
+                    args.into_iter()
+                        .map(|Spanned { item, span }| Value::string(item, span))
+                        .collect(),
+                    args_span,
```
Comment (blindFS) [inline crates/nu-cli/src/completions/custom_completions.rs:267]: Does this change of spanned args have further implications, like how are the spans going to be used?

File: crates/nu-cli/src/completions/custom_completions.rs [hunk 5]
```diff
@@ -166,3 +167,176 @@ impl<T: Completer> Completer for CustomCompletion<T> {
         }
     }
 }
+
+pub fn get_command_arguments(
```
Comment (blindFS) [inline crates/nu-cli/src/completions/custom_completions.rs:171]: Make it `pub(super)`? Or make it more general and move it somewhere in `flatten.rs`?

File: crates/nu-cli/src/completions/custom_completions.rs [hunk 6]
```diff
@@ -166,3 +167,176 @@ impl<T: Completer> Completer for CustomCompletion<T> {
...
+    working_set: &StateWorkingSet<'_>,
+    element_expression: &Expression,
+) -> Spanned<Vec<Spanned<String>>> {
+    let span = element_expression.span(&working_set);
```
Comment (blindFS) [inline crates/nu-cli/src/completions/custom_completions.rs:175]: Is this different from `element_expression.span`?

File: crates/nu-parser/src/parse_shape_specs.rs [hunk 7]
```diff
@@ -82,7 +82,12 @@ pub fn parse_completer(
         ));
         return None;
     }
-    working_set.find_decl(cmd_name)
+
+    let decl_id = working_set.find_decl(cmd_name);
+    if decl_id.is_none() {
+        working_set.error(ParseError::UnknownCommand(span));
+    }
+    decl_id
```
Comment (blindFS) [inline crates/nu-parser/src/parse_shape_specs.rs]: Maybe we want to move

https://github.com/nushell/nushell/blob/b226bf548f1bb2b84fc8415a7fefcc3f9951dc8f/crates/nu-parser/src/parser.rs#L4267

to this `parse_completer`, as we probably will add support of `@[]` syntax for `Completion:List` in the future.

File: crates/nu-cmd-lang/src/core_commands/attr/complete.rs (hunk 2 above)
Comment (Bahex) [reply crates/nu-cmd-lang/src/core_commands/attr/complete.rs]: Took a look and it's not just `attr category`, some other `attr` commands have incorrect signatures too. I'll fix them in another PR.

File: crates/nu-cli/src/completions/custom_completions.rs (hunk 4 above)
Comment (Bahex) [reply crates/nu-cli/src/completions/custom_completions.rs:267]: I don't think anyone's gonna actually check the spans of `spans: list<string>`, but they will have correct spans now :shrug:.

Also we're trying to keep preserve span information (and get rid of `Span::unkown()` calls) as much as possible.

File: crates/nu-cli/src/completions/custom_completions.rs (hunk 6 above)
Comment (Bahex) [reply crates/nu-cli/src/completions/custom_completions.rs:175]: They should be the same, but the method gets the actual span from the working set using a `SpanId`.

There was some effort to switch from storing `Span`s everywhere to using `SpanId` which has stalled for a while now:
- #12963

File: crates/nu-cli/src/completions/custom_completions.rs (hunk 4 above)
Comment (blindFS) [reply crates/nu-cli/src/completions/custom_completions.rs:267]: I see, thanks!

File: crates/nu-cli/src/completions/custom_completions.rs (hunk 6 above)
Comment (blindFS) [reply crates/nu-cli/src/completions/custom_completions.rs:175]: That's new to me, thanks for the info. I used `.span` everywhere in my early PRs, 🤣

File: crates/nu-cli/tests/completions/mod.rs [hunk 8]
```diff
@@ -773,6 +773,50 @@ fn external_completer_invalid() {
...
+        extern "gh" []
+
+        gh alias one two"#;
+
+    let suggestions = completer.complete(sample, sample.len());
+    let got = suggestions
+        .iter()
+        .map(|s| s.value.as_str())
+        .collect::<Vec<_>>();
+    let expacted = vec!["gh", "alias", "one", "two"];
```
Comment (blindFS) [inline crates/nu-cli/tests/completions/mod.rs]: You can simply this with the helper function of `match_suggestions`.

Also there's a typo in `expected`.

File: crates/nu-cli/tests/completions/mod.rs [hunk 9]
```diff
@@ -773,6 +773,50 @@ fn external_completer_invalid() {
...
+
+    assert_eq!(got, expacted);
+}
+
```
Comment (blindFS) [inline crates/nu-cli/tests/completions/mod.rs:790]: I'd like to see another test case where command level completer is overridden by argument level custom completer.

**Comment by Bahex** [comment]
Found on unexpected bug. Due to order in which different completions are generated, this currently prevents completing flags, though completing a flag's argument still works

File: crates/nu-cli/tests/completions/mod.rs [hunk 10]
```diff
@@ -773,6 +773,96 @@ fn external_completer_invalid() {
...
+            --flag(-f): string
+            foo: string,
+            bar: string@"nu-complete cmd bar",
+            ...rest
+        ] {}
+
+        cmd -"#;
+
+    let suggestions = completer.complete(sample, sample.len());
+    let expected = vec!["--flag", "--help", "--switch", "-f", "-h", "-s"];
```
Comment (blindFS) [inline crates/nu-cli/tests/completions/mod.rs]: Is this expected behavior? I thought users may want the external program, say carapace to do the flag completions for them.

`--help` is something special though, but typing `-h` is quick enough IMO so that it's OK to omit it.

File: crates/nu-cli/tests/completions/mod.rs [hunk 11]
```diff
@@ -773,6 +773,96 @@ fn external_completer_invalid() {
...
+        @complete "nu-complete cmd"
+        def "cmd" [
+            --switch(-s)
+            --flag(-f): string
+            foo: string,
+            bar: string@"nu-complete cmd bar",
+            ...rest
+        ] {}
+
+        cmd -"#;
```
Comment (blindFS) [inline crates/nu-cli/tests/completions/mod.rs:861]: There's a way to reuse the code and merge the 2 test cases:
1. copying the code of `custom_completer()`, maybe only the `new_engine` stuff for these 2 cases.
2. call `support::merge_input` for those definitions
3. shorten the command-to-complete: `cmd one `/`cmd -`

That's totally optional, there're duplications everywhere in this file. I hope AI agents are smart enough to refactor it correctly without any review.

Comment (Bahex) [reply crates/nu-cli/tests/completions/mod.rs:861]: I have some ideas about how to refactor these tests especially wrt how rstest is used here.

Comment (blindFS) [reply crates/nu-cli/tests/completions/mod.rs:861]: > I have some ideas about how to refactor these tests especially wrt how rstest is used here.

Cool, let's leave it for future PR then.

File: crates/nu-cli/tests/completions/mod.rs (hunk 10 above)
Comment (Bahex) [reply crates/nu-cli/tests/completions/mod.rs]: 2f3d4e8 solves this problem, it includes both the flags from the command definition and from the external (or custom command wide) completer.

I think it would be really useful with `def --wrapped` commands.

Comment (blindFS) [reply crates/nu-cli/tests/completions/mod.rs]: Sometimes it will result in duplicated `--help` for example. I'm fine with it as long as it's well documented. Hope the learning curve isn't too steep with properly organized chapters.

File: crates/nu-cli/src/completions/custom_completions.rs (hunk 5 above)
Comment (ysthakur) [reply crates/nu-cli/src/completions/custom_completions.rs:171]: Yeah, this might come in handy somewhere else. Not a blocker for this PR though

File: crates/nu-protocol/src/signature.rs (hunk 1 above)
Comment (ysthakur) [reply crates/nu-protocol/src/signature.rs]: If not an enum, then at least a doc comment explaining how this works

**Review by ysthakur — APPROVED** [review]
LGTM overall, this is going to be really great. I do agree with blindFS that it needs to be documented very well, since this is not easy to grasp.

**Comment by blindFS** [comment]
There seems to be a really weird regression:

https://github.com/nushell/nushell/issues/16075#issuecomment-3384249512

```nushell
$env.config.completions.algorithm = "fuzzy"
def l [arg: string@[a b c]] {  }
```

`l <tab>` now automatically appends an `a`

image

The interesting part:

```nushell
def l [arg: string@[b c]] {  }

def ll [arg: string@[a b c]] {  }
```

both have no regression issue.

And I've checked the returning values of `complete_by_expression`. They are exactly the same before or after this PR.

Plus, lsp completion is not affected, which means it certainly has something to do with the placeholder character:

image

**Comment by blindFS** [comment]
@ysthakur @Bahex @b0o Can you guys reproduce it?

Most of other single character named commands don't share this problem, only `l`/`L` (also `rl` and its case variants) according to my test.

Could be a reedline issue happens to be triggered by those `l ` fuzzy matched internal commands.

 But I don't get what it has to do with this PR.

**Comment by Bahex** [comment]
@blindFS yeah I can reproduce it. I'm also guessing it has something to do with the placeholder character.

> But I don't get what it has to do with this PR.

Maybe fallback order/behavior got modified?

**Comment by blindFS** [comment]
> Maybe fallback order/behavior got modified?

Not likely, but I have absolutely no clue 🤔.

I feel it may reveal something very funny underneath. What's so special about `l` and `rl` after all 🥲.

**Comment by b0o** [comment]
Yes, I can also reproduce it. Strange.

**Comment by ysthakur** [comment]
Since it's specifically `[a b c]` that this happens with, and we use `a` as our placeholder, could it be that the placeholder isn't getting stripped correctly? Should be easy to confirm but I can't compile/run stuff right now

**Comment by blindFS** [comment]
> Since it's specifically `[a b c]` that this happens with, and we use `a` as our placeholder, could it be that the placeholder isn't getting stripped correctly? Should be easy to confirm but I can't compile/run stuff right now

Actually it's not the case. As I stated in a previous comment, the vector of suggestions sent to reedline remains unchanged. That's why I said it might be a hidden reedline issue.

**Comment by blindFS** [comment]
Well, I think I've found the connection:

It turns out that

> the vector of suggestions sent to reedline remains unchanged

is not correct:

image

The diff is this `attr complete external` new command.

**Comment by ofek** [comment]
Heads-up that the TODO item in the PR description hasn't been done so this functionality is not mentioned in the [docs](https://www.nushell.sh/book/custom_completions.html) nor [cookbook](https://www.nushell.sh/cookbook/external_completers.html), only in the release note. I was looking into implementing completion for a tool and didn't even come across this by way of the release note but rather through Clap's ongoing [discussion](https://github.com/clap-rs/clap/issues/5840#issuecomment-3423864439) of their implementation.

image

**Comment by ysthakur** [comment]
@Bahex do you have time to document this? No worries if not, there are other completion-related doc updates that I was planning to do anyway

**Comment by ofek** [comment]
@ysthakur Hello! Did you happen to document this in one of your updates?

**Comment by ysthakur** [comment]
@ofek Sorry, not yet. I'll try to get to it this week

**Comment by ofek** [comment]
No worries, thank you!
