### PR TITLE
Prevents panic when parsing JSON containing large number

### LINKED ISSUE #5907: PosOverflow when parsing JSON containing very large number
### Describe the bug

When parsing a JSON file where an object contains a very large number I see `thread 'main' panicked at 'Internal error: json parsing: ParseIntError { kind: PosOverflow }', crates/nu-json/src/util.rs:220:52` as it's attempting to parse the number as a u64, and hitting the `expect`

### How to reproduce

Try to parse 
```﻿
﻿          {
            "cmd_get": 1.998001998001998,
            "couch_docs_actual_disk_size": 29044032244,
            "couch_docs_data_size": 20956132290,
            "couch_spatial_data_size": 0,
            "couch_spatial_disk_size": 0,
            "couch_views_actual_disk_size": 18785057365,
            "couch_views_data_size": 5323749123,
            "curr_items": 18446744073715094000,
            "curr_items_tot": 16626891,
            "ep_bg_fetched": 0,
            "get_hits": 0.999000999000999,
            "mem_used": 14482854736,
            "ops": 1.998001998001998,
            "vb_active_num_non_resident": 2640298,
            "vb_replica_curr_items": 11086582
          }
```
The `curr_items` field causes a panic. I did this by creating a json file and just using `open`.

### Expected behavior

It should parse the number correctly.

### Screenshots

_No response_

### Configuration

_No response_

### Additional context

I'm happy to undertake the work required here but needs discussion around how to handle this. Something with https://crates.io/crates/num maybe?

### PR DESCRIPTION
**Pull request by merelymyself**
# Description

Fixes #5907... hopefully.

@jntrnr suggested reading the numbers as f64 and then attempting a conversion to int if it works. This PR tries to read it as I64/U64 first, and if that fails reads it and passes it as a float. It might not be ideal. 

# Tests

Make sure you've done the following:

- [ ] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [ ] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [ ] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [ ] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [ ] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [ ] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

File: crates/nu-json/src/util.rs [hunk 1]
```diff
@@ -207,18 +207,19 @@ impl<Iter: Iterator<Item = u8>> ParseNumber<Iter> {
...
-                            Ok(Number::I64(
-                                res.parse::<i64>().expect("Internal error: json parsing"),
-                            ))
-                        } else {
-                            Ok(Number::U64(
-                                res.parse::<u64>().expect("Internal error: json parsing"),
-                            ))
+                        if !is_float {
+                            if let Ok(n) = res.parse::<i64>() {
+                                if res.starts_with('-') {
```
Comment (jntrnr) [inline crates/nu-json/src/util.rs:212]: do you want to check for the `-` first then try to parse as i64, otherwise parse as u64?

Comment (merelymyself) [reply crates/nu-json/src/util.rs]: Works for me, thanks!
