### PR TITLE
Fix pipeline `let` builtin var validation

### LINKED ISSUE #17372: `let` in pipelines doesn't respect built-in variables
### Bug report form

- [x] I have done a basic search of the issue tracker to find any existing issues that are similar.
- [x] I have checked that my version is at least the latest stable release available via my installation method.

### Describe the bug

Classical `let` throws error when assigning to built-in variables (`in`, `nu`, `env`).  `let` in pipelines doesn't have this check.

### How to reproduce

```nushell
~>  1 | let $nu | let $in | let $env
```

None of these throw an error, though the values of the built-ins aren't affected either.

### Expected behavior

I expected an error similar to that of `let`:

```nushell
~> let $env = 1
Error: nu::parser::name_is_builtin_var

  × `env` used as variable name.
   ╭─[entry #50:1:5]
 1 │ let $env = 1
   ·     ──┬─
   ·       ╰── already a builtin variable
   ╰────
  help: 'env' is the name of a builtin Nushell variable and cannot be used as a variable name
```

### Configuration

| key                  | value                                                                                     |
| -------------------- | ----------------------------------------------------------------------------------------- |
| version              | 0.110.0                                                                                   |
| major                | 0                                                                                         |
| minor                | 110                                                                                       |
| patch                | 0                                                                                         |
| branch               |                                                                                           |
| commit_hash          | d40e191d8efad32a174d85b2a45f7ba4796cff84                                                  |
| build_os             | linux-x86_64                                                                              |
| build_target         | x86_64-unknown-linux-musl                                                                 |
| rust_version         | rustc 1.92.0 (ded5c06cf 2025-12-08)                                                       |
| rust_channel         | stable-x86_64-unknown-linux-musl                                                          |
| cargo_version        | cargo 1.92.0 (344c4567c 2025-10-21)                                                       |
| build_time           | 2026-01-18 21:44:09 +03:00                                                                |
| build_rust_channel   | release                                                                                   |
| allocator            | standard                                                                                  |
| features             | default, mcp, network, plugin, rustls-tls, sqlite, trash-support                          |
| installed_plugins    | endecode 0.109.0, fs 0.109.0                                                              |
| experimental_options | example=false, reorder-cell-paths=true, pipefail=false, enforce-runtime-annotations=false |

### PR DESCRIPTION
**Pull request by it-education-md**
Fixes #17372

- Root cause: pipeline `let` had no builtin-variable name check, while non-pipeline `let` already did.
- Fix: reuse the existing builtin-var validation in pipeline `let` parsing (`parse_internal_call`).
- Tests: `cargo test --test main parse_let_pipeline_builtin_var`

## Release notes summary - What our users need to know
Fixed: pipeline `let` now errors when attempting to assign to builtin variables like `$in`, `$it`, `$env`, and `$nu`.

## Tasks after submitting
N/A

### CODE REVIEW

**Comment by it-education-md** [comment]
> I don't think it's good to change `parse_internal_call`. It may results to mode lines of code, but the changes should be limited to `parse_let/mut/const`.

@WindSoilder `parse_let` is only used via `parse_builtin_commands` for single-command pipelines. Multi-command pipelines like `1 | let $nu | let $env` go through `parse_pipeline_element -> parse_expression -> parse_internal_call`, so I think that  `parse_internal_call` (guarded to `let` only) is right place. Thoughts?

File: crates/nu-parser/src/parser.rs [hunk 1]
```diff
@@ -4,7 +4,7 @@ use crate::{
     Token, TokenContents,
     lex::{LexState, is_assignment_operator, lex, lex_n_tokens, lex_signature},
     lite_parser::{LiteCommand, LitePipeline, LiteRedirection, LiteRedirectionTarget, lite_parse},
-    parse_keywords::*,
+    parse_keywords::{ensure_not_reserved_variable_name, *},
```
Comment (WindSoilder) [inline crates/nu-parser/src/parser.rs]: no need to use it ensure_not_reserved_variable_name explicitly.

Comment (it-education-md) [reply crates/nu-parser/src/parser.rs]: Thanks, updated.

**Review by WindSoilder — APPROVED** [review]
Thanks!  LGTM

**Comment by blindFS** [comment]
> > I don't think it's good to change `parse_internal_call`. It may results to mode lines of code, but the changes should be limited to `parse_let/mut/const`.
> 
> @WindSoilder `parse_let` is only used via `parse_builtin_commands` for single-command pipelines. Multi-command pipelines like `1 | let $nu | let $env` go through `parse_pipeline_element -> parse_expression -> parse_internal_call`, so I think that `parse_internal_call` (guarded to `let` only) is right place. Thoughts?

How about moving the check into `parse_var_with_opt_type`?
